In [209]:
import sys
import os

# Add the path to the parent directory
sys.path.append(os.path.abspath(".."))

# Now you can import the module
from dep.openai_api import OpenAIChatCompletion
from dep.response_formats import SyntheticPositiveFactsheetResponse,AspectQueryResponse

In [20]:
ASPECTS = [
    "Industry", 
    "Customer Segment", 
    "Products & Services", 
    "Business Model", 
    "Technology Used", 
    "Revenue Model"
]

In [24]:
# res=llm.get_text_completion(prompt,0)['choices'][0]['message']['content']
import json
def generate_queries(aspects,n_queries=100,response_format=AspectQueryResponse):
    
    success=False
    
    sys_msg_path1='../prompts/aspect_queries.txt'
    system_message1=open(sys_msg_path1,'r').read()
    llm1=OpenAIChatCompletion(model='gpt-4o',system_message=system_message1)

    if aspects=='Industry':
        print('induystr')
        prompt1=f"Please provide {n_queries} queries for the aspects: {aspects}. Please Provide Industries such that their exist businesses for which these industries are customer industries. Customer industry of a company is the industry to which company sells its solutions. "
    else:
        prompt1=f"Please provide {n_queries} queries for the aspects: {aspects}"
    

    temperature=0.5
    
    res1=llm1.structured_response(prompt1,temperature,response_format)
    try:
        r1=json.loads(res1)
        success=True
        return success,r1
        
    except Exception as e:
        
        print(f'failed for {aspects} - {e}')
        success=False
        return success,{}

In [293]:
import concurrent.futures
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm
from typing import Callable, List, Any, TypeVar, Optional, Tuple, Dict

T = TypeVar('T')
R = TypeVar('R')

def parallel_execute(
    func: Callable[..., R],
    argument_sets: List[Tuple[List, Dict]],
    max_workers: Optional[int] = None,
    show_progress: bool = True,
    desc: str = "Processing items"
) -> List[R]:
    """
    Execute a function in parallel across multiple threads with different argument sets.
    
    Args:
        func: The function to execute in parallel
        argument_sets: List of (args, kwargs) tuples, where:
            - args is a list of positional arguments
            - kwargs is a dictionary of keyword arguments
        max_workers: Maximum number of threads to use (defaults to min(32, len(argument_sets)))
        show_progress: Whether to show a progress bar
        desc: Description for the progress bar
        
    Returns:
        List of results in the same order as the input argument_sets
    """
    if max_workers is None:
        max_workers = min(1, len(argument_sets))
    
    results = [None] * len(argument_sets)
    
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Define a worker function that captures the index
        def worker(idx, args_list, kwargs_dict):
            return idx, func(*args_list, **kwargs_dict)
        
        # Submit all tasks
        futures = {}
        for idx, (args, kwargs) in enumerate(argument_sets):
            future = executor.submit(worker, idx, args, kwargs)
            futures[future] = idx
        
        # Process results as they complete
        iterator = concurrent.futures.as_completed(futures)
        if show_progress:
            iterator = tqdm(iterator, total=len(futures), desc=desc)
            
        for future in iterator:
            idx, result = future.result()
            results[idx] = result
    
    return results

In [22]:
# and common enough that ColBERT would likely have seen similar terms during pre-training

In [23]:
# generate_queries('Customer Segment')

In [18]:
aspect_queries={}
from tqdm import tqdm
for aspect in tqdm(ASPECTS):
        
    if aspect=='Revenue Model':
        n_queries=25
    elif aspect=='Business Model':
        n_queries=10
    elif aspect=='Technology Used':
        n_queries=30
    else:
        n_queries=100
    queries=generate_queries(aspect,n_queries=n_queries)
    aspect_queries[aspect]=queries

  0%|          | 0/6 [00:00<?, ?it/s]

induystr

100%|██████████| 6/6 [00:38<00:00,  6.35s/it]

In [28]:
!pwd

/home/ec2-user/SageMaker/ColBERT

In [29]:
out_dir='../synthetic_data/complete_aspect_training'
os.makedirs(out_dir)

In [30]:
import pickle
with open('../synthetic_data/complete_aspect_training/aspect_queries.pkl','wb') as f:
    pickle.dump(aspect_queries,f)

In [19]:
aspect_queries

{'Industry': (True,
  {'queries': ['Healthcare',
    'Finance',
    'Retail',
    'Automotive',
    'Technology',
    'Education',
    'Manufacturing',
    'Construction',
    'Real Estate',
    'Energy',
    'Telecommunications',
    'Transportation',
    'Agriculture',
    'Pharmaceutical',
    'Food and Beverage',
    'Hospitality',
    'Entertainment',
    'Media',
    'Aerospace',
    'Defense',
    'Consumer Electronics',
    'Fashion',
    'Beauty',
    'Insurance',
    'Banking',
    'Legal',
    'Logistics',
    'Mining',
    'Chemicals',
    'Biotechnology',
    'Renewable Energy',
    'Utilities',
    'Public Sector',
    'Non-Profit',
    'Sports',
    'Gaming',
    'Textiles',
    'Furniture',
    'Petroleum',
    'Metals',
    'Paper and Pulp',
    'Printing',
    'Marine',
    'Fishing',
    'Forestry',
    'Plastics',
    'Ceramics',
    'Glass',
    'Jewelry',
    'Tobacco',
    'Advertising',
    'Consulting',
    'Event Management',
    'Travel',
    'Tourism',
    'E-commerce',
    'Cybersecurity',
    'Human Resources',
    'Information Technology',
    'Software Development',
    'Hardware Manufacturing',
    'Broadcasting',
    'Publishing',
    'Music Industry',
    'Film Production',
    'Animation',
    'Virtual Reality',
    'Augmented Reality',
    'Smart Home Technology',
    'Wearable Technology',
    'Nanotechnology',
    'Artificial Intelligence',
    'Machine Learning',
    'Data Analytics',
    'Internet of Things',
    'Blockchain',
    'Quantum Computing',
    'Robotics',
    '3D Printing',
    'Space Exploration',
    'Satellite Technology',
    'Agritech',
    'Fintech',
    'Healthtech',
    'Edtech',
    'Proptech',
    'Cleantech',
    'Foodtech',
    'Medtech',
    'Insurtech',
    'Govtech',
    'Regtech',
    'Legaltech',
    'Martech',
    'Adtech',
    'Retailtech',
    'Logitech',
    'Supply Chain Management',
    'Customer Relationship Management']}),
 'Customer Segment': (True,
  {'queries': ['Healthcare providers',
    'Small businesses',
    'Enterprise customers',
    'Educational institutions',
    'Doctors',
    'Lawyers',
    'Retailers',
    'Government agencies',
    'Non-profit organizations',
    'Financial institutions',
    'Tech startups',
    'Manufacturing companies',
    'Real estate developers',
    'Construction firms',
    'Pharmaceutical companies',
    'Automotive industry',
    'Energy companies',
    'Telecommunications providers',
    'Media companies',
    'Agricultural businesses',
    'Hospitality industry',
    'Restaurants',
    'E-commerce businesses',
    'Fashion brands',
    'Consumer electronics',
    'Logistics companies',
    'Travel agencies',
    'Fitness centers',
    'Beauty salons',
    'Pet care services',
    'Event planners',
    'Sports teams',
    'Insurance companies',
    'Banks',
    'Credit unions',
    'Investment firms',
    'Venture capitalists',
    'Private equity firms',
    'Hedge funds',
    'Accounting firms',
    'Consulting firms',
    'Marketing agencies',
    'Advertising agencies',
    'Public relations firms',
    'Human resources departments',
    'Legal departments',
    'Research institutions',
    'Universities',
    'Colleges',
    'High schools',
    'Elementary schools',
    'Preschools',
    'Daycare centers',
    'Senior living facilities',
    'Hospitals',
    'Clinics',
    'Dental practices',
    'Veterinary clinics',
    'Pharmacies',
    'Supermarkets',
    'Convenience stores',
    'Online retailers',
    'Wholesale distributors',
    'Import/export businesses',
    'Car dealerships',
    'Motorcycle dealerships',
    'Bicycle shops',
    'Furniture stores',
    'Home improvement stores',
    'Garden centers',
    'Toy stores',
    'Bookstores',
    'Music stores',
    'Art galleries',
    'Museums',
    'Theaters',
    'Cinemas',
    'Concert venues',
    'Sports arenas',
    'Stadiums',
    'Gyms',
    'Spas',
    'Resorts',
    'Hotels',
    'Motels',
    'Bed and breakfasts',
    'Hostels',
    'Airlines',
    'Shipping companies',
    'Rail companies',
    'Bus companies',
    'Taxi services',
    'Ride-sharing services',
    'Car rental services',
    'Software companies',
    'Hardware companies',
    'Biotech companies',
    'Medical device companies',
    'Chemical companies',
    'Mining companies',
    'Forestry companies',
    'Fishing companies']}),
 'Products & Services': (True,
  {'queries': ['Accounting software',
    'Mobile payment solutions',
    'Cybersecurity services',
    'E-commerce platforms',
    'Digital marketing tools',
    'Online learning platforms',
    'Telehealth services',
    'CRM software',
    'Supply chain management solutions',
    'Cloud storage services',
    'Data analytics tools',
    'Virtual reality experiences',
    'Subscription box services',
    'Online travel booking',
    'Video conferencing software',
    'Content management systems',
    'Social media management tools',
    'Project management software',
    'HR management platforms',
    'Customer support chatbots',
    'Freelance marketplace',
    'Online grocery delivery',
    'Fitness tracking apps',
    'Home automation devices',
    'Electric vehicle charging stations',
    'Renewable energy solutions',
    'Podcast hosting services',
    'Music streaming platforms',
    'Food delivery services',
    'Online dating apps',
    '3D printing services',
    'Augmented reality applications',
    'Blockchain development services',
    'Online gaming platforms',
    'Personal finance management tools',
    'Remote work solutions',
    'Business intelligence software',
    'Digital asset management',
    'Event management platforms',
    'Inventory management systems',
    'Point of sale systems',
    'Online survey tools',
    'Email marketing services',
    'Affiliate marketing networks',
    'Web hosting services',
    'SEO optimization tools',
    'Online course creation platforms',
    'Virtual event platforms',
    'Fleet management solutions',
    'Property management software',
    'Payment gateway services',
    'Cybersecurity training',
    'Data privacy solutions',
    'Employee wellness programs',
    'Online auction platforms',
    'Drone delivery services',
    'Smart home security systems',
    'Online fundraising platforms',
    'Digital signature services',
    'Legal document automation',
    'Virtual assistant services',
    'On-demand staffing platforms',
    'Online therapy services',
    'Crowdfunding platforms',
    'Peer-to-peer lending services',
    'Online job boards',
    'Digital health records',
    'Remote patient monitoring',
    'Telecom expense management',
    'Mobile app development',
    'E-book publishing platforms',
    'Online stock trading',
    'Digital currency exchange',
    'Video editing software',
    'Online language learning',
    'Cloud-based call centers',
    'AI-powered writing tools',
    'Online ticketing systems',
    'B2B marketplace',
    'Smart contract development',
    'Online reputation management',
    'Digital transformation consulting',
    'Online notarization services',
    'Augmented reality shopping',
    'Virtual fitting rooms',
    'Live streaming platforms',
    'Workforce management software',
    'Online portfolio management',
    'Voice recognition software',
    'Online pet care services',
    'Digital signage solutions',
    'Online tutoring services',
    'Virtual coworking spaces',
    'Robotic process automation',
    'Online car rental services',
    'Online fitness classes',
    'Eco-friendly packaging solutions',
    'Online interior design services']}),
 'Business Model': (True,
  {'queries': ['B2B',
    'B2C',
    'Subscription-based',
    'Freemium',
    'Marketplace',
    'Direct sales',
    'Franchise',
    'Licensing',
    'On-demand',
    'Peer-to-peer']}),
 'Technology Used': (True,
  {'queries': ['AI',
    'Machine learning',
    'Blockchain',
    'Cloud computing',
    'IoT',
    'Big data analytics',
    'Natural language processing',
    'Augmented reality',
    'Virtual reality',
    'Edge computing',
    'Quantum computing',
    'Cybersecurity solutions',
    '5G technology',
    'Robotics',
    '3D printing',
    'Computer vision',
    'Voice recognition',
    'Biometrics',
    'Wearable technology',
    'Digital twins',
    'Neural networks',
    'Deep learning',
    'Autonomous vehicles',
    'Smart contracts',
    'Cryptography',
    'Geolocation services',
    'Facial recognition',
    'Chatbots',
    'RPA (Robotic Process Automation)',
    'Microservices architecture']}),
 'Revenue Model': (True,
  {'queries': ['Subscription-based',
    'Freemium',
    'Pay-per-use',
    'Licensing',
    'Advertising',
    'Commission',
    'Marketplace',
    'Affiliate',
    'SaaS',
    'PaaS',
    'B2B',
    'B2C',
    'Direct sales',
    'Retail',
    'Wholesale',
    'Franchise',
    'Leasing',
    'Crowdsourcing',
    'Donation',
    'Sponsorship',
    'In-app purchases',
    'Microtransactions',
    'Consulting fees',
    'Membership',
    'Royalties']})}

In [ ]:
Total dataset:
per query 10 positives : For consumer industry and industry: 30 positives
Industry: 
    Negatives from Corresponding Consumer Industry: per positive 10-20 negatives
    Some negatives from people operating in a different industry? - 10 negatives
Customer Industry:
    Negatives from Corresponding Industry: per positive 10-30 negatives
Business Model:
    Synthetic Negatives : 30 per query 
Revenue Model:
    Synthetic Negatives : 30 per wquery 
Technology Used: 
    Synthetic Negatives: 30 per query 
Customer Segment: 
    Choose Other consumer Segments which are likely to be negative 



Cost Estimate:

Input tokens:
60*100*2*512 (Industry+Consumer Industry) + (100*100*3) (Industry intra query negatives) + (500*3*20) (Bm+RM+Tech negatives creation)

Output Tokens:
60*100*2*10 + (100*10) + (20*3*512)

In [35]:
output_cost=10*(60*100*2*10 + (100*10) + (20*3*512*30))/1000000

In [36]:
output_cost

10.426

In [37]:
dataset_size=300*100*2 + 30*10*20*3 + 300*100

In [38]:
dataset_size

108000

In [39]:
# If we generate positives for Consumer Industry each query

10*(100*30*512/1000000)

15.36

In [40]:
!pwd

/home/ec2-user/SageMaker/ColBERT

In [42]:
!pip3 install -U numpy

Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/colbert_env/lib/python3.10/site-packages (1.24.4)
Collecting numpy
  Downloading numpy-2.2.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Downloading numpy-2.2.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 167.5 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4
Successfully installed numpy-2.2.4

In [1]:
import pickle
with open('../synthetic_data/aspect_query_fetched_positives.pkl','rb') as f:
    aspect_query_res=pickle.load(f)

In [2]:
aspect_query_res.keys()

dict_keys(['Industry', 'Customer Segment', 'Products & Services', 'Business Model', 'Technology Used', 'Revenue Model', 'Customer Industry'])

In [55]:
aspect_prompt={
'Industry':'Please ONLY qualify Companies that are providing solutions as a part of the given industry.Customer industry of a company is the industry to which company sells its solutions. DO NOT QUALIFY COMPANIES WHICH ALSO HAVE THE SAME CUSTOMER INDUSTRY SINCE WE WILL BE USING COMPANIES WITH SAME CUSTOMER INDUSTRY AS NEGATIVES FOR COMPANIES WITH SAME INDUSTRY',
'Customer Segment':'Customer Segment describes the class of customers that a company has',
'Products & Services':'',
'Business Model':'',
'Technology Used':'',
'Revenue Model':'',
'Customer Industry':'Please ONLY qualify Companies that are providing solutions to the provided industry as their customer industry.Customer industry of a company is the industry to which company sells its solutions. DO NOT QUALIFY COMPANIES WHICH ALSO HAVE THE SAME INDUSTRY SINCE WE WILL BE USING COMPANIES WITH SAME INDUSTRY AS NEGATIVES FOR COMPANIES WITH SAME CUSTOMER INDUSTRY'}

In [56]:
from dep.response_formats import FilteringResponse

In [57]:
# res=llm.get_text_completion(prompt,0)['choices'][0]['message']['content']
import json
def filter_companies(aspect,query,factsheet,response_format=FilteringResponse):
    
    success=False
    
    sys_msg_path1='../prompts/factsheet_relevance_check.txt'
    system_message1=open(sys_msg_path1,'r').read()
    llm1=OpenAIChatCompletion(model='gpt-4o',system_message=system_message1)
    
    prompt1=aspect_prompt[aspect] + f'Query: {aspect} - {query}\nFactsheet: {factsheet}'
    

    temperature=0
    
    res1=llm1.structured_response(prompt1,temperature,response_format)
    try:
        r1=json.loads(res1)
        success=True
        return success,r1
        
    except Exception as e:
        
        print(f'failed for {aspects} - {e}')
        success=False
        return success,{}

In [91]:
# Load the BERT tokenizer
model_name="bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
from transformers import BertTokenizer

def count_tokens(text, model_name="bert-base-uncased"):
    """
    Count the number of tokens in a text using BERT tokenizer.
    
    Args:
        text (str): The input text to tokenize and count
        model_name (str): The specific BERT model tokenizer to use
                         (default: 'bert-base-uncased')
    
    Returns:
        int: The number of tokens in the text
    """
    
    
    # Tokenize the text
    tokens = tokenizer.encode(text, add_special_tokens=True)
    
    # Return the count of tokens
    return len(tokens)

count_tokens(remove_text_before_pattern(factsheet))

Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors

559

In [100]:
import re

def remove_text_before_pattern(text):
    return re.sub(r'^.*?\* \*', '* *', text, count=1, flags=re.DOTALL).split('* * overall assessment :* *')[0]

In [102]:
from tqdm import tqdm 
for aspect,q_dict in tqdm(aspect_query_res.items()):
    for query,res in tqdm(q_dict.items()):
        res['token_count']=res.descriptions.apply(lambda x:count_tokens(remove_text_before_pattern(x)))
        aspect_query_res[aspect][query]=res

  0%|          | 0/7 [00:00<?, ?it/s]
%|          | 0/99 [00:00<?, ?it/s]
%|          | 1/99 [00:00<01:23,  1.17it/s]
%|▏         | 2/99 [00:01<01:22,  1.17it/s]
%|▎         | 3/99 [00:02<01:23,  1.15it/s]
%|▍         | 4/99 [00:03<01:20,  1.18it/s]
%|▌         | 5/99 [00:04<01:14,  1.26it/s]
%|▌         | 6/99 [00:05<01:18,  1.19it/s]
%|▋         | 7/99 [00:05<01:18,  1.17it/s]
%|▊         | 8/99 [00:06<01:19,  1.14it/s]
%|▉         | 9/99 [00:07<01:17,  1.16it/s]
%|█         | 10/99 [00:08<01:16,  1.17it/s]
%|█         | 11/99 [00:09<01:15,  1.17it/s]
%|█▏        | 12/99 [00:10<01:15,  1.16it/s]
%|█▎        | 13/99 [00:11<01:13,  1.17it/s]
%|█▍        | 14/99 [00:11<01:12,  1.17it/s]
%|█▌        | 15/99 [00:12<01:12,  1.16it/s]
%|█▌        | 16/99 [00:13<01:11,  1.16it/s]
%|█▋        | 17/99 [00:14<01:11,  1.15it/s]
%|█▊        | 18/99 [00:15<01:10,  1.14it/s]
%|█▉        | 19/99 [00:16<01:06,  1.20it/s]
%|██        | 20/99 [00:17<01:05,  1.20it/s]
%|██        | 21/99 [00:17<01:04,  1.20it/s]
%|██▏       | 22/99 [00:18<01:04,  1.19it/s]
%|██▎       | 23/99 [00:19<01:03,  1.20it/s]
%|██▍       | 24/99 [00:20<01:02,  1.19it/s]
%|██▌       | 25/99 [00:21<01:02,  1.18it/s]
%|██▋       | 26/99 [00:22<01:02,  1.16it/s]
%|██▋       | 27/99 [00:22<01:00,  1.18it/s]
%|██▊       | 28/99 [00:23<00:59,  1.19it/s]
%|██▉       | 29/99 [00:24<00:59,  1.18it/s]
%|███       | 30/99 [00:25<00:58,  1.18it/s]
%|███▏      | 31/99 [00:26<00:56,  1.20it/s]
%|███▏      | 32/99 [00:27<00:55,  1.21it/s]
%|███▎      | 33/99 [00:27<00:54,  1.22it/s]
%|███▍      | 34/99 [00:28<00:53,  1.21it/s]
%|███▌      | 35/99 [00:29<00:53,  1.20it/s]
%|███▋      | 36/99 [00:30<00:53,  1.19it/s]
%|███▋      | 37/99 [00:31<00:52,  1.18it/s]
%|███▊      | 38/99 [00:32<00:51,  1.18it/s]
%|███▉      | 39/99 [00:33<00:50,  1.18it/s]
%|████      | 40/99 [00:33<00:49,  1.19it/s]
%|████▏     | 41/99 [00:34<00:47,  1.22it/s]
%|████▏     | 42/99 [00:35<00:46,  1.23it/s]
%|████▎     | 43/99 [00:36<00:45,  1.22it/s]
%|████▍     | 44/99 [00:37<00:45,  1.21it/s]
%|████▌     | 45/99 [00:37<00:45,  1.20it/s]
%|████▋     | 46/99 [00:38<00:45,  1.17it/s]
%|████▋     | 47/99 [00:39<00:44,  1.17it/s]
%|████▊     | 48/99 [00:40<00:43,  1.17it/s]
%|████▉     | 49/99 [00:41<00:42,  1.18it/s]
%|█████     | 50/99 [00:42<00:41,  1.18it/s]
%|█████▏    | 51/99 [00:43<00:40,  1.18it/s]
%|█████▎    | 52/99 [00:43<00:39,  1.18it/s]
%|█████▎    | 53/99 [00:44<00:38,  1.18it/s]
%|█████▍    | 54/99 [00:45<00:37,  1.20it/s]
%|█████▌    | 55/99 [00:46<00:40,  1.08it/s]
%|█████▋    | 56/99 [00:47<00:38,  1.11it/s]
%|█████▊    | 57/99 [00:48<00:37,  1.13it/s]
%|█████▊    | 58/99 [00:49<00:35,  1.15it/s]
%|█████▉    | 59/99 [00:50<00:33,  1.18it/s]
%|██████    | 60/99 [00:50<00:33,  1.17it/s]
%|██████▏   | 61/99 [00:51<00:31,  1.20it/s]
%|██████▎   | 62/99 [00:52<00:31,  1.16it/s]
%|██████▎   | 63/99 [00:53<00:30,  1.17it/s]
%|██████▍   | 64/99 [00:54<00:30,  1.15it/s]
%|██████▌   | 65/99 [00:55<00:28,  1.20it/s]
%|██████▋   | 66/99 [00:55<00:27,  1.20it/s]
%|██████▊   | 67/99 [00:56<00:26,  1.22it/s]
%|██████▊   | 68/99 [00:57<00:25,  1.22it/s]
%|██████▉   | 69/99 [00:58<00:24,  1.20it/s]
%|███████   | 70/99 [00:59<00:23,  1.21it/s]
%|███████▏  | 71/99 [01:00<00:22,  1.23it/s]
%|███████▎  | 72/99 [01:00<00:21,  1.24it/s]
%|███████▎  | 73/99 [01:01<00:21,  1.21it/s]
%|███████▍  | 74/99 [01:02<00:20,  1.20it/s]
%|███████▌  | 75/99 [01:03<00:19,  1.20it/s]
%|███████▋  | 76/99 [01:04<00:19,  1.21it/s]
%|███████▊  | 77/99 [01:05<00:18,  1.19it/s]
%|███████▉  | 78/99 [01:05<00:17,  1.17it/s]
%|███████▉  | 79/99 [01:06<00:16,  1.18it/s]
%|████████  | 80/99 [01:07<00:15,  1.19it/s]
%|████████▏ | 81/99 [01:08<00:14,  1.21it/s]
%|████████▎ | 82/99 [01:09<00:14,  1.20it/s]
%|████████▍ | 83/99 [01:09<00:13,  1.23it/s]
%|████████▍ | 84/99 [01:10<00:11,  1.26it/s]
%|████████▌ | 85/99 [01:11<00:11,  1.22it/s]
%|████████▋ | 86/99 [01:12<00:11,  1.18it/s]
%|████████▊ | 87/99 [01:13<00:10,  1.17it/s]
%|████████▉ | 88/99 [01:14<00:09,  1.18it/s]
%|████████▉ | 89/99 [01:15<00:08,  1.18it/s]
%|█████████ | 90/99 [01:15<00:07,  1.19it/s]
%|█████████▏| 91/99 [01:16<00:06,  1.21it/s]
%|█████████▎| 92/99 [01:17<00:05,  1.22it/s]
%|█████████▍| 93/99 [01:18<00:04,  1.23it/s]
%|█████████▍| 94/99 [01:19<00:04,  1.20it/s]
%|█████████▌| 95/99 [01:19<00:03,  1.22it/s]
%|█████████▋| 96/99 [01:20<00:02,  1.22it/s]
%|█████████▊| 97/99 [01:21<00:01,  1.19it/s]
%|█████████▉| 98/99 [01:22<00:00,  1.21it/s]
100%|██████████| 99/99 [01:23<00:00,  1.19it/s]
 14%|█▍        | 1/7 [01:23<08:19, 83.30s/it]
%|          | 0/102 [00:00<?, ?it/s]
%|          | 1/102 [00:00<01:24,  1.20it/s]
%|▏         | 2/102 [00:01<01:21,  1.23it/s]
%|▎         | 3/102 [00:02<01:19,  1.25it/s]
%|▍         | 4/102 [00:03<01:21,  1.20it/s]
%|▍         | 5/102 [00:04<01:21,  1.20it/s]
%|▌         | 6/102 [00:04<01:20,  1.19it/s]
%|▋         | 7/102 [00:05<01:19,  1.20it/s]
%|▊         | 8/102 [00:06<01:19,  1.19it/s]
%|▉         | 9/102 [00:07<01:16,  1.21it/s]
%|▉         | 10/102 [00:08<01:14,  1.24it/s]
%|█         | 11/102 [00:09<01:14,  1.22it/s]
%|█▏        | 12/102 [00:09<01:15,  1.19it/s]
%|█▎        | 13/102 [00:10<01:14,  1.19it/s]
%|█▎        | 14/102 [00:11<01:11,  1.23it/s]
%|█▍        | 15/102 [00:12<01:11,  1.22it/s]
%|█▌        | 16/102 [00:13<01:10,  1.22it/s]
%|█▋        | 17/102 [00:14<01:09,  1.22it/s]
%|█▊        | 18/102 [00:14<01:08,  1.23it/s]
%|█▊        | 19/102 [00:15<01:08,  1.21it/s]
%|█▉        | 20/102 [00:16<01:07,  1.21it/s]
%|██        | 21/102 [00:17<01:06,  1.21it/s]
%|██▏       | 22/102 [00:18<01:04,  1.23it/s]
%|██▎       | 23/102 [00:18<01:04,  1.22it/s]
%|██▎       | 24/102 [00:19<01:04,  1.21it/s]
%|██▍       | 25/102 [00:20<01:03,  1.21it/s]
%|██▌       | 26/102 [00:21<01:03,  1.20it/s]
%|██▋       | 27/102 [00:22<01:02,  1.20it/s]
%|██▋       | 28/102 [00:23<01:02,  1.19it/s]
%|██▊       | 29/102 [00:23<01:01,  1.19it/s]
%|██▉       | 30/102 [00:24<01:00,  1.18it/s]
%|███       | 31/102 [00:25<01:00,  1.18it/s]
%|███▏      | 32/102 [00:26<00:58,  1.20it/s]
%|███▏      | 33/102 [00:27<00:57,  1.19it/s]
%|███▎      | 34/102 [00:28<00:57,  1.18it/s]
%|███▍      | 35/102 [00:29<00:56,  1.18it/s]
%|███▌      | 36/102 [00:29<00:56,  1.17it/s]
%|███▋      | 37/102 [00:30<00:54,  1.19it/s]
%|███▋      | 38/102 [00:31<00:54,  1.18it/s]
%|███▊      | 39/102 [00:32<00:52,  1.20it/s]
%|███▉      | 40/102 [00:33<00:51,  1.21it/s]
%|████      | 41/102 [00:34<00:49,  1.22it/s]
%|████      | 42/102 [00:34<00:49,  1.22it/s]
%|████▏     | 43/102 [00:35<00:49,  1.20it/s]
%|████▎     | 44/102 [00:36<00:48,  1.19it/s]
%|████▍     | 45/102 [00:37<00:48,  1.18it/s]
%|████▌     | 46/102 [00:38<00:47,  1.19it/s]
%|████▌     | 47/102 [00:39<00:46,  1.19it/s]
%|████▋     | 48/102 [00:39<00:45,  1.19it/s]
%|████▊     | 49/102 [00:40<00:44,  1.20it/s]
%|████▉     | 50/102 [00:41<00:43,  1.18it/s]
%|█████     | 51/102 [00:42<00:43,  1.18it/s]
%|█████     | 52/102 [00:43<00:42,  1.18it/s]
%|█████▏    | 53/102 [00:44<00:41,  1.19it/s]
%|█████▎    | 54/102 [00:44<00:40,  1.18it/s]
%|█████▍    | 55/102 [00:45<00:38,  1.21it/s]
%|█████▍    | 56/102 [00:46<00:38,  1.20it/s]
%|█████▌    | 57/102 [00:47<00:37,  1.18it/s]
%|█████▋    | 58/102 [00:48<00:37,  1.19it/s]
%|█████▊    | 59/102 [00:49<00:36,  1.18it/s]
%|█████▉    | 60/102 [00:50<00:35,  1.18it/s]
%|█████▉    | 61/102 [00:50<00:33,  1.21it/s]
%|██████    | 62/102 [00:51<00:33,  1.20it/s]
%|██████▏   | 63/102 [00:52<00:32,  1.21it/s]
%|██████▎   | 64/102 [00:53<00:31,  1.21it/s]
%|██████▎   | 65/102 [00:54<00:31,  1.19it/s]
%|██████▍   | 66/102 [00:55<00:30,  1.18it/s]
%|██████▌   | 67/102 [00:55<00:29,  1.18it/s]
%|██████▋   | 68/102 [00:56<00:28,  1.18it/s]
%|██████▊   | 69/102 [00:57<00:27,  1.19it/s]
%|██████▊   | 70/102 [00:58<00:27,  1.18it/s]
%|██████▉   | 71/102 [00:59<00:26,  1.19it/s]
%|███████   | 72/102 [01:00<00:25,  1.19it/s]
%|███████▏  | 73/102 [01:00<00:23,  1.22it/s]
%|███████▎  | 74/102 [01:01<00:22,  1.23it/s]
%|███████▎  | 75/102 [01:02<00:22,  1.22it/s]
%|███████▍  | 76/102 [01:03<00:21,  1.21it/s]
%|███████▌  | 77/102 [01:04<00:20,  1.21it/s]
%|███████▋  | 78/102 [01:05<00:20,  1.20it/s]
%|███████▋  | 79/102 [01:05<00:17,  1.30it/s]
%|███████▊  | 80/102 [01:06<00:17,  1.27it/s]
%|███████▉  | 81/102 [01:07<00:16,  1.27it/s]
%|████████  | 82/102 [01:08<00:15,  1.27it/s]
%|████████▏ | 83/102 [01:08<00:15,  1.26it/s]
%|████████▏ | 84/102 [01:09<00:14,  1.26it/s]
%|████████▎ | 85/102 [01:10<00:13,  1.25it/s]
%|████████▍ | 86/102 [01:11<00:13,  1.23it/s]
%|████████▌ | 87/102 [01:12<00:12,  1.24it/s]
%|████████▋ | 88/102 [01:12<00:11,  1.23it/s]
%|████████▋ | 89/102 [01:13<00:10,  1.20it/s]
%|████████▊ | 90/102 [01:14<00:10,  1.20it/s]
%|████████▉ | 91/102 [01:15<00:09,  1.19it/s]
%|█████████ | 92/102 [01:16<00:08,  1.19it/s]
%|█████████ | 93/102 [01:17<00:07,  1.23it/s]
%|█████████▏| 94/102 [01:17<00:06,  1.24it/s]
%|█████████▎| 95/102 [01:18<00:05,  1.24it/s]
%|█████████▍| 96/102 [01:19<00:04,  1.25it/s]
%|█████████▌| 97/102 [01:20<00:04,  1.23it/s]
%|█████████▌| 98/102 [01:21<00:03,  1.22it/s]
%|█████████▋| 99/102 [01:21<00:02,  1.25it/s]
%|█████████▊| 100/102 [01:22<00:01,  1.24it/s]
%|█████████▉| 101/102 [01:23<00:00,  1.23it/s]
100%|██████████| 102/102 [01:24<00:00,  1.21it/s]
 29%|██▊       | 2/7 [02:47<06:59, 83.93s/it]
%|          | 0/98 [00:00<?, ?it/s]
%|          | 1/98 [00:00<01:28,  1.09it/s]
%|▏         | 2/98 [00:01<01:24,  1.13it/s]
%|▎         | 3/98 [00:02<01:21,  1.17it/s]
%|▍         | 4/98 [00:03<01:21,  1.15it/s]
%|▌         | 5/98 [00:04<01:20,  1.15it/s]
%|▌         | 6/98 [00:05<01:18,  1.18it/s]
%|▋         | 7/98 [00:05<01:16,  1.19it/s]
%|▊         | 8/98 [00:06<01:16,  1.17it/s]
%|▉         | 9/98 [00:07<01:16,  1.16it/s]
%|█         | 10/98 [00:08<01:15,  1.17it/s]
%|█         | 11/98 [00:09<01:15,  1.15it/s]
%|█▏        | 12/98 [00:10<01:15,  1.14it/s]
%|█▎        | 13/98 [00:11<01:14,  1.14it/s]
%|█▍        | 14/98 [00:12<01:12,  1.15it/s]
%|█▌        | 15/98 [00:12<01:10,  1.17it/s]
%|█▋        | 16/98 [00:13<01:07,  1.21it/s]
%|█▋        | 17/98 [00:14<01:07,  1.21it/s]
%|█▊        | 18/98 [00:15<01:06,  1.20it/s]
%|█▉        | 19/98 [00:16<01:06,  1.18it/s]
%|██        | 20/98 [00:17<01:07,  1.15it/s]
%|██▏       | 21/98 [00:17<01:04,  1.19it/s]
%|██▏       | 22/98 [00:18<01:03,  1.19it/s]
%|██▎       | 23/98 [00:19<01:03,  1.18it/s]
%|██▍       | 24/98 [00:20<01:03,  1.16it/s]
%|██▌       | 25/98 [00:21<01:02,  1.16it/s]
%|██▋       | 26/98 [00:22<01:01,  1.17it/s]
%|██▊       | 27/98 [00:23<01:01,  1.16it/s]
%|██▊       | 28/98 [00:23<00:59,  1.19it/s]
%|██▉       | 29/98 [00:24<00:58,  1.18it/s]
%|███       | 30/98 [00:25<00:58,  1.15it/s]
%|███▏      | 31/98 [00:26<00:56,  1.18it/s]
%|███▎      | 32/98 [00:27<00:56,  1.18it/s]
%|███▎      | 33/98 [00:28<00:56,  1.15it/s]
%|███▍      | 34/98 [00:29<00:55,  1.16it/s]
%|███▌      | 35/98 [00:29<00:54,  1.16it/s]
%|███▋      | 36/98 [00:30<00:53,  1.16it/s]
%|███▊      | 37/98 [00:31<00:51,  1.19it/s]
%|███▉      | 38/98 [00:32<00:50,  1.19it/s]
%|███▉      | 39/98 [00:33<00:48,  1.21it/s]
%|████      | 40/98 [00:34<00:48,  1.20it/s]
%|████▏     | 41/98 [00:34<00:46,  1.22it/s]
%|████▎     | 42/98 [00:35<00:45,  1.24it/s]
%|████▍     | 43/98 [00:36<00:45,  1.21it/s]
%|████▍     | 44/98 [00:37<00:46,  1.17it/s]
%|████▌     | 45/98 [00:38<00:45,  1.17it/s]
%|████▋     | 46/98 [00:39<00:45,  1.15it/s]
%|████▊     | 47/98 [00:40<00:44,  1.15it/s]
%|████▉     | 48/98 [00:40<00:42,  1.18it/s]
%|█████     | 49/98 [00:41<00:41,  1.19it/s]
%|█████     | 50/98 [00:42<00:40,  1.18it/s]
%|█████▏    | 51/98 [00:43<00:39,  1.18it/s]
%|█████▎    | 52/98 [00:44<00:38,  1.20it/s]
%|█████▍    | 53/98 [00:45<00:37,  1.20it/s]
%|█████▌    | 54/98 [00:45<00:37,  1.18it/s]
%|█████▌    | 55/98 [00:46<00:36,  1.18it/s]
%|█████▋    | 56/98 [00:47<00:35,  1.17it/s]
%|█████▊    | 57/98 [00:48<00:35,  1.16it/s]
%|█████▉    | 58/98 [00:49<00:34,  1.17it/s]
%|██████    | 59/98 [00:50<00:33,  1.17it/s]
%|██████    | 60/98 [00:51<00:32,  1.18it/s]
%|██████▏   | 61/98 [00:51<00:31,  1.19it/s]
%|██████▎   | 62/98 [00:52<00:29,  1.20it/s]
%|██████▍   | 63/98 [00:53<00:32,  1.08it/s]
%|██████▌   | 64/98 [00:54<00:30,  1.11it/s]
%|██████▋   | 65/98 [00:55<00:28,  1.15it/s]
%|██████▋   | 66/98 [00:56<00:27,  1.18it/s]
%|██████▊   | 67/98 [00:57<00:26,  1.17it/s]
%|██████▉   | 68/98 [00:57<00:25,  1.18it/s]
%|███████   | 69/98 [00:58<00:24,  1.18it/s]
%|███████▏  | 70/98 [00:59<00:23,  1.18it/s]
%|███████▏  | 71/98 [01:00<00:22,  1.19it/s]
%|███████▎  | 72/98 [01:01<00:21,  1.19it/s]
%|███████▍  | 73/98 [01:02<00:21,  1.19it/s]
%|███████▌  | 74/98 [01:03<00:20,  1.17it/s]
%|███████▋  | 75/98 [01:03<00:19,  1.16it/s]
%|███████▊  | 76/98 [01:04<00:18,  1.18it/s]
%|███████▊  | 77/98 [01:05<00:17,  1.20it/s]
%|███████▉  | 78/98 [01:06<00:16,  1.18it/s]
%|████████  | 79/98 [01:07<00:16,  1.18it/s]
%|████████▏ | 80/98 [01:08<00:15,  1.18it/s]
%|████████▎ | 81/98 [01:08<00:14,  1.20it/s]
%|████████▎ | 82/98 [01:09<00:13,  1.19it/s]
%|████████▍ | 83/98 [01:10<00:12,  1.20it/s]
%|████████▌ | 84/98 [01:11<00:11,  1.19it/s]
%|████████▋ | 85/98 [01:12<00:10,  1.19it/s]
%|████████▊ | 86/98 [01:13<00:10,  1.18it/s]
%|████████▉ | 87/98 [01:13<00:09,  1.20it/s]
%|████████▉ | 88/98 [01:14<00:08,  1.22it/s]
%|█████████ | 89/98 [01:15<00:07,  1.20it/s]
%|█████████▏| 90/98 [01:16<00:06,  1.17it/s]
%|█████████▎| 91/98 [01:17<00:05,  1.22it/s]
%|█████████▍| 92/98 [01:18<00:04,  1.24it/s]
%|█████████▍| 93/98 [01:18<00:04,  1.20it/s]
%|█████████▌| 94/98 [01:19<00:03,  1.18it/s]
%|█████████▋| 95/98 [01:20<00:02,  1.17it/s]
%|█████████▊| 96/98 [01:21<00:01,  1.16it/s]
%|█████████▉| 97/98 [01:22<00:00,  1.17it/s]
100%|██████████| 98/98 [01:23<00:00,  1.18it/s]
 43%|████▎     | 3/7 [04:10<05:34, 83.61s/it]
%|          | 0/10 [00:00<?, ?it/s]
%|█         | 1/10 [00:00<00:07,  1.28it/s]
%|██        | 2/10 [00:01<00:06,  1.22it/s]
%|███       | 3/10 [00:02<00:05,  1.23it/s]
%|████      | 4/10 [00:03<00:04,  1.24it/s]
%|█████     | 5/10 [00:04<00:04,  1.22it/s]
%|██████    | 6/10 [00:04<00:03,  1.26it/s]
%|███████   | 7/10 [00:05<00:02,  1.22it/s]
%|████████  | 8/10 [00:06<00:01,  1.26it/s]
%|█████████ | 9/10 [00:07<00:00,  1.27it/s]
100%|██████████| 10/10 [00:07<00:00,  1.25it/s]
 57%|█████▋    | 4/7 [04:18<02:41, 53.76s/it]
%|          | 0/30 [00:00<?, ?it/s]
%|▎         | 1/30 [00:00<00:25,  1.12it/s]
%|▋         | 2/30 [00:01<00:25,  1.08it/s]
%|█         | 3/30 [00:02<00:24,  1.10it/s]
%|█▎        | 4/30 [00:03<00:22,  1.13it/s]
%|█▋        | 5/30 [00:04<00:21,  1.14it/s]
%|██        | 6/30 [00:05<00:21,  1.14it/s]
%|██▎       | 7/30 [00:06<00:19,  1.17it/s]
%|██▋       | 8/30 [00:07<00:19,  1.13it/s]
%|███       | 9/30 [00:07<00:18,  1.14it/s]
%|███▎      | 10/30 [00:08<00:17,  1.15it/s]
%|███▋      | 11/30 [00:09<00:16,  1.13it/s]
%|████      | 12/30 [00:10<00:15,  1.13it/s]
%|████▎     | 13/30 [00:11<00:15,  1.11it/s]
%|████▋     | 14/30 [00:12<00:14,  1.13it/s]
%|█████     | 15/30 [00:13<00:13,  1.12it/s]
%|█████▎    | 16/30 [00:14<00:12,  1.13it/s]
%|█████▋    | 17/30 [00:14<00:11,  1.14it/s]
%|██████    | 18/30 [00:15<00:10,  1.15it/s]
%|██████▎   | 19/30 [00:16<00:09,  1.14it/s]
%|██████▋   | 20/30 [00:17<00:08,  1.14it/s]
%|███████   | 21/30 [00:18<00:07,  1.15it/s]
%|███████▎  | 22/30 [00:19<00:06,  1.15it/s]
%|███████▋  | 23/30 [00:20<00:06,  1.14it/s]
%|████████  | 24/30 [00:21<00:05,  1.15it/s]
%|████████▎ | 25/30 [00:21<00:04,  1.14it/s]
%|████████▋ | 26/30 [00:22<00:03,  1.15it/s]
%|█████████ | 27/30 [00:23<00:02,  1.13it/s]
%|█████████▎| 28/30 [00:24<00:01,  1.14it/s]
%|█████████▋| 29/30 [00:25<00:00,  1.14it/s]
100%|██████████| 30/30 [00:26<00:00,  1.14it/s]
 71%|███████▏  | 5/7 [04:45<01:27, 43.89s/it]
%|          | 0/25 [00:00<?, ?it/s]
%|▍         | 1/25 [00:00<00:19,  1.25it/s]
%|▊         | 2/25 [00:01<00:18,  1.23it/s]
%|█▏        | 3/25 [00:02<00:17,  1.25it/s]
%|█▌        | 4/25 [00:03<00:16,  1.24it/s]
%|██        | 5/25 [00:03<00:15,  1.26it/s]
%|██▍       | 6/25 [00:04<00:15,  1.25it/s]
%|██▊       | 7/25 [00:05<00:14,  1.26it/s]
%|███▏      | 8/25 [00:06<00:13,  1.23it/s]
%|███▌      | 9/25 [00:07<00:12,  1.24it/s]
%|████      | 10/25 [00:07<00:11,  1.27it/s]
%|████▍     | 11/25 [00:08<00:10,  1.28it/s]
%|████▊     | 12/25 [00:09<00:10,  1.24it/s]
%|█████▏    | 13/25 [00:10<00:09,  1.24it/s]
%|█████▌    | 14/25 [00:11<00:08,  1.23it/s]
%|██████    | 15/25 [00:12<00:08,  1.24it/s]
%|██████▍   | 16/25 [00:12<00:07,  1.24it/s]
%|██████▊   | 17/25 [00:13<00:06,  1.24it/s]
%|███████▏  | 18/25 [00:14<00:05,  1.22it/s]
%|███████▌  | 19/25 [00:15<00:04,  1.23it/s]
%|████████  | 20/25 [00:16<00:04,  1.25it/s]
%|████████▍ | 21/25 [00:16<00:03,  1.22it/s]
%|████████▊ | 22/25 [00:17<00:02,  1.22it/s]
%|█████████▏| 23/25 [00:18<00:01,  1.24it/s]
%|█████████▌| 24/25 [00:19<00:00,  1.23it/s]
100%|██████████| 25/25 [00:20<00:00,  1.24it/s]
 86%|████████▌ | 6/7 [05:05<00:35, 35.82s/it]
%|          | 0/99 [00:00<?, ?it/s]
%|          | 1/99 [00:00<01:19,  1.23it/s]
%|▏         | 2/99 [00:01<01:07,  1.44it/s]
%|▎         | 3/99 [00:02<01:12,  1.33it/s]
%|▍         | 4/99 [00:03<01:15,  1.26it/s]
%|▌         | 5/99 [00:03<01:15,  1.24it/s]
%|▌         | 6/99 [00:04<01:13,  1.26it/s]
%|▋         | 7/99 [00:05<01:15,  1.23it/s]
%|▊         | 8/99 [00:06<01:14,  1.23it/s]
%|▉         | 9/99 [00:07<01:12,  1.24it/s]
%|█         | 10/99 [00:07<01:12,  1.23it/s]
%|█         | 11/99 [00:08<01:11,  1.23it/s]
%|█▏        | 12/99 [00:09<01:10,  1.23it/s]
%|█▎        | 13/99 [00:10<01:09,  1.23it/s]
%|█▍        | 14/99 [00:11<01:08,  1.23it/s]
%|█▌        | 15/99 [00:11<01:06,  1.26it/s]
%|█▌        | 16/99 [00:12<01:03,  1.30it/s]
%|█▋        | 17/99 [00:13<01:04,  1.27it/s]
%|█▊        | 18/99 [00:14<01:04,  1.26it/s]
%|█▉        | 19/99 [00:15<01:00,  1.32it/s]
%|██        | 20/99 [00:15<01:01,  1.29it/s]
%|██        | 21/99 [00:16<00:58,  1.33it/s]
%|██▏       | 22/99 [00:17<00:59,  1.30it/s]
%|██▎       | 23/99 [00:17<00:55,  1.36it/s]
%|██▍       | 24/99 [00:18<00:54,  1.39it/s]
%|██▌       | 25/99 [00:19<00:54,  1.35it/s]
%|██▋       | 26/99 [00:20<00:56,  1.30it/s]
%|██▋       | 27/99 [00:21<00:55,  1.30it/s]
%|██▊       | 28/99 [00:21<00:55,  1.27it/s]
%|██▉       | 29/99 [00:22<00:55,  1.27it/s]
%|███       | 30/99 [00:23<00:53,  1.29it/s]
%|███▏      | 31/99 [00:24<00:52,  1.29it/s]
%|███▏      | 32/99 [00:25<00:52,  1.28it/s]
%|███▎      | 33/99 [00:25<00:52,  1.26it/s]
%|███▍      | 34/99 [00:26<00:51,  1.26it/s]
%|███▌      | 35/99 [00:27<00:50,  1.26it/s]
%|███▋      | 36/99 [00:28<00:49,  1.26it/s]
%|███▋      | 37/99 [00:29<00:49,  1.25it/s]
%|███▊      | 38/99 [00:29<00:48,  1.25it/s]
%|███▉      | 39/99 [00:30<00:48,  1.23it/s]
%|████      | 40/99 [00:31<00:46,  1.26it/s]
%|████▏     | 41/99 [00:32<00:45,  1.27it/s]
%|████▏     | 42/99 [00:32<00:43,  1.30it/s]
%|████▎     | 43/99 [00:33<00:41,  1.34it/s]
%|████▍     | 44/99 [00:34<00:41,  1.32it/s]
%|████▌     | 45/99 [00:35<00:41,  1.31it/s]
%|████▋     | 46/99 [00:35<00:41,  1.29it/s]
%|████▋     | 47/99 [00:36<00:41,  1.25it/s]
%|████▊     | 48/99 [00:37<00:41,  1.24it/s]
%|████▉     | 49/99 [00:38<00:40,  1.25it/s]
%|█████     | 50/99 [00:39<00:40,  1.22it/s]
%|█████▏    | 51/99 [00:40<00:38,  1.23it/s]
%|█████▎    | 52/99 [00:40<00:37,  1.26it/s]
%|█████▎    | 53/99 [00:41<00:36,  1.24it/s]
%|█████▍    | 54/99 [00:42<00:36,  1.23it/s]
%|█████▌    | 55/99 [00:43<00:35,  1.23it/s]
%|█████▋    | 56/99 [00:44<00:35,  1.23it/s]
%|█████▊    | 57/99 [00:44<00:34,  1.23it/s]
%|█████▊    | 58/99 [00:45<00:33,  1.21it/s]
%|█████▉    | 59/99 [00:46<00:32,  1.24it/s]
%|██████    | 60/99 [00:47<00:30,  1.28it/s]
%|██████▏   | 61/99 [00:48<00:29,  1.28it/s]
%|██████▎   | 62/99 [00:48<00:28,  1.29it/s]
%|██████▎   | 63/99 [00:49<00:28,  1.28it/s]
%|██████▍   | 64/99 [00:50<00:28,  1.25it/s]
%|██████▌   | 65/99 [00:51<00:27,  1.26it/s]
%|██████▋   | 66/99 [00:52<00:26,  1.24it/s]

In [112]:
# print(remove_text_before_pattern(aspect_query_res[test_aspect][test_query][aspect_query_res[test_aspect][test_query].token_count>600].loc[9].descriptions))
len(aspect_query_res[test_aspect][test_query][aspect_query_res[test_aspect][test_query].token_count>650])

14

In [114]:
print(aspect_query_res[test_aspect][test_query][aspect_query_res[test_aspect][test_query].token_count>650].descriptions.iloc[0])

international trading companies, international presence, logistics sectors, international regulations, international trade, api connectors, financial services compliance, export transactions, business litigation, international legal professionals, international events, key authorities, business banking, logistics services, key competitors, business management functions, trade secret protection, business services, business printing, business loan, key differentiators, partner program, analytics services, business loans & lines of, business intelligence software, debt collection, business checking, business customers, import containers, business software solutions, debt recovery, lenders, business clients, facilitation services, logistics industry, business profile, logistics platform, business management support, business travel management solutions, business model, payment services, payment processing volume, logistics management,
 okay , here 's the final the company company fact sheet based on our research .    keep in mind that due to the limited information publicly available on their website and through standard online searches , some aspects remain incomplete .    further investigation , potentially including direct contact with nu - credits , would be beneficial for a more comprehensive understanding .


 * * the company company fact sheet * *

 * * 1 .   overview :* *

 the company positions itself as a provider of " business finance without borders , " offering a " cross - border , 24 - hour finance solution . "   their stated aim is to deliver efficient , flexible , and competitive financial solutions for businesses involved in international trade .

 * * 2 .   products , services , and offerings :* *

 * * * import / export finance :* *   facilitates financing for both import and export transactions .
 * * * payment services :* *   offers payment processing and facilitation services for international trade .
 * * * data analytics ( for lenders ): * *   provides analytical tools and insights to lenders .
 * * * debt collection ( for lenders ): * *   assists lenders with debt recovery .
 * * * referral program :* *   a partner program for client referrals .
 * * * api market :* *   offers an api for integration with other systems .

 * * 3 .   industry and target audience :* *

 the company operates within the * * fintech * * industry , specializing in * * cross - border b2b finance * * .   their target audience includes :

 * * * importers :* * businesses importing goods internationally .
 * * * exporters :* * businesses exporting goods internationally .
 * * * lenders :* * financial institutions providing trade finance .
 * * * partners :* * logistics companies , banks , third - party service providers , and referral partners .

 * * 4 .   unique selling propositions ( usps ) and key differentiators :* *

 the company highlights :

 * * * speed :* *   promises invoice payment ( minus fees ) within 24 hours of receipt .
 * * * global reach :* *   emphasizes their cross - border capabilities .
 * * * efficiency :* *   claims to offer efficient and flexible solutions .
 * * * 24/7 availability :* *   markets itself as a 24 - hour finance solution .

 however , concrete differentiators compared to competitors require further investigation .

 * * 5 .   business model :* *

 the company employs a * * b2b * * model , providing financial services to businesses and lenders involved in international trade .

 * * 6 .   revenue model :* *

 the revenue model is presumed to be * * transaction - based fees * * , charged per transaction facilitated on their platform .    specific fee structures are not publicly available .

 * * 7 .   technology used :* *

 the specific technology stack is not publicly disclosed .

 * * 8 .   competitive landscape :* *

 identifying direct competitors proved challenging due to the broad nature of the cross - border b2b finance market and the lack of specific details regarding nu - credits ' niche .    further research is needed to identify and analyze key competitors .

 * * 9 .   funding :* *

 the company has received funding from the european union 's horizon 2020 program .    no other funding rounds were identified through our research .

 * * 10 .   market analysis :* *

 our research indicated a growing market for cross - border b2b finance and fintech solutions .   however , we did not find specific market analysis reports focused on the company or its precise market segment .    general market trend reports from sources like statista and bank of america were reviewed , but did not contain specific data on nu - credits .

 * * 11 .   additional notes :* *

 nu - credits ' website lacks detailed information on pricing , technology , and competitive positioning .    further research , including potentially contacting the company directly , is strongly recommended for a more complete assessment .

In [117]:
### filtering oput factsheets that exceed max token limit of colbert: keeping the threshold a bit relaxed since the information in the end is usually junk and not needed anyway
for aspect,q_dict in tqdm(aspect_query_res.items()):
    for query,res in tqdm(q_dict.items()):
        res=res[res.token_count<=650]
        aspect_query_res[aspect][query]=res
        print(len(res),aspect,query)

  0%|          | 0/7 [00:00<?, ?it/s]
100%|██████████| 99/99 [00:00<00:00, 3113.62it/s]

74 Industry Entertainment
68 Industry Real Estate
64 Industry Biotechnology
80 Industry Insurance
94 Industry Legal
64 Industry Defense
78 Industry Telecommunications
65 Industry Utilities
77 Industry Pharmaceutical
77 Industry Hospitality
66 Industry Automotive
71 Industry Energy
77 Industry Technology
75 Industry Banking
65 Industry Fashion
74 Industry Chemicals
66 Industry Food and Beverage
65 Industry Renewable Energy
90 Industry Mining
80 Industry Logistics
82 Industry Beauty
83 Industry Agriculture
77 Industry Media
76 Industry Construction
72 Industry Consumer Electronics
68 Industry Education
86 Industry Finance
82 Industry Manufacturing
81 Industry Aerospace
73 Industry Healthcare
84 Industry Transportation
83 Industry Retail
80 Industry Public Sector
82 Industry Non-Profit
75 Industry Sports
75 Industry Gaming
78 Industry Paper and Pulp
77 Industry Fishing
78 Industry Furniture
82 Industry Marine
83 Industry Printing
84 Industry Advertising
77 Industry Textiles
79 Industry Ceramics
75 Industry Petroleum
64 Industry Metals
74 Industry Forestry
77 Industry Plastics
83 Industry Tobacco
70 Industry Glass
75 Industry Jewelry
74 Industry Consulting
77 Industry Travel
82 Industry Tourism
81 Industry Event Management
79 Industry E-commerce
70 Industry Cybersecurity
78 Industry Human Resources
86 Industry Information Technology
70 Industry Hardware Manufacturing
80 Industry Software Development
64 Industry Broadcasting
78 Industry Publishing
62 Industry Music Industry
88 Industry Film Production
80 Industry Animation
82 Industry Virtual Reality
88 Industry Augmented Reality
72 Industry Smart Home Technology
78 Industry Wearable Technology
76 Industry Artificial Intelligence
81 Industry Nanotechnology
71 Industry Machine Learning
73 Industry Internet of Things
80 Industry Robotics
76 Industry Proptech
73 Industry Agritech
73 Industry Satellite Technology
81 Industry 3D Printing
74 Industry Data Analytics
85 Industry Blockchain
75 Industry Healthtech
76 Industry Edtech
90 Industry Fintech
77 Industry Space Exploration
75 Industry Quantum Computing
73 Industry Cleantech
88 Industry Foodtech
77 Industry Medtech
79 Industry Insurtech
74 Industry Govtech
75 Industry Legaltech
81 Industry Regtech
68 Industry Martech
78 Industry Adtech
74 Industry Retailtech
69 Industry Logitech
84 Industry Supply Chain Management
78 Industry Customer Relationship Management

100%|██████████| 102/102 [00:00<00:00, 3183.11it/s]

87 Customer Segment Financial institutions
84 Customer Segment Pet care services
86 Customer Segment Beauty salons
77 Customer Segment Sports teams
84 Customer Segment Doctors
88 Customer Segment Pharmaceutical companies
81 Customer Segment Small businesses
78 Customer Segment Fitness centers
88 Customer Segment Government agencies
93 Customer Segment Logistics companies
79 Customer Segment Fashion brands
81 Customer Segment Automotive industry
86 Customer Segment Hospitality industry
91 Customer Segment Manufacturing companies
84 Customer Segment Travel agencies
83 Customer Segment Retailers
83 Customer Segment Consumer electronics
84 Customer Segment Lawyers
78 Customer Segment Healthcare providers
79 Customer Segment E-commerce businesses
84 Customer Segment Event planners
91 Customer Segment Energy companies
84 Customer Segment Restaurants
80 Customer Segment Media companies
79 Customer Segment Educational institutions
80 Customer Segment Telecommunications providers
81 Customer Segment Non-profit organizations
76 Customer Segment Tech startups
82 Customer Segment Construction firms
77 Customer Segment Real estate developers
79 Customer Segment Enterprise customers
90 Customer Segment Agricultural businesses
81 Customer Segment Insurance companies
80 Customer Segment Banks
76 Customer Segment Investment firms
80 Customer Segment Venture capitalists
87 Customer Segment Private equity firms
85 Customer Segment Credit unions
85 Customer Segment Public relations firms
84 Customer Segment Consulting firms
88 Customer Segment Hedge funds
85 Customer Segment Human resources departments
80 Customer Segment Accounting firms
73 Customer Segment Universities
78 Customer Segment Hospitals
84 Customer Segment Advertising agencies
82 Customer Segment Colleges
89 Customer Segment Daycare centers
82 Customer Segment Marketing agencies
76 Customer Segment Elementary schools
75 Customer Segment High schools
86 Customer Segment Senior living facilities
85 Customer Segment Legal departments
81 Customer Segment Clinics
84 Customer Segment Research institutions
81 Customer Segment Dental practices
81 Customer Segment Preschools
84 Customer Segment Veterinary clinics
85 Customer Segment Pharmacies
79 Customer Segment Supermarkets
83 Customer Segment Online retailers
79 Customer Segment Convenience stores
85 Customer Segment Wholesale distributors
81 Customer Segment Import/export businesses
81 Customer Segment Car dealerships
83 Customer Segment Motorcycle dealerships
78 Customer Segment Home improvement stores
82 Customer Segment Furniture stores
83 Customer Segment Garden centers
79 Customer Segment Bicycle shops
89 Customer Segment Art galleries
88 Customer Segment Music stores
87 Customer Segment Toy stores
87 Customer Segment Airlines
89 Customer Segment Museums
83 Customer Segment Bookstores
84 Customer Segment Hotels
83 Customer Segment Cinemas
98 Customer Segment Motels
77 Customer Segment Resorts
86 Customer Segment Theaters
90 Customer Segment Shipping companies
87 Customer Segment Bus companies
88 Customer Segment Hostels
87 Customer Segment Concert venues
84 Customer Segment Sports arenas
86 Customer Segment Ride-sharing services
77 Customer Segment Stadiums
77 Customer Segment Rail companies
90 Customer Segment Spas
85 Customer Segment Bed and breakfasts
81 Customer Segment Gyms
86 Customer Segment Taxi services
85 Customer Segment Car rental services
81 Customer Segment Software companies
84 Customer Segment Hardware companies
86 Customer Segment Biotech companies
84 Customer Segment Medical device companies
91 Customer Segment Chemical companies
77 Customer Segment Mining companies
82 Customer Segment Forestry companies
83 Customer Segment Fishing companies

100%|██████████| 98/98 [00:00<00:00, 3123.06it/s]
 43%|████▎     | 3/7 [00:00<00:00, 29.00it/s]

63 Products & Services Mobile payment solutions
80 Products & Services Telehealth services
81 Products & Services Accounting software
72 Products & Services Supply chain management solutions
63 Products & Services E-commerce platforms
81 Products & Services Podcast hosting services
84 Products & Services HR management platforms
69 Products & Services Video conferencing software
76 Products & Services Online learning platforms
84 Products & Services Fitness tracking apps
68 Products & Services Customer support chatbots
67 Products & Services Cloud storage services
74 Products & Services Project management software
77 Products & Services Electric vehicle charging stations
81 Products & Services Augmented reality applications
94 Products & Services Subscription box services
74 Products & Services 3D printing services
72 Products & Services CRM software
76 Products & Services Online grocery delivery
65 Products & Services Home automation devices
89 Products & Services Online dating apps
81 Products & Services Freelance marketplace
68 Products & Services Renewable energy solutions
73 Products & Services Social media management tools
79 Products & Services Virtual reality experiences
81 Products & Services Online travel booking
71 Products & Services Data analytics tools
82 Products & Services Music streaming platforms
70 Products & Services Cybersecurity services
64 Products & Services Digital marketing tools
83 Products & Services Food delivery services
78 Products & Services Content management systems
68 Products & Services Personal finance management tools
78 Products & Services Blockchain development services
73 Products & Services Remote work solutions
79 Products & Services Business intelligence software
79 Products & Services Online gaming platforms
80 Products & Services Digital asset management
80 Products & Services Email marketing services
78 Products & Services Inventory management systems
89 Products & Services Affiliate marketing networks
82 Products & Services Web hosting services
68 Products & Services Payment gateway services
61 Products & Services Smart home security systems
79 Products & Services Employee wellness programs
63 Products & Services Cybersecurity training
79 Products & Services Online course creation platforms
91 Products & Services Crowdfunding platforms
85 Products & Services Property management software
71 Products & Services SEO optimization tools
78 Products & Services Virtual event platforms
87 Products & Services Legal document automation
77 Products & Services Fleet management solutions
67 Products & Services Point of sale systems
84 Products & Services Data privacy solutions
71 Products & Services Drone delivery services
75 Products & Services Digital signature services
75 Products & Services Online auction platforms
83 Products & Services Online fundraising platforms
84 Products & Services Online therapy services
85 Products & Services On-demand staffing platforms
84 Products & Services Virtual assistant services
89 Products & Services Event management platforms
77 Products & Services Online survey tools
82 Products & Services Peer-to-peer lending services
87 Products & Services Online job boards
78 Products & Services Digital health records
81 Products & Services Remote patient monitoring
77 Products & Services Telecom expense management
82 Products & Services Mobile app development
81 Products & Services E-book publishing platforms
71 Products & Services Online stock trading
71 Products & Services Digital currency exchange
70 Products & Services Online language learning
66 Products & Services Cloud-based call centers
85 Products & Services Video editing software
79 Products & Services AI-powered writing tools
65 Products & Services Smart contract development
79 Products & Services Online reputation management
79 Products & Services Workforce management software
83 Products & Services B2B marketplace
70 Products & Services Online ticketing systems
83 Products & Services Online tutoring services
72 Products & Services Augmented reality shopping
76 Products & Services Virtual coworking spaces
81 Products & Services Online portfolio management
85 Products & Services Live streaming platforms
87 Products & Services Online car rental services
75 Products & Services Online fitness classes
72 Products & Services Digital signage solutions
92 Products & Services Online notarization services
87 Products & Services Online pet care services
67 Products & Services Voice recognition software
72 Products & Services Virtual fitting rooms
73 Products & Services Robotic process automation
66 Products & Services Digital transformation consulting
82 Products & Services Eco-friendly packaging solutions
92 Products & Services Online interior design services

100%|██████████| 10/10 [00:00<00:00, 3024.01it/s]

83 Business Model Franchise
85 Business Model B2B
76 Business Model Freemium
78 Business Model Marketplace
77 Business Model B2C
87 Business Model On-demand
80 Business Model Subscription-based
89 Business Model Peer-to-peer
91 Business Model Licensing
87 Business Model Direct sales

100%|██████████| 30/30 [00:00<00:00, 3135.07it/s]

73 Technology Used Augmented reality
63 Technology Used Blockchain
75 Technology Used AI
83 Technology Used Computer vision
80 Technology Used Natural language processing
73 Technology Used Chatbots
87 Technology Used Neural networks
59 Technology Used Biometrics
81 Technology Used Deep learning
75 Technology Used RPA (Robotic Process Automation)
72 Technology Used IoT
71 Technology Used Cybersecurity solutions
67 Technology Used Edge computing
81 Technology Used Voice recognition
64 Technology Used Smart contracts
77 Technology Used Quantum computing
83 Technology Used Facial recognition
75 Technology Used 5G technology
69 Technology Used Geolocation services
78 Technology Used Autonomous vehicles
81 Technology Used Machine learning
80 Technology Used Robotics
70 Technology Used Big data analytics
83 Technology Used Digital twins
64 Technology Used Cryptography
74 Technology Used Microservices architecture
63 Technology Used Wearable technology
71 Technology Used 3D printing
76 Technology Used Virtual reality
78 Technology Used Cloud computing

100%|██████████| 25/25 [00:00<00:00, 3167.14it/s]

80 Revenue Model Pay-per-use
89 Revenue Model Subscription-based
86 Revenue Model Marketplace
87 Revenue Model Commission
90 Revenue Model Licensing
83 Revenue Model Crowdsourcing
90 Revenue Model Freemium
79 Revenue Model Consulting fees
89 Revenue Model PaaS
88 Revenue Model SaaS
89 Revenue Model Royalties
80 Revenue Model Advertising
82 Revenue Model Wholesale
86 Revenue Model Retail
87 Revenue Model Affiliate
91 Revenue Model Direct sales
82 Revenue Model Franchise
80 Revenue Model Membership
91 Revenue Model B2C
81 Revenue Model B2B
72 Revenue Model Microtransactions
86 Revenue Model Sponsorship
86 Revenue Model Leasing
84 Revenue Model In-app purchases
83 Revenue Model Donation

100%|██████████| 99/99 [00:00<00:00, 3203.56it/s]
100%|██████████| 7/7 [00:00<00:00, 41.98it/s]

84 Customer Industry Automotive
92 Customer Industry Mining
78 Customer Industry Retail
82 Customer Industry Banking
78 Customer Industry Food and Beverage
89 Customer Industry Finance
79 Customer Industry Entertainment
82 Customer Industry Fashion
89 Customer Industry Logistics
86 Customer Industry Agriculture
79 Customer Industry Transportation
80 Customer Industry Utilities
79 Customer Industry Insurance
84 Customer Industry Aerospace
84 Customer Industry Manufacturing
88 Customer Industry Telecommunications
79 Customer Industry Real Estate
83 Customer Industry Renewable Energy
94 Customer Industry Technology
91 Customer Industry Defense
95 Customer Industry Energy
88 Customer Industry Hospitality
93 Customer Industry Chemicals
88 Customer Industry Education
86 Customer Industry Healthcare
79 Customer Industry Construction
87 Customer Industry Consumer Electronics
83 Customer Industry Pharmaceutical
80 Customer Industry Beauty
90 Customer Industry Biotechnology
84 Customer Industry Legal
83 Customer Industry Media
83 Customer Industry Public Sector
87 Customer Industry Non-Profit
90 Customer Industry Sports
86 Customer Industry Textiles
81 Customer Industry Gaming
84 Customer Industry Furniture
82 Customer Industry Ceramics
85 Customer Industry Marine
85 Customer Industry Forestry
94 Customer Industry Information Technology
94 Customer Industry Cybersecurity
86 Customer Industry Jewelry
89 Customer Industry Tobacco
89 Customer Industry Fishing
74 Customer Industry Consulting
85 Customer Industry Plastics
85 Customer Industry Event Management
77 Customer Industry Broadcasting
89 Customer Industry Travel
91 Customer Industry Printing
81 Customer Industry Human Resources
71 Customer Industry Paper and Pulp
78 Customer Industry Music Industry
82 Customer Industry E-commerce
85 Customer Industry Tourism
82 Customer Industry Hardware Manufacturing
92 Customer Industry Petroleum
92 Customer Industry Metals
91 Customer Industry Publishing
89 Customer Industry Glass
84 Customer Industry Software Development
77 Customer Industry Advertising
89 Customer Industry Film Production
81 Customer Industry Animation
76 Customer Industry Virtual Reality
81 Customer Industry Augmented Reality
90 Customer Industry Smart Home Technology
86 Customer Industry Wearable Technology
87 Customer Industry Machine Learning
94 Customer Industry Nanotechnology
88 Customer Industry Artificial Intelligence
89 Customer Industry Data Analytics
90 Customer Industry Internet of Things
86 Customer Industry Blockchain
89 Customer Industry Quantum Computing
76 Customer Industry Robotics
86 Customer Industry 3D Printing
89 Customer Industry Space Exploration
85 Customer Industry Satellite Technology
87 Customer Industry Fintech
92 Customer Industry Proptech
83 Customer Industry Agritech
94 Customer Industry Cleantech
93 Customer Industry Edtech
84 Customer Industry Healthtech
87 Customer Industry Foodtech
89 Customer Industry Medtech
83 Customer Industry Insurtech
79 Customer Industry Govtech
90 Customer Industry Regtech
87 Customer Industry Legaltech
90 Customer Industry Martech
82 Customer Industry Adtech
86 Customer Industry Retailtech
81 Customer Industry Logitech
76 Customer Industry Supply Chain Management
72 Customer Industry Customer Relationship Management

In [118]:
with open('../synthetic_data/aspect_query_fetched_positives_filtered_tokc.pkl','wb') as f:
    pickle.dump(aspect_query_res,f)

In [116]:
test_aspect='Customer Industry'
test_aspect='Business Model'
test_aspect='Technology Used'
test_aspect='Revenue Model'
# 'Mining', 'Retail', 'Banking'
test_query='Automotive'
test_query='Mining'
test_query='Banking'
test_query='B2B'
test_query='Computer vision'
test_query='Pay-per-use'
test_query='Marketplace'
aspect_query_res[test_aspect].keys()
factsheet=aspect_query_res[test_aspect][test_query].descriptions.iloc[10]

In [82]:
aspect_query_res['Revenue Model'].keys()

dict_keys(['Pay-per-use', 'Subscription-based', 'Marketplace', 'Commission', 'Licensing', 'Crowdsourcing', 'Freemium', 'Consulting fees', 'PaaS', 'SaaS', 'Royalties', 'Advertising', 'Wholesale', 'Retail', 'Affiliate', 'Direct sales', 'Franchise', 'Membership', 'B2C', 'B2B', 'Microtransactions', 'Sponsorship', 'Leasing', 'In-app purchases', 'Donation'])

In [83]:
filter_companies(test_aspect,test_query,factsheet)

(True, {'decision': 'YES'})

In [85]:
print(remove_text_before_pattern(factsheet))

* * africa sokoni fact sheet * *

 * * 1 .   company overview :* * africa sokoni is a company ( inferred from the   . the company   domain ) aiming to empower micro , small , and medium - sized enterprises ( msmes ) across africa .    their mission is to provide comprehensive support , encompassing financing , e - commerce solutions , and various value - added services .

 * * 2 .   products and services :* *

 * * * fintech services :* *   access to working capital through tailored financing solutions .
 * * * e - commerce platform :* * a multi - vendor marketplace with features like merchant central , ready market , sales insights , and a white label program .
 * * * value - added services :* * business consultancy , training programs , custom solutions , legal and compliance assistance , technology integration , and market research and insights .
 * * * supply chain management :* * a state - of - the - art logistics and warehousing system designed to streamline and automate supply chain processes .

 * * 3 .   industry and target audience :* *   africa sokoni operates within the fintech and e - commerce industries , specifically targeting msmes across africa .

 * * 4 .   unique selling propositions ( usps ): * *

 * * * holistic approach :* *   offers a comprehensive suite of services addressing multiple needs of msmes .
 * * * msme focus :* *   specifically tailored to the challenges and opportunities faced by african msmes .
 * * * advanced supply chain technology :* *   leverages technology to improve efficiency and automation in logistics and warehousing .

 * * 5 .   business model :* *   africa sokoni functions as a b2b marketplace and a provider of value - added services .    it 's likely a hybrid model incorporating transaction fees from the marketplace , fees for consulting and other services , and potentially revenue sharing or fees related to the financing solutions offered .

 * * 6 .   technology used :* *   while not explicitly detailed , the company uses technology for its e - commerce platform , supply chain management system , and likely for financial services integration .    specific technologies remain unknown without further investigation .

 * * 7 .   revenue model :* *   the revenue model is likely multi - faceted , combining transaction fees ( marketplace ) , service fees ( consulting , training , etc . ) , and potentially revenue sharing or fees from the financing arm of the business .

 * * 8 .   competitive landscape :* *   this requires further research beyond the website .    identifying key competitors in the msme support and e - commerce space would require a competitive analysis .


 this fact sheet provides a solid foundation for further due diligence .    additional research into their financials , technology stack , and competitive landscape would provide a more complete picture for investment consideration .

In [139]:

query_positve_dict={}
for aspect,q_dict in tqdm(aspect_query_res.items()):
    for query,res in q_dict.items():
        query_positve_dict[(aspect,query)]=[]
        
        factsheets=res['descriptions'].to_list()
        args=[([aspect,query,factsheet],{}) for factsheet in factsheets]

        res=parallel_execute(
                        func= filter_companies,
                        argument_sets=args,
                        max_workers = 128,
                        show_progress= True,
                        desc = "judging factsheets retrieved"
                    )
        query_positve_dict[(aspect,query)]=list(zip([remove_text_before_pattern(factsheet) for factsheet in factsheets],res))

  0%|          | 0/7 [00:00<?, ?it/s]
ging factsheets retrieved:   0%|          | 0/74 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/74 [00:00<00:20,  3.54it/s]
ging factsheets retrieved:  18%|█▊        | 13/74 [00:00<00:01, 39.64it/s]
ging factsheets retrieved:  31%|███       | 23/74 [00:00<00:00, 54.17it/s]
ging factsheets retrieved:  41%|████      | 30/74 [00:00<00:00, 54.23it/s]
ging factsheets retrieved:  50%|█████     | 37/74 [00:00<00:00, 54.26it/s]
ging factsheets retrieved:  58%|█████▊    | 43/74 [00:00<00:00, 55.26it/s]
ging factsheets retrieved:  66%|██████▌   | 49/74 [00:01<00:00, 53.18it/s]
ging factsheets retrieved:  74%|███████▍  | 55/74 [00:01<00:00, 50.55it/s]
ging factsheets retrieved:  82%|████████▏ | 61/74 [00:01<00:00, 51.60it/s]
ging factsheets retrieved:  91%|█████████ | 67/74 [00:01<00:00, 44.43it/s]
judging factsheets retrieved: 100%|██████████| 74/74 [00:04<00:00, 16.81it/s]

ging factsheets retrieved:   0%|          | 0/68 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/68 [00:00<00:14,  4.68it/s]
ging factsheets retrieved:   6%|▌         | 4/68 [00:00<00:04, 14.40it/s]
ging factsheets retrieved:  22%|██▏       | 15/68 [00:00<00:01, 48.54it/s]
ging factsheets retrieved:  37%|███▋      | 25/68 [00:00<00:00, 61.43it/s]
ging factsheets retrieved:  47%|████▋     | 32/68 [00:00<00:00, 46.69it/s]
ging factsheets retrieved:  62%|██████▏   | 42/68 [00:00<00:00, 56.67it/s]
ging factsheets retrieved:  79%|███████▉  | 54/68 [00:01<00:00, 69.81it/s]
judging factsheets retrieved: 100%|██████████| 68/68 [00:01<00:00, 47.84it/s]

ging factsheets retrieved:   0%|          | 0/64 [00:00<?, ?it/s]
ging factsheets retrieved:   2%|▏         | 1/64 [00:00<00:18,  3.35it/s]
ging factsheets retrieved:  14%|█▍        | 9/64 [00:00<00:02, 27.47it/s]
ging factsheets retrieved:  34%|███▍      | 22/64 [00:00<00:00, 56.49it/s]
ging factsheets retrieved:  47%|████▋     | 30/64 [00:00<00:00, 63.24it/s]
ging factsheets retrieved:  59%|█████▉    | 38/64 [00:00<00:00, 48.09it/s]
ging factsheets retrieved:  77%|███████▋  | 49/64 [00:00<00:00, 62.04it/s]
judging factsheets retrieved: 100%|██████████| 64/64 [00:01<00:00, 36.44it/s]

ging factsheets retrieved:   0%|          | 0/80 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/80 [00:00<00:19,  4.01it/s]
ging factsheets retrieved:  12%|█▎        | 10/80 [00:00<00:02, 34.84it/s]
ging factsheets retrieved:  26%|██▋       | 21/80 [00:00<00:00, 59.63it/s]
ging factsheets retrieved:  36%|███▋      | 29/80 [00:00<00:00, 53.43it/s]
ging factsheets retrieved:  45%|████▌     | 36/80 [00:00<00:00, 51.92it/s]
ging factsheets retrieved:  56%|█████▋    | 45/80 [00:01<00:00, 37.51it/s]
ging factsheets retrieved:  72%|███████▎  | 58/80 [00:01<00:00, 40.57it/s]
ging factsheets retrieved:  90%|█████████ | 72/80 [00:01<00:00, 56.48it/s]
judging factsheets retrieved: 100%|██████████| 80/80 [00:03<00:00, 23.33it/s]

ging factsheets retrieved:   0%|          | 0/94 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|          | 1/94 [00:00<00:18,  4.90it/s]
ging factsheets retrieved:   4%|▍         | 4/94 [00:00<00:06, 14.31it/s]
ging factsheets retrieved:  21%|██▏       | 20/94 [00:00<00:01, 58.52it/s]
ging factsheets retrieved:  32%|███▏      | 30/94 [00:00<00:00, 64.78it/s]
ging factsheets retrieved:  39%|███▉      | 37/94 [00:00<00:01, 52.89it/s]
ging factsheets retrieved:  46%|████▌     | 43/94 [00:00<00:00, 53.10it/s]
ging factsheets retrieved:  60%|█████▉    | 56/94 [00:01<00:00, 70.73it/s]
ging factsheets retrieved:  68%|██████▊   | 64/94 [00:01<00:00, 62.20it/s]
ging factsheets retrieved:  76%|███████▌  | 71/94 [00:01<00:00, 55.35it/s]
ging factsheets retrieved:  83%|████████▎ | 78/94 [00:01<00:00, 57.07it/s]
judging factsheets retrieved: 100%|██████████| 94/94 [00:05<00:00, 18.50it/s]

ging factsheets retrieved:   0%|          | 0/64 [00:00<?, ?it/s]
ging factsheets retrieved:   2%|▏         | 1/64 [00:00<00:18,  3.34it/s]
ging factsheets retrieved:  17%|█▋        | 11/64 [00:00<00:01, 34.44it/s]
ging factsheets retrieved:  39%|███▉      | 25/64 [00:00<00:00, 65.40it/s]
ging factsheets retrieved:  53%|█████▎    | 34/64 [00:00<00:00, 49.33it/s]
ging factsheets retrieved:  64%|██████▍   | 41/64 [00:00<00:00, 50.10it/s]
ging factsheets retrieved:  84%|████████▍ | 54/64 [00:01<00:00, 64.04it/s]
judging factsheets retrieved: 100%|██████████| 64/64 [00:04<00:00, 12.86it/s]

ging factsheets retrieved:   0%|          | 0/78 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/78 [00:00<00:23,  3.25it/s]
ging factsheets retrieved:  19%|█▉        | 15/78 [00:00<00:01, 43.09it/s]
ging factsheets retrieved:  28%|██▊       | 22/78 [00:00<00:01, 48.49it/s]
ging factsheets retrieved:  37%|███▋      | 29/78 [00:00<00:00, 53.94it/s]
ging factsheets retrieved:  46%|████▌     | 36/78 [00:00<00:00, 48.28it/s]
ging factsheets retrieved:  56%|█████▋    | 44/78 [00:00<00:00, 55.57it/s]
ging factsheets retrieved:  69%|██████▉   | 54/78 [00:01<00:00, 61.76it/s]
ging factsheets retrieved:  78%|███████▊  | 61/78 [00:01<00:00, 57.35it/s]
ging factsheets retrieved:  87%|████████▋ | 68/78 [00:01<00:00, 50.87it/s]
judging factsheets retrieved: 100%|██████████| 78/78 [00:06<00:00, 12.47it/s]

ging factsheets retrieved:   0%|          | 0/65 [00:00<?, ?it/s]
ging factsheets retrieved:   2%|▏         | 1/65 [00:00<00:12,  5.12it/s]
ging factsheets retrieved:   9%|▉         | 6/65 [00:00<00:02, 23.72it/s]
ging factsheets retrieved:  22%|██▏       | 14/65 [00:00<00:01, 44.19it/s]
ging factsheets retrieved:  38%|███▊      | 25/65 [00:00<00:00, 66.41it/s]
ging factsheets retrieved:  51%|█████     | 33/65 [00:00<00:00, 57.49it/s]
ging factsheets retrieved:  62%|██████▏   | 40/65 [00:00<00:00, 58.78it/s]
ging factsheets retrieved:  72%|███████▏  | 47/65 [00:00<00:00, 58.23it/s]
ging factsheets retrieved:  86%|████████▌ | 56/65 [00:01<00:00, 55.72it/s]
judging factsheets retrieved: 100%|██████████| 65/65 [00:01<00:00, 36.73it/s]

ging factsheets retrieved:   0%|          | 0/77 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/77 [00:00<00:19,  3.92it/s]
ging factsheets retrieved:  16%|█▌        | 12/77 [00:00<00:01, 41.22it/s]
ging factsheets retrieved:  25%|██▍       | 19/77 [00:00<00:02, 28.77it/s]
ging factsheets retrieved:  45%|████▌     | 35/77 [00:00<00:00, 54.50it/s]
ging factsheets retrieved:  56%|█████▌    | 43/77 [00:01<00:00, 37.72it/s]
ging factsheets retrieved:  78%|███████▊  | 60/77 [00:01<00:00, 56.22it/s]
ging factsheets retrieved:  90%|████████▉ | 69/77 [00:01<00:00, 52.84it/s]
judging factsheets retrieved: 100%|██████████| 77/77 [00:01<00:00, 41.06it/s]

ging factsheets retrieved:   0%|          | 0/77 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/77 [00:00<00:16,  4.50it/s]
ging factsheets retrieved:   9%|▉         | 7/77 [00:00<00:02, 25.26it/s]
ging factsheets retrieved:  27%|██▋       | 21/77 [00:00<00:00, 61.10it/s]
ging factsheets retrieved:  39%|███▉      | 30/77 [00:00<00:00, 66.86it/s]
ging factsheets retrieved:  49%|████▉     | 38/77 [00:00<00:00, 53.03it/s]
ging factsheets retrieved:  64%|██████▎   | 49/77 [00:00<00:00, 65.10it/s]
ging factsheets retrieved:  74%|███████▍  | 57/77 [00:01<00:00, 60.23it/s]
ging factsheets retrieved:  83%|████████▎ | 64/77 [00:01<00:00, 61.55it/s]
judging factsheets retrieved: 100%|██████████| 77/77 [00:06<00:00, 11.46it/s]

ging factsheets retrieved:   0%|          | 0/66 [00:00<?, ?it/s]
ging factsheets retrieved:   2%|▏         | 1/66 [00:00<00:15,  4.28it/s]
ging factsheets retrieved:  12%|█▏        | 8/66 [00:00<00:02, 28.60it/s]
ging factsheets retrieved:  24%|██▍       | 16/66 [00:00<00:01, 46.25it/s]
ging factsheets retrieved:  33%|███▎      | 22/66 [00:00<00:00, 50.00it/s]
ging factsheets retrieved:  42%|████▏     | 28/66 [00:00<00:00, 45.01it/s]
ging factsheets retrieved:  53%|█████▎    | 35/66 [00:00<00:00, 50.64it/s]
ging factsheets retrieved:  73%|███████▎  | 48/66 [00:00<00:00, 68.32it/s]
ging factsheets retrieved:  85%|████████▍ | 56/66 [00:01<00:00, 69.16it/s]
judging factsheets retrieved: 100%|██████████| 66/66 [00:03<00:00, 17.84it/s]

ging factsheets retrieved:   0%|          | 0/71 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/71 [00:00<00:17,  4.00it/s]
ging factsheets retrieved:   8%|▊         | 6/71 [00:00<00:03, 20.48it/s]
ging factsheets retrieved:  23%|██▎       | 16/71 [00:00<00:01, 44.66it/s]
ging factsheets retrieved:  32%|███▏      | 23/71 [00:00<00:01, 47.42it/s]
ging factsheets retrieved:  41%|████      | 29/71 [00:00<00:00, 44.33it/s]
ging factsheets retrieved:  51%|█████     | 36/71 [00:00<00:00, 49.91it/s]
ging factsheets retrieved:  63%|██████▎   | 45/71 [00:00<00:00, 59.69it/s]
ging factsheets retrieved:  73%|███████▎  | 52/71 [00:01<00:00, 51.32it/s]
ging factsheets retrieved:  82%|████████▏ | 58/71 [00:01<00:00, 49.24it/s]
ging factsheets retrieved:  90%|█████████ | 64/71 [00:01<00:00, 36.69it/s]
judging factsheets retrieved: 100%|██████████| 71/71 [00:05<00:00, 12.66it/s]

ging factsheets retrieved:   0%|          | 0/77 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/77 [00:00<00:17,  4.23it/s]
ging factsheets retrieved:  12%|█▏        | 9/77 [00:00<00:02, 31.31it/s]
ging factsheets retrieved:  23%|██▎       | 18/77 [00:00<00:01, 50.75it/s]
ging factsheets retrieved:  39%|███▉      | 30/77 [00:00<00:00, 64.27it/s]
ging factsheets retrieved:  49%|████▉     | 38/77 [00:00<00:00, 48.27it/s]
ging factsheets retrieved:  65%|██████▍   | 50/77 [00:00<00:00, 63.89it/s]
ging factsheets retrieved:  75%|███████▌  | 58/77 [00:01<00:00, 65.63it/s]
ging factsheets retrieved:  86%|████████▌ | 66/77 [00:01<00:00, 58.55it/s]
judging factsheets retrieved: 100%|██████████| 77/77 [00:02<00:00, 38.41it/s]

ging factsheets retrieved:   0%|          | 0/75 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/75 [00:00<00:17,  4.17it/s]
ging factsheets retrieved:  13%|█▎        | 10/75 [00:00<00:01, 34.48it/s]
ging factsheets retrieved:  21%|██▏       | 16/75 [00:00<00:02, 25.94it/s]
ging factsheets retrieved:  43%|████▎     | 32/75 [00:00<00:00, 54.94it/s]
ging factsheets retrieved:  53%|█████▎    | 40/75 [00:01<00:00, 36.77it/s]
ging factsheets retrieved:  73%|███████▎  | 55/75 [00:01<00:00, 54.61it/s]
ging factsheets retrieved:  89%|████████▉ | 67/75 [00:01<00:00, 59.12it/s]
judging factsheets retrieved: 100%|██████████| 75/75 [00:02<00:00, 30.64it/s]

ging factsheets retrieved:   0%|          | 0/65 [00:00<?, ?it/s]
ging factsheets retrieved:   2%|▏         | 1/65 [00:00<00:09,  6.66it/s]
ging factsheets retrieved:   3%|▎         | 2/65 [00:00<00:08,  7.47it/s]
ging factsheets retrieved:  20%|██        | 13/65 [00:00<00:01, 46.94it/s]
ging factsheets retrieved:  32%|███▏      | 21/65 [00:00<00:00, 57.82it/s]
ging factsheets retrieved:  48%|████▊     | 31/65 [00:00<00:00, 63.52it/s]
ging factsheets retrieved:  58%|█████▊    | 38/65 [00:00<00:00, 50.51it/s]
ging factsheets retrieved:  75%|███████▌  | 49/65 [00:00<00:00, 63.88it/s]
judging factsheets retrieved: 100%|██████████| 65/65 [00:02<00:00, 26.30it/s]

ging factsheets retrieved:   0%|          | 0/74 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/74 [00:00<00:19,  3.80it/s]
ging factsheets retrieved:  14%|█▎        | 10/74 [00:00<00:01, 32.79it/s]
ging factsheets retrieved:  28%|██▊       | 21/74 [00:00<00:00, 56.75it/s]
ging factsheets retrieved:  39%|███▉      | 29/74 [00:00<00:00, 48.05it/s]
ging factsheets retrieved:  49%|████▊     | 36/74 [00:00<00:00, 48.15it/s]
ging factsheets retrieved:  64%|██████▎   | 47/74 [00:00<00:00, 61.56it/s]
ging factsheets retrieved:  74%|███████▍  | 55/74 [00:01<00:00, 54.31it/s]
ging factsheets retrieved:  84%|████████▍ | 62/74 [00:01<00:00, 55.58it/s]
judging factsheets retrieved: 100%|██████████| 74/74 [00:04<00:00, 15.58it/s]

ging factsheets retrieved:   0%|          | 0/66 [00:00<?, ?it/s]
ging factsheets retrieved:   2%|▏         | 1/66 [00:00<00:13,  4.76it/s]
ging factsheets retrieved:   5%|▍         | 3/66 [00:00<00:06, 10.07it/s]
ging factsheets retrieved:  24%|██▍       | 16/66 [00:00<00:01, 49.06it/s]
ging factsheets retrieved:  42%|████▏     | 28/66 [00:00<00:00, 71.43it/s]
ging factsheets retrieved:  56%|█████▌    | 37/66 [00:00<00:00, 45.81it/s]
ging factsheets retrieved:  67%|██████▋   | 44/66 [00:00<00:00, 49.33it/s]
ging factsheets retrieved:  80%|████████  | 53/66 [00:01<00:00, 57.31it/s]
judging factsheets retrieved: 100%|██████████| 66/66 [00:04<00:00, 15.40it/s]

ging factsheets retrieved:   0%|          | 0/65 [00:00<?, ?it/s]
ging factsheets retrieved:   2%|▏         | 1/65 [00:00<00:11,  5.62it/s]
ging factsheets retrieved:   8%|▊         | 5/65 [00:00<00:02, 20.91it/s]
ging factsheets retrieved:  22%|██▏       | 14/65 [00:00<00:01, 45.19it/s]
ging factsheets retrieved:  35%|███▌      | 23/65 [00:00<00:00, 60.48it/s]
ging factsheets retrieved:  48%|████▊     | 31/65 [00:00<00:00, 59.29it/s]
ging factsheets retrieved:  58%|█████▊    | 38/65 [00:00<00:00, 56.83it/s]
ging factsheets retrieved:  69%|██████▉   | 45/65 [00:00<00:00, 60.24it/s]
ging factsheets retrieved:  86%|████████▌ | 56/65 [00:01<00:00, 67.79it/s]
judging factsheets retrieved: 100%|██████████| 65/65 [00:04<00:00, 14.58it/s]

ging factsheets retrieved:   0%|          | 0/90 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|          | 1/90 [00:00<00:18,  4.74it/s]
ging factsheets retrieved:  14%|█▍        | 13/90 [00:00<00:01, 45.48it/s]
ging factsheets retrieved:  22%|██▏       | 20/90 [00:00<00:01, 53.13it/s]
ging factsheets retrieved:  30%|███       | 27/90 [00:00<00:01, 57.43it/s]
ging factsheets retrieved:  38%|███▊      | 34/90 [00:00<00:01, 53.76it/s]
ging factsheets retrieved:  51%|█████     | 46/90 [00:00<00:00, 67.71it/s]
ging factsheets retrieved:  60%|██████    | 54/90 [00:00<00:00, 66.71it/s]
ging factsheets retrieved:  68%|██████▊   | 61/90 [00:01<00:00, 46.11it/s]
ging factsheets retrieved:  83%|████████▎ | 75/90 [00:01<00:00, 43.32it/s]
judging factsheets retrieved: 100%|██████████| 90/90 [00:02<00:00, 42.86it/s]

ging factsheets retrieved:   0%|          | 0/80 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/80 [00:00<00:18,  4.35it/s]
ging factsheets retrieved:  16%|█▋        | 13/80 [00:00<00:01, 48.22it/s]
ging factsheets retrieved:  28%|██▊       | 22/80 [00:00<00:00, 62.66it/s]
ging factsheets retrieved:  38%|███▊      | 30/80 [00:00<00:01, 47.03it/s]
ging factsheets retrieved:  51%|█████▏    | 41/80 [00:00<00:00, 59.95it/s]
ging factsheets retrieved:  61%|██████▏   | 49/80 [00:00<00:00, 61.60it/s]
ging factsheets retrieved:  71%|███████▏  | 57/80 [00:01<00:00, 53.42it/s]
ging factsheets retrieved:  81%|████████▏ | 65/80 [00:01<00:00, 59.21it/s]
ging factsheets retrieved:  90%|█████████ | 72/80 [00:01<00:00, 61.58it/s]
judging factsheets retrieved: 100%|██████████| 80/80 [00:05<00:00, 15.28it/s]

ging factsheets retrieved:   0%|          | 0/82 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|          | 1/82 [00:00<00:15,  5.37it/s]
ging factsheets retrieved:   5%|▍         | 4/82 [00:00<00:05, 13.92it/s]
ging factsheets retrieved:  17%|█▋        | 14/82 [00:00<00:01, 43.29it/s]
ging factsheets retrieved:  34%|███▍      | 28/82 [00:00<00:00, 67.40it/s]
ging factsheets retrieved:  44%|████▍     | 36/82 [00:00<00:00, 46.88it/s]
ging factsheets retrieved:  51%|█████     | 42/82 [00:01<00:00, 43.00it/s]
ging factsheets retrieved:  62%|██████▏   | 51/82 [00:01<00:00, 51.98it/s]
ging factsheets retrieved:  73%|███████▎  | 60/82 [00:01<00:00, 58.50it/s]
ging factsheets retrieved:  82%|████████▏ | 67/82 [00:01<00:00, 56.00it/s]
ging factsheets retrieved:  90%|█████████ | 74/82 [00:01<00:00, 49.64it/s]
judging factsheets retrieved: 100%|██████████| 82/82 [00:04<00:00, 19.39it/s]

ging factsheets retrieved:   0%|          | 0/83 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|          | 1/83 [00:00<00:14,  5.66it/s]
ging factsheets retrieved:   5%|▍         | 4/83 [00:00<00:04, 15.99it/s]
ging factsheets retrieved:  19%|█▉        | 16/83 [00:00<00:01, 52.11it/s]
ging factsheets retrieved:  30%|███       | 25/83 [00:00<00:00, 62.96it/s]
ging factsheets retrieved:  39%|███▊      | 32/83 [00:00<00:00, 64.97it/s]
ging factsheets retrieved:  47%|████▋     | 39/83 [00:00<00:00, 58.45it/s]
ging factsheets retrieved:  57%|█████▋    | 47/83 [00:00<00:00, 62.67it/s]
ging factsheets retrieved:  65%|██████▌   | 54/83 [00:00<00:00, 64.37it/s]
ging factsheets retrieved:  73%|███████▎  | 61/83 [00:01<00:00, 65.68it/s]
ging factsheets retrieved:  82%|████████▏ | 68/83 [00:01<00:00, 61.88it/s]
ging factsheets retrieved:  90%|█████████ | 75/83 [00:01<00:00, 63.28it/s]
judging factsheets retrieved: 100%|██████████| 83/83 [00:05<00:00, 16.36it/s]

ging factsheets retrieved:   0%|          | 0/77 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/77 [00:00<00:19,  3.86it/s]
ging factsheets retrieved:  13%|█▎        | 10/77 [00:00<00:02, 32.91it/s]
ging factsheets retrieved:  29%|██▊       | 22/77 [00:00<00:00, 58.38it/s]
ging factsheets retrieved:  39%|███▉      | 30/77 [00:00<00:00, 48.65it/s]
ging factsheets retrieved:  47%|████▋     | 36/77 [00:00<00:00, 51.44it/s]
ging factsheets retrieved:  57%|█████▋    | 44/77 [00:00<00:00, 57.91it/s]
ging factsheets retrieved:  70%|███████   | 54/77 [00:01<00:00, 67.29it/s]
ging factsheets retrieved:  81%|████████  | 62/77 [00:01<00:00, 58.32it/s]
judging factsheets retrieved: 100%|██████████| 77/77 [00:05<00:00, 15.17it/s]

ging factsheets retrieved:   0%|          | 0/76 [00:00<?, ?it/s]
ging factsheets retrieved:   8%|▊         | 6/76 [00:00<00:04, 17.37it/s]
ging factsheets retrieved:  25%|██▌       | 19/76 [00:00<00:01, 49.49it/s]
ging factsheets retrieved:  39%|███▉      | 30/76 [00:00<00:00, 64.54it/s]
ging factsheets retrieved:  51%|█████▏    | 39/76 [00:00<00:00, 46.16it/s]
ging factsheets retrieved:  68%|██████▊   | 52/76 [00:00<00:00, 62.81it/s]
ging factsheets retrieved:  80%|████████  | 61/76 [00:01<00:00, 53.69it/s]
ging factsheets retrieved:  91%|█████████ | 69/76 [00:01<00:00, 52.25it/s]
judging factsheets retrieved: 100%|██████████| 76/76 [00:04<00:00, 17.77it/s]

ging factsheets retrieved:   0%|          | 0/72 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/72 [00:00<00:12,  5.68it/s]
ging factsheets retrieved:   4%|▍         | 3/72 [00:00<00:06, 10.39it/s]
ging factsheets retrieved:  12%|█▎        | 9/72 [00:00<00:02, 27.26it/s]
ging factsheets retrieved:  29%|██▉       | 21/72 [00:00<00:00, 55.56it/s]
ging factsheets retrieved:  39%|███▉      | 28/72 [00:00<00:00, 48.97it/s]
ging factsheets retrieved:  47%|████▋     | 34/72 [00:00<00:00, 48.21it/s]
ging factsheets retrieved:  57%|█████▋    | 41/72 [00:00<00:00, 53.35it/s]
ging factsheets retrieved:  71%|███████   | 51/72 [00:01<00:00, 62.50it/s]
ging factsheets retrieved:  81%|████████  | 58/72 [00:01<00:00, 51.52it/s]
judging factsheets retrieved: 100%|██████████| 72/72 [00:05<00:00, 13.64it/s]

ging factsheets retrieved:   0%|          | 0/68 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|▏         | 1/68 [00:00<00:14,  4.59it/s]
ging factsheets retrieved:  12%|█▏        | 8/68 [00:00<00:02, 28.67it/s]
ging factsheets retrieved:  25%|██▌       | 17/68 [00:00<00:01, 49.69it/s]
ging factsheets retrieved:  40%|███▉      | 27/68 [00:00<00:00, 56.90it/s]
ging factsheets retrieved:  50%|█████     | 34/68 [00:00<00:00, 58.05it/s]
ging factsheets retrieved:  60%|██████    | 41/68 [00:00<00:00, 55.94it/s]
ging factsheets retrieved:  69%|██████▉   | 47/68 [00:00<00:00, 56.58it/s]
ging factsheets retrieved:  78%|███████▊  | 53/68 [00:01<00:00, 55.83it/s]
ging factsheets retrieved:  87%|████████▋ | 59/68 [00:01<00:00, 53.57it/s]
judging factsheets retrieved: 100%|██████████| 68/68 [00:01<00:00, 45.68it/s]

ging factsheets retrieved:   0%|          | 0/86 [00:00<?, ?it/s]
ging factsheets retrieved:   1%|          | 1/86 [00:00<00:17,  4.92it/s]

In [140]:
with open('../synthetic_data/aspect_query_positives_filtered_tokc_llm.pkl','wb') as f:
    pickle.dump(query_positve_dict,f)

In [290]:
### synthesizing positives for consumer industry queries which have less than threshold positives 

# res=llm.get_text_completion(prompt,0)['choices'][0]['message']['content']
additional_prompt={'Industry':'''Please ONLY provide synthetic facthseets for companies that are providing solutions as a part of the given industry.
Customer industry of a company is the industry to which company sells its solutions. 
DO NOT ADD FACTSHEET WHICH HAVE THE SAME CUSTOMER INDUSTRY SINCE WE WILL BE USING COMPANIES WITH SAME CUSTOMER INDUSTRY 
AS NEGATIVES FOR COMPANIES WITH SAME INDUSTRY''',
                   
                  'Customer Industry':'''Please ONLY provide synthetic facthseets for companies that are providing solutions to the given industry. i.e the customers of the company operate in the given industry
Customer industry of a company is the industry to which company sells its solutions. 
DO NOT ADD FACTSHEET WHICH HAVE THE SAME INDUSTRY AND CUSTOMER INDUSTRY SINCE WE WILL BE USING COMPANIES WITH SAME CUSTOMER INDUSTRY 
AS NEGATIVES FOR COMPANIES WITH SAME INDUSTRY'''}
from dep.response_formats import SyntheticPositiveFactsheetResponse

def generate_factsheets(query,n_fatchsheets,prompt1=None):
    success=False
    response_format=SyntheticPositiveFactsheetResponse
    sys_msg_path1='../prompts/synthetic_positive_factsheet.txt'
    system_message1=open(sys_msg_path1,'r').read()
    llm1=OpenAIChatCompletion(model='gpt-4o',system_message=system_message1)
    if prompt1 is None:
        prompt1=additional_prompt.get(f'{query[0]}','')+f"\nPlease provide {n_fatchsheets} facsheets for companies that are positives for the query: {query}"
    
    temperature=0.3
    
    res1=llm1.structured_response(prompt1,temperature,response_format)

    try:
        r1=json.loads(res1)['factsheets']

        success=True
        return success,r1
    except Exception as e:
        
        print(f'failed for {query} - {e}')
        success=False
        return success,[]

In [291]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import tqdm.notebook as tqdm
import json
def generate_factsheets_parallel(queries, n_factsheets=20, max_workers=10):
    """
    Run generate_factsheets in parallel for multiple queries.
    
    Args:
        queries (list): List of query strings to process
        n_factsheets (int): Number of factsheets to generate per query
        max_workers (int): Maximum number of parallel threads
        
    Returns:
        dict: Dictionary mapping queries to (success, factsheets) tuples
    """
    results = {}
    
    # Use tqdm for progress bar in Jupyter
    progress_bar = tqdm.tqdm(total=len(queries), desc="Processing queries")
    
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Start the tasks
        future_to_query = {
            executor.submit(generate_factsheets, query, n_factsheets): query 
            for query in queries
        }
        
        # Process results as they complete
        for future in as_completed(future_to_query):
            query = future_to_query[future]
            try:
                success, factsheets = future.result()
                results[query] = (success, factsheets)
            except Exception as e:
                print(f"Query '{query}' generated an exception: {e}")
                results[query] = (False, [])
            
            progress_bar.update(1)
    
    progress_bar.close()
    return results

In [275]:
# list(query_positve_dict.values())[0]

In [158]:
rows=[]

for query_asp, factsheet_res in query_positve_dict.items():
    rows.extend([{'aspect':query_asp[0],'query':query_asp[1],'factsheet':factsheet_res[j][0],'judge_res':factsheet_res[j][1]} for j in range(len(factsheet_res))])

In [159]:


import pandas as pd
judge_res_df=pd.DataFrame(rows)

In [161]:
judge_res_df['judge_decision']=judge_res_df.judge_res.apply(lambda x:x[1]['decision'])

In [198]:
NO_df=judge_res_df[judge_res_df.judge_decision=='NO']
positives_df=judge_res_df[judge_res_df.judge_decision=='YES']

In [207]:
# NO_df

In [204]:
venture_df=NO_df[(NO_df.factsheet.str.lower().str.contains('venture')) | (NO_df.factsheet.str.lower().str.contains('capital'))]

In [221]:
factsheets=venture_df.factsheet.to_list()
### judging venture as true or False
args=[(['Industry','Venture Capital',factsheet],{}) for factsheet in factsheets]
bs=128
res=[]
for i in tqdm(range(0,len(args),bs)):
    
    _res=parallel_execute(
                    func= filter_companies,
                    argument_sets=args[i:i+bs],
                    max_workers = 128,
                    show_progress= True,
                    desc = "judging factsheets retrieved"
                )
    res.extend(_res)

  0%|          | 0/47 [00:00<?, ?it/s]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  42%|████▏     | 54/128 [00:00<00:00, 171.53it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:05<00:00, 21.65it/s]
  2%|▏         | 1/47 [00:07<05:31,  7.21s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:00<00:00, 143.07it/s]
  4%|▍         | 2/47 [00:09<03:06,  4.14s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 33.07it/s]
  6%|▋         | 3/47 [00:14<03:17,  4.48s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 34.73it/s]
  9%|▊         | 4/47 [00:18<03:16,  4.57s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  37%|███▋      | 47/128 [00:00<00:00, 111.25it/s]
ging factsheets retrieved:  46%|████▌     | 59/128 [00:00<00:00, 109.67it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:07<00:00, 17.09it/s]
 11%|█         | 5/47 [00:27<04:15,  6.09s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  52%|█████▏    | 66/128 [00:00<00:00, 612.23it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:02<00:00, 43.97it/s]
 13%|█▎        | 6/47 [00:31<03:40,  5.38s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 38.27it/s]
 15%|█▍        | 7/47 [00:35<03:21,  5.04s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  52%|█████▏    | 66/128 [00:00<00:00, 541.05it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:05<00:00, 21.55it/s]
 17%|█▋        | 8/47 [00:42<03:40,  5.65s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  42%|████▏     | 54/128 [00:00<00:00, 127.58it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 28.43it/s]
 19%|█▉        | 9/47 [00:48<03:36,  5.70s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 27.07it/s]
 21%|██▏       | 10/47 [00:54<03:32,  5.74s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 30.91it/s]
 23%|██▎       | 11/47 [00:59<03:20,  5.57s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:01<00:00, 94.71it/s]
 26%|██▌       | 12/47 [01:02<02:40,  4.60s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  40%|███▉      | 51/128 [00:00<00:00, 109.57it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 42.59it/s]
 28%|██▊       | 13/47 [01:06<02:33,  4.51s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:05<00:00, 25.55it/s]
 30%|██▉       | 14/47 [01:12<02:45,  5.00s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:01<00:00, 109.51it/s]
 32%|███▏      | 15/47 [01:14<02:12,  4.15s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:00<00:00, 181.68it/s]
 34%|███▍      | 16/47 [01:16<01:45,  3.41s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  43%|████▎     | 55/128 [00:00<00:00, 130.53it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 25.71it/s]
 36%|███▌      | 17/47 [01:22<02:08,  4.28s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  51%|█████     | 65/128 [00:00<00:00, 537.99it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:02<00:00, 46.44it/s]
 38%|███▊      | 18/47 [01:26<02:00,  4.14s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  53%|█████▎    | 68/128 [00:00<00:00, 553.34it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 29.45it/s]
 40%|████      | 19/47 [01:31<02:06,  4.52s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:05<00:00, 25.15it/s]
 43%|████▎     | 20/47 [01:37<02:14,  4.99s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  42%|████▏     | 54/128 [00:00<00:00, 125.41it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:06<00:00, 20.32it/s]
 45%|████▍     | 21/47 [01:45<02:30,  5.77s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:00<00:00, 128.52it/s]
 47%|████▋     | 22/47 [01:47<01:56,  4.66s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:01<00:00, 92.81it/s]
 49%|████▉     | 23/47 [01:50<01:35,  3.97s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 39.83it/s]
 51%|█████     | 24/47 [01:54<01:33,  4.05s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  34%|███▎      | 43/128 [00:00<00:00, 87.05it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 42.43it/s]
 53%|█████▎    | 25/47 [01:58<01:30,  4.13s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  51%|█████     | 65/128 [00:00<00:00, 617.53it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 27.15it/s]
 55%|█████▌    | 26/47 [02:04<01:37,  4.63s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:05<00:00, 23.35it/s]
 57%|█████▋    | 27/47 [02:10<01:43,  5.18s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  52%|█████▏    | 66/128 [00:00<00:00, 617.92it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 36.53it/s]
 60%|█████▉    | 28/47 [02:15<01:34,  4.97s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  37%|███▋      | 47/128 [00:00<00:00, 104.20it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 33.05it/s]
 62%|██████▏   | 29/47 [02:20<01:30,  5.03s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:02<00:00, 58.54it/s]
 64%|██████▍   | 30/47 [02:23<01:16,  4.50s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:02<00:00, 60.55it/s]
 66%|██████▌   | 31/47 [02:26<01:05,  4.09s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:02<00:00, 53.48it/s]
 68%|██████▊   | 32/47 [02:30<00:58,  3.88s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  35%|███▌      | 45/128 [00:00<00:00, 95.06it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:05<00:00, 23.56it/s]
 70%|███████   | 33/47 [02:37<01:06,  4.74s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  52%|█████▏    | 67/128 [00:00<00:00, 602.35it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 31.93it/s]
 72%|███████▏  | 34/47 [02:42<01:03,  4.86s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:02<00:00, 61.98it/s]
 74%|███████▍  | 35/47 [02:45<00:51,  4.33s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 35.23it/s]
 77%|███████▋  | 36/47 [02:49<00:48,  4.44s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  39%|███▉      | 50/128 [00:00<00:00, 116.50it/s]
ging factsheets retrieved:  48%|████▊     | 62/128 [00:00<00:00, 111.04it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:00<00:00, 156.90it/s]
 79%|███████▊  | 37/47 [02:52<00:37,  3.75s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 36.20it/s]
 81%|████████  | 38/47 [02:56<00:36,  4.02s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 25.87it/s]
 83%|████████▎ | 39/47 [03:02<00:36,  4.61s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:03<00:00, 33.13it/s]
 85%|████████▌ | 40/47 [03:07<00:32,  4.70s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  41%|████      | 52/128 [00:00<00:00, 121.28it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:01<00:00, 65.16it/s]
 87%|████████▋ | 41/47 [03:10<00:25,  4.29s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:13<00:00,  9.52it/s]
 89%|████████▉ | 42/47 [03:25<00:36,  7.36s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  52%|█████▏    | 67/128 [00:00<00:00, 529.81it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 31.77it/s]
 91%|█████████▏| 43/47 [03:30<00:26,  6.66s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:00<00:00, 167.23it/s]
 94%|█████████▎| 44/47 [03:32<00:15,  5.19s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
ging factsheets retrieved:  49%|████▉     | 63/128 [00:00<00:00, 625.22it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:01<00:00, 126.17it/s]
 96%|█████████▌| 45/47 [03:35<00:08,  4.48s/it]
ging factsheets retrieved:   0%|          | 0/128 [00:00<?, ?it/s]
judging factsheets retrieved: 100%|██████████| 128/128 [00:04<00:00, 26.45it/s]
 98%|█████████▊| 46/47 [03:40<00:04,  4.90s/it]
ging factsheets retrieved:   0%|          | 0/36 [00:00<?, ?it/s]
ging factsheets retrieved:   3%|▎         | 1/36 [00:00<00:06,  5.55it/s]
ging factsheets retrieved:  14%|█▍        | 5/36 [00:00<00:01, 20.13it/s]
ging factsheets retrieved:  39%|███▉      | 14/36 [00:00<00:00, 45.49it/s]
ging factsheets retrieved:  67%|██████▋   | 24/36 [00:00<00:00, 62.87it/s]
judging factsheets retrieved: 100%|██████████| 36/36 [00:04<00:00,  7.52it/s]
100%|██████████| 47/47 [03:45<00:00,  4.81s/it]

In [222]:
venture_df['judge_res']=res
venture_df['judge_decision']=venture_df.judge_res.apply(lambda x:x[1]['decision'])

/tmp/ipykernel_31231/646181627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  venture_df['judge_res']=res
/tmp/ipykernel_31231/646181627.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  venture_df['judge_decision']=venture_df.judge_res.apply(lambda x:x[1]['decision'])

In [240]:
venture_df['new_query']='Venture Capital'
venture_df['new_aspect']='Industry'

/tmp/ipykernel_31231/2404367603.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  venture_df['new_query']='Venture Capital'
/tmp/ipykernel_31231/2404367603.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  venture_df['new_aspect']='Industry'

In [318]:
venture_df.to_pickle('../synthetic_data/venture_df.pkl')

In [248]:
judge_res_df=pd.concat([judge_res_df,venture_df[['new_aspect', 'new_query', 'factsheet', 'judge_res', 'judge_decision']].rename(columns={'new_aspect':'aspect','new_query':'query'})])

In [251]:
judge_res_df

,aspect,query,factsheet,judge_res,judge_decision
0,Industry,Entertainment,* * 2112inc company fact sheet * * \n\n * * co...,"(True, {'decision': 'NO'})",NO
1,Industry,Entertainment,* * company fact sheet : oneragtime * * \n\n *...,"(True, {'decision': 'NO'})",NO
2,Industry,Entertainment,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'NO'})",NO
3,Industry,Entertainment,* * company fact sheet : the company ( the com...,"(True, {'decision': 'NO'})",NO
4,Industry,Entertainment,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'NO'})",NO
...,...,...,...,...,...
37069,Industry,Venture Capital,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'NO'})",NO
37099,Industry,Venture Capital,* * crisbro company fact sheet * * \n\n * * co...,"(True, {'decision': 'NO'})",NO
37114,Industry,Venture Capital,* * company fact sheet : asyx * * \n\n * * 1 ....,"(True, {'decision': 'NO'})",NO
37158,Industry,Venture Capital,"* * liqun commercial group co . , ltd . fact...","(True, {'decision': 'NO'})",NO
37178,Industry,Venture Capital,* * africa sokoni fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'NO'})",NO

In [253]:
# true_counts

In [254]:
true_counts=judge_res_df[judge_res_df.judge_decision=='YES'].groupby(['aspect','query']).judge_decision.value_counts().reset_index()

In [261]:

true_counts[(true_counts['count']<30) & (true_counts['aspect'].isin(['Customer Industry','Industry']))]

                aspect                    query judge_decision  count
9    Customer Industry                   Adtech            YES     22
11   Customer Industry                Aerospace            YES      4
12   Customer Industry              Agriculture            YES     25
13   Customer Industry                 Agritech            YES     20
14   Customer Industry  Artificial Intelligence            YES      1
..                 ...                      ...            ...    ...
240           Industry     Satellite Technology            YES      1
244           Industry                   Sports            YES      7
246           Industry       Telecommunications            YES     20
248           Industry                  Tobacco            YES      3
252           Industry                Utilities            YES     25

[119 rows x 4 columns]

In [267]:
regeneration_df=pd.DataFrame(columns=['aspect','query','n_docs'])

reg_less_positives=true_counts[(true_counts['count']<10) | ((true_counts['count']<20) & (true_counts.aspect.isin(['Customer Industry','Industry'])))]
reg_less_positives['n_docs']=reg_less_positives['count']
reg_less_positives.loc[reg_less_positives.aspect.isin(['Customer Industry','Industry']),'n_docs']=20-reg_less_positives.loc[reg_less_positives.aspect.isin(['Customer Industry','Industry']),'count']
reg_less_positives.loc[~reg_less_positives.aspect.isin(['Customer Industry','Industry']),'n_docs']=10-reg_less_positives.loc[~reg_less_positives.aspect.isin(['Customer Industry','Industry']),'count']

regeneration_df=pd.concat([regeneration_df,reg_less_positives[['aspect','query','n_docs']]])

/tmp/ipykernel_31231/1354226784.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reg_less_positives['n_docs']=reg_less_positives['count']

In [336]:
queries=list(zip(regeneration_df.aspect.to_list(),regeneration_df['query'].to_list()))
args=[([queries[i],regeneration_df.iloc[i].n_docs],{'prompt1':None}) for i in range(len(queries))]

In [337]:

generated_factsheets=parallel_execute(
                        func= generate_factsheets,
                        argument_sets=args,
                        max_workers = 256,
                        show_progress= True,
                        desc = "generating factsheets"
                    )

[([('Business Model', 'Direct sales'), 3], {'prompt1': None}),
 ([('Business Model', 'Direct sales'), 3], {'prompt1': None}),
 ([('Business Model', 'Direct sales'), 3], {'prompt1': None}),
 ([('Business Model', 'Franchise'), 6], {'prompt1': None}),
 ([('Business Model', 'Franchise'), 6], {'prompt1': None})]

In [340]:

aspects=['Revenue model','Customer Segment','Customer Segment','Industry','Customer Industry','Industry','Customer Industry']
quries=['Usage based','K-12','Startups','Cybersecurity','Cybersecurity','Quantum Computing','Quantum Computing']
new_additions=pd.DataFrame({'aspect':aspects,'query':quries,'n_docs':[10]*(len(aspects)-3)+[30,30,30]})

In [341]:
queries=list(zip(new_additions.aspect.to_list(),new_additions['query'].to_list()))
args=[([queries[i],new_additions.iloc[i].n_docs],{'prompt1':None}) for i in range(len(queries))]

new_additions_generated_factsheets=parallel_execute(
                        func= generate_factsheets,
                        argument_sets=args,
                        max_workers = 7,
                        show_progress= True,
                        desc = "generating factsheets"
                    )

generating factsheets: 100%|██████████| 7/7 [01:47<00:00, 15.41s/it]

In [378]:
quntum_computing_facsheet_gen=generate_factsheets(('Customer Industry','Quantum Computing'),30)

In [343]:
new_additions['factsheet']=new_additions_generated_factsheets

In [344]:
new_additions['factsheet']=new_additions['factsheet'].apply(lambda x:x[1])

In [345]:
new_additions=new_additions.explode('factsheet')

In [348]:
new_additions

,aspect,query,n_docs,factsheet,judge_decision
0,Revenue model,Usage based,10,**Company Name:** CloudScale Technologies \n*...,YES
0,Revenue model,Usage based,10,**Company Name:** DataStream Analytics \n**We...,YES
0,Revenue model,Usage based,10,**Company Name:** GreenEnergy Solutions \n**W...,YES
0,Revenue model,Usage based,10,**Company Name:** FlexiNet Communications \n*...,YES
0,Revenue model,Usage based,10,**Company Name:** AquaPure Technologies \n**W...,YES
...,...,...,...,...,...
6,Custom Industry,Quantum Computing,30,**Company Name:** QuantumRetail Solutions \n*...,YES
6,Custom Industry,Quantum Computing,30,**Company Name:** QuantumTransport Labs \n**W...,YES
6,Custom Industry,Quantum Computing,30,**Company Name:** QuantumMedia Solutions \n**...,YES
6,Custom Industry,Quantum Computing,30,**Company Name:** QuantumSecurity Labs \n**We...,YES
6,Custom Industry,Quantum Computing,30,**Company Name:** QuantumFinance Solutions \n...,YES

In [347]:
new_additions['judge_decision']='YES'

In [300]:
regeneration_df['factsheet']=generated_factsheets

In [302]:
regeneration_df['factsheet']=regeneration_df['factsheet'].apply(lambda x:x[1])

In [304]:
regeneration_df=regeneration_df.explode('factsheet')

In [350]:
regeneration_df=pd.concat([regeneration_df,new_additions])

In [379]:
regeneration_df=regeneration_df[regeneration_df.aspect!='Custom Industry']

In [380]:
regeneration_df

,aspect,query,n_docs,factsheet,judge_decision
2,Business Model,Direct sales,3,**Company Name:** DirectTech Solutions \n**We...,YES
2,Business Model,Direct sales,3,**Company Name:** GreenHome Innovations \n**W...,YES
2,Business Model,Direct sales,3,**Company Name:** HealthDirect Supplies \n**W...,YES
3,Business Model,Franchise,6,**Company Name:** GreenLeaf Cafe \n**Website:...,YES
3,Business Model,Franchise,6,**Company Name:** FitZone Gyms \n**Website:**...,YES
...,...,...,...,...,...
5,Industry,Quantum Computing,30,**Company Name:** QuantumFlow Systems \n**Web...,YES
5,Industry,Quantum Computing,30,**Company Name:** QuantumCircuit Technologies ...,YES
5,Industry,Quantum Computing,30,**Company Name:** QuantumCompute Solutions \n...,YES
5,Industry,Quantum Computing,30,**Company Name:** QuantumFusion Technologies ...,YES
5,Industry,Quantum Computing,30,**Company Name:** QuantumInsight Solutions \n...,YES

In [385]:
quntum_computing_facsheet_gen_df=pd.DataFrame({'factsheet':quntum_computing_facsheet_gen[1],
                                               'aspect':['Customer Industry']*len(quntum_computing_facsheet_gen[1]),
                                                'query':['Quantum Computing']*len(quntum_computing_facsheet_gen[1]),
                                              'judge_decision':['YES']*len(quntum_computing_facsheet_gen[1])})

In [388]:
regeneration_df.to_pickle('../synthetic_data/generated_factsheets.pkl')

In [389]:
regeneration_df

,aspect,query,n_docs,factsheet,judge_decision
2,Business Model,Direct sales,3,**Company Name:** DirectTech Solutions \n**We...,YES
2,Business Model,Direct sales,3,**Company Name:** GreenHome Innovations \n**W...,YES
2,Business Model,Direct sales,3,**Company Name:** HealthDirect Supplies \n**W...,YES
3,Business Model,Franchise,6,**Company Name:** GreenLeaf Cafe \n**Website:...,YES
3,Business Model,Franchise,6,**Company Name:** FitZone Gyms \n**Website:**...,YES
...,...,...,...,...,...
23,Customer Industry,Quantum Computing,NaN,**Company Name:** QuantumDev Integration \n**...,YES
24,Customer Industry,Quantum Computing,NaN,**Company Name:** QuantumSecure Integration \...,YES
25,Customer Industry,Quantum Computing,NaN,**Company Name:** QuantumAI Solutions \n**Web...,YES
26,Customer Industry,Quantum Computing,NaN,**Company Name:** QuantumCompute Tools \n**We...,YES
27,Customer Industry,Quantum Computing,NaN,**Company Name:** QuantumSecure Tools \n**Web...,YES

In [312]:
# regeneration_df['judge_decision']='YES'

In [353]:
judge_res_df=pd.concat([judge_res_df,regeneration_df[['aspect', 'query', 'factsheet', 'judge_decision']]])

In [392]:
judge_res_df.to_pickle('../synthetic_data/final_factsheet_judged_df.pkl')

In [393]:
judge_res_df

,aspect,query,factsheet,judge_res,judge_decision
0,Industry,Entertainment,* * 2112inc company fact sheet * * \n\n * * co...,"(True, {'decision': 'NO'})",NO
1,Industry,Entertainment,* * company fact sheet : oneragtime * * \n\n *...,"(True, {'decision': 'NO'})",NO
2,Industry,Entertainment,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'NO'})",NO
3,Industry,Entertainment,* * company fact sheet : the company ( the com...,"(True, {'decision': 'NO'})",NO
4,Industry,Entertainment,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'NO'})",NO
...,...,...,...,...,...
23,Customer Industry,Quantum Computing,**Company Name:** QuantumDev Integration \n**...,NaN,YES
24,Customer Industry,Quantum Computing,**Company Name:** QuantumSecure Integration \...,NaN,YES
25,Customer Industry,Quantum Computing,**Company Name:** QuantumAI Solutions \n**Web...,NaN,YES
26,Customer Industry,Quantum Computing,**Company Name:** QuantumCompute Tools \n**We...,NaN,YES
27,Customer Industry,Quantum Computing,**Company Name:** QuantumSecure Tools \n**Web...,NaN,YES

In [394]:
positives_df=judge_res_df[judge_res_df.judge_decision=='YES']

In [395]:
positives_df.to_pickle('../synthetic_data/positives.pkl')

In [396]:
positives_df.groupby(['aspect','query']).judge_decision.value_counts()

aspect           query                judge_decision
Business Model   B2B                  YES               67
                 B2C                  YES               25
                 Direct sales         YES               10
                 Franchise            YES               10
                 Freemium             YES               10
                                                        ..
Technology Used  Robotics             YES               78
                 Smart contracts      YES               24
                 Virtual reality      YES               65
                 Voice recognition    YES               47
                 Wearable technology  YES               31
Name: count, Length: 410, dtype: int64

In [397]:
positives_df

,aspect,query,factsheet,judge_res,judge_decision
16,Industry,Entertainment,* * company name :* * potato productions \n\n ...,"(True, {'decision': 'YES'})",YES
28,Industry,Entertainment,* * company name :* * the company group \n\n *...,"(True, {'decision': 'YES'})",YES
54,Industry,Entertainment,* * company fact sheet : the company managemen...,"(True, {'decision': 'YES'})",YES
55,Industry,Entertainment,* * the company fact sheet * * \n\n * * compan...,"(True, {'decision': 'YES'})",YES
106,Industry,Real Estate,* * company fact sheet : styrkonstruktion * * ...,"(True, {'decision': 'YES'})",YES
...,...,...,...,...,...
23,Customer Industry,Quantum Computing,**Company Name:** QuantumDev Integration \n**...,NaN,YES
24,Customer Industry,Quantum Computing,**Company Name:** QuantumSecure Integration \...,NaN,YES
25,Customer Industry,Quantum Computing,**Company Name:** QuantumAI Solutions \n**Web...,NaN,YES
26,Customer Industry,Quantum Computing,**Company Name:** QuantumCompute Tools \n**We...,NaN,YES
27,Customer Industry,Quantum Computing,**Company Name:** QuantumSecure Tools \n**Web...,NaN,YES

In [399]:
print(positives_df[(positives_df.aspect=='Customer Industry') & (positives_df.judge_res.isna())].iloc[0].factsheet)

**Company Name:** AeroTech Solutions
**Website:** aerotechsolutions.com
**Industry:** Develops advanced materials and composites for high-performance applications.
**Target Audience:** Aerospace manufacturers, including aircraft and spacecraft producers seeking innovative material solutions.
**Products & Services:**
- **NanoComposite Materials:** Lightweight, durable materials designed to enhance fuel efficiency and performance in aerospace applications.
- **Thermal Protection Systems:** Advanced coatings and materials for heat resistance in high-speed aerospace vehicles.
**Unique Selling Propositions (USPs) & Key Differentiators:**
- Proprietary technology that reduces weight while maintaining structural integrity.
- Customizable solutions tailored to specific aerospace requirements.
**Business Model:** B2B with project-based contracts and long-term supply agreements.
**Technology Used:** Nanotechnology, advanced polymer science, and thermal engineering.
**Revenue Model:** Project-based contracts with recurring supply agreements.
**Competitive Landscape:** Competes with major materials science companies, offering unique customization capabilities.
**Overall Assessment:** AeroTech Solutions is positioned as a leader in innovative material solutions, offering significant advantages in weight reduction and thermal management for aerospace applications.

In [370]:
print(positives_df.iloc[-10].factsheet)

**Company Name:** QuantumSecurity Solutions
**Website:** quantumsecurity.com
**Industry:** Specializes in quantum computing applications for cybersecurity and data protection.
**Target Audience:** Financial institutions, government agencies, and enterprises seeking advanced tools for data security and threat detection.
**Products & Services:**
- **QuantumThreat Detector:** A tool that uses quantum algorithms to detect and prevent cyber threats with unprecedented speed and accuracy.
- **Data Quantum Protector:** Software for securing sensitive data and communications with quantum encryption.
**Unique Selling Propositions (USPs) & Key Differentiators:**
- Unmatched speed and accuracy in threat detection and prevention.
- Integration with existing security systems for seamless operation.
**Business Model:** B2B with software licensing and consulting services.
**Technology Used:** Quantum computing, cybersecurity frameworks, and data protection systems.
**Revenue Model:** Licensing fees and project-based consulting.
**Competitive Landscape:** Competes with companies like Symantec and McAfee in the cybersecurity space, focusing on quantum-enhanced solutions.
**Overall Assessment:** QuantumSecurity Solutions is at the forefront of cybersecurity, leveraging quantum computing to address the challenges of modern data protection and threat detection.

In [400]:
negatives_df=pd.DataFrame(columns=['aspect','query','factsheet'])

In [402]:
### venture Df was only made of rows that were not correct documents for aspect, query
## what we will be doing now is that we will be setting the correct venture capital docs as negatives for individual 
positive_venture_df=venture_df[venture_df.judge_decision=='YES']

In [410]:
(positive_venture_df.groupby(['aspect','query']).judge_decision.value_counts().sort_values().reset_index()['count']>10).sum()

np.int64(68)

In [411]:
positive_venture_df

,aspect,query,factsheet,judge_res,judge_decision,new_query,new_aspect
1,Industry,Entertainment,* * company fact sheet : oneragtime * * \n\n *...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
2,Industry,Entertainment,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
11,Industry,Entertainment,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
14,Industry,Entertainment,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
17,Industry,Entertainment,* * company name :* * the company inc . \n\n *...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
...,...,...,...,...,...,...,...
37018,Customer Industry,Retailtech,* * company fact sheet : shape capital * * \n\...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
37019,Customer Industry,Retailtech,* * the company fact sheet * * \n\n * * 1 . ...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
37020,Customer Industry,Retailtech,* * company name :* * aerox ventures \n\n * * ...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
37021,Customer Industry,Retailtech,* * company name :* * golden section \n * * we...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry
37024,Customer Industry,Retailtech,* * company name :* * sekhmet ventures \n\n * ...,"(True, {'decision': 'YES'})",YES,Venture Capital,Industry

In [1377]:
negatives_df=positive_venture_df[['aspect','query','factsheet']]

In [1378]:
negatives_df['strategy']='venture'

/tmp/ipykernel_31231/2478520030.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negatives_df['strategy']='venture'

In [1379]:
customer_negatives=positives_df[positives_df.aspect.str.contains('Industry')][['aspect','query','factsheet']]

In [1380]:
customer_negatives['aspect']=customer_negatives['aspect'].apply(lambda x:'Customer Industry' if x=='Industry' else 'Industry')

In [1381]:
customer_negatives

,aspect,query,factsheet
16,Customer Industry,Entertainment,* * company name :* * potato productions \n\n ...
28,Customer Industry,Entertainment,* * company name :* * the company group \n\n *...
54,Customer Industry,Entertainment,* * company fact sheet : the company managemen...
55,Customer Industry,Entertainment,* * the company fact sheet * * \n\n * * compan...
106,Customer Industry,Real Estate,* * company fact sheet : styrkonstruktion * * ...
...,...,...,...
23,Industry,Quantum Computing,**Company Name:** QuantumDev Integration \n**...
24,Industry,Quantum Computing,**Company Name:** QuantumSecure Integration \...
25,Industry,Quantum Computing,**Company Name:** QuantumAI Solutions \n**Web...
26,Industry,Quantum Computing,**Company Name:** QuantumCompute Tools \n**We...
27,Industry,Quantum Computing,**Company Name:** QuantumSecure Tools \n**Web...

In [871]:
# positives_df[positives_df['query']=='Venture Capital']

In [1362]:
### curating negatives for Technology Used,  Revenue Model, Business Model

# from dep.response_formats import HardNegativeFactsheetResponse
aspect_system_message_file={'Technology Used':'../prompts/tech_used_hard_negatives.txt',
                           'Revenue Model':'../prompts/revenue_model_hard_negative_prompt.txt',
                            'Business Model':'../prompts/business_model_hard_negatives_prompt.txt',
                            'Customer Segment': '../prompts/customer_segment.txt',
                            'Customer Industry':'../prompts/customer_industry.txt',
                            'Industry':'../prompts/Industry.txt',
                            'Products & Services': '../prompts/Products&Services.txt'
                           }

def generate_factsheets(query,n_fatchsheets,aspect):
    success=False
    response_format=HardNegativeFactsheetResponse
    
    sys_msg_path1=aspect_system_message_file[aspect]
    
    system_message1=open(sys_msg_path1,'r').read()
    # print(system_message1)|
    llm1=OpenAIChatCompletion(model='gpt-4o',system_message=system_message1)
    

    prompt1=f"\nPlease provide {n_fatchsheets} facsheets for companies that are hard negatives for the query: {query}. Keep each Factsheet less than 200-250 words, Since the model to be trained has a token limit."
    
    temperature=0.3
    
    res1=llm1.structured_response(prompt1,temperature,response_format)

    try:
        r1=json.loads(res1)['factsheets']

        success=True
        return success,r1
    except Exception as e:
        
        print(f'failed for {query} - {e}')
        success=False
        return success,[]

In [1363]:
positives_df[positives_df.aspect.str.contains('Tech')]['query'].unique()

array(['Augmented reality', 'Blockchain', 'AI', 'Computer vision',
       'Natural language processing', 'Chatbots', 'Neural networks',
       'Biometrics', 'Deep learning', 'RPA (Robotic Process Automation)',
       'IoT', 'Cybersecurity solutions', 'Edge computing',
       'Voice recognition', 'Smart contracts', 'Quantum computing',
       'Facial recognition', '5G technology', 'Geolocation services',
       'Autonomous vehicles', 'Machine learning', 'Robotics',
       'Big data analytics', 'Digital twins', 'Cryptography',
       'Microservices architecture', 'Wearable technology', '3D printing',
       'Virtual reality', 'Cloud computing'], dtype=object)

In [1364]:
factsheets=generate_factsheets(('Customer Segment','Legal Departments'),10,'Customer Segment')
# factsheets=generate_factsheets(('Products & Services','Augmented reality applications'),10,'Products & Services')
# factsheets=generate_factsheets(('Technology Used','3D printing'),10,'Technology Used')

In [1365]:
print(factsheets[1][0])

Company Name: FinTech Solutions  Website: fintechsolutions.com  Industry: Financial Technology  Target Audience: Small to medium-sized financial institutions  Products & Services:  - FinTech Suite: Comprehensive financial management tools  - FinTech Analytics: Data-driven insights for financial decision-making  Unique Selling Propositions (USPs) & Key Differentiators:  - Customizable financial solutions tailored to client needs  - Advanced security features for financial data protection  Business Model: B2B SaaS  Technology Used: Blockchain, AI-driven analytics  Revenue Model: Subscription-based  Competitive Landscape: Competes with Plaid, Stripe, and Square

In [1366]:
print(factsheets[1][5])

Company Name: SmartCity Solutions  Website: smartcitysolutions.com  Industry: Urban Development Technology  Target Audience: Municipal governments and urban planners  Products & Services:  - SmartCity Infrastructure: IoT-enabled urban management systems  - SmartCity Analytics: Data-driven urban planning tools  Unique Selling Propositions (USPs) & Key Differentiators:  - Comprehensive smart city solutions for urban efficiency  - Real-time data analytics for informed decision-making  Business Model: B2G (Business to Government)  Technology Used: IoT, Big Data analytics  Revenue Model: Government contracts and service fees  Competitive Landscape: Competes with Siemens, IBM Smart Cities, and Cisco

In [1367]:
print(factsheets[1][9])

Company Name: MediaTech Innovations  Website: mediatechinnovations.com  Industry: Media and Entertainment Technology  Target Audience: Broadcasting companies and media networks  Products & Services:  - MediaTech Streaming: High-quality streaming solutions  - MediaTech Analytics: Audience engagement and analytics tools  Unique Selling Propositions (USPs) & Key Differentiators:  - Scalable streaming technology for large audiences  - In-depth audience insights for content optimization  Business Model: B2B SaaS  Technology Used: Cloud-based streaming, AI-driven analytics  Revenue Model: Subscription and licensing fees  Competitive Landscape: Competes with Brightcove, Vimeo, and Kaltura

In [1368]:
# factsheets[1]

In [525]:
positives_df['consolidated_query']=positives_df.apply(lambda x:(x.aspect,x['query']),axis=1)

/tmp/ipykernel_31231/2929412718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  positives_df['consolidated_query']=positives_df.apply(lambda x:(x.aspect,x['query']),axis=1)

In [536]:
# positives_df.consolidated_query.unique()

In [ ]:
# query_negatives_dict={}

In [1338]:
for aspect in tqdm(['Customer Segment']):
    queries=list(positives_df[positives_df.aspect==aspect].consolidated_query.unique())

    args=[([queries[i],60,aspect],{}) for i in range(len(queries))]
    bs=20
    _query_negatives_dict={}
    
    for i in tqdm(range(0,60,20)):
        # basically calculating 3 times to get 60 in total
        
        
        args=[([queries[i],20,aspect],{}) for i in range(len(queries))]
            
        factsheets=parallel_execute(
                            func= generate_factsheets,
                            argument_sets=args,
                            max_workers = 32,
                            show_progress= True,
                            desc = "generating negative factsheets"
                        )

        for i in range(len(queries)):
            
            query=queries[i]
            factsheet=factsheets[i]
            
            if query in _query_negatives_dict:
                _query_negatives_dict[query]=_query_negatives_dict[query]+factsheet[1]
            else:
                _query_negatives_dict[query]=factsheet[1]

    query_negatives_dict={**query_negatives_dict,**_query_negatives_dict}

  0%|          | 0/1 [00:00<?, ?it/s]
%|          | 0/3 [00:00<?, ?it/s]

ting negative factsheets:   0%|          | 0/84 [00:00<?, ?it/s]

ting negative factsheets:   1%|          | 1/84 [00:18<25:03, 18.11s/it]

ting negative factsheets:   2%|▏         | 2/84 [00:18<10:21,  7.58s/it]

ting negative factsheets:   4%|▎         | 3/84 [00:18<05:54,  4.38s/it]

ting negative factsheets:   5%|▍         | 4/84 [00:19<03:59,  2.99s/it]

ting negative factsheets:   6%|▌         | 5/84 [00:19<02:34,  1.96s/it]

ting negative factsheets:   7%|▋         | 6/84 [00:20<01:59,  1.53s/it]

ting negative factsheets:   8%|▊         | 7/84 [00:20<01:27,  1.13s/it]

ting negative factsheets:  11%|█         | 9/84 [00:21<00:46,  1.62it/s]

ting negative factsheets:  12%|█▏        | 10/84 [00:21<00:36,  2.00it/s]

ting negative factsheets:  13%|█▎        | 11/84 [00:21<00:29,  2.51it/s]

ting negative factsheets:  15%|█▌        | 13/84 [00:21<00:23,  3.05it/s]

ting negative factsheets:  17%|█▋        | 14/84 [00:22<00:28,  2.50it/s]

ting negative factsheets:  18%|█▊        | 15/84 [00:22<00:22,  3.03it/s]

ting negative factsheets:  19%|█▉        | 16/84 [00:22<00:21,  3.18it/s]

ting negative factsheets:  20%|██        | 17/84 [00:22<00:18,  3.70it/s]

ting negative factsheets:  21%|██▏       | 18/84 [00:23<00:17,  3.71it/s]

ting negative factsheets:  23%|██▎       | 19/84 [00:23<00:20,  3.18it/s]

ting negative factsheets:  24%|██▍       | 20/84 [00:23<00:18,  3.53it/s]

ting negative factsheets:  25%|██▌       | 21/84 [00:24<00:17,  3.60it/s]

ting negative factsheets:  26%|██▌       | 22/84 [00:24<00:14,  4.16it/s]

ting negative factsheets:  27%|██▋       | 23/84 [00:24<00:18,  3.26it/s]

ting negative factsheets:  29%|██▊       | 24/84 [00:24<00:15,  3.92it/s]

ting negative factsheets:  30%|██▉       | 25/84 [00:25<00:29,  2.02it/s]

ting negative factsheets:  31%|███       | 26/84 [00:26<00:27,  2.09it/s]

ting negative factsheets:  33%|███▎      | 28/84 [00:28<00:35,  1.57it/s]

ting negative factsheets:  35%|███▍      | 29/84 [00:28<00:38,  1.43it/s]

ting negative factsheets:  36%|███▌      | 30/84 [00:29<00:38,  1.39it/s]

ting negative factsheets:  37%|███▋      | 31/84 [00:31<01:00,  1.15s/it]

ting negative factsheets:  38%|███▊      | 32/84 [00:32<00:45,  1.13it/s]

ting negative factsheets:  39%|███▉      | 33/84 [00:40<02:26,  2.87s/it]

ting negative factsheets:  40%|████      | 34/84 [00:41<01:59,  2.40s/it]

ting negative factsheets:  42%|████▏     | 35/84 [00:42<01:39,  2.04s/it]

ting negative factsheets:  43%|████▎     | 36/84 [00:43<01:23,  1.73s/it]

ting negative factsheets:  44%|████▍     | 37/84 [00:43<01:00,  1.28s/it]

ting negative factsheets:  48%|████▊     | 40/84 [00:43<00:26,  1.64it/s]

ting negative factsheets:  49%|████▉     | 41/84 [00:44<00:23,  1.81it/s]

ting negative factsheets:  51%|█████     | 43/84 [00:44<00:17,  2.35it/s]

ting negative factsheets:  54%|█████▎    | 45/84 [00:46<00:24,  1.59it/s]

ting negative factsheets:  55%|█████▍    | 46/84 [00:47<00:22,  1.72it/s]

ting negative factsheets:  56%|█████▌    | 47/84 [00:47<00:18,  2.05it/s]

ting negative factsheets:  58%|█████▊    | 49/84 [00:47<00:12,  2.87it/s]

ting negative factsheets:  60%|█████▉    | 50/84 [00:48<00:17,  1.98it/s]

ting negative factsheets:  61%|██████    | 51/84 [00:48<00:15,  2.17it/s]

ting negative factsheets:  62%|██████▏   | 52/84 [00:50<00:21,  1.47it/s]

ting negative factsheets:  63%|██████▎   | 53/84 [00:50<00:17,  1.81it/s]

ting negative factsheets:  64%|██████▍   | 54/84 [00:50<00:13,  2.30it/s]

ting negative factsheets:  65%|██████▌   | 55/84 [00:51<00:18,  1.58it/s]

ting negative factsheets:  67%|██████▋   | 56/84 [00:53<00:26,  1.08it/s]

ting negative factsheets:  69%|██████▉   | 58/84 [00:54<00:17,  1.49it/s]

ting negative factsheets:  70%|███████   | 59/84 [00:54<00:16,  1.52it/s]

ting negative factsheets:  71%|███████▏  | 60/84 [00:54<00:12,  1.91it/s]

ting negative factsheets:  73%|███████▎  | 61/84 [00:54<00:09,  2.42it/s]

ting negative factsheets:  74%|███████▍  | 62/84 [00:57<00:25,  1.14s/it]

ting negative factsheets:  75%|███████▌  | 63/84 [00:58<00:18,  1.12it/s]

ting negative factsheets:  76%|███████▌  | 64/84 [01:01<00:31,  1.60s/it]

ting negative factsheets:  77%|███████▋  | 65/84 [01:02<00:25,  1.34s/it]

ting negative factsheets:  79%|███████▊  | 66/84 [01:04<00:31,  1.73s/it]

ting negative factsheets:  80%|███████▉  | 67/84 [01:05<00:21,  1.27s/it]

ting negative factsheets:  81%|████████  | 68/84 [01:06<00:21,  1.35s/it]

ting negative factsheets:  82%|████████▏ | 69/84 [01:07<00:19,  1.28s/it]

ting negative factsheets:  83%|████████▎ | 70/84 [01:08<00:16,  1.16s/it]

ting negative factsheets:  85%|████████▍ | 71/84 [01:09<00:12,  1.06it/s]

ting negative factsheets:  86%|████████▌ | 72/84 [01:10<00:11,  1.01it/s]

ting negative factsheets:  88%|████████▊ | 74/84 [01:13<00:12,  1.20s/it]

ting negative factsheets:  89%|████████▉ | 75/84 [01:13<00:09,  1.10s/it]

ting negative factsheets:  90%|█████████ | 76/84 [01:14<00:08,  1.09s/it]

ting negative factsheets:  92%|█████████▏| 77/84 [01:15<00:06,  1.01it/s]

ting negative factsheets:  93%|█████████▎| 78/84 [01:18<00:08,  1.38s/it]

ting negative factsheets:  94%|█████████▍| 79/84 [01:18<00:06,  1.25s/it]

ting negative factsheets:  96%|█████████▋| 81/84 [01:19<00:02,  1.38it/s]

ting negative factsheets:  98%|█████████▊| 82/84 [01:19<00:01,  1.71it/s]

ting negative factsheets:  99%|█████████▉| 83/84 [01:19<00:00,  1.67it/s]

generating negative factsheets: 100%|██████████| 84/84 [01:21<00:00,  1.04it/s]

%|███▎      | 1/3 [01:21<02:42, 81.35s/it]

ting negative factsheets:   0%|          | 0/84 [00:00<?, ?it/s]

ting negative factsheets:   1%|          | 1/84 [00:20<28:27, 20.57s/it]

ting negative factsheets:   2%|▏         | 2/84 [00:23<13:54, 10.17s/it]

ting negative factsheets:   4%|▎         | 3/84 [00:25<08:40,  6.42s/it]

ting negative factsheets:   6%|▌         | 5/84 [00:25<03:44,  2.84s/it]

ting negative factsheets:   7%|▋         | 6/84 [00:25<02:41,  2.07s/it]

ting negative factsheets:   8%|▊         | 7/84 [00:25<01:55,  1.50s/it]

ting negative factsheets:  10%|▉         | 8/84 [00:26<01:24,  1.12s/it]

ting negative factsheets:  12%|█▏        | 10/84 [00:26<00:46,  1.58it/s]

ting negative factsheets:  13%|█▎        | 11/84 [00:26<00:36,  1.99it/s]

ting negative factsheets:  15%|█▌        | 13/84 [00:26<00:25,  2.80it/s]

ting negative factsheets:  17%|█▋        | 14/84 [00:27<00:28,  2.46it/s]

ting negative factsheets:  18%|█▊        | 15/84 [00:27<00:25,  2.68it/s]

ting negative factsheets:  20%|██        | 17/84 [00:27<00:16,  3.98it/s]

ting negative factsheets:  21%|██▏       | 18/84 [00:27<00:16,  3.98it/s]

ting negative factsheets:  24%|██▍       | 20/84 [00:28<00:20,  3.05it/s]

ting negative factsheets:  25%|██▌       | 21/84 [00:29<00:19,  3.17it/s]

ting negative factsheets:  27%|██▋       | 23/84 [00:29<00:17,  3.52it/s]

ting negative factsheets:  30%|██▉       | 25/84 [00:29<00:13,  4.42it/s]

ting negative factsheets:  31%|███       | 26/84 [00:30<00:15,  3.68it/s]

ting negative factsheets:  32%|███▏      | 27/84 [00:30<00:13,  4.18it/s]

ting negative factsheets:  33%|███▎      | 28/84 [00:30<00:14,  3.90it/s]

ting negative factsheets:  36%|███▌      | 30/84 [00:30<00:09,  5.79it/s]

ting negative factsheets:  37%|███▋      | 31/84 [00:34<00:46,  1.14it/s]

ting negative factsheets:  38%|███▊      | 32/84 [00:37<01:14,  1.44s/it]

ting negative factsheets:  39%|███▉      | 33/84 [00:42<01:58,  2.31s/it]

ting negative factsheets:  40%|████      | 34/84 [00:47<02:42,  3.26s/it]

ting negative factsheets:  43%|████▎     | 36/84 [00:48<01:35,  2.00s/it]

ting negative factsheets:  44%|████▍     | 37/84 [00:48<01:12,  1.55s/it]

ting negative factsheets:  45%|████▌     | 38/84 [00:48<00:55,  1.20s/it]

ting negative factsheets:  46%|████▋     | 39/84 [00:49<00:42,  1.06it/s]

ting negative factsheets:  48%|████▊     | 40/84 [00:49<00:31,  1.39it/s]

ting negative factsheets:  49%|████▉     | 41/84 [00:50<00:33,  1.28it/s]

ting negative factsheets:  50%|█████     | 42/84 [00:50<00:27,  1.55it/s]

ting negative factsheets:  51%|█████     | 43/84 [00:50<00:22,  1.80it/s]

ting negative factsheets:  52%|█████▏    | 44/84 [00:51<00:24,  1.60it/s]

ting negative factsheets:  54%|█████▎    | 45/84 [00:51<00:18,  2.12it/s]

ting negative factsheets:  55%|█████▍    | 46/84 [00:51<00:15,  2.41it/s]

ting negative factsheets:  56%|█████▌    | 47/84 [00:52<00:12,  3.02it/s]

ting negative factsheets:  58%|█████▊    | 49/84 [00:53<00:14,  2.35it/s]

ting negative factsheets:  61%|██████    | 51/84 [00:53<00:09,  3.60it/s]

ting negative factsheets:  62%|██████▏   | 52/84 [00:54<00:16,  1.92it/s]

ting negative factsheets:  63%|██████▎   | 53/84 [00:55<00:19,  1.61it/s]

ting negative factsheets:  64%|██████▍   | 54/84 [00:55<00:16,  1.84it/s]

ting negative factsheets:  65%|██████▌   | 55/84 [00:56<00:13,  2.22it/s]

ting negative factsheets:  67%|██████▋   | 56/84 [00:57<00:19,  1.42it/s]

ting negative factsheets:  68%|██████▊   | 57/84 [00:57<00:17,  1.55it/s]

ting negative factsheets:  69%|██████▉   | 58/84 [00:58<00:16,  1.57it/s]

ting negative factsheets:  70%|███████   | 59/84 [00:59<00:18,  1.39it/s]

ting negative factsheets:  73%|███████▎  | 61/84 [01:00<00:13,  1.65it/s]

ting negative factsheets:  74%|███████▍  | 62/84 [01:00<00:11,  1.91it/s]

ting negative factsheets:  75%|███████▌  | 63/84 [01:02<00:17,  1.19it/s]

ting negative factsheets:  77%|███████▋  | 65/84 [01:05<00:19,  1.04s/it]

ting negative factsheets:  79%|███████▊  | 66/84 [01:13<00:48,  2.71s/it]

ting negative factsheets:  80%|███████▉  | 67/84 [01:15<00:43,  2.57s/it]

ting negative factsheets:  81%|████████  | 68/84 [01:15<00:32,  2.00s/it]

ting negative factsheets:  82%|████████▏ | 69/84 [01:15<00:22,  1.49s/it]

ting negative factsheets:  83%|████████▎ | 70/84 [01:16<00:17,  1.24s/it]

ting negative factsheets:  85%|████████▍ | 71/84 [01:16<00:12,  1.06it/s]

ting negative factsheets:  87%|████████▋ | 73/84 [01:17<00:08,  1.30it/s]

ting negative factsheets:  88%|████████▊ | 74/84 [01:18<00:06,  1.44it/s]

ting negative factsheets:  89%|████████▉ | 75/84 [01:18<00:05,  1.68it/s]

ting negative factsheets:  90%|█████████ | 76/84 [01:19<00:06,  1.27it/s]

ting negative factsheets:  93%|█████████▎| 78/84 [01:20<00:02,  2.11it/s]

ting negative factsheets:  94%|█████████▍| 79/84 [01:21<00:03,  1.53it/s]

ting negative factsheets:  95%|█████████▌| 80/84 [01:22<00:03,  1.11it/s]

ting negative factsheets:  96%|█████████▋| 81/84 [01:24<00:03,  1.14s/it]

ting negative factsheets:  98%|█████████▊| 82/84 [01:25<00:01,  1.11it/s]

ting negative factsheets:  99%|█████████▉| 83/84 [01:25<00:00,  1.26it/s]

generating negative factsheets: 100%|██████████| 84/84 [01:31<00:00,  1.08s/it]

%|██████▋   | 2/3 [02:52<01:27, 87.19s/it]

ting negative factsheets:   0%|          | 0/84 [00:00<?, ?it/s]

ting negative factsheets:   1%|          | 1/84 [00:20<28:27, 20.57s/it]

ting negative factsheets:   2%|▏         | 2/84 [00:20<11:55,  8.72s/it]

ting negative factsheets:   4%|▎         | 3/84 [00:21<06:56,  5.14s/it]

ting negative factsheets:   6%|▌         | 5/84 [00:21<02:58,  2.26s/it]

ting negative factsheets:   7%|▋         | 6/84 [00:22<02:10,  1.68s/it]

ting negative factsheets:  10%|▉         | 8/84 [00:22<01:18,  1.04s/it]

ting negative factsheets:  12%|█▏        | 10/84 [00:22<00:48,  1.53it/s]

ting negative factsheets:  13%|█▎        | 11/84 [00:23<00:46,  1.56it/s]

ting negative factsheets:  14%|█▍        | 12/84 [00:23<00:38,  1.87it/s]

ting negative factsheets:  18%|█▊        | 15/84 [00:23<00:20,  3.45it/s]

ting negative factsheets:  21%|██▏       | 18/84 [00:24<00:14,  4.46it/s]

ting negative factsheets:  23%|██▎       | 19/84 [00:24<00:17,  3.80it/s]

ting negative factsheets:  24%|██▍       | 20/84 [00:24<00:17,  3.65it/s]

ting negative factsheets:  25%|██▌       | 21/84 [00:25<00:16,  3.84it/s]

ting negative factsheets:  27%|██▋       | 23/84 [00:25<00:18,  3.25it/s]

ting negative factsheets:  29%|██▊       | 24/84 [00:26<00:18,  3.33it/s]

ting negative factsheets:  30%|██▉       | 25/84 [00:26<00:23,  2.47it/s]

ting negative factsheets:  32%|███▏      | 27/84 [00:27<00:20,  2.83it/s]

ting negative factsheets:  33%|███▎      | 28/84 [00:28<00:28,  1.95it/s]

ting negative factsheets:  35%|███▍      | 29/84 [00:30<00:47,  1.17it/s]

ting negative factsheets:  36%|███▌      | 30/84 [00:32<01:04,  1.20s/it]

ting negative factsheets:  37%|███▋      | 31/84 [00:34<01:09,  1.32s/it]

ting negative factsheets:  38%|███▊      | 32/84 [00:34<00:53,  1.02s/it]

ting negative factsheets:  39%|███▉      | 33/84 [00:46<03:22,  3.96s/it]

ting negative factsheets:  40%|████      | 34/84 [00:46<02:29,  2.98s/it]

ting negative factsheets:  42%|████▏     | 35/84 [00:47<01:55,  2.36s/it]

ting negative factsheets:  43%|████▎     | 36/84 [00:47<01:21,  1.70s/it]

ting negative factsheets:  45%|████▌     | 38/84 [00:47<00:46,  1.01s/it]

ting negative factsheets:  48%|████▊     | 40/84 [00:48<00:32,  1.36it/s]

ting negative factsheets:  49%|████▉     | 41/84 [00:48<00:26,  1.59it/s]

ting negative factsheets:  51%|█████     | 43/84 [00:49<00:21,  1.88it/s]

ting negative factsheets:  52%|█████▏    | 44/84 [00:51<00:29,  1.34it/s]

ting negative factsheets:  54%|█████▎    | 45/84 [00:51<00:25,  1.53it/s]

ting negative factsheets:  55%|█████▍    | 46/84 [00:51<00:21,  1.78it/s]

ting negative factsheets:  57%|█████▋    | 48/84 [00:52<00:14,  2.57it/s]

ting negative factsheets:  60%|█████▉    | 50/84 [00:52<00:09,  3.72it/s]

ting negative factsheets:  61%|██████    | 51/84 [00:52<00:12,  2.59it/s]

ting negative factsheets:  62%|██████▏   | 52/84 [00:53<00:16,  1.92it/s]

ting negative factsheets:  64%|██████▍   | 54/84 [00:55<00:16,  1.84it/s]

ting negative factsheets:  65%|██████▌   | 55/84 [00:55<00:14,  2.04it/s]

ting negative factsheets:  67%|██████▋   | 56/84 [00:56<00:15,  1.77it/s]

ting negative factsheets:  68%|██████▊   | 57/84 [00:57<00:22,  1.18it/s]

ting negative factsheets:  69%|██████▉   | 58/84 [00:58<00:20,  1.30it/s]

ting negative factsheets:  70%|███████   | 59/84 [00:58<00:17,  1.41it/s]

ting negative factsheets:  71%|███████▏  | 60/84 [00:59<00:14,  1.61it/s]

ting negative factsheets:  73%|███████▎  | 61/84 [01:01<00:25,  1.12s/it]

ting negative factsheets:  74%|███████▍  | 62/84 [01:03<00:25,  1.17s/it]

ting negative factsheets:  75%|███████▌  | 63/84 [01:03<00:23,  1.11s/it]

ting negative factsheets:  76%|███████▌  | 64/84 [01:05<00:23,  1.17s/it]

ting negative factsheets:  77%|███████▋  | 65/84 [01:12<00:54,  2.86s/it]

ting negative factsheets:  80%|███████▉  | 67/84 [01:13<00:30,  1.80s/it]

ting negative factsheets:  82%|████████▏ | 69/84 [01:15<00:22,  1.50s/it]

ting negative factsheets:  83%|████████▎ | 70/84 [01:15<00:17,  1.25s/it]

ting negative factsheets:  86%|████████▌ | 72/84 [01:15<00:09,  1.22it/s]

ting negative factsheets:  87%|████████▋ | 73/84 [01:16<00:07,  1.43it/s]

ting negative factsheets:  88%|████████▊ | 74/84 [01:16<00:06,  1.60it/s]

ting negative factsheets:  89%|████████▉ | 75/84 [01:17<00:06,  1.37it/s]

ting negative factsheets:  90%|█████████ | 76/84 [01:17<00:04,  1.71it/s]

ting negative factsheets:  92%|█████████▏| 77/84 [01:18<00:03,  1.93it/s]

ting negative factsheets:  93%|█████████▎| 78/84 [01:20<00:05,  1.05it/s]

ting negative factsheets:  94%|█████████▍| 79/84 [01:20<00:03,  1.35it/s]

ting negative factsheets:  95%|█████████▌| 80/84 [01:22<00:03,  1.03it/s]

ting negative factsheets:  96%|█████████▋| 81/84 [01:22<00:02,  1.16it/s]

ting negative factsheets:  98%|█████████▊| 82/84 [01:23<00:01,  1.17it/s]

ting negative factsheets:  99%|█████████▉| 83/84 [01:29<00:02,  2.48s/it]

generating negative factsheets: 100%|██████████| 84/84 [01:30<00:00,  1.08s/it]

100%|██████████| 3/3 [04:23<00:00, 87.92s/it]
100%|██████████| 1/1 [04:23<00:00, 263.77s/it]

In [542]:
query_negatives_dict={}
for aspect in tqdm(['Technology Used','Revenue Model','Business Model','Customer Segment']):
    queries=list(positives_df[positives_df.aspect==aspect].consolidated_query.unique())
    
    args=[([queries[i],60,aspect],{}) for i in range(len(queries))]
    
    factsheets=parallel_execute(
                        func= generate_factsheets,
                        argument_sets=args,
                        max_workers = 32,
                        show_progress= True,
                        desc = "generating negative factsheets"
                    )
    
    
    _query_negatives_dict=dict(zip(queries,factsheets))
    
    query_negatives_dict={**query_negatives_dict,**_query_negatives_dict}

  0%|          | 0/3 [00:00<?, ?it/s]
erating negative factsheets:   0%|          | 0/30 [00:00<?, ?it/s]
erating negative factsheets:   3%|▎         | 1/30 [01:22<40:05, 82.95s/it]
erating negative factsheets:   7%|▋         | 2/30 [01:25<16:42, 35.81s/it]
erating negative factsheets:  10%|█         | 3/30 [01:27<09:03, 20.12s/it]
erating negative factsheets:  13%|█▎        | 4/30 [01:28<05:26, 12.54s/it]
erating negative factsheets:  17%|█▋        | 5/30 [01:28<03:22,  8.11s/it]
erating negative factsheets:  20%|██        | 6/30 [01:30<02:24,  6.02s/it]
erating negative factsheets:  23%|██▎       | 7/30 [01:30<01:36,  4.21s/it]
erating negative factsheets:  27%|██▋       | 8/30 [01:33<01:18,  3.57s/it]
erating negative factsheets:  30%|███       | 9/30 [01:33<00:57,  2.73s/it]
erating negative factsheets:  33%|███▎      | 10/30 [01:35<00:48,  2.45s/it]
erating negative factsheets:  37%|███▋      | 11/30 [01:35<00:33,  1.78s/it]
erating negative factsheets:  40%|████      | 12/30 [01:36<00:26,  1.45s/it]
erating negative factsheets:  43%|████▎     | 13/30 [01:37<00:19,  1.18s/it]
erating negative factsheets:  47%|████▋     | 14/30 [01:38<00:21,  1.35s/it]
erating negative factsheets:  50%|█████     | 15/30 [01:39<00:17,  1.13s/it]
erating negative factsheets:  53%|█████▎    | 16/30 [01:40<00:12,  1.09it/s]
erating negative factsheets:  57%|█████▋    | 17/30 [01:40<00:12,  1.07it/s]
erating negative factsheets:  60%|██████    | 18/30 [01:42<00:12,  1.06s/it]
erating negative factsheets:  63%|██████▎   | 19/30 [01:46<00:22,  2.05s/it]
erating negative factsheets:  67%|██████▋   | 20/30 [01:48<00:19,  1.92s/it]
erating negative factsheets:  70%|███████   | 21/30 [01:48<00:12,  1.43s/it]
erating negative factsheets:  73%|███████▎  | 22/30 [01:52<00:16,  2.02s/it]
erating negative factsheets:  77%|███████▋  | 23/30 [01:53<00:13,  1.93s/it]
erating negative factsheets:  80%|████████  | 24/30 [01:55<00:11,  1.94s/it]
erating negative factsheets:  83%|████████▎ | 25/30 [01:59<00:11,  2.38s/it]
erating negative factsheets:  87%|████████▋ | 26/30 [02:00<00:07,  1.97s/it]
erating negative factsheets:  90%|█████████ | 27/30 [02:06<00:09,  3.30s/it]
erating negative factsheets:  93%|█████████▎| 28/30 [02:11<00:07,  3.85s/it]
erating negative factsheets:  97%|█████████▋| 29/30 [02:44<00:12, 12.48s/it]
generating negative factsheets: 100%|██████████| 30/30 [03:03<00:00,  6.11s/it]
 33%|███▎      | 1/3 [03:03<06:06, 183.46s/it]
erating negative factsheets:   0%|          | 0/23 [00:00<?, ?it/s]
erating negative factsheets:   4%|▍         | 1/23 [01:46<39:05, 106.61s/it]
erating negative factsheets:   9%|▊         | 2/23 [01:53<16:43, 47.80s/it]
erating negative factsheets:  13%|█▎        | 3/23 [01:54<08:51, 26.56s/it]
erating negative factsheets:  17%|█▋        | 4/23 [02:01<05:59, 18.90s/it]
erating negative factsheets:  22%|██▏       | 5/23 [02:03<03:48, 12.72s/it]
erating negative factsheets:  26%|██▌       | 6/23 [02:05<02:35,  9.14s/it]
erating negative factsheets:  30%|███       | 7/23 [02:06<01:40,  6.28s/it]
erating negative factsheets:  35%|███▍      | 8/23 [02:08<01:15,  5.03s/it]
erating negative factsheets:  39%|███▉      | 9/23 [02:08<00:49,  3.55s/it]
erating negative factsheets:  43%|████▎     | 10/23 [02:10<00:37,  2.86s/it]
erating negative factsheets:  52%|█████▏    | 12/23 [02:11<00:20,  1.88s/it]
erating negative factsheets:  57%|█████▋    | 13/23 [02:17<00:28,  2.84s/it]
erating negative factsheets:  61%|██████    | 14/23 [02:20<00:26,  2.96s/it]
erating negative factsheets:  65%|██████▌   | 15/23 [02:22<00:21,  2.68s/it]
erating negative factsheets:  70%|██████▉   | 16/23 [02:26<00:22,  3.19s/it]
erating negative factsheets:  74%|███████▍  | 17/23 [02:28<00:16,  2.73s/it]
erating negative factsheets:  78%|███████▊  | 18/23 [02:30<00:12,  2.54s/it]
erating negative factsheets:  83%|████████▎ | 19/23 [02:32<00:09,  2.27s/it]
erating negative factsheets:  87%|████████▋ | 20/23 [02:34<00:06,  2.20s/it]
erating negative factsheets:  91%|█████████▏| 21/23 [02:37<00:04,  2.40s/it]
erating negative factsheets:  96%|█████████▌| 22/23 [02:41<00:02,  2.88s/it]
generating negative factsheets: 100%|██████████| 23/23 [03:04<00:00,  8.03s/it]
 67%|██████▋   | 2/3 [06:08<03:04, 184.22s/it]
erating negative factsheets:   0%|          | 0/9 [00:00<?, ?it/s]
erating negative factsheets:  11%|█         | 1/9 [01:36<12:55, 96.94s/it]
erating negative factsheets:  22%|██▏       | 2/9 [01:53<05:46, 49.43s/it]
erating negative factsheets:  33%|███▎      | 3/9 [01:57<02:53, 28.89s/it]
erating negative factsheets:  44%|████▍     | 4/9 [02:05<01:42, 20.51s/it]
erating negative factsheets:  56%|█████▌    | 5/9 [02:13<01:04, 16.24s/it]
erating negative factsheets:  67%|██████▋   | 6/9 [02:15<00:33, 11.16s/it]
erating negative factsheets:  78%|███████▊  | 7/9 [02:17<00:16,  8.18s/it]
erating negative factsheets:  89%|████████▉ | 8/9 [02:21<00:06,  6.99s/it]
generating negative factsheets: 100%|██████████| 9/9 [02:27<00:00, 16.41s/it]
100%|██████████| 3/3 [08:35<00:00, 171.99s/it]

In [546]:
query_negatives_dict[('Technology Used', 'Augmented reality')]

(True,
 ['**Company Name:** CrystalTech Innovations  **Website:** crystaltech.com  **Industry:** Optical Solutions  **Target Audience:** Manufacturers in need of advanced optical components  **Products & Services:**  - Crystal Lenses: Precision lenses for industrial applications  - Optical Coatings: Anti-reflective coatings for various surfaces  **Unique Selling Propositions (USPs) & Key Differentiators:**  - High precision manufacturing processes  - Customizable optical solutions  **Business Model:** B2B  **Technology Used:** Advanced optics and laser technology, but no implementation of augmented reality solutions  **Revenue Model:** Project-based contracts  **Competitive Landscape:** Competes with other optical component manufacturers  **Overall Assessment:** While CrystalTech is at the forefront of optical solutions, their product line does not integrate augmented reality technology. They focus on traditional optics, which are unrelated to AR applications.',
  '**Company Name:** VisionWare Enterprises  **Website:** visionware-enterprises.com  **Industry:** Data Visualization Software  **Target Audience:** Enterprises needing enhanced data visualizations  **Products & Services:**  - VisionWare Studio: Data visualization tool with dynamic charting  - VisionWare Cloud: Cloud-based data analytics platform  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Easy integration with existing data systems  - Advanced visualization techniques  **Business Model:** B2B SaaS  **Technology Used:** Proprietary data visualization algorithms, no augmented reality features  **Revenue Model:** Subscription-based  **Competitive Landscape:** Competes with Tableau and Power BI  **Overall Assessment:** VisionWare provides sophisticated data visualization tools, but their platform does not incorporate augmented reality elements. They focus strictly on enhancing traditional data representation methods.',
  '**Company Name:** DigiArt Studios  **Website:** digiartstudios.com  **Industry:** Digital Content Creation  **Target Audience:** Media companies and advertising agencies  **Products & Services:**  - Digital Animations: 2D and 3D animation services  - Graphic Design: Comprehensive design services for digital media  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Creative and engaging digital content  - Skilled team of artists and designers  **Business Model:** B2B Services  **Technology Used:** 3D modeling and animation software, but no augmented reality capabilities  **Revenue Model:** Project-based  **Competitive Landscape:** Competes with traditional animation studios  **Overall Assessment:** DigiArt Studios excels in creating digital art and animations, but does not implement augmented reality in their services. Their expertise lies in conventional digital media, not AR.',
  '**Company Name:** SoundWave Inc.  **Website:** soundwaveinc.com  **Industry:** Audio Technology  **Target Audience:** Professional sound engineers and studios  **Products & Services:**  - AudioMix Pro: Professional-grade audio mixing software  - SoundWave Hardware: High-fidelity audio equipment  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Superior sound quality with cutting-edge audio processing  - Compatible with all major audio formats  **Business Model:** B2B and B2C  **Technology Used:** Advanced digital audio processing, no augmented reality features  **Revenue Model:** Product sales and software licensing  **Competitive Landscape:** Competes with other audio tech companies like Bose and Sennheiser  **Overall Assessment:** SoundWave is a leader in audio technology, focusing on sound quality and innovation. However, their technology stack does not include augmented reality, as their products are strictly audio-focused.',
  '**Company Name:** GeoMap Solutions  **Website:** geomapsolutions.com  **Industry:** Geographic Information Systems (GIS)  **Target Audience:** Government agencies and environmental organizations  **Products & Services:**  - GeoMap Pro: Advanced GIS software for mapping and spatial analysis  - Remote Sensing Tools: Satellite imagery processing tools  **Unique Selling Propositions (USPs) & Key Differentiators:**  - High accuracy spatial data processing  - Extensive GIS toolset for professionals  **Business Model:** B2B Software Licensing  **Technology Used:** GIS technology and remote sensing, no augmented reality  **Revenue Model:** License fees and subscriptions  **Competitive Landscape:** Competes with ESRI and other GIS providers  **Overall Assessment:** GeoMap Solutions is a GIS powerhouse, providing robust spatial data tools. However, their technology offerings do not extend to augmented reality, focusing instead on conventional mapping solutions.',
  '**Company Name:** SecureNet Technologies  **Website:** securenet-tech.com  **Industry:** Cybersecurity  **Target Audience:** Enterprises and government entities  **Products & Services:**  - SecureGuard: Comprehensive cybersecurity platform  - Threat Intelligence Services: Real-time threat monitoring and analysis  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Advanced threat detection algorithms  - Seamless integration with existing IT infrastructure  **Business Model:** B2B Services  **Technology Used:** Cybersecurity and threat intelligence technologies, no augmented reality  **Revenue Model:** Subscription and consulting fees  **Competitive Landscape:** Competes with Palo Alto Networks and CrowdStrike  **Overall Assessment:** SecureNet is a leader in cybersecurity, focusing on protecting digital assets. Their technology stack is robust in security but lacks augmented reality elements, staying within the cybersecurity domain.',
  '**Company Name:** EcoTech Systems  **Website:** ecotech-systems.com  **Industry:** Environmental Technology  **Target Audience:** Municipalities and environmental agencies  **Products & Services:**  - Waste Management Systems: Solutions for efficient waste processing  - Renewable Energy Solutions: Solar and wind energy systems  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Sustainable and eco-friendly technology  - High-efficiency energy systems  **Business Model:** B2B  **Technology Used:** Renewable energy technologies, no augmented reality  **Revenue Model:** Project-based and product sales  **Competitive Landscape:** Competes with other renewable energy companies  **Overall Assessment:** EcoTech Systems provides cutting-edge environmental solutions but does not incorporate augmented reality. Their focus remains on sustainability and renewable energy technologies.',
  '**Company Name:** MedTech Solutions  **Website:** medtech-solutions.com  **Industry:** Medical Devices  **Target Audience:** Hospitals and healthcare providers  **Products & Services:**  - Diagnostic Imaging Equipment: Advanced MRI and CT machines  - Patient Monitoring Systems: Real-time health monitoring devices  **Unique Selling Propositions (USPs) & Key Differentiators:**  - High-precision diagnostic tools  - Comprehensive patient care solutions  **Business Model:** B2B  **Technology Used:** Medical imaging and monitoring technology, no augmented reality  **Revenue Model:** Product sales and service contracts  **Competitive Landscape:** Competes with Siemens Healthineers and GE Healthcare  **Overall Assessment:** MedTech Solutions is a leader in medical technology, focusing on diagnostic tools and patient care. Their product line does not include augmented reality, centering instead on traditional medical devices.',
  '**Company Name:** FinServe Solutions  **Website:** finservesolutions.com  **Industry:** Financial Technology  **Target Audience:** Banks and financial institutions  **Products & Services:**  - FinServe Platform: Comprehensive financial management software  - Risk Analysis Tools: Advanced tools for financial risk assessment  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Robust financial analytics capabilities  - Secure and compliant with industry standards  **Business Model:** B2B SaaS  **Technology Used:** Financial analytics and risk management tools, no augmented reality  **Revenue Model:** Subscription-based  **Competitive Landscape:** Competes with major fintech providers like Bloomberg and Thomson Reuters  **Overall Assessment:** FinServe Solutions offers advanced financial technology solutions, focusing on analytics and risk management. Their platform does not integrate augmented reality, remaining in the fintech space.',
  '**Company Name:** GreenTech Innovations  **Website:** greentech-innovations.com  **Industry:** Clean Energy  **Target Audience:** Renewable energy providers and large enterprises  **Products & Services:**  - SolarGrid Systems: Advanced solar panel systems  - WindPower Solutions: High-efficiency wind turbines  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Environmentally friendly energy solutions  - High return on investment for energy systems  **Business Model:** B2B  **Technology Used:** Solar and wind technology, no augmented reality  **Revenue Model:** Project-based and product sales  **Competitive Landscape:** Competes with other clean energy companies like Tesla and Vestas  **Overall Assessment:** GreenTech Innovations excels in providing renewable energy solutions. Their technology is focused on clean energy without any augmented reality components, staying within the sustainable energy sector.',
  '**Company Name:** EduLearn Systems  **Website:** edulearn-systems.com  **Industry:** Educational Technology  **Target Audience:** Schools and educational institutions  **Products & Services:**  - EduLearn Platform: Online learning management system  - Interactive Learning Modules: Digital courses and content  **Unique Selling Propositions (USPs) & Key Differentiators:**  - User-friendly interface for educators and students  - Comprehensive analytics for tracking student progress  **Business Model:** B2B and B2C  **Technology Used:** e-learning technologies, no augmented reality  **Revenue Model:** Subscription-based and licensing  **Competitive Landscape:** Competes with other edtech companies like Blackboard and Canvas  **Overall Assessment:** EduLearn Systems provides robust e-learning solutions. While their platform is highly interactive, it does not utilize augmented reality, focusing instead on traditional digital education methods.',
  '**Company Name:** SmartHome Inc.  **Website:** smarthome-inc.com  **Industry:** Home Automation  **Target Audience:** Homeowners and residential developers  **Products & Services:**  - SmartHub: Centralized home automation system  - SmartSecurity: Advanced home security solutions  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Seamless integration with existing home devices  - High security and ease of use for homeowners  **Business Model:** B2C  **Technology Used:** IoT and automation technologies, no augmented reality  **Revenue Model:** Product sales  **Competitive Landscape:** Competes with other smart home solutions like Nest and Ring  **Overall Assessment:** SmartHome Inc. focuses on home automation and security. Their technology stack is centered around IoT, with no augmented reality components, aligning with traditional smart home technologies.',
  '**Company Name:** BrightTech Solutions  **Website:** brighttech-solutions.com  **Industry:** LED Lighting  **Target Audience:** Commercial and industrial sectors  **Products & Services:**  - BrightLED: High-efficiency LED lighting systems  - EnergySaver: Smart lighting management solutions  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Energy-efficient lighting with extended lifespan  - Smart lighting controls for reduced energy consumption  **Business Model:** B2B  **Technology Used:** LED and smart lighting technologies, no augmented reality  **Revenue Model:** Product sales and service agreements  **Competitive Landscape:** Competes with other lighting companies like Philips and GE Lighting  **Overall Assessment:** BrightTech Solutions excels in providing energy-efficient lighting solutions. Their focus is on smart and LED technologies, without integrating augmented reality into their product offerings.',
  '**Company Name:** AquaTech Systems  **Website:** aquatech-systems.com  **Industry:** Water Treatment  **Target Audience:** Municipalities and industrial clients  **Products & Services:**  - AquaClean: Advanced water purification systems  - WasteWater Solutions: Efficient wastewater treatment technologies  **Unique Selling Propositions (USPs) & Key Differentiators:**  - High-efficiency purification processes  - Customizable solutions for various water treatment needs  **Business Model:** B2B  **Technology Used:** Water filtration and treatment, no augmented reality  **Revenue Model:** Project-based and product sales  **Competitive Landscape:** Competes with other water treatment companies like Veolia and Suez  **Overall Assessment:** AquaTech Systems specializes in water treatment technologies, focusing on purification and wastewater solutions. Their offerings do not include augmented reality, staying within the traditional water management industry.',
  '**Company Name:** RoboTech Enterprises  **Website:** robotech-enterprises.com  **Industry:** Robotics  **Target Audience:** Manufacturing and industrial sectors  **Products & Services:**  - RoboArm: Precision robotic arms for assembly lines  - RoboControl: Advanced robotics control systems  **Unique Selling Propositions (USPs) & Key Differentiators:**  - High precision and reliability in robotics  - Customizable solutions for complex manufacturing needs  **Business Model:** B2B  **Technology Used:** Robotics and automation, no augmented reality  **Revenue Model:** Product sales and service agreements  **Competitive Landscape:** Competes with other robotics companies like ABB and FANUC  **Overall Assessment:** RoboTech Enterprises is a leader in robotic automation, focusing on manufacturing solutions. Their technology stack does not include augmented reality, focusing instead on traditional robotics.',
  '**Company Name:** HealthCare Innovations  **Website:** healthcare-innovations.com  **Industry:** Health Technology  **Target Audience:** Hospitals and clinics  **Products & Services:**  - HealthMonitor: Advanced patient monitoring systems  - TeleHealth Solutions: Remote healthcare consultation platforms  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Comprehensive patient data management  - Secure and reliable telehealth services  **Business Model:** B2B  **Technology Used:** Health monitoring and telehealth technologies, no augmented reality  **Revenue Model:** Subscription and service fees  **Competitive Landscape:** Competes with other health tech companies like Philips and Cerner  **Overall Assessment:** HealthCare Innovations provides cutting-edge health technology solutions. Their focus is on patient monitoring and telehealth, without augmented reality integration, staying within the traditional health tech space.',
  '**Company Name:** DataGuard Solutions  **Website:** dataguard-solutions.com  **Industry:** Data Security  **Target Audience:** Enterprises and government agencies  **Products & Services:**  - DataShield: Comprehensive data protection platform  - CyberDefense Services: Proactive cybersecurity solutions  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Advanced encryption and threat detection  - Seamless integration with existing IT systems  **Business Model:** B2B  **Technology Used:** Data security and encryption technologies, no augmented reality  **Revenue Model:** Subscription and consulting fees  **Competitive Landscape:** Competes with other cybersecurity firms like McAfee and Symantec  **Overall Assessment:** DataGuard Solutions is a leader in data security, focusing on protection and threat management. Their offerings do not include augmented reality, sticking strictly to cybersecurity solutions.',
  '**Company Name:** CommsTech Innovations  **Website:** commstech-innovations.com  **Industry:** Telecommunications  **Target Audience:** Telecom providers and large enterprises  **Products & Services:**  - NetworkBoost: Advanced network infrastructure solutions  - CommsManager: Comprehensive telecom management software  **Unique Selling Propositions (USPs) & Key Differentiators:**  - High-speed and reliable network solutions  - Scalable telecom management systems  **Business Model:** B2B  **Technology Used:** Telecommunications and network technologies, no augmented reality  **Revenue Model:** Project-based and software licensing  **Competitive Landscape:** Competes with major telecom infrastructure providers like Cisco and Ericsson  **Overall Assessment:** CommsTech Innovations excels in telecommunications solutions. Their focus is on network infrastructure and management, without integrating augmented reality, remaining in the telecom domain.',
  '**Company Name:** CleanAir Technologies  **Website:** cleanair-technologies.com  **Industry:** Environmental Solutions  **Target Audience:** Industrial and commercial sectors  **Products & Services:**  - AirPurify: Advanced air purification systems  - EmissionControl: Solutions for reducing industrial emissions  **Unique Selling Propositions (USPs) & Key Differentiators:**  - High-efficiency air filtration  - Custom solutions for emission reduction  **Business Model:** B2B  **Technology Used:** Air purification and emission control technologies, no augmented reality  **Revenue Model:** Project-based and product sales  **Competitive Landscape:** Competes with other environmental solution providers  **Overall Assessment:** CleanAir Technologies focuses on air quality solutions, providing purification and emission control technologies. Their offerings do not include augmented reality, staying within the environmental sector.',
  '**Company Name:** AgriTech Solutions  **Website:** agritech-solutions.com  **Industry:** Agricultural Technology  **Target Audience:** Farmers and agricultural enterprises  **Products & Services:**  - SmartFarm: Advanced farm management software  - CropMonitor: Real-time crop monitoring systems  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Precision agriculture techniques  - Real-time data for improved crop yields  **Business Model:** B2B  **Technology Used:** Agricultural technologies, no augmented reality  **Revenue Model:** Subscription-based and product sales  **Competitive Landscape:** Competes with other agri-tech companies like John Deere and Trimble  **Overall Assessment:** AgriTech Solutions provides innovative agricultural technologies, focusing on precision farming. Their technology stack does not include augmented reality, staying within the conventional agriculture domain.',
  '**Company Name:** UrbanTech Solutions  **Website:** urbantech-solutions.com  **Industry:** Urban Planning and Development  **Target Audience:** Municipalities and urban developers  **Products & Services:**  - CityPlan Pro: Advanced urban planning software  - SmartCity Solutions: Integrated smart city technologies  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Comprehensive urban analysis tools  - Scalable solutions for smart city development  **Business Model:** B2B  **Technology Used:** Urban planning and smart city technologies, no augmented reality  **Revenue Model:** Project-based and software licensing  **Competitive Landscape:** Competes with other urban planning firms and smart city solution providers  **Overall Assessment:** UrbanTech Solutions specializes in urban planning and development, focusing on smart city technologies. Their offerings do not include augmented reality, staying within the urban planning space.',

In [1369]:
with open('../synthetic_data/synthetic_negatives.pkl','wb') as f:
    pickle.dump(query_negatives_dict,f)

In [ ]:
for aspect in tqdm(['Customer Segment']):
    queries=list(positives_df[positives_df.aspect==aspect].consolidated_query.unique())
    
    args=[([queries[i],60,aspect],{}) for i in range(len(queries))]
    
    factsheets=parallel_execute(
                        func= generate_factsheets,
                        argument_sets=args,
                        max_workers = 50,
                        show_progress= True,
                        desc = "generating negative factsheets"
                    )
    
    
    _query_negatives_dict=dict(zip(queries,factsheets))
    
    query_negatives_dict={**query_negatives_dict,**_query_negatives_dict}

  0%|          | 0/1 [00:00<?, ?it/s]
erating negative factsheets:   0%|          | 0/84 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/84 [01:34<2:10:15, 94.16s/it]
erating negative factsheets:   2%|▏         | 2/84 [01:42<59:19, 43.41s/it]
erating negative factsheets:   4%|▎         | 3/84 [01:46<34:52, 25.83s/it]
erating negative factsheets:   5%|▍         | 4/84 [01:51<23:19, 17.50s/it]
erating negative factsheets:   6%|▌         | 5/84 [01:56<16:57, 12.89s/it]
erating negative factsheets:   7%|▋         | 6/84 [01:57<11:25,  8.79s/it]
erating negative factsheets:   8%|▊         | 7/84 [01:59<08:27,  6.60s/it]
erating negative factsheets:  10%|▉         | 8/84 [02:00<06:04,  4.79s/it]
erating negative factsheets:  11%|█         | 9/84 [02:00<04:24,  3.53s/it]
erating negative factsheets:  13%|█▎        | 11/84 [02:02<02:46,  2.27s/it]
erating negative factsheets:  14%|█▍        | 12/84 [02:06<03:06,  2.59s/it]
erating negative factsheets:  15%|█▌        | 13/84 [02:09<03:11,  2.70s/it]
erating negative factsheets:  17%|█▋        | 14/84 [02:10<02:43,  2.34s/it]
erating negative factsheets:  18%|█▊        | 15/84 [02:10<02:00,  1.74s/it]
erating negative factsheets:  19%|█▉        | 16/84 [02:12<02:01,  1.79s/it]
erating negative factsheets:  20%|██        | 17/84 [02:13<01:39,  1.49s/it]
erating negative factsheets:  21%|██▏       | 18/84 [02:14<01:27,  1.33s/it]
erating negative factsheets:  23%|██▎       | 19/84 [02:17<02:01,  1.87s/it]
erating negative factsheets:  24%|██▍       | 20/84 [02:18<01:34,  1.47s/it]
erating negative factsheets:  25%|██▌       | 21/84 [02:18<01:08,  1.08s/it]
erating negative factsheets:  27%|██▋       | 23/84 [02:18<00:44,  1.38it/s]
erating negative factsheets:  29%|██▊       | 24/84 [02:24<02:02,  2.04s/it]
erating negative factsheets:  30%|██▉       | 25/84 [02:25<01:34,  1.60s/it]
erating negative factsheets:  31%|███       | 26/84 [02:28<02:00,  2.08s/it]
erating negative factsheets:  37%|███▋      | 31/84 [02:35<01:23,  1.58s/it]
erating negative factsheets:  38%|███▊      | 32/84 [02:36<01:09,  1.34s/it]
erating negative factsheets:  39%|███▉      | 33/84 [02:38<01:20,  1.59s/it]
erating negative factsheets:  40%|████      | 34/84 [02:39<01:05,  1.31s/it]
erating negative factsheets:  42%|████▏     | 35/84 [02:41<01:20,  1.64s/it]
erating negative factsheets:  43%|████▎     | 36/84 [02:42<01:06,  1.38s/it]
erating negative factsheets:  44%|████▍     | 37/84 [02:45<01:20,  1.72s/it]
erating negative factsheets:  45%|████▌     | 38/84 [02:46<01:18,  1.70s/it]
erating negative factsheets:  46%|████▋     | 39/84 [02:47<01:00,  1.35s/it]
erating negative factsheets:  48%|████▊     | 40/84 [02:47<00:43,  1.00it/s]
erating negative factsheets:  49%|████▉     | 41/84 [02:48<00:38,  1.10it/s]
erating negative factsheets:  50%|█████     | 42/84 [02:53<01:35,  2.27s/it]
erating negative factsheets:  51%|█████     | 43/84 [02:56<01:43,  2.51s/it]
erating negative factsheets:  52%|█████▏    | 44/84 [02:57<01:15,  1.89s/it]
erating negative factsheets:  54%|█████▎    | 45/84 [02:59<01:21,  2.08s/it]
erating negative factsheets:  55%|█████▍    | 46/84 [03:02<01:25,  2.26s/it]
erating negative factsheets:  56%|█████▌    | 47/84 [03:02<01:03,  1.72s/it]
erating negative factsheets:  57%|█████▋    | 48/84 [03:08<01:44,  2.90s/it]
erating negative factsheets:  58%|█████▊    | 49/84 [03:17<02:42,  4.63s/it]
erating negative factsheets:  60%|█████▉    | 50/84 [03:25<03:13,  5.70s/it]
erating negative factsheets:  61%|██████    | 51/84 [03:36<04:06,  7.46s/it]
erating negative factsheets:  62%|██████▏   | 52/84 [03:39<03:13,  6.06s/it]
erating negative factsheets:  63%|██████▎   | 53/84 [03:44<02:53,  5.61s/it]
erating negative factsheets:  64%|██████▍   | 54/84 [03:46<02:18,  4.61s/it]
erating negative factsheets:  65%|██████▌   | 55/84 [03:48<01:49,  3.78s/it]
erating negative factsheets:  67%|██████▋   | 56/84 [03:52<01:52,  4.01s/it]
erating negative factsheets:  68%|██████▊   | 57/84 [03:53<01:18,  2.90s/it]
erating negative factsheets:  70%|███████   | 59/84 [04:00<01:21,  3.25s/it]
erating negative factsheets:  71%|███████▏  | 60/84 [04:04<01:25,  3.57s/it]
erating negative factsheets:  73%|███████▎  | 61/84 [04:05<01:04,  2.78s/it]
erating negative factsheets:  74%|███████▍  | 62/84 [04:06<00:52,  2.37s/it]
erating negative factsheets:  75%|███████▌  | 63/84 [04:11<01:05,  3.11s/it]
erating negative factsheets:  76%|███████▌  | 64/84 [04:12<00:48,  2.42s/it]
erating negative factsheets:  77%|███████▋  | 65/84 [04:14<00:43,  2.27s/it]
erating negative factsheets:  79%|███████▊  | 66/84 [04:16<00:42,  2.35s/it]
erating negative factsheets:  80%|███████▉  | 67/84 [04:18<00:33,  1.98s/it]
erating negative factsheets:  81%|████████  | 68/84 [04:20<00:32,  2.00s/it]
erating negative factsheets:  82%|████████▏ | 69/84 [04:24<00:39,  2.65s/it]
erating negative factsheets:  83%|████████▎ | 70/84 [04:24<00:27,  1.95s/it]
erating negative factsheets:  85%|████████▍ | 71/84 [04:25<00:22,  1.76s/it]
erating negative factsheets:  86%|████████▌ | 72/84 [04:31<00:34,  2.85s/it]
erating negative factsheets:  87%|████████▋ | 73/84 [04:32<00:26,  2.43s/it]
erating negative factsheets:  88%|████████▊ | 74/84 [04:35<00:25,  2.51s/it]
erating negative factsheets:  89%|████████▉ | 75/84 [04:38<00:24,  2.74s/it]
erating negative factsheets:  90%|█████████ | 76/84 [04:40<00:19,  2.43s/it]
erating negative factsheets:  92%|█████████▏| 77/84 [04:42<00:16,  2.37s/it]
erating negative factsheets:  93%|█████████▎| 78/84 [04:43<00:12,  2.04s/it]
erating negative factsheets:  94%|█████████▍| 79/84 [04:44<00:08,  1.74s/it]
erating negative factsheets:  96%|█████████▋| 81/84 [04:46<00:03,  1.18s/it]
erating negative factsheets:  98%|█████████▊| 82/84 [04:49<00:03,  1.70s/it]
erating negative factsheets:  99%|█████████▉| 83/84 [04:55<00:02,  2.77s/it]
generating negative factsheets: 100%|██████████| 84/84 [04:59<00:00,  3.57s/it]
100%|██████████| 1/1 [05:00<00:00, 300.18s/it]

In [ ]:
$267.71 -> $260.22

In [581]:
with open('../synthetic_data/synthetic_negatives.pkl','wb') as f:
    pickle.dump(query_negatives_dict,f)

In [ ]:
254.47

In [675]:
for aspect in tqdm(['Customer Industry','Industry']):
    queries=list(positives_df[positives_df.aspect==aspect].consolidated_query.unique())
    
    args=[([queries[i],50,aspect],{}) for i in range(len(queries))]
    
    factsheets=parallel_execute(
                        func= generate_factsheets,
                        argument_sets=args,
                        max_workers = 50,
                        show_progress= True,
                        desc = "generating negative factsheets"
                    )
    
    
    _query_negatives_dict=dict(zip(queries,factsheets))
    
    query_negatives_dict={**query_negatives_dict,**_query_negatives_dict}

  0%|          | 0/2 [00:00<?, ?it/s]
erating negative factsheets:   0%|          | 0/75 [00:00<?, ?it/s]
erating negative factsheets:   1%|▏         | 1/75 [00:47<58:03, 47.07s/it]
erating negative factsheets:   3%|▎         | 2/75 [00:52<27:39, 22.74s/it]
erating negative factsheets:   4%|▍         | 3/75 [00:53<15:11, 12.66s/it]
erating negative factsheets:   5%|▌         | 4/75 [00:53<09:16,  7.83s/it]
erating negative factsheets:   7%|▋         | 5/75 [00:54<06:10,  5.30s/it]
erating negative factsheets:   8%|▊         | 6/75 [00:56<04:36,  4.01s/it]
erating negative factsheets:   9%|▉         | 7/75 [00:56<03:17,  2.91s/it]
erating negative factsheets:  11%|█         | 8/75 [00:57<02:30,  2.24s/it]
erating negative factsheets:  12%|█▏        | 9/75 [00:57<01:44,  1.59s/it]
erating negative factsheets:  13%|█▎        | 10/75 [00:58<01:28,  1.36s/it]
erating negative factsheets:  16%|█▌        | 12/75 [00:58<00:49,  1.28it/s]
erating negative factsheets:  17%|█▋        | 13/75 [00:59<00:42,  1.47it/s]
erating negative factsheets:  19%|█▊        | 14/75 [00:59<00:33,  1.82it/s]
erating negative factsheets:  20%|██        | 15/75 [00:59<00:27,  2.17it/s]
erating negative factsheets:  21%|██▏       | 16/75 [00:59<00:22,  2.65it/s]
erating negative factsheets:  24%|██▍       | 18/75 [00:59<00:13,  4.26it/s]
erating negative factsheets:  25%|██▌       | 19/75 [01:00<00:18,  3.03it/s]
erating negative factsheets:  27%|██▋       | 20/75 [01:01<00:20,  2.65it/s]
erating negative factsheets:  28%|██▊       | 21/75 [01:01<00:16,  3.29it/s]
erating negative factsheets:  29%|██▉       | 22/75 [01:01<00:13,  3.82it/s]
erating negative factsheets:  31%|███       | 23/75 [01:01<00:12,  4.05it/s]
erating negative factsheets:  32%|███▏      | 24/75 [01:02<00:16,  3.09it/s]
erating negative factsheets:  33%|███▎      | 25/75 [01:02<00:17,  2.86it/s]
erating negative factsheets:  35%|███▍      | 26/75 [01:02<00:18,  2.61it/s]
erating negative factsheets:  36%|███▌      | 27/75 [01:04<00:32,  1.46it/s]
erating negative factsheets:  37%|███▋      | 28/75 [01:04<00:25,  1.82it/s]
erating negative factsheets:  39%|███▊      | 29/75 [01:05<00:27,  1.70it/s]
erating negative factsheets:  40%|████      | 30/75 [01:05<00:25,  1.79it/s]
erating negative factsheets:  41%|████▏     | 31/75 [01:07<00:34,  1.28it/s]
erating negative factsheets:  44%|████▍     | 33/75 [01:07<00:21,  1.95it/s]
erating negative factsheets:  47%|████▋     | 35/75 [01:07<00:14,  2.69it/s]
erating negative factsheets:  48%|████▊     | 36/75 [01:08<00:17,  2.23it/s]
erating negative factsheets:  49%|████▉     | 37/75 [01:08<00:17,  2.22it/s]
erating negative factsheets:  51%|█████     | 38/75 [01:10<00:23,  1.58it/s]
erating negative factsheets:  52%|█████▏    | 39/75 [01:11<00:27,  1.31it/s]
erating negative factsheets:  53%|█████▎    | 40/75 [01:12<00:29,  1.20it/s]
erating negative factsheets:  56%|█████▌    | 42/75 [01:12<00:20,  1.62it/s]
erating negative factsheets:  57%|█████▋    | 43/75 [01:17<00:50,  1.57s/it]
erating negative factsheets:  59%|█████▊    | 44/75 [01:18<00:40,  1.30s/it]
erating negative factsheets:  60%|██████    | 45/75 [01:18<00:33,  1.12s/it]
erating negative factsheets:  61%|██████▏   | 46/75 [01:20<00:34,  1.19s/it]
erating negative factsheets:  63%|██████▎   | 47/75 [01:22<00:39,  1.42s/it]
erating negative factsheets:  64%|██████▍   | 48/75 [01:22<00:32,  1.20s/it]
erating negative factsheets:  65%|██████▌   | 49/75 [01:22<00:23,  1.11it/s]
erating negative factsheets:  67%|██████▋   | 50/75 [01:27<00:48,  1.94s/it]
erating negative factsheets:  68%|██████▊   | 51/75 [01:41<02:11,  5.49s/it]
erating negative factsheets:  69%|██████▉   | 52/75 [01:49<02:25,  6.31s/it]
erating negative factsheets:  71%|███████   | 53/75 [01:53<02:05,  5.73s/it]
erating negative factsheets:  72%|███████▏  | 54/75 [01:54<01:28,  4.22s/it]
erating negative factsheets:  73%|███████▎  | 55/75 [01:55<01:04,  3.22s/it]
erating negative factsheets:  76%|███████▌  | 57/75 [01:56<00:36,  2.02s/it]
erating negative factsheets:  77%|███████▋  | 58/75 [02:00<00:43,  2.57s/it]
erating negative factsheets:  79%|███████▊  | 59/75 [02:02<00:37,  2.36s/it]
erating negative factsheets:  80%|████████  | 60/75 [02:04<00:32,  2.17s/it]
erating negative factsheets:  81%|████████▏ | 61/75 [02:04<00:22,  1.61s/it]
erating negative factsheets:  83%|████████▎ | 62/75 [02:05<00:20,  1.54s/it]
erating negative factsheets:  84%|████████▍ | 63/75 [02:09<00:26,  2.22s/it]
erating negative factsheets:  85%|████████▌ | 64/75 [02:10<00:19,  1.82s/it]
erating negative factsheets:  87%|████████▋ | 65/75 [02:11<00:14,  1.47s/it]
erating negative factsheets:  88%|████████▊ | 66/75 [02:11<00:10,  1.13s/it]
erating negative factsheets:  89%|████████▉ | 67/75 [02:11<00:07,  1.09it/s]
erating negative factsheets:  91%|█████████ | 68/75 [02:13<00:06,  1.02it/s]
erating negative factsheets:  92%|█████████▏| 69/75 [02:13<00:04,  1.38it/s]
erating negative factsheets:  93%|█████████▎| 70/75 [02:14<00:04,  1.19it/s]
erating negative factsheets:  95%|█████████▍| 71/75 [02:15<00:03,  1.00it/s]
erating negative factsheets:  96%|█████████▌| 72/75 [02:16<00:02,  1.20it/s]
erating negative factsheets:  97%|█████████▋| 73/75 [02:18<00:02,  1.38s/it]
erating negative factsheets:  99%|█████████▊| 74/75 [02:21<00:01,  1.74s/it]
generating negative factsheets: 100%|██████████| 75/75 [02:22<00:00,  1.90s/it]
 50%|█████     | 1/2 [02:22<02:22, 142.93s/it]
erating negative factsheets:   0%|          | 0/90 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/90 [00:49<1:13:58, 49.87s/it]
erating negative factsheets:   2%|▏         | 2/90 [00:51<31:15, 21.32s/it]
erating negative factsheets:   3%|▎         | 3/90 [00:52<17:51, 12.31s/it]
erating negative factsheets:   4%|▍         | 4/90 [00:52<10:44,  7.49s/it]
erating negative factsheets:   6%|▌         | 5/90 [00:53<07:17,  5.14s/it]
erating negative factsheets:   7%|▋         | 6/90 [00:54<04:54,  3.51s/it]
erating negative factsheets:   9%|▉         | 8/90 [00:54<02:38,  1.93s/it]
erating negative factsheets:  10%|█         | 9/90 [00:56<02:21,  1.75s/it]
erating negative factsheets:  12%|█▏        | 11/90 [00:56<01:34,  1.20s/it]
erating negative factsheets:  13%|█▎        | 12/90 [00:57<01:28,  1.14s/it]
erating negative factsheets:  16%|█▌        | 14/90 [00:58<01:07,  1.13it/s]
erating negative factsheets:  17%|█▋        | 15/90 [00:59<00:53,  1.41it/s]
erating negative factsheets:  18%|█▊        | 16/90 [00:59<00:50,  1.47it/s]
erating negative factsheets:  21%|██        | 19/90 [00:59<00:28,  2.50it/s]
erating negative factsheets:  22%|██▏       | 20/90 [01:00<00:30,  2.26it/s]
erating negative factsheets:  23%|██▎       | 21/90 [01:00<00:26,  2.62it/s]
erating negative factsheets:  24%|██▍       | 22/90 [01:01<00:30,  2.23it/s]
erating negative factsheets:  26%|██▌       | 23/90 [01:01<00:30,  2.20it/s]
erating negative factsheets:  28%|██▊       | 25/90 [01:02<00:20,  3.15it/s]
erating negative factsheets:  29%|██▉       | 26/90 [01:02<00:17,  3.57it/s]
erating negative factsheets:  31%|███       | 28/90 [01:02<00:13,  4.59it/s]
erating negative factsheets:  33%|███▎      | 30/90 [01:03<00:23,  2.55it/s]
erating negative factsheets:  34%|███▍      | 31/90 [01:04<00:24,  2.37it/s]
erating negative factsheets:  36%|███▌      | 32/90 [01:05<00:28,  2.03it/s]
erating negative factsheets:  37%|███▋      | 33/90 [01:05<00:25,  2.23it/s]
erating negative factsheets:  39%|███▉      | 35/90 [01:06<00:29,  1.88it/s]
erating negative factsheets:  40%|████      | 36/90 [01:07<00:30,  1.75it/s]
erating negative factsheets:  41%|████      | 37/90 [01:08<00:30,  1.76it/s]
erating negative factsheets:  42%|████▏     | 38/90 [01:09<00:36,  1.44it/s]
erating negative factsheets:  43%|████▎     | 39/90 [01:09<00:32,  1.58it/s]
erating negative factsheets:  44%|████▍     | 40/90 [01:09<00:26,  1.91it/s]
erating negative factsheets:  46%|████▌     | 41/90 [01:10<00:21,  2.26it/s]
erating negative factsheets:  47%|████▋     | 42/90 [01:10<00:20,  2.38it/s]
erating negative factsheets:  48%|████▊     | 43/90 [01:11<00:27,  1.72it/s]
erating negative factsheets:  49%|████▉     | 44/90 [01:12<00:32,  1.42it/s]
erating negative factsheets:  50%|█████     | 45/90 [01:14<00:45,  1.01s/it]
erating negative factsheets:  51%|█████     | 46/90 [01:14<00:39,  1.12it/s]
erating negative factsheets:  52%|█████▏    | 47/90 [01:15<00:40,  1.07it/s]
erating negative factsheets:  53%|█████▎    | 48/90 [01:16<00:41,  1.00it/s]
erating negative factsheets:  54%|█████▍    | 49/90 [01:17<00:40,  1.00it/s]
erating negative factsheets:  56%|█████▌    | 50/90 [01:25<02:02,  3.07s/it]
erating negative factsheets:  57%|█████▋    | 51/90 [01:42<04:41,  7.22s/it]
erating negative factsheets:  58%|█████▊    | 52/90 [01:48<04:21,  6.87s/it]
erating negative factsheets:  59%|█████▉    | 53/90 [01:54<04:01,  6.54s/it]
erating negative factsheets:  60%|██████    | 54/90 [01:55<02:49,  4.72s/it]
erating negative factsheets:  61%|██████    | 55/90 [01:55<01:57,  3.35s/it]
erating negative factsheets:  62%|██████▏   | 56/90 [01:55<01:24,  2.50s/it]
erating negative factsheets:  63%|██████▎   | 57/90 [01:56<01:02,  1.91s/it]
erating negative factsheets:  64%|██████▍   | 58/90 [01:58<01:02,  1.96s/it]
erating negative factsheets:  66%|██████▌   | 59/90 [01:59<00:56,  1.82s/it]
erating negative factsheets:  67%|██████▋   | 60/90 [02:00<00:39,  1.32s/it]
erating negative factsheets:  68%|██████▊   | 61/90 [02:03<00:59,  2.04s/it]
erating negative factsheets:  69%|██████▉   | 62/90 [02:03<00:41,  1.47s/it]
erating negative factsheets:  70%|███████   | 63/90 [02:05<00:39,  1.48s/it]
erating negative factsheets:  71%|███████   | 64/90 [02:05<00:29,  1.12s/it]
erating negative factsheets:  73%|███████▎  | 66/90 [02:06<00:20,  1.15it/s]
erating negative factsheets:  74%|███████▍  | 67/90 [02:07<00:17,  1.32it/s]
erating negative factsheets:  77%|███████▋  | 69/90 [02:07<00:10,  2.04it/s]
erating negative factsheets:  78%|███████▊  | 70/90 [02:08<00:13,  1.46it/s]
erating negative factsheets:  79%|███████▉  | 71/90 [02:09<00:10,  1.77it/s]
erating negative factsheets:  80%|████████  | 72/90 [02:09<00:09,  1.91it/s]
erating negative factsheets:  82%|████████▏ | 74/90 [02:12<00:13,  1.16it/s]
erating negative factsheets:  83%|████████▎ | 75/90 [02:13<00:15,  1.02s/it]
erating negative factsheets:  84%|████████▍ | 76/90 [02:14<00:13,  1.06it/s]
erating negative factsheets:  86%|████████▌ | 77/90 [02:14<00:11,  1.15it/s]
erating negative factsheets:  87%|████████▋ | 78/90 [02:17<00:14,  1.24s/it]
erating negative factsheets:  88%|████████▊ | 79/90 [02:17<00:11,  1.05s/it]
erating negative factsheets:  89%|████████▉ | 80/90 [02:18<00:09,  1.00it/s]
erating negative factsheets:  90%|█████████ | 81/90 [02:18<00:06,  1.33it/s]
erating negative factsheets:  91%|█████████ | 82/90 [02:19<00:05,  1.39it/s]
erating negative factsheets:  92%|█████████▏| 83/90 [02:21<00:08,  1.25s/it]
erating negative factsheets:  93%|█████████▎| 84/90 [02:22<00:05,  1.07it/s]
erating negative factsheets:  94%|█████████▍| 85/90 [02:22<00:03,  1.26it/s]
erating negative factsheets:  96%|█████████▌| 86/90 [02:24<00:04,  1.09s/it]
erating negative factsheets:  97%|█████████▋| 87/90 [02:29<00:07,  2.40s/it]
erating negative factsheets:  98%|█████████▊| 88/90 [02:34<00:06,  3.06s/it]
erating negative factsheets:  99%|█████████▉| 89/90 [02:35<00:02,  2.57s/it]
generating negative factsheets: 100%|██████████| 90/90 [03:16<00:00,  2.18s/it]
100%|██████████| 2/2 [05:39<00:00, 169.96s/it]

In [679]:
for aspect in tqdm(['Products & Services']):
    queries=list(positives_df[positives_df.aspect==aspect].consolidated_query.unique())
    
    args=[([queries[i],25,aspect],{}) for i in range(len(queries))]

    factsheets=parallel_execute(
                        func= generate_factsheets,
                        argument_sets=args,
                        max_workers = 25,
                        show_progress= True,
                        desc = "generating negative factsheets"
                    )
    
    
    _query_negatives_dict=dict(zip(queries,factsheets))
    
    query_negatives_dict={**query_negatives_dict,**_query_negatives_dict}

  0%|          | 0/1 [00:00<?, ?it/s]
erating negative factsheets:   0%|          | 0/98 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/98 [00:27<44:24, 27.47s/it]
erating negative factsheets:   2%|▏         | 2/98 [00:31<21:34, 13.48s/it]
erating negative factsheets:   3%|▎         | 3/98 [00:33<13:16,  8.38s/it]
erating negative factsheets:   4%|▍         | 4/98 [00:33<08:01,  5.12s/it]
erating negative factsheets:   6%|▌         | 6/98 [00:33<03:50,  2.51s/it]
erating negative factsheets:   7%|▋         | 7/98 [00:35<03:13,  2.13s/it]
erating negative factsheets:   9%|▉         | 9/98 [00:35<01:55,  1.29s/it]
erating negative factsheets:  10%|█         | 10/98 [00:36<01:38,  1.12s/it]
erating negative factsheets:  11%|█         | 11/98 [00:37<01:35,  1.10s/it]
erating negative factsheets:  12%|█▏        | 12/98 [00:39<02:11,  1.53s/it]
erating negative factsheets:  13%|█▎        | 13/98 [00:40<01:38,  1.16s/it]
erating negative factsheets:  14%|█▍        | 14/98 [00:40<01:16,  1.09it/s]
erating negative factsheets:  15%|█▌        | 15/98 [00:40<01:02,  1.32it/s]
erating negative factsheets:  16%|█▋        | 16/98 [00:41<00:57,  1.42it/s]
erating negative factsheets:  17%|█▋        | 17/98 [00:41<00:45,  1.77it/s]
erating negative factsheets:  18%|█▊        | 18/98 [00:43<01:29,  1.12s/it]
erating negative factsheets:  19%|█▉        | 19/98 [00:47<02:15,  1.72s/it]
erating negative factsheets:  20%|██        | 20/98 [00:47<01:51,  1.43s/it]
erating negative factsheets:  21%|██▏       | 21/98 [00:50<02:09,  1.68s/it]
erating negative factsheets:  24%|██▍       | 24/98 [00:51<01:08,  1.08it/s]
erating negative factsheets:  26%|██▌       | 25/98 [00:53<01:30,  1.24s/it]
erating negative factsheets:  27%|██▋       | 26/98 [01:01<03:23,  2.83s/it]
erating negative factsheets:  28%|██▊       | 27/98 [01:05<03:31,  2.98s/it]
erating negative factsheets:  29%|██▊       | 28/98 [01:06<03:04,  2.64s/it]
erating negative factsheets:  30%|██▉       | 29/98 [01:07<02:32,  2.22s/it]
erating negative factsheets:  31%|███       | 30/98 [01:08<02:05,  1.85s/it]
erating negative factsheets:  32%|███▏      | 31/98 [01:09<01:45,  1.58s/it]
erating negative factsheets:  34%|███▎      | 33/98 [01:10<01:02,  1.04it/s]
erating negative factsheets:  35%|███▍      | 34/98 [01:11<01:09,  1.08s/it]
erating negative factsheets:  36%|███▌      | 35/98 [01:11<00:53,  1.18it/s]
erating negative factsheets:  37%|███▋      | 36/98 [01:12<00:45,  1.37it/s]
erating negative factsheets:  38%|███▊      | 37/98 [01:12<00:42,  1.45it/s]
erating negative factsheets:  40%|███▉      | 39/98 [01:18<01:40,  1.70s/it]
erating negative factsheets:  41%|████      | 40/98 [01:19<01:22,  1.42s/it]
erating negative factsheets:  42%|████▏     | 41/98 [01:20<01:13,  1.29s/it]
erating negative factsheets:  43%|████▎     | 42/98 [01:21<01:08,  1.22s/it]
erating negative factsheets:  44%|████▍     | 43/98 [01:24<01:42,  1.87s/it]
erating negative factsheets:  45%|████▍     | 44/98 [01:27<01:52,  2.09s/it]
erating negative factsheets:  46%|████▌     | 45/98 [01:27<01:28,  1.66s/it]
erating negative factsheets:  48%|████▊     | 47/98 [01:28<00:49,  1.04it/s]
erating negative factsheets:  49%|████▉     | 48/98 [01:28<00:40,  1.25it/s]
erating negative factsheets:  50%|█████     | 49/98 [01:29<00:47,  1.02it/s]
erating negative factsheets:  51%|█████     | 50/98 [01:30<00:35,  1.33it/s]
erating negative factsheets:  52%|█████▏    | 51/98 [01:36<01:50,  2.34s/it]
erating negative factsheets:  53%|█████▎    | 52/98 [01:39<01:56,  2.53s/it]
erating negative factsheets:  54%|█████▍    | 53/98 [01:41<01:42,  2.29s/it]
erating negative factsheets:  55%|█████▌    | 54/98 [01:44<01:47,  2.44s/it]
erating negative factsheets:  56%|█████▌    | 55/98 [01:44<01:23,  1.93s/it]
erating negative factsheets:  58%|█████▊    | 57/98 [01:45<00:50,  1.24s/it]
erating negative factsheets:  59%|█████▉    | 58/98 [01:45<00:38,  1.03it/s]
erating negative factsheets:  60%|██████    | 59/98 [01:46<00:30,  1.27it/s]
erating negative factsheets:  61%|██████    | 60/98 [01:48<00:42,  1.11s/it]
erating negative factsheets:  62%|██████▏   | 61/98 [01:49<00:47,  1.28s/it]
erating negative factsheets:  63%|██████▎   | 62/98 [01:56<01:41,  2.81s/it]
erating negative factsheets:  65%|██████▌   | 64/98 [01:58<01:07,  1.98s/it]
erating negative factsheets:  66%|██████▋   | 65/98 [01:59<00:56,  1.70s/it]
erating negative factsheets:  67%|██████▋   | 66/98 [02:00<00:50,  1.57s/it]
erating negative factsheets:  69%|██████▉   | 68/98 [02:01<00:32,  1.08s/it]
erating negative factsheets:  70%|███████   | 69/98 [02:03<00:37,  1.30s/it]
erating negative factsheets:  71%|███████▏  | 70/98 [02:03<00:31,  1.11s/it]
erating negative factsheets:  72%|███████▏  | 71/98 [02:11<01:19,  2.95s/it]
erating negative factsheets:  73%|███████▎  | 72/98 [02:12<01:02,  2.42s/it]
erating negative factsheets:  74%|███████▍  | 73/98 [02:13<00:44,  1.79s/it]
erating negative factsheets:  76%|███████▌  | 74/98 [02:13<00:32,  1.36s/it]
erating negative factsheets:  77%|███████▋  | 75/98 [02:19<01:03,  2.76s/it]
erating negative factsheets:  78%|███████▊  | 76/98 [02:23<01:05,  2.98s/it]
erating negative factsheets:  79%|███████▊  | 77/98 [02:25<00:58,  2.78s/it]
erating negative factsheets:  80%|███████▉  | 78/98 [02:26<00:44,  2.20s/it]
erating negative factsheets:  81%|████████  | 79/98 [02:27<00:36,  1.93s/it]
erating negative factsheets:  82%|████████▏ | 80/98 [02:28<00:29,  1.62s/it]
erating negative factsheets:  83%|████████▎ | 81/98 [02:30<00:30,  1.78s/it]
erating negative factsheets:  84%|████████▎ | 82/98 [02:33<00:33,  2.09s/it]
erating negative factsheets:  85%|████████▍ | 83/98 [02:35<00:29,  1.99s/it]
erating negative factsheets:  86%|████████▌ | 84/98 [02:35<00:21,  1.57s/it]
erating negative factsheets:  87%|████████▋ | 85/98 [02:36<00:19,  1.49s/it]
erating negative factsheets:  88%|████████▊ | 86/98 [02:37<00:14,  1.21s/it]
erating negative factsheets:  89%|████████▉ | 87/98 [02:38<00:11,  1.01s/it]
erating negative factsheets:  90%|████████▉ | 88/98 [02:39<00:10,  1.03s/it]
erating negative factsheets:  91%|█████████ | 89/98 [02:39<00:07,  1.26it/s]
erating negative factsheets:  92%|█████████▏| 90/98 [02:41<00:08,  1.08s/it]
erating negative factsheets:  93%|█████████▎| 91/98 [02:41<00:05,  1.23it/s]
erating negative factsheets:  94%|█████████▍| 92/98 [02:41<00:03,  1.54it/s]
erating negative factsheets:  95%|█████████▍| 93/98 [02:42<00:04,  1.18it/s]
erating negative factsheets:  96%|█████████▌| 94/98 [02:49<00:10,  2.58s/it]
erating negative factsheets:  97%|█████████▋| 95/98 [02:49<00:05,  1.92s/it]
erating negative factsheets:  98%|█████████▊| 96/98 [02:50<00:03,  1.63s/it]
erating negative factsheets:  99%|█████████▉| 97/98 [02:51<00:01,  1.33s/it]
generating negative factsheets: 100%|██████████| 98/98 [02:56<00:00,  1.80s/it]
100%|██████████| 1/1 [02:56<00:00, 176.93s/it]

In [680]:
for aspect in tqdm(['Products & Services']):
    queries=list(positives_df[positives_df.aspect==aspect].consolidated_query.unique())
    
    args=[([queries[i],25,aspect],{}) for i in range(len(queries))]

    factsheets=parallel_execute(
                        func= generate_factsheets,
                        argument_sets=args,
                        max_workers = 25,
                        show_progress= True,
                        desc = "generating negative factsheets"
                    )
    
    
    _query_negatives_dict=dict(zip(queries,factsheets))
    
    for query, factsheets in _query_negatives_dict.items():
        if query in query_negatives_dict:
            print('appending')
            query_negatives_dict[query]=query_negatives_dict[query]+factsheets
        else:
            
            query_negatives_dict[query]=factsheets

  0%|          | 0/1 [00:00<?, ?it/s]
erating negative factsheets:   0%|          | 0/98 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/98 [00:30<49:59, 30.93s/it]
erating negative factsheets:   2%|▏         | 2/98 [00:31<21:00, 13.13s/it]
erating negative factsheets:   3%|▎         | 3/98 [00:32<12:14,  7.73s/it]
erating negative factsheets:   4%|▍         | 4/98 [00:33<07:30,  4.79s/it]
erating negative factsheets:   6%|▌         | 6/98 [00:35<04:22,  2.85s/it]
erating negative factsheets:   7%|▋         | 7/98 [00:37<04:09,  2.74s/it]
erating negative factsheets:   8%|▊         | 8/98 [00:38<03:03,  2.04s/it]
erating negative factsheets:  10%|█         | 10/98 [00:38<01:54,  1.30s/it]
erating negative factsheets:  12%|█▏        | 12/98 [00:39<01:10,  1.22it/s]
erating negative factsheets:  13%|█▎        | 13/98 [00:39<01:05,  1.30it/s]
erating negative factsheets:  14%|█▍        | 14/98 [00:40<01:09,  1.22it/s]
erating negative factsheets:  15%|█▌        | 15/98 [00:40<00:55,  1.49it/s]
erating negative factsheets:  16%|█▋        | 16/98 [00:40<00:43,  1.89it/s]
erating negative factsheets:  17%|█▋        | 17/98 [00:42<01:00,  1.33it/s]
erating negative factsheets:  18%|█▊        | 18/98 [00:43<01:11,  1.12it/s]
erating negative factsheets:  19%|█▉        | 19/98 [00:45<01:34,  1.19s/it]
erating negative factsheets:  20%|██        | 20/98 [00:45<01:11,  1.10it/s]
erating negative factsheets:  21%|██▏       | 21/98 [00:46<00:57,  1.33it/s]
erating negative factsheets:  22%|██▏       | 22/98 [00:46<00:53,  1.42it/s]
erating negative factsheets:  23%|██▎       | 23/98 [00:46<00:42,  1.76it/s]
erating negative factsheets:  24%|██▍       | 24/98 [00:47<00:47,  1.57it/s]
erating negative factsheets:  26%|██▌       | 25/98 [00:47<00:35,  2.03it/s]
erating negative factsheets:  27%|██▋       | 26/98 [01:06<07:13,  6.02s/it]
erating negative factsheets:  28%|██▊       | 27/98 [01:09<05:47,  4.89s/it]
erating negative factsheets:  29%|██▊       | 28/98 [01:09<04:03,  3.48s/it]
erating negative factsheets:  30%|██▉       | 29/98 [01:12<03:58,  3.45s/it]
erating negative factsheets:  31%|███       | 30/98 [01:13<02:54,  2.56s/it]
erating negative factsheets:  32%|███▏      | 31/98 [01:15<02:38,  2.37s/it]
erating negative factsheets:  34%|███▎      | 33/98 [01:15<01:24,  1.30s/it]
erating negative factsheets:  35%|███▍      | 34/98 [01:15<01:04,  1.01s/it]
erating negative factsheets:  36%|███▌      | 35/98 [01:16<00:59,  1.06it/s]
erating negative factsheets:  37%|███▋      | 36/98 [01:16<00:50,  1.22it/s]
erating negative factsheets:  38%|███▊      | 37/98 [01:18<01:06,  1.08s/it]
erating negative factsheets:  39%|███▉      | 38/98 [01:18<00:53,  1.13it/s]
erating negative factsheets:  40%|███▉      | 39/98 [01:19<00:53,  1.10it/s]
erating negative factsheets:  41%|████      | 40/98 [01:21<01:15,  1.30s/it]
erating negative factsheets:  42%|████▏     | 41/98 [01:22<00:55,  1.02it/s]
erating negative factsheets:  43%|████▎     | 42/98 [01:22<00:43,  1.29it/s]
erating negative factsheets:  45%|████▍     | 44/98 [01:23<00:33,  1.62it/s]
erating negative factsheets:  46%|████▌     | 45/98 [01:23<00:29,  1.78it/s]
erating negative factsheets:  47%|████▋     | 46/98 [01:23<00:24,  2.15it/s]
erating negative factsheets:  48%|████▊     | 47/98 [01:27<01:02,  1.24s/it]
erating negative factsheets:  49%|████▉     | 48/98 [01:29<01:18,  1.56s/it]
erating negative factsheets:  50%|█████     | 49/98 [01:32<01:33,  1.92s/it]
erating negative factsheets:  51%|█████     | 50/98 [01:37<02:22,  2.96s/it]
erating negative factsheets:  52%|█████▏    | 51/98 [01:45<03:19,  4.25s/it]
erating negative factsheets:  53%|█████▎    | 52/98 [01:46<02:34,  3.35s/it]
erating negative factsheets:  54%|█████▍    | 53/98 [01:47<02:05,  2.78s/it]
erating negative factsheets:  55%|█████▌    | 54/98 [01:50<01:54,  2.60s/it]
erating negative factsheets:  56%|█████▌    | 55/98 [01:51<01:33,  2.17s/it]
erating negative factsheets:  57%|█████▋    | 56/98 [01:55<01:54,  2.73s/it]
erating negative factsheets:  58%|█████▊    | 57/98 [01:55<01:19,  1.95s/it]
erating negative factsheets:  59%|█████▉    | 58/98 [01:56<01:04,  1.61s/it]
erating negative factsheets:  60%|██████    | 59/98 [01:57<00:54,  1.40s/it]
erating negative factsheets:  62%|██████▏   | 61/98 [02:00<00:56,  1.53s/it]
erating negative factsheets:  64%|██████▍   | 63/98 [02:00<00:33,  1.03it/s]
erating negative factsheets:  65%|██████▌   | 64/98 [02:02<00:37,  1.12s/it]
erating negative factsheets:  67%|██████▋   | 66/98 [02:04<00:33,  1.04s/it]
erating negative factsheets:  68%|██████▊   | 67/98 [02:05<00:36,  1.16s/it]
erating negative factsheets:  69%|██████▉   | 68/98 [02:06<00:33,  1.12s/it]
erating negative factsheets:  70%|███████   | 69/98 [02:09<00:44,  1.53s/it]
erating negative factsheets:  71%|███████▏  | 70/98 [02:09<00:33,  1.19s/it]
erating negative factsheets:  72%|███████▏  | 71/98 [02:10<00:26,  1.03it/s]
erating negative factsheets:  74%|███████▍  | 73/98 [02:12<00:28,  1.16s/it]
erating negative factsheets:  76%|███████▌  | 74/98 [02:14<00:32,  1.34s/it]
erating negative factsheets:  77%|███████▋  | 75/98 [02:16<00:33,  1.44s/it]
erating negative factsheets:  78%|███████▊  | 76/98 [02:22<00:59,  2.69s/it]
erating negative factsheets:  79%|███████▊  | 77/98 [02:23<00:44,  2.13s/it]
erating negative factsheets:  80%|███████▉  | 78/98 [02:27<00:52,  2.62s/it]
erating negative factsheets:  81%|████████  | 79/98 [02:36<01:27,  4.60s/it]
erating negative factsheets:  82%|████████▏ | 80/98 [02:36<00:59,  3.32s/it]
erating negative factsheets:  83%|████████▎ | 81/98 [02:37<00:40,  2.41s/it]
erating negative factsheets:  84%|████████▎ | 82/98 [02:39<00:36,  2.29s/it]
erating negative factsheets:  85%|████████▍ | 83/98 [02:39<00:27,  1.83s/it]
erating negative factsheets:  86%|████████▌ | 84/98 [02:40<00:19,  1.41s/it]
erating negative factsheets:  88%|████████▊ | 86/98 [02:44<00:19,  1.66s/it]
erating negative factsheets:  89%|████████▉ | 87/98 [02:45<00:16,  1.53s/it]
erating negative factsheets:  90%|████████▉ | 88/98 [02:46<00:12,  1.29s/it]
erating negative factsheets:  91%|█████████ | 89/98 [02:47<00:11,  1.27s/it]
erating negative factsheets:  92%|█████████▏| 90/98 [02:47<00:08,  1.00s/it]
erating negative factsheets:  93%|█████████▎| 91/98 [02:51<00:12,  1.80s/it]
erating negative factsheets:  94%|█████████▍| 92/98 [02:51<00:08,  1.39s/it]
erating negative factsheets:  95%|█████████▍| 93/98 [02:54<00:09,  1.94s/it]
erating negative factsheets:  96%|█████████▌| 94/98 [02:56<00:07,  1.80s/it]
erating negative factsheets:  97%|█████████▋| 95/98 [02:58<00:05,  1.87s/it]
erating negative factsheets:  98%|█████████▊| 96/98 [03:03<00:05,  2.69s/it]
generating negative factsheets: 100%|██████████| 98/98 [03:04<00:00,  1.89s/it]
100%|██████████| 1/1 [03:05<00:00, 185.18s/it]

appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending
appending

In [1216]:
query_negatives_dict.keys()

dict_keys([('Technology Used', 'Augmented reality'), ('Technology Used', 'Blockchain'), ('Technology Used', 'AI'), ('Technology Used', 'Computer vision'), ('Technology Used', 'Natural language processing'), ('Technology Used', 'Chatbots'), ('Technology Used', 'Neural networks'), ('Technology Used', 'Biometrics'), ('Technology Used', 'Deep learning'), ('Technology Used', 'RPA (Robotic Process Automation)'), ('Technology Used', 'IoT'), ('Technology Used', 'Cybersecurity solutions'), ('Technology Used', 'Edge computing'), ('Technology Used', 'Voice recognition'), ('Technology Used', 'Smart contracts'), ('Technology Used', 'Quantum computing'), ('Technology Used', 'Facial recognition'), ('Technology Used', '5G technology'), ('Technology Used', 'Geolocation services'), ('Technology Used', 'Autonomous vehicles'), ('Technology Used', 'Machine learning'), ('Technology Used', 'Robotics'), ('Technology Used', 'Big data analytics'), ('Technology Used', 'Digital twins'), ('Technology Used', 'Cryptography'), ('Technology Used', 'Microservices architecture'), ('Technology Used', 'Wearable technology'), ('Technology Used', '3D printing'), ('Technology Used', 'Virtual reality'), ('Technology Used', 'Cloud computing'), ('Revenue Model', 'Pay-per-use'), ('Revenue Model', 'Subscription-based'), ('Revenue Model', 'Marketplace'), ('Revenue Model', 'Commission'), ('Revenue Model', 'Licensing'), ('Revenue Model', 'Crowdsourcing'), ('Revenue Model', 'Freemium'), ('Revenue Model', 'Consulting fees'), ('Revenue Model', 'PaaS'), ('Revenue Model', 'SaaS'), ('Revenue Model', 'Royalties'), ('Revenue Model', 'Advertising'), ('Revenue Model', 'Retail'), ('Revenue Model', 'Affiliate'), ('Revenue Model', 'Direct sales'), ('Revenue Model', 'Membership'), ('Revenue Model', 'B2C'), ('Revenue Model', 'B2B'), ('Revenue Model', 'Microtransactions'), ('Revenue Model', 'Sponsorship'), ('Revenue Model', 'Leasing'), ('Revenue Model', 'In-app purchases'), ('Revenue Model', 'Donation'), ('Business Model', 'Franchise'), ('Business Model', 'B2B'), ('Business Model', 'Freemium'), ('Business Model', 'Marketplace'), ('Business Model', 'B2C'), ('Business Model', 'On-demand'), ('Business Model', 'Subscription-based'), ('Business Model', 'Licensing'), ('Business Model', 'Direct sales'), ('Customer Segment', 'Financial institutions'), ('Customer Segment', 'Pet care services'), ('Customer Segment', 'Beauty salons'), ('Customer Segment', 'Sports teams'), ('Customer Segment', 'Doctors'), ('Customer Segment', 'Pharmaceutical companies'), ('Customer Segment', 'Small businesses'), ('Customer Segment', 'Fitness centers'), ('Customer Segment', 'Logistics companies'), ('Customer Segment', 'Fashion brands'), ('Customer Segment', 'Automotive industry'), ('Customer Segment', 'Hospitality industry'), ('Customer Segment', 'Manufacturing companies'), ('Customer Segment', 'Travel agencies'), ('Customer Segment', 'Retailers'), ('Customer Segment', 'Lawyers'), ('Customer Segment', 'Healthcare providers'), ('Customer Segment', 'E-commerce businesses'), ('Customer Segment', 'Event planners'), ('Customer Segment', 'Energy companies'), ('Customer Segment', 'Restaurants'), ('Customer Segment', 'Media companies'), ('Customer Segment', 'Educational institutions'), ('Customer Segment', 'Telecommunications providers'), ('Customer Segment', 'Non-profit organizations'), ('Customer Segment', 'Construction firms'), ('Customer Segment', 'Real estate developers'), ('Customer Segment', 'Enterprise customers'), ('Customer Segment', 'Agricultural businesses'), ('Customer Segment', 'Insurance companies'), ('Customer Segment', 'Banks'), ('Customer Segment', 'Private equity firms'), ('Customer Segment', 'Credit unions'), ('Customer Segment', 'Public relations firms'), ('Customer Segment', 'Human resources departments'), ('Customer Segment', 'Accounting firms'), ('Customer Segment', 'Universities'), ('Customer Segment', 'Hospitals'), ('Customer Segment', 'Advertising agencies'), ('Customer Segment', 'Colleges'), ('Customer Segment', 'Daycare centers'), ('Customer Segment', 'Marketing agencies'), ('Customer Segment', 'Elementary schools'), ('Customer Segment', 'Senior living facilities'), ('Customer Segment', 'Legal departments'), ('Customer Segment', 'Clinics'), ('Customer Segment', 'Dental practices'), ('Customer Segment', 'Preschools'), ('Customer Segment', 'Veterinary clinics'), ('Customer Segment', 'Pharmacies'), ('Customer Segment', 'Supermarkets'), ('Customer Segment', 'Online retailers'), ('Customer Segment', 'Convenience stores'), ('Customer Segment', 'Import/export businesses'), ('Customer Segment', 'Car dealerships'), ('Customer Segment', 'Motorcycle dealerships'), ('Customer Segment', 'Home improvement stores'), ('Customer Segment', 'Bicycle shops'), ('Customer Segment', 'Art galleries'), ('Customer Segment', 'Music stores'), ('Customer Segment', 'Toy stores'), ('Customer Segment', 'Airlines'), ('Customer Segment', 'Museums'), ('Customer Segment', 'Bookstores'), ('Customer Segment', 'Hotels'), ('Customer Segment', 'Cinemas'), ('Customer Segment', 'Resorts'), ('Customer Segment', 'Theaters'), ('Customer Segment', 'Shipping companies'), ('Customer Segment', 'Bus companies'), ('Customer Segment', 'Hostels'), ('Customer Segment', 'Concert venues'), ('Customer Segment', 'Sports arenas'), ('Customer Segment', 'Ride-sharing services'), ('Customer Segment', 'Stadiums'), ('Customer Segment', 'Gyms'), ('Customer Segment', 'Taxi services'), ('Customer Segment', 'Car rental services'), ('Customer Segment', 'Software companies'), ('Customer Segment', 'Biotech companies'), ('Customer Segment', 'Medical device companies'), ('Customer Segment', 'Chemical companies'), ('Customer Segment', 'K-12'), ('Customer Segment', 'Startups'), ('Customer Industry', 'Automotive'), ('Customer Industry', 'Retail'), ('Customer Industry', 'Banking'), ('Customer Industry', 'Food and Beverage'), ('Customer Industry', 'Finance'), ('Customer Industry', 'Entertainment'), ('Customer Industry', 'Fashion'), ('Customer Industry', 'Logistics'), ('Customer Industry', 'Agriculture'), ('Customer Industry', 'Transportation'), ('Customer Industry', 'Utilities'), ('Customer Industry', 'Insurance'), ('Customer Industry', 'Aerospace'), ('Customer Industry', 'Manufacturing'), ('Customer Industry', 'Real Estate'), ('Customer Industry', 'Renewable Energy'), ('Customer Industry', 'Technology'), ('Customer Industry', 'Defense'), ('Customer Industry', 'Energy'), ('Customer Industry', 'Hospitality'), ('Customer Industry', 'Education'), ('Customer Industry', 'Healthcare'), ('Customer Industry', 'Construction'), ('Customer Industry', 'Consumer Electronics'), ('Customer Industry', 'Pharmaceutical'), ('Customer Industry', 'Beauty'), ('Customer Industry', 'Biotechnology'), ('Customer Industry', 'Legal'), ('Customer Industry', 'Media'), ('Customer Industry', 'Public Sector'), ('Customer Industry', 'Non-Profit'), ('Customer Industry', 'Sports'), ('Customer Industry', 'Gaming'), ('Customer Industry', 'Furniture'), ('Customer Industry', 'Marine'), ('Customer Industry', 'Forestry'), ('Customer Industry', 'Information Technology'), ('Customer Industry', 'Jewelry'), ('Customer Industry', 'Consulting'), ('Customer Industry', 'Event Management'), ('Customer Industry', 'Broadcasting'), ('Customer Industry', 'Travel'), ('Customer Industry', 'Human Resources'), ('Customer Industry', 'Music Industry'), ('Customer Industry', 'E-commerce'), ('Customer Industry', 'Tourism'), ('Customer Industry', 'Hardware Manufacturing'), ('Customer Industry', 'Petroleum'), ('Customer Industry', 'Publishing'), ('Customer Industry', 'Glass'), ('Customer Industry', 'Software Development'), ('Customer Industry', 'Advertising'), ('Customer Industry', 'Film Production'), ('Customer Industry', 'Virtual Reality'), ('Customer Industry', 'Augmented Reality'), ('Customer Industry', 'Artificial Intelligence'), ('Customer Industry', 'Data Analytics'), ('Customer Industry', 'Internet of Things'), ('Customer Industry', 'Quantum Computing'), ('Customer Industry', 'Fintech'), ('Customer Industry', 'Agritech'), ('Customer Industry', 'Cleantech'), ('Customer Industry', 'Edtech'), ('Customer Industry', 'Healthtech'), ('Customer Industry', 'Foodtech'), ('Customer Industry', 'Medtech'), ('Customer Industry', 'Insurtech'), ('Customer Industry', 'Govtech'), ('Customer Industry', 'Legaltech'), ('Customer Industry', 'Martech'), ('Customer Industry', 'Adtech'), ('Customer Industry', 'Retailtech'), ('Customer Industry', 'Supply Chain Management'), ('Customer Industry', 'Customer Relationship Management'), ('Customer Industry', 'Cybersecurity'), ('Industry', 'Entertainment'), ('Industry', 'Real Estate'), ('Industry', 'Biotechnology'), ('Industry', 'Insurance'), ('Industry', 'Legal'), ('Industry', 'Defense'), ('Industry', 'Telecommunications'), ('Industry', 'Utilities'), ('Industry', 'Pharmaceutical'), ('Industry', 'Hospitality'), ('Industry', 'Automotive'), ('Industry', 'Energy'), ('Industry', 'Banking'), ('Industry', 'Fashion'), ('Industry', 'Chemicals'), ('Industry', 'Food and Beverage'), ('Industry', 'Renewable Energy'), ('Industry', 'Mining'), ('Industry', 'Logistics'), ('Industry', 'Beauty'), ('Industry', 'Agriculture'), ('Industry', 'Media'), ('Industry', 'Construction'), ('Industry', 'Education'), ('Industry', 'Finance'), ('Industry', 'Manufacturing'), ('Industry', 'Aerospace'), ('Industry', 'Healthcare'), ('Industry', 'Transportation'), ('Industry', 'Retail'), ('Industry', 'Public Sector'), ('Industry', 'Non-Profit'), ('Industry', 'Sports'), ('Industry', 'Gaming'), ('Industry', 'Paper and Pulp'), ('Industry', 'Furniture'), ('Industry', 'Marine'), ('Industry', 'Printing'), ('Industry', 'Advertising'), ('Industry', 'Textiles'), ('Industry', 'Ceramics'), ('Industry', 'Petroleum'), ('Industry', 'Metals'), ('Industry', 'Forestry'), ('Industry', 'Plastics'), ('Industry', 'Tobacco'), ('Industry', 'Glass'), ('Industry', 'Jewelry'), ('Industry', 'Consulting'), ('Industry', 'Travel'), ('Industry', 'Tourism'), ('Industry', 'Event Management'), ('Industry', 'E-commerce'), ('Industry', 'Cybersecurity'), ('Industry', 'Human Resources'), ('Industry', 'Information Technology'), ('Industry', 'Hardware Manufacturing'), ('Industry', 'Software Development'), ('Industry', 'Broadcasting'), ('Industry', 'Music Industry'), ('Industry', 'Film Production'), ('Industry', 'Animation'), ('Industry', 'Virtual Reality'), ('Industry', 'Augmented Reality'), ('Industry', 'Smart Home Technology'), ('Industry', 'Artificial Intelligence'), ('Industry', 'Machine Learning'), ('Industry', 'Internet of Things'), ('Industry', 'Robotics'), ('Industry', 'Proptech'), ('Industry', 'Agritech'), ('Industry', 'Satellite Technology'), ('Industry', '3D Printing'), ('Industry', 'Data Analytics'), ('Industry', 'Blockchain'), ('Industry', 'Healthtech'), ('Industry', 'Edtech'), ('Industry', 'Fintech'), ('Industry', 'Space Exploration'), ('Industry', 'Quantum Computing'), ('Industry', 'Cleantech'), ('Industry', 'Foodtech'), ('Industry', 'Medtech'), ('Industry', 'Insurtech'), ('Industry', 'Govtech'), ('Industry', 'Adtech'), ('Industry', 'Retailtech'), ('Industry', 'Supply Chain Management'), ('Industry', 'Customer Relationship Management'), ('Industry', 'Venture Capital'), ('Products & Services', 'Mobile payment solutions'), ('Products & Services', 'Telehealth services'), ('Products & Services', 'Accounting software'), ('Products & Services', 'Supply chain management solutions'), ('Products & Services', 'E-commerce platforms'), ('Products & Services', 'Podcast hosting services'), ('Products & Services', 'HR management platforms'), ('Products & Services', 'Video conferencing software'), ('Products & Services', 'Online learning platforms'), ('Products & Services', 'Fitness tracking apps'), ('Products & Services', 'Customer support chatbots'), ('Products & Services', 'Cloud storage services'), ('Products & Services', 'Project management software'), ('Products & Services', 'Electric vehicle charging stations'), ('Products & Services', 'Augmented reality applications'), ('Products & Services', 'Subscription box services'), ('Products & Services', '3D printing services'), ('Products & Services', 'CRM software'), ('Products & Services', 'Online grocery delivery'), ('Products & Services', 'Home automation devices'), ('Products & Services', 'Online dating apps'), ('Products & Services', 'Freelance marketplace'), ('Products & Services', 'Renewable energy solutions'), ('Products & Services', 'Social media management tools'), ('Products & Services', 'Virtual reality experiences'), ('Products & Services', 'Online travel booking'), ('Products & Services', 'Data analytics tools'), ('Products & Services', 'Music streaming platforms'), ('Products & Services', 'Cybersecurity services'), ('Products & Services', 'Digital marketing tools'), ('Products & Services', 'Food delivery services'), ('Products & Services', 'Content management systems'), ('Products & Services', 'Personal finance management tools'), ('Products & Services', 'Blockchain development services'), ('Products & Services', 'Remote work solutions'), ('Products & Services', 'Business intelligence software'), ('Products & Services', 'Online gaming platforms'), ('Products & Services', 'Digital asset management'), ('Products & Services', 'Email marketing services'), ('Products & Services', 'Inventory management systems'), ('Products & Services', 'Affiliate marketing networks'), ('Products & Services', 'Web hosting services'), ('Products & Services', 'Payment gateway services'), ('Products & Services', 'Smart home security systems'), ('Products & Services', 'Employee wellness programs'), ('Products & Services', 'Cybersecurity training'), ('Products & Services', 'Online course creation platforms'), ('Products & Services', 'Crowdfunding platforms'), ('Products & Services', 'Property management software'), ('Products & Services', 'SEO optimization tools'), ('Products & Services', 'Virtual event platforms'), ('Products & Services', 'Legal document automation'), ('Products & Services', 'Fleet management solutions'), ('Products & Services', 'Point of sale systems'), ('Products & Services', 'Data privacy solutions'), ('Products & Services', 'Drone delivery services'), ('Products & Services', 'Digital signature services'), ('Products & Services', 'Online auction platforms'), ('Products & Services', 'Online fundraising platforms'), ('Products & Services', 'Online therapy services'), ('Products & Services', 'On-demand staffing platforms'), ('Products & Services', 'Virtual assistant services'), ('Products & Services', 'Event management platforms'), ('Products & Services', 'Online survey tools'), ('Products & Services', 'Peer-to-peer lending services'), ('Products & Services', 'Online job boards'), ('Products & Services', 'Digital health records'), ('Products & Services', 'Remote patient monitoring'), ('Products & Services', 'Telecom expense management'), ('Products & Services', 'Mobile app development'), ('Products & Services', 'E-book publishing platforms'), ('Products & Services', 'Online stock trading'), ('Products & Services', 'Digital currency exchange'), ('Products & Services', 'Online language learning'), ('Products & Services', 'Cloud-based call centers'), ('Products & Services', 'Video editing software'), ('Products & Services', 'AI-powered writing tools'), ('Products & Services', 'Smart contract development'), ('Products & Services', 'Online reputation management'), ('Products & Services', 'Workforce management software'), ('Products & Services', 'B2B marketplace'), ('Products & Services', 'Online ticketing systems'), ('Products & Services', 'Online tutoring services'), ('Products & Services', 'Augmented reality shopping'), ('Products & Services', 'Virtual coworking spaces'), ('Products & Services', 'Online portfolio management'), ('Products & Services', 'Live streaming platforms'), ('Products & Services', 'Online car rental services'), ('Products & Services', 'Online fitness classes'), ('Products & Services', 'Digital signage solutions'), ('Products & Services', 'Online notarization services'), ('Products & Services', 'Online pet care services'), ('Products & Services', 'Voice recognition software'), ('Products & Services', 'Virtual fitting rooms'), ('Products & Services', 'Robotic process automation'), ('Products & Services', 'Digital transformation consulting'), ('Products & Services', 'Eco-friendly packaging solutions'), ('Products & Services', 'Online interior design services')])

In [1228]:
positives_df[positives_df['query']=='Advertising'].aspect.unique()

array(['Industry', 'Revenue Model', 'Customer Industry'], dtype=object)

In [1231]:
len(query_negatives_dict[('Customer Industry', 'Advertising')][1])

48

In [1007]:
query_negatives_dict.keys()

dict_keys([('Technology Used', 'Augmented reality'), ('Technology Used', 'Blockchain'), ('Technology Used', 'AI'), ('Technology Used', 'Computer vision'), ('Technology Used', 'Natural language processing'), ('Technology Used', 'Chatbots'), ('Technology Used', 'Neural networks'), ('Technology Used', 'Biometrics'), ('Technology Used', 'Deep learning'), ('Technology Used', 'RPA (Robotic Process Automation)'), ('Technology Used', 'IoT'), ('Technology Used', 'Cybersecurity solutions'), ('Technology Used', 'Edge computing'), ('Technology Used', 'Voice recognition'), ('Technology Used', 'Smart contracts'), ('Technology Used', 'Quantum computing'), ('Technology Used', 'Facial recognition'), ('Technology Used', '5G technology'), ('Technology Used', 'Geolocation services'), ('Technology Used', 'Autonomous vehicles'), ('Technology Used', 'Machine learning'), ('Technology Used', 'Robotics'), ('Technology Used', 'Big data analytics'), ('Technology Used', 'Digital twins'), ('Technology Used', 'Cryptography'), ('Technology Used', 'Microservices architecture'), ('Technology Used', 'Wearable technology'), ('Technology Used', '3D printing'), ('Technology Used', 'Virtual reality'), ('Technology Used', 'Cloud computing'), ('Revenue Model', 'Pay-per-use'), ('Revenue Model', 'Subscription-based'), ('Revenue Model', 'Marketplace'), ('Revenue Model', 'Commission'), ('Revenue Model', 'Licensing'), ('Revenue Model', 'Crowdsourcing'), ('Revenue Model', 'Freemium'), ('Revenue Model', 'Consulting fees'), ('Revenue Model', 'PaaS'), ('Revenue Model', 'SaaS'), ('Revenue Model', 'Royalties'), ('Revenue Model', 'Advertising'), ('Revenue Model', 'Retail'), ('Revenue Model', 'Affiliate'), ('Revenue Model', 'Direct sales'), ('Revenue Model', 'Membership'), ('Revenue Model', 'B2C'), ('Revenue Model', 'B2B'), ('Revenue Model', 'Microtransactions'), ('Revenue Model', 'Sponsorship'), ('Revenue Model', 'Leasing'), ('Revenue Model', 'In-app purchases'), ('Revenue Model', 'Donation'), ('Business Model', 'Franchise'), ('Business Model', 'B2B'), ('Business Model', 'Freemium'), ('Business Model', 'Marketplace'), ('Business Model', 'B2C'), ('Business Model', 'On-demand'), ('Business Model', 'Subscription-based'), ('Business Model', 'Licensing'), ('Business Model', 'Direct sales'), ('Customer Segment', 'Financial institutions'), ('Customer Segment', 'Pet care services'), ('Customer Segment', 'Beauty salons'), ('Customer Segment', 'Sports teams'), ('Customer Segment', 'Doctors'), ('Customer Segment', 'Pharmaceutical companies'), ('Customer Segment', 'Small businesses'), ('Customer Segment', 'Fitness centers'), ('Customer Segment', 'Logistics companies'), ('Customer Segment', 'Fashion brands'), ('Customer Segment', 'Automotive industry'), ('Customer Segment', 'Hospitality industry'), ('Customer Segment', 'Manufacturing companies'), ('Customer Segment', 'Travel agencies'), ('Customer Segment', 'Retailers'), ('Customer Segment', 'Lawyers'), ('Customer Segment', 'Healthcare providers'), ('Customer Segment', 'E-commerce businesses'), ('Customer Segment', 'Event planners'), ('Customer Segment', 'Energy companies'), ('Customer Segment', 'Restaurants'), ('Customer Segment', 'Media companies'), ('Customer Segment', 'Educational institutions'), ('Customer Segment', 'Telecommunications providers'), ('Customer Segment', 'Non-profit organizations'), ('Customer Segment', 'Construction firms'), ('Customer Segment', 'Real estate developers'), ('Customer Segment', 'Enterprise customers'), ('Customer Segment', 'Agricultural businesses'), ('Customer Segment', 'Insurance companies'), ('Customer Segment', 'Banks'), ('Customer Segment', 'Private equity firms'), ('Customer Segment', 'Credit unions'), ('Customer Segment', 'Public relations firms'), ('Customer Segment', 'Human resources departments'), ('Customer Segment', 'Accounting firms'), ('Customer Segment', 'Universities'), ('Customer Segment', 'Hospitals'), ('Customer Segment', 'Advertising agencies'), ('Customer Segment', 'Colleges'), ('Customer Segment', 'Daycare centers'), ('Customer Segment', 'Marketing agencies'), ('Customer Segment', 'Elementary schools'), ('Customer Segment', 'Senior living facilities'), ('Customer Segment', 'Legal departments'), ('Customer Segment', 'Clinics'), ('Customer Segment', 'Dental practices'), ('Customer Segment', 'Preschools'), ('Customer Segment', 'Veterinary clinics'), ('Customer Segment', 'Pharmacies'), ('Customer Segment', 'Supermarkets'), ('Customer Segment', 'Online retailers'), ('Customer Segment', 'Convenience stores'), ('Customer Segment', 'Import/export businesses'), ('Customer Segment', 'Car dealerships'), ('Customer Segment', 'Motorcycle dealerships'), ('Customer Segment', 'Home improvement stores'), ('Customer Segment', 'Bicycle shops'), ('Customer Segment', 'Art galleries'), ('Customer Segment', 'Music stores'), ('Customer Segment', 'Toy stores'), ('Customer Segment', 'Airlines'), ('Customer Segment', 'Museums'), ('Customer Segment', 'Bookstores'), ('Customer Segment', 'Hotels'), ('Customer Segment', 'Cinemas'), ('Customer Segment', 'Resorts'), ('Customer Segment', 'Theaters'), ('Customer Segment', 'Shipping companies'), ('Customer Segment', 'Bus companies'), ('Customer Segment', 'Hostels'), ('Customer Segment', 'Concert venues'), ('Customer Segment', 'Sports arenas'), ('Customer Segment', 'Ride-sharing services'), ('Customer Segment', 'Stadiums'), ('Customer Segment', 'Gyms'), ('Customer Segment', 'Taxi services'), ('Customer Segment', 'Car rental services'), ('Customer Segment', 'Software companies'), ('Customer Segment', 'Biotech companies'), ('Customer Segment', 'Medical device companies'), ('Customer Segment', 'Chemical companies'), ('Customer Segment', 'K-12'), ('Customer Segment', 'Startups'), ('Customer Industry', 'Automotive'), ('Customer Industry', 'Retail'), ('Customer Industry', 'Banking'), ('Customer Industry', 'Food and Beverage'), ('Customer Industry', 'Finance'), ('Customer Industry', 'Entertainment'), ('Customer Industry', 'Fashion'), ('Customer Industry', 'Logistics'), ('Customer Industry', 'Agriculture'), ('Customer Industry', 'Transportation'), ('Customer Industry', 'Utilities'), ('Customer Industry', 'Insurance'), ('Customer Industry', 'Aerospace'), ('Customer Industry', 'Manufacturing'), ('Customer Industry', 'Real Estate'), ('Customer Industry', 'Renewable Energy'), ('Customer Industry', 'Technology'), ('Customer Industry', 'Defense'), ('Customer Industry', 'Energy'), ('Customer Industry', 'Hospitality'), ('Customer Industry', 'Education'), ('Customer Industry', 'Healthcare'), ('Customer Industry', 'Construction'), ('Customer Industry', 'Consumer Electronics'), ('Customer Industry', 'Pharmaceutical'), ('Customer Industry', 'Beauty'), ('Customer Industry', 'Biotechnology'), ('Customer Industry', 'Legal'), ('Customer Industry', 'Media'), ('Customer Industry', 'Public Sector'), ('Customer Industry', 'Non-Profit'), ('Customer Industry', 'Sports'), ('Customer Industry', 'Gaming'), ('Customer Industry', 'Furniture'), ('Customer Industry', 'Marine'), ('Customer Industry', 'Forestry'), ('Customer Industry', 'Information Technology'), ('Customer Industry', 'Jewelry'), ('Customer Industry', 'Consulting'), ('Customer Industry', 'Event Management'), ('Customer Industry', 'Broadcasting'), ('Customer Industry', 'Travel'), ('Customer Industry', 'Human Resources'), ('Customer Industry', 'Music Industry'), ('Customer Industry', 'E-commerce'), ('Customer Industry', 'Tourism'), ('Customer Industry', 'Hardware Manufacturing'), ('Customer Industry', 'Petroleum'), ('Customer Industry', 'Publishing'), ('Customer Industry', 'Glass'), ('Customer Industry', 'Software Development'), ('Customer Industry', 'Advertising'), ('Customer Industry', 'Film Production'), ('Customer Industry', 'Virtual Reality'), ('Customer Industry', 'Augmented Reality'), ('Customer Industry', 'Artificial Intelligence'), ('Customer Industry', 'Data Analytics'), ('Customer Industry', 'Internet of Things'), ('Customer Industry', 'Quantum Computing'), ('Customer Industry', 'Fintech'), ('Customer Industry', 'Agritech'), ('Customer Industry', 'Cleantech'), ('Customer Industry', 'Edtech'), ('Customer Industry', 'Healthtech'), ('Customer Industry', 'Foodtech'), ('Customer Industry', 'Medtech'), ('Customer Industry', 'Insurtech'), ('Customer Industry', 'Govtech'), ('Customer Industry', 'Legaltech'), ('Customer Industry', 'Martech'), ('Customer Industry', 'Adtech'), ('Customer Industry', 'Retailtech'), ('Customer Industry', 'Supply Chain Management'), ('Customer Industry', 'Customer Relationship Management'), ('Customer Industry', 'Cybersecurity'), ('Industry', 'Entertainment'), ('Industry', 'Real Estate'), ('Industry', 'Biotechnology'), ('Industry', 'Insurance'), ('Industry', 'Legal'), ('Industry', 'Defense'), ('Industry', 'Telecommunications'), ('Industry', 'Utilities'), ('Industry', 'Pharmaceutical'), ('Industry', 'Hospitality'), ('Industry', 'Automotive'), ('Industry', 'Energy'), ('Industry', 'Banking'), ('Industry', 'Fashion'), ('Industry', 'Chemicals'), ('Industry', 'Food and Beverage'), ('Industry', 'Renewable Energy'), ('Industry', 'Mining'), ('Industry', 'Logistics'), ('Industry', 'Beauty'), ('Industry', 'Agriculture'), ('Industry', 'Media'), ('Industry', 'Construction'), ('Industry', 'Education'), ('Industry', 'Finance'), ('Industry', 'Manufacturing'), ('Industry', 'Aerospace'), ('Industry', 'Healthcare'), ('Industry', 'Transportation'), ('Industry', 'Retail'), ('Industry', 'Public Sector'), ('Industry', 'Non-Profit'), ('Industry', 'Sports'), ('Industry', 'Gaming'), ('Industry', 'Paper and Pulp'), ('Industry', 'Furniture'), ('Industry', 'Marine'), ('Industry', 'Printing'), ('Industry', 'Advertising'), ('Industry', 'Textiles'), ('Industry', 'Ceramics'), ('Industry', 'Petroleum'), ('Industry', 'Metals'), ('Industry', 'Forestry'), ('Industry', 'Plastics'), ('Industry', 'Tobacco'), ('Industry', 'Glass'), ('Industry', 'Jewelry'), ('Industry', 'Consulting'), ('Industry', 'Travel'), ('Industry', 'Tourism'), ('Industry', 'Event Management'), ('Industry', 'E-commerce'), ('Industry', 'Cybersecurity'), ('Industry', 'Human Resources'), ('Industry', 'Information Technology'), ('Industry', 'Hardware Manufacturing'), ('Industry', 'Software Development'), ('Industry', 'Broadcasting'), ('Industry', 'Music Industry'), ('Industry', 'Film Production'), ('Industry', 'Animation'), ('Industry', 'Virtual Reality'), ('Industry', 'Augmented Reality'), ('Industry', 'Smart Home Technology'), ('Industry', 'Artificial Intelligence'), ('Industry', 'Machine Learning'), ('Industry', 'Internet of Things'), ('Industry', 'Robotics'), ('Industry', 'Proptech'), ('Industry', 'Agritech'), ('Industry', 'Satellite Technology'), ('Industry', '3D Printing'), ('Industry', 'Data Analytics'), ('Industry', 'Blockchain'), ('Industry', 'Healthtech'), ('Industry', 'Edtech'), ('Industry', 'Fintech'), ('Industry', 'Space Exploration'), ('Industry', 'Quantum Computing'), ('Industry', 'Cleantech'), ('Industry', 'Foodtech'), ('Industry', 'Medtech'), ('Industry', 'Insurtech'), ('Industry', 'Govtech'), ('Industry', 'Adtech'), ('Industry', 'Retailtech'), ('Industry', 'Supply Chain Management'), ('Industry', 'Customer Relationship Management'), ('Industry', 'Venture Capital'), ('Products & Services', 'Mobile payment solutions'), ('Products & Services', 'Telehealth services'), ('Products & Services', 'Accounting software'), ('Products & Services', 'Supply chain management solutions'), ('Products & Services', 'E-commerce platforms'), ('Products & Services', 'Podcast hosting services'), ('Products & Services', 'HR management platforms'), ('Products & Services', 'Video conferencing software'), ('Products & Services', 'Online learning platforms'), ('Products & Services', 'Fitness tracking apps'), ('Products & Services', 'Customer support chatbots'), ('Products & Services', 'Cloud storage services'), ('Products & Services', 'Project management software'), ('Products & Services', 'Electric vehicle charging stations'), ('Products & Services', 'Augmented reality applications'), ('Products & Services', 'Subscription box services'), ('Products & Services', '3D printing services'), ('Products & Services', 'CRM software'), ('Products & Services', 'Online grocery delivery'), ('Products & Services', 'Home automation devices'), ('Products & Services', 'Online dating apps'), ('Products & Services', 'Freelance marketplace'), ('Products & Services', 'Renewable energy solutions'), ('Products & Services', 'Social media management tools'), ('Products & Services', 'Virtual reality experiences'), ('Products & Services', 'Online travel booking'), ('Products & Services', 'Data analytics tools'), ('Products & Services', 'Music streaming platforms'), ('Products & Services', 'Cybersecurity services'), ('Products & Services', 'Digital marketing tools'), ('Products & Services', 'Food delivery services'), ('Products & Services', 'Content management systems'), ('Products & Services', 'Personal finance management tools'), ('Products & Services', 'Blockchain development services'), ('Products & Services', 'Remote work solutions'), ('Products & Services', 'Business intelligence software'), ('Products & Services', 'Online gaming platforms'), ('Products & Services', 'Digital asset management'), ('Products & Services', 'Email marketing services'), ('Products & Services', 'Inventory management systems'), ('Products & Services', 'Affiliate marketing networks'), ('Products & Services', 'Web hosting services'), ('Products & Services', 'Payment gateway services'), ('Products & Services', 'Smart home security systems'), ('Products & Services', 'Employee wellness programs'), ('Products & Services', 'Cybersecurity training'), ('Products & Services', 'Online course creation platforms'), ('Products & Services', 'Crowdfunding platforms'), ('Products & Services', 'Property management software'), ('Products & Services', 'SEO optimization tools'), ('Products & Services', 'Virtual event platforms'), ('Products & Services', 'Legal document automation'), ('Products & Services', 'Fleet management solutions'), ('Products & Services', 'Point of sale systems'), ('Products & Services', 'Data privacy solutions'), ('Products & Services', 'Drone delivery services'), ('Products & Services', 'Digital signature services'), ('Products & Services', 'Online auction platforms'), ('Products & Services', 'Online fundraising platforms'), ('Products & Services', 'Online therapy services'), ('Products & Services', 'On-demand staffing platforms'), ('Products & Services', 'Virtual assistant services'), ('Products & Services', 'Event management platforms'), ('Products & Services', 'Online survey tools'), ('Products & Services', 'Peer-to-peer lending services'), ('Products & Services', 'Online job boards'), ('Products & Services', 'Digital health records'), ('Products & Services', 'Remote patient monitoring'), ('Products & Services', 'Telecom expense management'), ('Products & Services', 'Mobile app development'), ('Products & Services', 'E-book publishing platforms'), ('Products & Services', 'Online stock trading'), ('Products & Services', 'Digital currency exchange'), ('Products & Services', 'Online language learning'), ('Products & Services', 'Cloud-based call centers'), ('Products & Services', 'Video editing software'), ('Products & Services', 'AI-powered writing tools'), ('Products & Services', 'Smart contract development'), ('Products & Services', 'Online reputation management'), ('Products & Services', 'Workforce management software'), ('Products & Services', 'B2B marketplace'), ('Products & Services', 'Online ticketing systems'), ('Products & Services', 'Online tutoring services'), ('Products & Services', 'Augmented reality shopping'), ('Products & Services', 'Virtual coworking spaces'), ('Products & Services', 'Online portfolio management'), ('Products & Services', 'Live streaming platforms'), ('Products & Services', 'Online car rental services'), ('Products & Services', 'Online fitness classes'), ('Products & Services', 'Digital signage solutions'), ('Products & Services', 'Online notarization services'), ('Products & Services', 'Online pet care services'), ('Products & Services', 'Voice recognition software'), ('Products & Services', 'Virtual fitting rooms'), ('Products & Services', 'Robotic process automation'), ('Products & Services', 'Digital transformation consulting'), ('Products & Services', 'Eco-friendly packaging solutions'), ('Products & Services', 'Online interior design services')])

In [681]:
with open('../synthetic_data/synthetic_negatives.pkl','wb') as f:
    pickle.dump(query_negatives_dict,f)

In [1382]:
set([key[0] for key in query_negatives_dict.keys()])

{'Business Model',
 'Customer Industry',
 'Customer Segment',
 'Industry',
 'Products & Services',
 'Revenue Model',
 'Technology Used'}

In [1383]:
# _query_negatives_dict.keys()

In [1384]:
rows=[]
for aspect_query, synthetic_negatives in query_negatives_dict.items():
    rows.extend([{'aspect':aspect_query[0],'query':aspect_query[1],'factsheet':factsheet} for factsheet in synthetic_negatives[1]])

In [1385]:
synthetic_negatives_df=pd.DataFrame(rows)

In [1386]:
customer_negatives['strategy']='rule'

In [1387]:
synthetic_negatives_df['strategy']='synthetic'

In [1388]:
synthetic_negatives_df

,aspect,query,factsheet,strategy
0,Technology Used,Augmented reality,**Company Name:** DataViz Analytics \n**Websi...,synthetic
1,Technology Used,Augmented reality,**Company Name:** AIToolbox \n**Website:** ai...,synthetic
2,Technology Used,Augmented reality,**Company Name:** CloudSync Solutions \n**Web...,synthetic
3,Technology Used,Augmented reality,**Company Name:** EcoTech Innovations \n**Web...,synthetic
4,Technology Used,Augmented reality,**Company Name:** FinTech Dynamics \n**Websit...,synthetic
...,...,...,...,...
18390,Products & Services,Online interior design services,**Company Name:** TechGadgets **Website:** te...,synthetic
18391,Products & Services,Online interior design services,**Company Name:** StyleSavvy **Website:** sty...,synthetic
18392,Products & Services,Online interior design services,**Company Name:** TravelTales **Website:** tr...,synthetic
18393,Products & Services,Online interior design services,**Company Name:** GreenEnergy **Website:** gr...,synthetic
18394,Products & Services,Online interior design services,**Company Name:** GameZone **Website:** gamez...,synthetic

In [1389]:
negatives_df=pd.concat([synthetic_negatives_df,customer_negatives,negatives_df])

In [1390]:
negatives_df

,aspect,query,factsheet,strategy
0,Technology Used,Augmented reality,**Company Name:** DataViz Analytics \n**Websi...,synthetic
1,Technology Used,Augmented reality,**Company Name:** AIToolbox \n**Website:** ai...,synthetic
2,Technology Used,Augmented reality,**Company Name:** CloudSync Solutions \n**Web...,synthetic
3,Technology Used,Augmented reality,**Company Name:** EcoTech Innovations \n**Web...,synthetic
4,Technology Used,Augmented reality,**Company Name:** FinTech Dynamics \n**Websit...,synthetic
...,...,...,...,...
37018,Customer Industry,Retailtech,* * company fact sheet : shape capital * * \n\...,venture
37019,Customer Industry,Retailtech,* * the company fact sheet * * \n\n * * 1 . ...,venture
37020,Customer Industry,Retailtech,* * company name :* * aerox ventures \n\n * * ...,venture
37021,Customer Industry,Retailtech,* * company name :* * golden section \n * * we...,venture
37024,Customer Industry,Retailtech,* * company name :* * sekhmet ventures \n\n * ...,venture

In [1391]:
# negatives_df.aspect.unique()

In [1392]:
# synthetic_negatives_df

In [1393]:
print(negatives_df[negatives_df.strategy=='rule'].iloc[-10].factsheet)

**Company Name:** QuantumDev Systems
**Website:** quantumdevsystems.com
**Industry:** Develops development tools and environments for quantum computing applications.
**Target Audience:** Quantum computing developers and researchers needing robust development environments.
**Products & Services:**
- **Quantum IDE:** Integrated development environment tailored for quantum programming.
- **Qubit Debugging Tools:** Tools for debugging and testing quantum algorithms.
**Unique Selling Propositions (USPs) & Key Differentiators:**
- Comprehensive development environment for quantum computing.
- Advanced debugging tools for quantum algorithms.
**Business Model:** B2B with software licensing and support services.
**Technology Used:** Quantum programming and development technologies.
**Revenue Model:** Licensing fees and support contracts.
**Competitive Landscape:** Competes with general development tool providers but focuses on quantum-specific applications.
**Overall Assessment:** QuantumDev Systems offers essential development environments and tools for the quantum computing industry, providing comprehensive solutions for developers and researchers.

In [1394]:
negatives_df_group=negatives_df.groupby(['aspect','query','strategy'])

In [1395]:
negatives_df_group.get_group(('Technology Used', 'Augmented reality', 'synthetic'))

,aspect,query,factsheet,strategy
0,Technology Used,Augmented reality,**Company Name:** DataViz Analytics \n**Websi...,synthetic
1,Technology Used,Augmented reality,**Company Name:** AIToolbox \n**Website:** ai...,synthetic
2,Technology Used,Augmented reality,**Company Name:** CloudSync Solutions \n**Web...,synthetic
3,Technology Used,Augmented reality,**Company Name:** EcoTech Innovations \n**Web...,synthetic
4,Technology Used,Augmented reality,**Company Name:** FinTech Dynamics \n**Websit...,synthetic
5,Technology Used,Augmented reality,**Company Name:** HealthSync Technologies \n*...,synthetic
6,Technology Used,Augmented reality,**Company Name:** LogiTech Systems \n**Websit...,synthetic
7,Technology Used,Augmented reality,**Company Name:** EduTech Innovators \n**Webs...,synthetic
8,Technology Used,Augmented reality,**Company Name:** SecureNet Solutions \n**Web...,synthetic
9,Technology Used,Augmented reality,**Company Name:** Urban Mobility Systems \n**...,synthetic
10,Technology Used,Augmented reality,**Company Name:** GreenTech Solutions \n**Web...,synthetic
11,Technology Used,Augmented reality,**Company Name:** RetailSync Technologies \n*...,synthetic
12,Technology Used,Augmented reality,**Company Name:** SmartHome Innovations \n**W...,synthetic
13,Technology Used,Augmented reality,**Company Name:** TravelTech Solutions \n**We...,synthetic
14,Technology Used,Augmented reality,**Company Name:** AgriTech Innovations \n**We...,synthetic
15,Technology Used,Augmented reality,**Company Name:** FinSecure Technologies \n**...,synthetic
16,Technology Used,Augmented reality,**Company Name:** MediaStream Networks \n**We...,synthetic
17,Technology Used,Augmented reality,**Company Name:** SmartGrid Technologies \n**...,synthetic
18,Technology Used,Augmented reality,**Company Name:** AutoTech Innovations \n**We...,synthetic
19,Technology Used,Augmented reality,**Company Name:** DataViz Analytics \n**Websi...,synthetic
20,Technology Used,Augmented reality,**Company Name:** AIToolbox \n**Website:** ai...,synthetic
21,Technology Used,Augmented reality,**Company Name:** SecureNet Solutions \n**Web...,synthetic
22,Technology Used,Augmented reality,**Company Name:** CloudSync Technologies \n**...,synthetic
23,Technology Used,Augmented reality,**Company Name:** FinTech Innovators \n**Webs...,synthetic
24,Technology Used,Augmented reality,**Company Name:** HealthTech Solutions \n**We...,synthetic
25,Technology Used,Augmented reality,**Company Name:** EduTech Innovations \n**Web...,synthetic
26,Technology Used,Augmented reality,**Company Name:** GreenEnergy Tech \n**Websit...,synthetic
27,Technology Used,Augmented reality,**Company Name:** RetailTech Dynamics \n**Web...,synthetic
28,Technology Used,Augmented reality,**Company Name:** SmartHome Innovations \n**W...,synthetic
29,Technology Used,Augmented reality,**Company Name:** Urban Mobility Systems \n**...,synthetic
30,Technology Used,Augmented reality,**Company Name:** BioTech Labs \n**Website:**...,synthetic
31,Technology Used,Augmented reality,**Company Name:** AgriTech Solutions \n**Webs...,synthetic
32,Technology Used,Augmented reality,**Company Name:** LogisticsPro Solutions \n**...,synthetic
33,Technology Used,Augmented reality,**Company Name:** MediaTech Creatives \n**Web...,synthetic
34,Technology Used,Augmented reality,**Company Name:** SmartCity Innovations \n**W...,synthetic
35,Technology Used,Augmented reality,**Company Name:** TravelTech Ventures \n**Web...,synthetic
36,Technology Used,Augmented reality,**Company Name:** FinSecure Technologies \n**...,synthetic
37,Technology Used,Augmented reality,**Company Name:** EduLearn Systems \n**Websit...,synthetic
38,Technology Used,Augmented reality,**Company Name:** DataViz Analytics \n**Websi...,synthetic
39,Technology Used,Augmented reality,**Company Name:** AIToolbox \n**Website:** ai...,synthetic
40,Technology Used,Augmented reality,**Company Name:** SecureNet Solutions \n**Web...,synthetic
41,Technology Used,Augmented reality,**Company Name:** GreenTech Innovations \n**W...,synthetic
42,Technology Used,Augmented reality,**Company Name:** FinTech Dynamics \n**Websit...,synthetic
43,Technology Used,Augmented reality,**Company Name:** HealthTech Solutions \n**We...,synthetic
44,Technology Used,Augmented reality,**Company Name:** EduTech Innovations \n**Web...,synthetic
45,Technology Used,Augmented reality,**Company Name:** RetailTech Solutions \n**We...,synthetic
46,Technology Used,Augmented reality,**Company Name:** AgriTech Innovations \n**We...,synthetic
47,Technology Used,Augmented reality,**Company Name:** SmartCity Innovations \n**W...,synthetic
48,Technology Used,Augmented reality,**Company Name:** BioTech Solutions \n**Websi...,synthetic
49,Technology Used,Augmented reality,**Company Name:** CleanTech Innovations \n**W...,synthetic
50,Technology Used,Augmented reality,**Company Name:** TransportTech Solutions \n*...,synthetic
51,Technology Used,Augmented reality,**Company Name:** InsureTech Innovations \n**...,synthetic
52,Technology Used,Augmented reality,**Company Name:** FoodTech Innovations \n**We...,synthetic
53,Technology Used,Augmented reality,**Company Name:** PropTech Solutions \n**Webs...,synthetic
54,Technology Used,Augmented reality,**Company Name:** MediaTech Innovations \n**W...,synthetic
55,Technology Used,Augmented reality,**Company Name:** LegalTech Solutions \n**Web...,synthetic

In [1396]:
triplet_rows=[]
for i, group in positives_df.groupby(['aspect','query']):
    
    aspect=group['aspect'].iloc[0]
    query=group['query'].iloc[0]
    positives=group['factsheet'].to_list()
    
    for positive in positives:
        if 'Industry' in aspect:
            strategy_dict= {'rule':20,'venture':10,'synthetic':5}
        else:
            strategy_dict= {'venture':5,'synthetic':27}
        
        remaining=32
        negatives=[]
        i=0
        
        for strategy,number in strategy_dict.items():
            try:
                all_negatives=negatives_df_group.get_group((aspect,query,strategy))
            except KeyError:
                print(f'counld not find {(aspect,query,strategy)}')
                i+=1
                continue

            if i==len(strategy_dict)-1:
                sampled=all_negatives.sample(min(len(all_negatives),remaining))
                
            else:
                sampled=all_negatives.sample(min(len(all_negatives),strategy_dict[strategy]))
                
            remaining=remaining-len(sampled)
            
            _negatives=sampled.factsheet.to_list()
            negatives.extend(_negatives)
            i+=1
                
                
        _triplets=[{'query':(aspect,query),'positive':positive,'negative':negative} for negative in negatives]
        triplet_rows.extend(_triplets)

counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Direct sales', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'Franchise', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'On-demand', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Business Model', 'Subscription-based', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Adtech', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Advertising', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Banking', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Beauty', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Broadcasting', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Construction', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consulting', 'venture')
counld not find ('Customer Industry', 'Consumer Electronics', 'rule')
counld not find ('Customer Industry', 'Consumer Electronics', 'rule')
counld not find ('Customer Industry', 'Consumer Electronics', 'rule')
counld not find ('Customer Industry', 'Consumer Electronics', 'rule')

In [1397]:
triplets_df=pd.DataFrame(triplet_rows)

In [1398]:
triplets_df

,query,positive,negative
0,"(Business Model, B2B)",* * the company holdings fact sheet * * \n\n *...,* * the company fact sheet * * \n\n * * compan...
1,"(Business Model, B2B)",* * the company holdings fact sheet * * \n\n *...,* * company name :* * colter ventures \n\n * *...
2,"(Business Model, B2B)",* * the company holdings fact sheet * * \n\n *...,* * company fact sheet : wy group * * \n\n * *...
3,"(Business Model, B2B)",* * the company holdings fact sheet * * \n\n *...,**Company Name:** TravelBuddy **Website:** tr...
4,"(Business Model, B2B)",* * the company holdings fact sheet * * \n\n *...,**Company Name:** SportShop **Website:** spor...
...,...,...,...
536421,"(Technology Used, Wearable technology)",* * actionstreamer company fact sheet * * \n\n...,**Company Name:** FinServe Innovations **Webs...
536422,"(Technology Used, Wearable technology)",* * actionstreamer company fact sheet * * \n\n...,**Company Name:** EduTech Solutions \n**Websi...
536423,"(Technology Used, Wearable technology)",* * actionstreamer company fact sheet * * \n\n...,**Company Name:** CleanTech Innovations \n**W...
536424,"(Technology Used, Wearable technology)",* * actionstreamer company fact sheet * * \n\n...,**Company Name:** AgriTech Innovations **Webs...
536425,"(Technology Used, Wearable technology)",* * actionstreamer company fact sheet * * \n\n...,**Company Name:** TravelTech Solutions \n**We...

In [1399]:
import random
k=[1,2]
random.shuffle(k)

In [1400]:
k

[2, 1]

In [1401]:
split_strategy={'train':0.85,'val':0.15}

In [1402]:
triplets_group=triplets_df.groupby(['query'])
split_groups=[]
for _, group in triplets_group:
    
    split_={split:prop*len(group) for split,prop in split_strategy.items()}
    split_array=[]
    i=0
    poitives_df=group[['positive']].drop_duplicates()
    
    for split_key, prop in split_strategy.items():
        if i==len(split_strategy)-1:
            n=len(poitives_df)-len(split_array)
        else:
            n=int(prop*len(poitives_df))
        
        split_array.extend([split_key]*n)
        i+=1
    for s in range(5):
        random.shuffle(split_array)
    
    poitives_df['split']=split_array
    group=group.merge(poitives_df,how='left')
    split_groups.append(group)

In [1403]:
split_df=pd.concat(split_groups)

In [1404]:
# split_df

In [1409]:
split_df['split'].value_counts()

split
train    449908
val       86518
Name: count, dtype: int64

In [1406]:
83608/449619

0.1859529957586312

In [1407]:
# query_negatives_dict.keys()

In [1410]:
# split_df.split.

In [1411]:
split_df.to_pickle('../synthetic_data/split.pkl')

In [1412]:
train_triplets_df=split_df[split_df.split=='train']

In [1413]:
val_triplets_df=split_df[split_df.split=='val']

In [1414]:
# train_triplets_df['query']=train_triplets_df['query'].apply(lambda x:'||'.join(x))

In [1415]:
# val_triplets_df['query']=val_triplets_df['query'].apply(lambda x:'||'.join(x))

In [1428]:
train_collections=pd.concat([train_triplets_df[['positive']].rename(columns={'positive':'collection'}),train_triplets_df[['negative']].rename(columns={'negative':'collection'})]).drop_duplicates()

In [1429]:
val_collections=pd.concat([val_triplets_df[['positive']].rename(columns={'positive':'collection'}),val_triplets_df[['negative']].rename(columns={'negative':'collection'})]).drop_duplicates()

In [1430]:
train_collections['id']=list(range(len(train_collections)))
val_collections['id']=list(range(len(val_collections)))

In [1431]:
train_collections.to_pickle('../synthetic_data/collection.train.raw.pkl')
val_collections.to_pickle('../synthetic_data/collection.val.raw.pkl')

In [1432]:
train_queries=train_triplets_df[['query']].drop_duplicates()
val_queries=val_triplets_df[['query']].drop_duplicates()

In [1433]:
train_queries['id']=list(range(len(train_queries)))

In [1434]:
train_queries.to_pickle('../synthetic_data/queries.train.raw.pkl')

In [1435]:
val_queries['id']=list(range(len(val_queries)))

In [1436]:
val_queries.to_pickle('../synthetic_data/queries.val.raw.pkl')

In [1437]:
train_triplets_df=train_triplets_df.merge(train_queries[['query','id']].rename(columns={'id':'qid'}),how='left')
train_triplets_df=train_triplets_df.merge(train_collections[['collection','id']].rename(columns={'id':'pid','collection':'positive'}),how='left')
train_triplets_df=train_triplets_df.merge(train_collections[['collection','id']].rename(columns={'id':'nid','collection':'negative'}),how='left')

In [1438]:
### let's remove **Overall Assessment:** for synthetic negatives
train_triplets_df.loc[train_triplets_df.negative.isin(synthetic_negatives_df.factsheet),'negative']=train_triplets_df.loc[train_triplets_df.negative.isin(synthetic_negatives_df.factsheet),'negative'].apply(lambda x:
                                                                                                                                                                                                     x.split('**Overall Assessment:**')[0])

In [1439]:
# train_triplets_df.loc[train_triplets_df.negative.isin(synthetic_negatives_df.factsheet.apply(lambda x:x.split('**Overall Assessment:**')[0])),'negative'].iloc[0]

In [1440]:
val_triplets_df=val_triplets_df.merge(val_queries[['query','id']].rename(columns={'id':'qid'}),how='left')
val_triplets_df=val_triplets_df.merge(val_collections[['collection','id']].rename(columns={'id':'pid','collection':'positive'}),how='left')
val_triplets_df=val_triplets_df.merge(val_collections[['collection','id']].rename(columns={'id':'nid','collection':'negative'}),how='left')

In [1441]:
### let's remove **Overall Assessment:** for synthetic negatives
val_triplets_df.loc[val_triplets_df.negative.isin(synthetic_negatives_df.factsheet),'negative']=val_triplets_df.loc[val_triplets_df.negative.isin(synthetic_negatives_df.factsheet),'negative'].apply(lambda x:
                                                                                                                                                                                                     x.split('**Overall Assessment:**')[0])

In [1442]:
val_triplets_df.to_pickle('../synthetic_data/triples.val.raw.pkl')

In [1443]:

train_triplets_df.to_pickle('../synthetic_data/triples.train.raw.pkl')

In [1444]:
### creating NLQ variations of queries

def generate_nlq(query,n_queries):
    success=False
    response_format=NaturalLanguageQueryResponse
    
    sys_msg_path1='../prompts/query_diversification.txt'
    
    system_message1=open(sys_msg_path1,'r').read()
    
    llm1=OpenAIChatCompletion(model='gpt-4o',system_message=system_message1)
    
    if 'Industry' in query[0]:
        definitions='''- **Customer Industry**: This refers to the industry in which the company's customers operate. For example, if a company provides AI solutions to legal industry, the customer industry is the "Legal Industry.
        - **Industry**: This refers to the sector in which the company operates and creates solutions. For example, a company creating AI applications or LLMs is part of the "Technology and AI Industry.
        Please be careful, both are different as stated above. The queries should be such that the difference is very clear without any confusion\n\n
        '''
        prompt1=definitions+f"\nPlease provide {n_queries} natural language queries that are different ways an investor could ask for companies related to the query: {query}. Keep the Queries less that 10-12 words"
    else:
        prompt1=f"\nPlease provide {n_queries} natural language queries that are different ways an investor could ask for companies related to the query: {query}. Keep the Queries less that 10-12 words"
    temperature=0.5
    
    res1=llm1.structured_response(prompt1,temperature,response_format)

    try:
        r1=json.loads(res1)

        success=True
        return success,r1
    except Exception as e:
        
        print(f'failed for {query} - {e}')
        success=False
        return success,[]

In [804]:
res=generate_factsheets(('Busniess Model','B2B'),20)

In [806]:
train_queries['aspect']=train_queries['query'].apply(lambda x: x[0])

In [811]:
query_dict={}
for aspect,group in tqdm(train_queries.groupby('aspect')):
    
    queries=group['query'].to_list()
    
    args=[([(query[0],query[1]),20],{}) for query in queries]
    
    nlq_queries=parallel_execute(
                        func= generate_nlq,
                        argument_sets=args,
                        max_workers = 25,
                        show_progress= True,
                        desc = "generating negative factsheets"
                    )
    generate_nlq_=dict(zip(queries,nlq_queries))
    
    query_dict={**query_dict,**generate_nlq_}

  0%|          | 0/7 [00:00<?, ?it/s]
erating negative factsheets:   0%|          | 0/9 [00:00<?, ?it/s]
erating negative factsheets:  11%|█         | 1/9 [00:02<00:19,  2.46s/it]
erating negative factsheets:  22%|██▏       | 2/9 [00:02<00:07,  1.14s/it]
erating negative factsheets:  33%|███▎      | 3/9 [00:02<00:04,  1.40it/s]
erating negative factsheets:  56%|█████▌    | 5/9 [00:03<00:01,  2.82it/s]
erating negative factsheets:  67%|██████▋   | 6/9 [00:03<00:00,  3.48it/s]
generating negative factsheets: 100%|██████████| 9/9 [00:03<00:00,  2.73it/s]
 14%|█▍        | 1/7 [00:03<00:20,  3.39s/it]
erating negative factsheets:   0%|          | 0/75 [00:00<?, ?it/s]
erating negative factsheets:   1%|▏         | 1/75 [00:02<02:52,  2.33s/it]
erating negative factsheets:   7%|▋         | 5/75 [00:02<00:25,  2.71it/s]
erating negative factsheets:  11%|█         | 8/75 [00:02<00:14,  4.69it/s]
erating negative factsheets:  17%|█▋        | 13/75 [00:02<00:07,  8.43it/s]
erating negative factsheets:  23%|██▎       | 17/75 [00:02<00:04, 11.88it/s]
erating negative factsheets:  29%|██▉       | 22/75 [00:02<00:03, 16.63it/s]
erating negative factsheets:  35%|███▍      | 26/75 [00:04<00:08,  5.88it/s]
erating negative factsheets:  39%|███▊      | 29/75 [00:04<00:06,  6.71it/s]
erating negative factsheets:  41%|████▏     | 31/75 [00:05<00:06,  7.25it/s]
erating negative factsheets:  44%|████▍     | 33/75 [00:05<00:05,  8.33it/s]
erating negative factsheets:  47%|████▋     | 35/75 [00:05<00:04,  9.38it/s]
erating negative factsheets:  51%|█████     | 38/75 [00:05<00:03, 12.00it/s]
erating negative factsheets:  55%|█████▍    | 41/75 [00:05<00:02, 11.92it/s]
erating negative factsheets:  59%|█████▊    | 44/75 [00:05<00:02, 14.49it/s]
erating negative factsheets:  63%|██████▎   | 47/75 [00:06<00:02, 13.37it/s]
erating negative factsheets:  65%|██████▌   | 49/75 [00:06<00:02, 10.78it/s]
erating negative factsheets:  68%|██████▊   | 51/75 [00:07<00:04,  5.73it/s]
erating negative factsheets:  71%|███████   | 53/75 [00:07<00:03,  6.51it/s]
erating negative factsheets:  73%|███████▎  | 55/75 [00:07<00:02,  7.95it/s]
erating negative factsheets:  77%|███████▋  | 58/75 [00:07<00:01, 10.67it/s]
erating negative factsheets:  80%|████████  | 60/75 [00:07<00:01,  9.76it/s]
erating negative factsheets:  83%|████████▎ | 62/75 [00:08<00:01,  7.97it/s]
erating negative factsheets:  88%|████████▊ | 66/75 [00:08<00:00, 11.47it/s]
erating negative factsheets:  91%|█████████ | 68/75 [00:08<00:00, 11.77it/s]
erating negative factsheets:  93%|█████████▎| 70/75 [00:08<00:00, 11.65it/s]
erating negative factsheets:  96%|█████████▌| 72/75 [00:09<00:00,  8.90it/s]
erating negative factsheets:  99%|█████████▊| 74/75 [00:09<00:00,  5.28it/s]
generating negative factsheets: 100%|██████████| 75/75 [00:14<00:00,  5.36it/s]
 29%|██▊       | 2/7 [00:17<00:48,  9.74s/it]
erating negative factsheets:   0%|          | 0/84 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/84 [00:01<02:34,  1.86s/it]
erating negative factsheets:   2%|▏         | 2/84 [00:02<01:12,  1.12it/s]
erating negative factsheets:   6%|▌         | 5/84 [00:02<00:22,  3.57it/s]
erating negative factsheets:  10%|▉         | 8/84 [00:02<00:11,  6.39it/s]
erating negative factsheets:  12%|█▏        | 10/84 [00:02<00:09,  7.80it/s]
erating negative factsheets:  14%|█▍        | 12/84 [00:02<00:07,  9.31it/s]
erating negative factsheets:  17%|█▋        | 14/84 [00:02<00:06, 10.29it/s]
erating negative factsheets:  19%|█▉        | 16/84 [00:02<00:06, 10.73it/s]
erating negative factsheets:  23%|██▎       | 19/84 [00:03<00:04, 13.70it/s]
erating negative factsheets:  25%|██▌       | 21/84 [00:03<00:04, 13.18it/s]
erating negative factsheets:  27%|██▋       | 23/84 [00:03<00:04, 12.97it/s]
erating negative factsheets:  30%|██▉       | 25/84 [00:04<00:13,  4.53it/s]
erating negative factsheets:  32%|███▏      | 27/84 [00:04<00:10,  5.56it/s]
erating negative factsheets:  35%|███▍      | 29/84 [00:04<00:08,  6.74it/s]
erating negative factsheets:  37%|███▋      | 31/84 [00:05<00:08,  5.94it/s]
erating negative factsheets:  42%|████▏     | 35/84 [00:05<00:05,  9.30it/s]
erating negative factsheets:  45%|████▌     | 38/84 [00:05<00:04, 10.20it/s]
erating negative factsheets:  48%|████▊     | 40/84 [00:05<00:04, 10.64it/s]
erating negative factsheets:  50%|█████     | 42/84 [00:05<00:03, 10.70it/s]
erating negative factsheets:  54%|█████▎    | 45/84 [00:06<00:02, 13.21it/s]
erating negative factsheets:  56%|█████▌    | 47/84 [00:06<00:03,  9.70it/s]
erating negative factsheets:  58%|█████▊    | 49/84 [00:06<00:04,  7.77it/s]
erating negative factsheets:  61%|██████    | 51/84 [00:07<00:05,  6.45it/s]
erating negative factsheets:  63%|██████▎   | 53/84 [00:07<00:05,  5.25it/s]
erating negative factsheets:  64%|██████▍   | 54/84 [00:07<00:05,  5.57it/s]
erating negative factsheets:  69%|██████▉   | 58/84 [00:08<00:02,  9.57it/s]
erating negative factsheets:  71%|███████▏  | 60/84 [00:08<00:02, 10.52it/s]
erating negative factsheets:  74%|███████▍  | 62/84 [00:08<00:02,  9.17it/s]
erating negative factsheets:  76%|███████▌  | 64/84 [00:08<00:02,  9.39it/s]
erating negative factsheets:  79%|███████▊  | 66/84 [00:08<00:01,  9.45it/s]
erating negative factsheets:  81%|████████  | 68/84 [00:09<00:01,  9.96it/s]
erating negative factsheets:  83%|████████▎ | 70/84 [00:09<00:01, 10.84it/s]
erating negative factsheets:  86%|████████▌ | 72/84 [00:09<00:01,  9.40it/s]
erating negative factsheets:  88%|████████▊ | 74/84 [00:09<00:00, 10.77it/s]
erating negative factsheets:  90%|█████████ | 76/84 [00:10<00:01,  6.15it/s]
erating negative factsheets:  92%|█████████▏| 77/84 [00:10<00:01,  5.48it/s]
erating negative factsheets:  93%|█████████▎| 78/84 [00:10<00:01,  5.40it/s]
erating negative factsheets:  94%|█████████▍| 79/84 [00:10<00:00,  5.97it/s]
erating negative factsheets:  95%|█████████▌| 80/84 [00:10<00:00,  6.60it/s]
erating negative factsheets:  96%|█████████▋| 81/84 [00:11<00:00,  6.88it/s]
erating negative factsheets:  98%|█████████▊| 82/84 [00:11<00:00,  3.10it/s]
erating negative factsheets:  99%|█████████▉| 83/84 [00:12<00:00,  2.29it/s]
generating negative factsheets: 100%|██████████| 84/84 [00:12<00:00,  6.49it/s]
 43%|████▎     | 3/7 [00:30<00:45, 11.28s/it]
erating negative factsheets:   0%|          | 0/90 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/90 [00:02<03:10,  2.14s/it]
erating negative factsheets:   3%|▎         | 3/90 [00:02<00:52,  1.66it/s]
erating negative factsheets:   7%|▋         | 6/90 [00:02<00:21,  3.92it/s]
erating negative factsheets:  10%|█         | 9/90 [00:02<00:13,  5.87it/s]
erating negative factsheets:  12%|█▏        | 11/90 [00:02<00:10,  7.50it/s]
erating negative factsheets:  19%|█▉        | 17/90 [00:02<00:04, 14.64it/s]
erating negative factsheets:  22%|██▏       | 20/90 [00:03<00:04, 14.86it/s]
erating negative factsheets:  26%|██▌       | 23/90 [00:03<00:04, 15.78it/s]
erating negative factsheets:  29%|██▉       | 26/90 [00:04<00:11,  5.56it/s]
erating negative factsheets:  31%|███       | 28/90 [00:04<00:10,  5.71it/s]
erating negative factsheets:  33%|███▎      | 30/90 [00:04<00:08,  6.73it/s]
erating negative factsheets:  36%|███▌      | 32/90 [00:05<00:07,  7.70it/s]
erating negative factsheets:  38%|███▊      | 34/90 [00:05<00:07,  7.91it/s]
erating negative factsheets:  40%|████      | 36/90 [00:05<00:06,  8.53it/s]
erating negative factsheets:  42%|████▏     | 38/90 [00:05<00:05,  9.79it/s]
erating negative factsheets:  46%|████▌     | 41/90 [00:05<00:03, 12.89it/s]
erating negative factsheets:  48%|████▊     | 43/90 [00:05<00:03, 12.09it/s]
erating negative factsheets:  51%|█████     | 46/90 [00:06<00:03, 11.51it/s]
erating negative factsheets:  53%|█████▎    | 48/90 [00:06<00:06,  6.91it/s]
erating negative factsheets:  56%|█████▌    | 50/90 [00:07<00:06,  6.43it/s]
erating negative factsheets:  58%|█████▊    | 52/90 [00:07<00:05,  7.41it/s]
erating negative factsheets:  60%|██████    | 54/90 [00:07<00:04,  7.66it/s]
erating negative factsheets:  61%|██████    | 55/90 [00:07<00:04,  7.01it/s]
erating negative factsheets:  62%|██████▏   | 56/90 [00:08<00:05,  6.24it/s]
erating negative factsheets:  66%|██████▌   | 59/90 [00:08<00:03,  9.46it/s]
erating negative factsheets:  68%|██████▊   | 61/90 [00:08<00:03,  9.28it/s]
erating negative factsheets:  70%|███████   | 63/90 [00:08<00:03,  8.78it/s]
erating negative factsheets:  72%|███████▏  | 65/90 [00:08<00:02,  8.64it/s]
erating negative factsheets:  74%|███████▍  | 67/90 [00:09<00:02,  9.44it/s]
erating negative factsheets:  77%|███████▋  | 69/90 [00:09<00:02,  8.46it/s]
erating negative factsheets:  78%|███████▊  | 70/90 [00:09<00:02,  7.03it/s]
erating negative factsheets:  79%|███████▉  | 71/90 [00:09<00:02,  7.17it/s]
erating negative factsheets:  81%|████████  | 73/90 [00:09<00:02,  8.32it/s]
erating negative factsheets:  84%|████████▍ | 76/90 [00:10<00:01,  8.63it/s]
erating negative factsheets:  88%|████████▊ | 79/90 [00:10<00:01, 10.33it/s]
erating negative factsheets:  90%|█████████ | 81/90 [00:10<00:00,  9.80it/s]
erating negative factsheets:  93%|█████████▎| 84/90 [00:10<00:00, 11.93it/s]
erating negative factsheets:  96%|█████████▌| 86/90 [00:10<00:00, 13.22it/s]
erating negative factsheets:  98%|█████████▊| 88/90 [00:11<00:00,  6.04it/s]
generating negative factsheets: 100%|██████████| 90/90 [00:12<00:00,  7.08it/s]
 57%|█████▋    | 4/7 [00:43<00:35, 11.91s/it]
erating negative factsheets:   0%|          | 0/98 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/98 [00:02<03:18,  2.05s/it]
erating negative factsheets:   3%|▎         | 3/98 [00:02<00:58,  1.64it/s]
erating negative factsheets:   8%|▊         | 8/98 [00:02<00:16,  5.47it/s]
erating negative factsheets:  11%|█         | 11/98 [00:02<00:11,  7.83it/s]
erating negative factsheets:  14%|█▍        | 14/98 [00:02<00:08,  9.71it/s]
erating negative factsheets:  18%|█▊        | 18/98 [00:02<00:06, 13.11it/s]
erating negative factsheets:  21%|██▏       | 21/98 [00:02<00:05, 14.18it/s]
erating negative factsheets:  24%|██▍       | 24/98 [00:03<00:06, 12.00it/s]
erating negative factsheets:  27%|██▋       | 26/98 [00:04<00:13,  5.50it/s]
erating negative factsheets:  29%|██▊       | 28/98 [00:04<00:13,  5.21it/s]
erating negative factsheets:  32%|███▏      | 31/98 [00:04<00:09,  6.94it/s]
erating negative factsheets:  34%|███▎      | 33/98 [00:05<00:09,  7.20it/s]
erating negative factsheets:  37%|███▋      | 36/98 [00:05<00:06,  9.45it/s]
erating negative factsheets:  39%|███▉      | 38/98 [00:05<00:05, 10.63it/s]
erating negative factsheets:  43%|████▎     | 42/98 [00:05<00:03, 14.12it/s]
erating negative factsheets:  45%|████▍     | 44/98 [00:05<00:04, 11.35it/s]
erating negative factsheets:  47%|████▋     | 46/98 [00:06<00:10,  5.19it/s]
erating negative factsheets:  50%|█████     | 49/98 [00:07<00:06,  7.26it/s]
erating negative factsheets:  53%|█████▎    | 52/98 [00:07<00:05,  8.12it/s]
erating negative factsheets:  55%|█████▌    | 54/98 [00:07<00:05,  8.77it/s]
erating negative factsheets:  57%|█████▋    | 56/98 [00:07<00:04,  9.18it/s]
erating negative factsheets:  59%|█████▉    | 58/98 [00:07<00:03, 10.21it/s]
erating negative factsheets:  61%|██████    | 60/98 [00:07<00:03, 10.53it/s]
erating negative factsheets:  63%|██████▎   | 62/98 [00:08<00:03, 11.24it/s]
erating negative factsheets:  65%|██████▌   | 64/98 [00:08<00:02, 11.34it/s]
erating negative factsheets:  68%|██████▊   | 67/98 [00:08<00:02, 12.20it/s]
erating negative factsheets:  70%|███████   | 69/98 [00:09<00:04,  5.88it/s]
erating negative factsheets:  71%|███████▏  | 70/98 [00:09<00:04,  6.24it/s]
erating negative factsheets:  72%|███████▏  | 71/98 [00:09<00:04,  5.97it/s]
erating negative factsheets:  76%|███████▌  | 74/98 [00:09<00:03,  7.78it/s]
erating negative factsheets:  78%|███████▊  | 76/98 [00:09<00:02,  9.40it/s]
erating negative factsheets:  80%|███████▉  | 78/98 [00:10<00:02,  8.34it/s]
erating negative factsheets:  82%|████████▏ | 80/98 [00:10<00:01,  9.74it/s]
erating negative factsheets:  85%|████████▍ | 83/98 [00:10<00:01,  8.76it/s]
erating negative factsheets:  88%|████████▊ | 86/98 [00:10<00:01, 10.89it/s]
erating negative factsheets:  90%|████████▉ | 88/98 [00:11<00:00, 11.53it/s]
erating negative factsheets:  92%|█████████▏| 90/98 [00:11<00:00,  9.27it/s]
erating negative factsheets:  94%|█████████▍| 92/98 [00:11<00:00,  7.39it/s]
erating negative factsheets:  96%|█████████▌| 94/98 [00:11<00:00,  8.84it/s]
erating negative factsheets:  98%|█████████▊| 96/98 [00:12<00:00,  7.12it/s]
erating negative factsheets:  99%|█████████▉| 97/98 [00:13<00:00,  4.04it/s]
generating negative factsheets: 100%|██████████| 98/98 [00:13<00:00,  7.15it/s]
 71%|███████▏  | 5/7 [00:57<00:25, 12.62s/it]
erating negative factsheets:   0%|          | 0/23 [00:00<?, ?it/s]
erating negative factsheets:   4%|▍         | 1/23 [00:02<00:46,  2.11s/it]
erating negative factsheets:   9%|▊         | 2/23 [00:02<00:21,  1.02s/it]
erating negative factsheets:  17%|█▋        | 4/23 [00:02<00:08,  2.34it/s]
erating negative factsheets:  30%|███       | 7/23 [00:02<00:03,  4.94it/s]
erating negative factsheets:  39%|███▉      | 9/23 [00:02<00:02,  6.42it/s]
erating negative factsheets:  52%|█████▏    | 12/23 [00:03<00:01,  7.48it/s]
erating negative factsheets:  65%|██████▌   | 15/23 [00:03<00:00,  9.18it/s]
erating negative factsheets:  78%|███████▊  | 18/23 [00:03<00:00,  9.13it/s]
erating negative factsheets:  91%|█████████▏| 21/23 [00:03<00:00, 11.55it/s]
generating negative factsheets: 100%|██████████| 23/23 [00:03<00:00,  5.85it/s]
 86%|████████▌ | 6/7 [01:01<00:09,  9.72s/it]
erating negative factsheets:   0%|          | 0/30 [00:00<?, ?it/s]
erating negative factsheets:   3%|▎         | 1/30 [00:02<00:59,  2.05s/it]
erating negative factsheets:  17%|█▋        | 5/30 [00:02<00:08,  3.04it/s]
erating negative factsheets:  27%|██▋       | 8/30 [00:02<00:04,  5.21it/s]
erating negative factsheets:  37%|███▋      | 11/30 [00:02<00:02,  7.43it/s]
erating negative factsheets:  47%|████▋     | 14/30 [00:02<00:01,  9.77it/s]
erating negative factsheets:  60%|██████    | 18/30 [00:02<00:00, 12.86it/s]
erating negative factsheets:  70%|███████   | 21/30 [00:02<00:00, 14.06it/s]
erating negative factsheets:  80%|████████  | 24/30 [00:03<00:00,  9.35it/s]
erating negative factsheets:  87%|████████▋ | 26/30 [00:04<00:00,  5.85it/s]
erating negative factsheets:  93%|█████████▎| 28/30 [00:04<00:00,  6.73it/s]
generating negative factsheets: 100%|██████████| 30/30 [00:04<00:00,  6.29it/s]
100%|██████████| 7/7 [01:06<00:00,  9.50s/it]

In [814]:
len(query_dict.keys())

409

In [815]:
train_nlq_rows=[]
for query, nlqs in query_dict.items():
    train_nlq_rows.append({'query':query,'nlq':nlqs[1]})

In [829]:
train_nlq_df=pd.DataFrame(train_nlq_rows)

In [830]:
train_nlq_df.to_pickle('../synthetic_data/train_nlq_df.pkl')

In [822]:
val_queries['aspect']=val_queries['query'].apply(lambda x: x[0])

In [823]:
query_dict={}
for aspect,group in tqdm(val_queries.groupby('aspect')):
    
    queries=group['query'].to_list()
    
    args=[([(query[0],query[1]),10],{}) for query in queries]
    
    nlq_queries=parallel_execute(
                        func= generate_nlq,
                        argument_sets=args,
                        max_workers = 25,
                        show_progress= True,
                        desc = "generating negative factsheets"
                    )
    generate_nlq_=dict(zip(queries,nlq_queries))
    
    query_dict={**query_dict,**generate_nlq_}

  0%|          | 0/7 [00:00<?, ?it/s]
erating negative factsheets:   0%|          | 0/9 [00:00<?, ?it/s]
erating negative factsheets:  11%|█         | 1/9 [00:01<00:13,  1.71s/it]
erating negative factsheets:  67%|██████▋   | 6/9 [00:01<00:00,  3.91it/s]
erating negative factsheets:  89%|████████▉ | 8/9 [00:02<00:00,  4.48it/s]
generating negative factsheets: 100%|██████████| 9/9 [00:02<00:00,  3.23it/s]
 14%|█▍        | 1/7 [00:02<00:17,  2.84s/it]
erating negative factsheets:   0%|          | 0/75 [00:00<?, ?it/s]
erating negative factsheets:   1%|▏         | 1/75 [00:01<01:42,  1.39s/it]
erating negative factsheets:   8%|▊         | 6/75 [00:01<00:14,  4.92it/s]
erating negative factsheets:  15%|█▍        | 11/75 [00:01<00:06,  9.85it/s]
erating negative factsheets:  20%|██        | 15/75 [00:01<00:04, 12.84it/s]
erating negative factsheets:  25%|██▌       | 19/75 [00:02<00:03, 14.85it/s]
erating negative factsheets:  31%|███       | 23/75 [00:02<00:02, 17.77it/s]
erating negative factsheets:  35%|███▍      | 26/75 [00:02<00:04, 10.91it/s]
erating negative factsheets:  37%|███▋      | 28/75 [00:03<00:05,  8.33it/s]
erating negative factsheets:  40%|████      | 30/75 [00:03<00:05,  8.83it/s]
erating negative factsheets:  45%|████▌     | 34/75 [00:03<00:03, 12.50it/s]
erating negative factsheets:  49%|████▉     | 37/75 [00:03<00:03, 12.21it/s]
erating negative factsheets:  53%|█████▎    | 40/75 [00:03<00:02, 13.28it/s]
erating negative factsheets:  59%|█████▊    | 44/75 [00:04<00:01, 15.91it/s]
erating negative factsheets:  63%|██████▎   | 47/75 [00:04<00:01, 15.59it/s]
erating negative factsheets:  65%|██████▌   | 49/75 [00:04<00:01, 15.17it/s]
erating negative factsheets:  68%|██████▊   | 51/75 [00:04<00:02, 10.75it/s]
erating negative factsheets:  71%|███████   | 53/75 [00:04<00:01, 11.49it/s]
erating negative factsheets:  75%|███████▍  | 56/75 [00:05<00:01, 13.27it/s]
erating negative factsheets:  77%|███████▋  | 58/75 [00:05<00:01, 11.74it/s]
erating negative factsheets:  80%|████████  | 60/75 [00:05<00:01, 12.03it/s]
erating negative factsheets:  83%|████████▎ | 62/75 [00:05<00:00, 13.45it/s]
erating negative factsheets:  85%|████████▌ | 64/75 [00:05<00:00, 12.65it/s]
erating negative factsheets:  91%|█████████ | 68/75 [00:05<00:00, 16.49it/s]
erating negative factsheets:  95%|█████████▍| 71/75 [00:06<00:00, 18.54it/s]
erating negative factsheets:  97%|█████████▋| 73/75 [00:06<00:00, 11.18it/s]
generating negative factsheets: 100%|██████████| 75/75 [00:06<00:00, 11.34it/s]
 29%|██▊       | 2/7 [00:09<00:25,  5.15s/it]
erating negative factsheets:   0%|          | 0/84 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/84 [00:01<01:40,  1.21s/it]
erating negative factsheets:   5%|▍         | 4/84 [00:01<00:21,  3.72it/s]
erating negative factsheets:  13%|█▎        | 11/84 [00:01<00:06, 11.84it/s]
erating negative factsheets:  18%|█▊        | 15/84 [00:01<00:04, 14.25it/s]
erating negative factsheets:  21%|██▏       | 18/84 [00:01<00:04, 14.93it/s]
erating negative factsheets:  27%|██▋       | 23/84 [00:02<00:03, 16.81it/s]
erating negative factsheets:  31%|███       | 26/84 [00:02<00:05, 10.69it/s]
erating negative factsheets:  33%|███▎      | 28/84 [00:02<00:05, 10.03it/s]
erating negative factsheets:  40%|████      | 34/84 [00:03<00:03, 15.98it/s]
erating negative factsheets:  44%|████▍     | 37/84 [00:03<00:02, 17.48it/s]
erating negative factsheets:  48%|████▊     | 40/84 [00:03<00:02, 14.99it/s]
erating negative factsheets:  52%|█████▏    | 44/84 [00:03<00:02, 17.94it/s]
erating negative factsheets:  56%|█████▌    | 47/84 [00:04<00:03,  9.81it/s]
erating negative factsheets:  60%|█████▉    | 50/84 [00:04<00:03, 10.43it/s]
erating negative factsheets:  63%|██████▎   | 53/84 [00:04<00:02, 12.37it/s]
erating negative factsheets:  68%|██████▊   | 57/84 [00:04<00:01, 14.79it/s]
erating negative factsheets:  70%|███████   | 59/84 [00:04<00:01, 15.36it/s]
erating negative factsheets:  73%|███████▎  | 61/84 [00:05<00:01, 14.14it/s]
erating negative factsheets:  77%|███████▋  | 65/84 [00:05<00:01, 18.81it/s]
erating negative factsheets:  81%|████████  | 68/84 [00:05<00:01, 14.88it/s]
erating negative factsheets:  83%|████████▎ | 70/84 [00:05<00:00, 14.23it/s]
erating negative factsheets:  86%|████████▌ | 72/84 [00:05<00:01, 11.55it/s]
erating negative factsheets:  88%|████████▊ | 74/84 [00:06<00:00, 10.38it/s]
erating negative factsheets:  92%|█████████▏| 77/84 [00:06<00:00, 13.30it/s]
erating negative factsheets:  94%|█████████▍| 79/84 [00:06<00:00, 13.76it/s]
generating negative factsheets: 100%|██████████| 84/84 [00:07<00:00, 10.77it/s]
 43%|████▎     | 3/7 [00:17<00:25,  6.43s/it]
erating negative factsheets:   0%|          | 0/90 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/90 [00:01<01:49,  1.23s/it]
erating negative factsheets:   6%|▌         | 5/90 [00:01<00:18,  4.71it/s]
erating negative factsheets:  12%|█▏        | 11/90 [00:01<00:07, 11.25it/s]
erating negative factsheets:  17%|█▋        | 15/90 [00:01<00:05, 13.69it/s]
erating negative factsheets:  20%|██        | 18/90 [00:01<00:04, 15.56it/s]
erating negative factsheets:  23%|██▎       | 21/90 [00:01<00:04, 15.88it/s]
erating negative factsheets:  27%|██▋       | 24/90 [00:02<00:07,  9.34it/s]
erating negative factsheets:  29%|██▉       | 26/90 [00:02<00:06,  9.62it/s]
erating negative factsheets:  31%|███       | 28/90 [00:02<00:05, 10.35it/s]
erating negative factsheets:  33%|███▎      | 30/90 [00:03<00:05, 10.99it/s]
erating negative factsheets:  41%|████      | 37/90 [00:03<00:03, 17.50it/s]
erating negative factsheets:  43%|████▎     | 39/90 [00:03<00:03, 15.90it/s]
erating negative factsheets:  46%|████▌     | 41/90 [00:03<00:03, 14.06it/s]
erating negative factsheets:  48%|████▊     | 43/90 [00:03<00:03, 12.88it/s]
erating negative factsheets:  50%|█████     | 45/90 [00:04<00:03, 13.39it/s]
erating negative factsheets:  52%|█████▏    | 47/90 [00:04<00:03, 13.34it/s]
erating negative factsheets:  54%|█████▍    | 49/90 [00:04<00:03, 11.46it/s]
erating negative factsheets:  58%|█████▊    | 52/90 [00:04<00:02, 14.43it/s]
erating negative factsheets:  61%|██████    | 55/90 [00:04<00:02, 16.54it/s]
erating negative factsheets:  66%|██████▌   | 59/90 [00:04<00:01, 19.95it/s]
erating negative factsheets:  69%|██████▉   | 62/90 [00:05<00:02, 12.18it/s]
erating negative factsheets:  71%|███████   | 64/90 [00:05<00:02, 12.11it/s]
erating negative factsheets:  74%|███████▍  | 67/90 [00:05<00:01, 11.70it/s]
erating negative factsheets:  79%|███████▉  | 71/90 [00:05<00:01, 13.03it/s]
erating negative factsheets:  81%|████████  | 73/90 [00:06<00:01, 12.35it/s]
erating negative factsheets:  86%|████████▌ | 77/90 [00:06<00:00, 13.91it/s]
erating negative factsheets:  90%|█████████ | 81/90 [00:06<00:00, 17.26it/s]
erating negative factsheets:  93%|█████████▎| 84/90 [00:06<00:00, 16.64it/s]
erating negative factsheets:  96%|█████████▌| 86/90 [00:06<00:00, 16.84it/s]
erating negative factsheets:  98%|█████████▊| 88/90 [00:07<00:00, 11.72it/s]
generating negative factsheets: 100%|██████████| 90/90 [00:10<00:00,  8.80it/s]
 57%|█████▋    | 4/7 [00:27<00:23,  8.00s/it]
erating negative factsheets:   0%|          | 0/98 [00:00<?, ?it/s]
erating negative factsheets:   1%|          | 1/98 [00:00<01:36,  1.01it/s]
erating negative factsheets:   2%|▏         | 2/98 [00:01<00:50,  1.89it/s]
erating negative factsheets:   5%|▌         | 5/98 [00:01<00:16,  5.64it/s]
erating negative factsheets:   7%|▋         | 7/98 [00:01<00:12,  7.35it/s]
erating negative factsheets:  11%|█         | 11/98 [00:01<00:07, 12.26it/s]
erating negative factsheets:  17%|█▋        | 17/98 [00:01<00:04, 19.89it/s]
erating negative factsheets:  20%|██        | 20/98 [00:01<00:04, 17.49it/s]
erating negative factsheets:  24%|██▍       | 24/98 [00:02<00:04, 17.02it/s]
erating negative factsheets:  28%|██▊       | 27/98 [00:02<00:07,  9.82it/s]
erating negative factsheets:  31%|███       | 30/98 [00:02<00:05, 11.86it/s]
erating negative factsheets:  35%|███▍      | 34/98 [00:03<00:04, 13.72it/s]
erating negative factsheets:  39%|███▉      | 38/98 [00:03<00:03, 16.80it/s]
erating negative factsheets:  42%|████▏     | 41/98 [00:03<00:03, 17.99it/s]
erating negative factsheets:  45%|████▍     | 44/98 [00:03<00:04, 11.71it/s]
erating negative factsheets:  48%|████▊     | 47/98 [00:04<00:04, 12.50it/s]
erating negative factsheets:  50%|█████     | 49/98 [00:04<00:04, 10.45it/s]
erating negative factsheets:  52%|█████▏    | 51/98 [00:04<00:04, 10.09it/s]
erating negative factsheets:  59%|█████▉    | 58/98 [00:04<00:02, 18.45it/s]
erating negative factsheets:  62%|██████▏   | 61/98 [00:05<00:02, 16.98it/s]
erating negative factsheets:  65%|██████▌   | 64/98 [00:05<00:02, 16.24it/s]
erating negative factsheets:  68%|██████▊   | 67/98 [00:05<00:02, 12.58it/s]
erating negative factsheets:  70%|███████   | 69/98 [00:05<00:02,  9.77it/s]
erating negative factsheets:  73%|███████▎  | 72/98 [00:06<00:02, 11.41it/s]
erating negative factsheets:  76%|███████▌  | 74/98 [00:06<00:01, 12.20it/s]
erating negative factsheets:  81%|████████  | 79/98 [00:06<00:01, 16.98it/s]
erating negative factsheets:  84%|████████▎ | 82/98 [00:06<00:01, 15.57it/s]
erating negative factsheets:  86%|████████▌ | 84/98 [00:06<00:00, 14.13it/s]
erating negative factsheets:  88%|████████▊ | 86/98 [00:07<00:01, 11.97it/s]
erating negative factsheets:  91%|█████████ | 89/98 [00:07<00:00, 11.64it/s]
erating negative factsheets:  93%|█████████▎| 91/98 [00:07<00:00, 12.36it/s]
erating negative factsheets:  95%|█████████▍| 93/98 [00:07<00:00, 13.32it/s]
erating negative factsheets:  97%|█████████▋| 95/98 [00:07<00:00, 14.03it/s]
generating negative factsheets: 100%|██████████| 98/98 [00:10<00:00,  9.71it/s]
 71%|███████▏  | 5/7 [00:38<00:17,  8.97s/it]
erating negative factsheets:   0%|          | 0/23 [00:00<?, ?it/s]
erating negative factsheets:   4%|▍         | 1/23 [00:01<00:31,  1.44s/it]
erating negative factsheets:   9%|▊         | 2/23 [00:01<00:13,  1.53it/s]
erating negative factsheets:  22%|██▏       | 5/23 [00:01<00:03,  4.71it/s]
erating negative factsheets:  30%|███       | 7/23 [00:01<00:02,  6.24it/s]
erating negative factsheets:  57%|█████▋    | 13/23 [00:01<00:00, 13.35it/s]
erating negative factsheets:  78%|███████▊  | 18/23 [00:02<00:00, 19.49it/s]
generating negative factsheets: 100%|██████████| 23/23 [00:05<00:00,  4.43it/s]
 86%|████████▌ | 6/7 [00:43<00:07,  7.73s/it]
erating negative factsheets:   0%|          | 0/30 [00:00<?, ?it/s]
erating negative factsheets:   3%|▎         | 1/30 [00:01<00:40,  1.38s/it]
erating negative factsheets:  13%|█▎        | 4/30 [00:01<00:07,  3.46it/s]
erating negative factsheets:  33%|███▎      | 10/30 [00:01<00:01, 10.03it/s]
erating negative factsheets:  53%|█████▎    | 16/30 [00:01<00:00, 16.82it/s]
erating negative factsheets:  70%|███████   | 21/30 [00:01<00:00, 20.22it/s]
erating negative factsheets:  83%|████████▎ | 25/30 [00:02<00:00, 11.33it/s]
generating negative factsheets: 100%|██████████| 30/30 [00:03<00:00,  9.57it/s]
100%|██████████| 7/7 [00:47<00:00,  6.75s/it]

In [824]:
val_nlq_rows=[]
for query, nlqs in query_dict.items():
    val_nlq_rows.append({'query':query,'nlq':nlqs[1]})

In [825]:
val_nlq_df=pd.DataFrame(val_nlq_rows)

In [827]:
val_nlq_df.to_pickle('../synthetic_data/val_nlq_df.pkl')

In [1446]:
train_triplets_df[train_triplets_df['query'].apply(lambda x:'Technology' in x[0])].iloc[2000:2050]

,query,positive,negative,split,qid,pid,nid
417444,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** EduTech Innovations \n**Web...,train,380,11972,28548
417445,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** RoboTech Systems **Website:...,train,380,11972,28581
417446,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** Urban Mobility Systems \n**...,train,380,11972,28552
417447,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** CloudSync Solutions \n**Web...,train,380,11972,28559
417448,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** AeroDynamics Corp **Website...,train,380,11972,28549
417449,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** CloudWave Systems **Website...,train,380,11972,28574
417450,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** MedTech Solutions \n**Websi...,train,380,11972,28584
417451,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** AutoTech Innovations **Webs...,train,380,11972,28561
417452,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** CleanEnergy Solutions \n**W...,train,380,11972,28596
417453,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** MedTech Solutions **Website...,train,380,11972,28600
417454,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** SkyNet Solutions **Website:...,train,380,11972,28575
417455,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** DataSecure Systems \n**Webs...,train,380,11972,28566
417456,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** FinTech Innovations \n**Web...,train,380,11972,28567
417457,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** GreenWave Energy **Website:...,train,380,11972,28569
417458,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** QuantumCompute Labs \n**Web...,train,380,11972,28597
417459,"(Technology Used, 5G technology)",* * astrome company fact sheet * * \n\n * * 1 ...,**Company Name:** GreenEnergy Innovations **W...,train,380,11972,28562
417460,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** QuantumCompute Labs \n**Web...,train,380,11973,28597
417461,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** SmartHome Innovations **Web...,train,380,11973,28601
417462,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** EduTech Innovations \n**Web...,train,380,11973,28548
417463,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** SmartGrid Solutions **Websi...,train,380,11973,28576
417464,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** CleanTech Innovations **Web...,train,380,11973,28573
417465,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** EduTech Innovations **Websi...,train,380,11973,28599
417466,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** UrbanMobility Solutions **W...,train,380,11973,28547
417467,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** DataViz Analytics **Website...,train,380,11973,28568
417468,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** BioTech Labs **Website:** b...,train,380,11973,28546
417469,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** FinTech Solutions **Website...,train,380,11973,28593
417470,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** AeroTech Innovations \n**We...,train,380,11973,28582
417471,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** CloudLink Systems **Website...,train,380,11973,28545
417472,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** AutoTech Innovations **Webs...,train,380,11973,28561
417473,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** HealthTech Innovations \n**...,train,380,11973,28577
417474,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** RetailTech Systems \n**Webs...,train,380,11973,28590
417475,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** MedTech Solutions \n**Websi...,train,380,11973,28584
417476,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** FinTech Innovations \n**Web...,train,380,11973,28567
417477,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** SmartHome Innovations **Web...,train,380,11973,28595
417478,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** CloudSync Solutions \n**Web...,train,380,11973,28559
417479,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** MedTech Innovations **Websi...,train,380,11973,28598
417480,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** DigiHealth Systems **Websit...,train,380,11973,28579
417481,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** FinTech Innovations **Websi...,train,380,11973,28551
417482,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** AeroDynamics Corp **Website...,train,380,11973,28592
417483,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** GreenFleet Logistics \n**We...,train,380,11973,28565
417484,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** SkyNet Solutions **Website:...,train,380,11973,28575
417485,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** MedTech Solutions **Website...,train,380,11973,28600
417486,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** RoboTech Systems **Website:...,train,380,11973,28581
417487,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** UrbanMobility Solutions **W...,train,380,11973,28587
417488,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** SolarGrid Innovations \n**W...,train,380,11973,28554
417489,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** FiberWave Networks **Websit...,train,380,11973,28558
417490,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** CloudWave Systems **Website...,train,380,11973,28574
417491,"(Technology Used, 5G technology)",* * the company company fact sheet * * \n\n * ...,**Company Name:** AgriTech Solutions **Websit...,train,380,11973,28591
417492,"(Technology Used, 5G technology)",* * kofre company fact sheet * * \n\n * * comp...,**Company Name:** BioTech Labs **Website:** b...,train,380,11974,28546
417493,"(Technology Used, 5G technology)",* * kofre company fact sheet * * \n\n * * comp...,**Company Name:** SmartHome Innovations **Web...,train,380,11974,28595

In [1445]:
print(train_triplets_df[train_triplets_df['query'].apply(lambda x:'Technology' in x[0])].iloc[2010].negative)

**Company Name:** SkyNet Solutions  **Website:** skynetsolutions.com  **Industry:** Satellite Communication  **Target Audience:** Global enterprises requiring satellite data services  **Products & Services:**  - SkyConnect: Satellite-based communication network  - SkyData: High-speed satellite internet service  **Unique Selling Propositions (USPs) & Key Differentiators:**  - Global coverage with low latency  - Robust network resilience in remote areas  **Business Model:** B2B Subscription  **Technology Used:** Utilizes satellite communication technologies and advanced signal processing. Their infrastructure is based on geostationary and low-earth orbit satellites.  **Revenue Model:** Subscription-based with tiered pricing for bandwidth usage  **Competitive Landscape:** Competes with HughesNet, Viasat, and other satellite internet providers

In [1450]:
# train_triplets_df

In [1452]:
val_triplets_df

,query,positive,negative,split,qid,pid,nid
0,"(Business Model, B2B)",* * company fact sheet : rsi ngd group of comp...,* * company name :* * colter ventures \n\n * *...,val,0,0,2604
1,"(Business Model, B2B)",* * company fact sheet : rsi ngd group of comp...,* * the company fact sheet * * \n\n * * compan...,val,0,0,2605
2,"(Business Model, B2B)",* * company fact sheet : rsi ngd group of comp...,* * company fact sheet : wy group * * \n\n * *...,val,0,0,2606
3,"(Business Model, B2B)",* * company fact sheet : rsi ngd group of comp...,**Company Name:** PetCare **Website:** petcar...,val,0,0,2607
4,"(Business Model, B2B)",* * company fact sheet : rsi ngd group of comp...,**Company Name:** Appetito **Website:** appet...,val,0,0,2608
...,...,...,...,...,...,...,...
86513,"(Technology Used, Wearable technology)",* * company fact sheet : ftsame * * \n\n * * 1...,**Company Name:** AgriTech Innovations \n**We...,val,408,2603,20011
86514,"(Technology Used, Wearable technology)",* * company fact sheet : ftsame * * \n\n * * 1...,**Company Name:** TravelTech Innovations \n**...,val,408,2603,19989
86515,"(Technology Used, Wearable technology)",* * company fact sheet : ftsame * * \n\n * * 1...,**Company Name:** UrbanTech Innovations \n**W...,val,408,2603,20007
86516,"(Technology Used, Wearable technology)",* * company fact sheet : ftsame * * \n\n * * 1...,**Company Name:** RetailTech Solutions \n**We...,val,408,2603,20010
86517,"(Technology Used, Wearable technology)",* * company fact sheet : ftsame * * \n\n * * 1...,**Company Name:** CyberTech Innovations \n**W...,val,408,2603,19994