In [2]:
# from colbert.infra import Run, RunConfig, ColBERTConfig
# from colbert import Indexer


# with Run().context(RunConfig(nranks=1, experiment="run_1741616267_evaluation")):

#     config = ColBERTConfig(
#         nbits=2,
#         root="./experiments/colbert_aspect_training/none/run_1741616267",
#         index_bsize=4
#     )

#     indexer = Indexer(checkpoint="./experiments/colbert_aspect_training/none/run_1741616267/checkpoints/colbert-best", 
#                       config=config)
#     indexer.index(name="run_1741616267.val.nbits=2",
#                   # collection="./experiments/colbert_aspect_training/run_1741616267/data/val/corpus.train.colbert.tsv",
#                   collection="./experiments/colbert_aspect_training/run_1741231665/data/val/corpus.train.colbert.tsv",
#                   overwrite=True)

## Eval Procedure

Index the entire collection from all_labelled_pairs into the index 

Search across all the queries 

Now map the positives from all the sets 

Now calculate precision top 10,50,100,500

In [1]:
import os

In [3]:
## creating one collection file with all the collections

import pandas as pd
all_labelled_pairs=pd.read_pickle('/home/ec2-user/SageMaker/data/labelled_pairs.all.pkl')

In [4]:
all_labelled_pairs['collection']=all_labelled_pairs['collection'].apply(lambda x:x.replace('\t',' ').replace('\n',' '))

In [5]:
all_labelled_pairs

,actual_query,aspect,collection,label
0,Artificial Intelligence,Industry,"Okay, here's the company fact sheet for Empowe...",1
1,Artificial Intelligence,Industry,Here's the KNS Technologies fact sheet based o...,1
2,Artificial Intelligence,Industry,"Okay, here's a company fact sheet for hi.guru ...",1
3,Artificial Intelligence,Industry,Here's a fact sheet for Lanchi Ventures based ...,1
4,Artificial Intelligence,Industry,"Here's the company fact sheet for nGrow.ai, ba...",1
...,...,...,...,...
54135479,Interpretation Services,Product/Service,"Okay, here's the Levay Mack Insurance Group fa...",0
54135480,Interpretation Services,Product/Service,"Okay, here's the company fact sheet for Marrio...",0
54135481,Interpretation Services,Product/Service,Here's a company fact sheet for NiceMaple base...,0
54135482,Interpretation Services,Product/Service,"Okay, here's the final company fact sheet for ...",0
54135483,Interpretation Services,Product/Service,"Here's the Shea Yeleen company fact sheet, bas...",0

In [ ]:
all_labelled_pairs['query']=all_labelled_pairs.apply(lambda x:f"{x['aspect']} - {x['actual_query']}",axis=1)

In [1]:
import os
import pandas as pd
### bringing it to o the same format as all other collections
if not os.path.exists('../data/all_collection.tsv'):
    all_collections=all_labelled_pairs[['collection']].drop_duplicates()
    all_collections['collection']=all_collections['collection'].apply(lambda x:x.replace('\t',' ').replace('\n',' '))
    all_collections['id']=list(range(len(all_collections)))
    all_collections=all_collections[['id','collection']]
    all_collections.to_csv('../data/all_collection.tsv',sep='\t',header=None,index=False)
else:
    print('reading collections')
    all_collections=pd.read_csv('../data/all_collection.tsv',sep='\t',header=None,index_col=None)

reading collections

In [6]:
all_collections.loc[6,1]

'Okay, here\'s the final fact sheet for SP Tech Solutions based on our analysis of their website, sptech.pl.  Keep in mind that the website is currently under construction, so this fact sheet is limited by the available information.  **SP Tech Solutions Fact Sheet**  **Company Name:** SP Tech Solutions sp. z o.o.  **Website:** sptech.pl  **Industry:** Railway Technology  **Target Audience:** Railway companies and organizations  **Products/Services:**  The company develops technological solutions for the railway industry, focusing on automation, AI, and ecological transformation.  However, specific product details are unavailable because the website\'s product pages are currently under construction.  **Unique Selling Propositions (USPs) and Key Differentiators:**  Cannot be determined at this time due to the website\'s incomplete state.  **Business Model:** B2B (Business-to-Business), providing technology solutions and services to the railway industry.  **Technology Used:** The company mentions using "modern IT technologies" and algorithms, but specific technologies are not detailed.  **Revenue Model:**  Likely project-based or licensing fees for their railway technology solutions.  **Competitive Landscape:**  Requires further external research.   **Overall Assessment:**  SP Tech Solutions appears to be a Polish company operating in the railway technology sector.  Their stated mission focuses on leveraging AI and automation to improve railway efficiency and sustainability.  However, a comprehensive assessment is currently impossible due to the website\'s under-construction status.  A follow-up analysis should be conducted once the website is fully operational and provides details on their specific products and services.  This will allow for a more accurate assessment of their USPs, competitive positioning, and overall market potential.'

In [ ]:
**Company Name:** Empower Social (Inferred from domain name)  **Website:** empower.social  **Products & Services:** Empower offers a suite of digital marketing tools and services, including:  * **Empower Marketing Platform:** A centralized platform leveraging customer data for personalized marketing.  Includes real-time account manager support. * **Empower Mail:** A platform for email marketing campaign creation, sending, and analysis. * **Managed Services:**  IT infrastructure services encompassing performance optimization and security enhancements. * **Intelligence & Reporting:** Data analytics services transforming raw data into actionable insights. * **Digital Data Integration:** Services connecting and optimizing data across various platforms.  **Industry:** Digital Marketing, SaaS (Inferred)  **Target Audience:**  The website doesn't explicitly define its target audience, but based on the offerings, it's likely businesses of various sizes requiring digital marketing and data analytics support.  Further research is needed to confirm this.  **Unique Selling Propositions (USPs) & Key Differentiators:**  The website doesn't explicitly highlight USPs or key differentiators.  More investigation is required to identify what sets Empower apart from competitors.  **Business Model:** SaaS (Software as a Service), inferred from the offered services and the likely subscription-based revenue model.  **Technology Used:** The website mentions the use of AI and advanced analytics, but specific technologies aren't detailed.  **Revenue Model:**  Likely subscription-based or a freemium model, typical for SaaS companies.  Pricing information is unavailable on the website.  **Competitive Landscape:**  No competitors are mentioned on the website.  Further market research is necessary to identify key competitors.   **Overall Assessment:** Empower Social appears to be a SaaS company offering a comprehensive suite of digital marketing tools and services.  However, crucial information regarding their USPs, target audience specifics, pricing, and competitive landscape is missing from their website and requires further investigation.  This fact sheet provides a preliminary overview, and additional research is strongly recommended before making any investment decisions.
**Company Name:** SP Tech Solutions sp. z o.o.  **Website:** sptech.pl  **Industry:** Railway Technology  **Target Audience:** Railway companies and organizations  **Products/Services:**  The company develops technological solutions for the railway industry, focusing on automation, AI, and ecological transformation.  However, specific product details are unavailable because the website\'s product pages are currently under construction.  **Unique Selling Propositions (USPs) and Key Differentiators:**  Cannot be determined at this time due to the website\'s incomplete state.  **Business Model:** B2B (Business-to-Business), providing technology solutions and services to the railway industry.  **Technology Used:** The company mentions using "modern IT technologies" and algorithms, but specific technologies are not detailed.  **Revenue Model:**  Likely project-based or licensing fees for their railway technology solutions.  **Competitive Landscape:**  Requires further external research.   **Overall Assessment:**  SP Tech Solutions appears to be a Polish company operating in the railway technology sector.  Their stated mission focuses on leveraging AI and automation to improve railway efficiency and sustainability.  However, a comprehensive assessment is currently impossible due to the website\'s under-construction status.  A follow-up analysis should be conducted once the website is fully operational and provides details on their specific products and services.  This will allow for a more accurate assessment of their USPs, competitive positioning, and overall market potential.

In [3]:

if not os.path.exists('../data/all_queries.tsv'):
    all_queries=all_labelled_pairs[['query']].drop_duplicates()
    all_queries['id']=list(range(len(all_queries)))
    all_queries=all_queries[['id','query']]
    all_queries.to_csv('../data/all_queries.tsv',sep='\t',header=None,index=False)
else:
    print('reading query')
    all_queries=pd.read_csv('../data/all_queries.tsv',sep='\t',header=None,index_col=None)

reading query

In [4]:
all_queries

         0                                          1
0        0         Industry - Artificial Intelligence
1        1                Industry - Machine Learning
2        2                   Industry - Cybersecurity
3        3                 Industry - Cloud Computing
4        4                      Industry - Blockchain
...    ...                                        ...
1052  1052         Product/Service - Testing Services
1053  1053   Product/Service - Certification Services
1054  1054  Product/Service - Event Planning Services
1055  1055     Product/Service - Translation Services
1056  1056  Product/Service - Interpretation Services

[1057 rows x 2 columns]

In [5]:
import json



def read_jsonl(file_path):
    """
    Read a JSONL file and return a list of parsed JSON objects.
    
    Args:
        file_path (str): Path to the JSONL file
        
    Returns:
        list: List of parsed JSON objects
    """
    data = []
    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            if line.strip():  # Skip empty lines
                data.append(json.loads(line))
    return data


# file_path = "./experiments/colbert_aspect_training/run_1741616267/data/train/triples.train.colbert.jsonl"
# # file_path= ''
# try:
#     results = read_jsonl(file_path)
#     print(f"Successfully loaded {len(results)} records from JSONL file")
    
#     # Example: Print the first item (if available)
#     if results:
#         print("First item:", results[0])
# except FileNotFoundError:
#     print(f"Error: File {file_path} not found")
# except json.JSONDecodeError as e:
#     print(f"Error decoding JSON: {e}")

In [6]:
import pandas as pd
rankings=pd.read_csv('/home/ec2-user/SageMaker/ColBERT/experiments/colbert-ir/colbertv2.0/colbert_searcher/2025-03/13/05.49.54/rankings.colbert.vanilla.all.ranking.tsv',
                     header=None,index_col=None,sep='\t')

In [7]:
rankings.columns=['qid','doc_id','rank','score']

In [8]:
ranking_collection=pd.read_csv('../data/all_collection.tsv',
                              sep='\t',index_col=None,header=None)
ranking_queries=pd.read_csv('../data/all_queries.tsv',
                           sep='\t',index_col=None,header=None)

In [9]:
ranking_collection.columns=['doc_id','collection']
ranking_queries.columns=['qid','query']

In [10]:
rankings=rankings.merge(ranking_collection)
rankings=rankings.merge(ranking_queries)

In [10]:
rankings

,qid,doc_id,rank,score,collection,query
0,0,5064,1,19.796875,"Okay, here's the final company fact sheet for ...",Industry - Artificial Intelligence
1,0,3686,2,19.781250,Here's the company fact sheet for Nothing Arti...,Industry - Artificial Intelligence
2,0,1757,3,19.468750,"Okay, here's the Relari.ai fact sheet based on...",Industry - Artificial Intelligence
3,0,3793,4,19.203125,Here's the EyeLevel.ai company fact sheet base...,Industry - Artificial Intelligence
4,0,1189,5,19.187500,Here's the company fact sheet for AI Innovatio...,Industry - Artificial Intelligence
...,...,...,...,...,...,...
1056995,1056,2202,996,13.398438,Here's the Cape Analytics company fact sheet b...,Product/Service - Interpretation Services
1056996,1056,1294,997,13.335938,Here's a company fact sheet for Veil.AI based ...,Product/Service - Interpretation Services
1056997,1056,11614,998,13.320312,"Okay, here's the final RiverZen Health company...",Product/Service - Interpretation Services
1056998,1056,30887,999,13.320312,Here's the Reward360 company fact sheet based ...,Product/Service - Interpretation Services
1056999,1056,2899,1000,13.312500,Here's the Lionize.ai company fact sheet based...,Product/Service - Interpretation Services

In [11]:
train_triples_path="./experiments/colbert_aspect_training/run_1741616267/data/train/triples.train.colbert.jsonl"
val_triples_path="./experiments/colbert_aspect_training/run_1741616267/data/val/triples.train.colbert.jsonl"
test_triples_path="./experiments/colbert_aspect_training/run_1741616267/data/test/triples.train.colbert.jsonl"


train_queries_path="./experiments/colbert_aspect_training/run_1741616267/data/train/queries.train.colbert.tsv"
val_queries_path="./experiments/colbert_aspect_training/run_1741616267/data/val/queries.train.colbert.tsv"
test_queries_path="./experiments/colbert_aspect_training/run_1741616267/data/test/queries.train.colbert.tsv"



train_collections_path="./experiments/colbert_aspect_training/run_1741616267/data/train/corpus.train.colbert.tsv"
val_collections_path="./experiments/colbert_aspect_training/run_1741616267/data/val/corpus.train.colbert.tsv"
test_collections_path="./experiments/colbert_aspect_training/run_1741616267/data/test/corpus.train.colbert.tsv"

In [12]:
train_queries=pd.read_csv(train_queries_path,sep='\t',header=None,index_col=None)
val_queries=pd.read_csv(val_queries_path,sep='\t',header=None,index_col=None)
test_queries=pd.read_csv(test_queries_path,sep='\t',header=None,index_col=None)

In [13]:
train_queries.columns=['qid','query']
val_queries.columns=['qid','query']
test_queries.columns=['qid','query']

In [14]:
train_collections=pd.read_csv(train_collections_path,sep='\t',header=None,index_col=None)
val_collections=pd.read_csv(val_collections_path,sep='\t',header=None,index_col=None)
test_collections=pd.read_csv(test_collections_path,sep='\t',header=None,index_col=None)

In [15]:
train_collections.columns=['doc_id','collection']
val_collections.columns=['doc_id','collection']
test_collections.columns=['doc_id','collection']

In [16]:
val_collections

       doc_id                                         collection
0           0  Okay, here's the final company fact sheet for ...
1           1  Here's the company fact sheet for Borderless C...
2           2  Okay, here's the True Linkswear company fact s...
3           3  Okay, here's the final company fact sheet for ...
4           4  Okay, here's the final fact sheet for Mount Ca...
...       ...                                                ...
51533   51533  Here's a company fact sheet for Like Air Snack...
51534   51534  Okay, here's the final company fact sheet for ...
51535   51535  Okay, here's the Dovetail fact sheet based on ...
51536   51536  Okay, here's the final fact sheet for Unutilit...
51537   51537  Here's the Pinnacle Experiential Marketing com...

[51538 rows x 2 columns]

In [17]:
train_triples=read_jsonl(train_triples_path)
val_triples=read_jsonl(val_triples_path)
test_triples=read_jsonl(test_triples_path)

In [18]:
val_triples_df=pd.DataFrame(val_triples, columns=['qid','pid','nid'])
train_triples_df=pd.DataFrame(train_triples, columns=['qid','pid','nid'])
test_triples_df=pd.DataFrame(test_triples, columns=['qid','pid','nid'])

In [19]:
test_triples_df_pos=test_triples_df[['qid','pid']].drop_duplicates()
train_triples_df_pos=train_triples_df[['qid','pid']].drop_duplicates()
val_triples_df_pos=val_triples_df[['qid','pid']].drop_duplicates()

In [20]:
test_triples_df_pos=test_triples_df_pos.merge(test_queries)

train_triples_df_pos=train_triples_df_pos.merge(test_queries)
val_triples_df_pos=val_triples_df_pos.merge(test_queries)

In [21]:
test_triples_df_pos=test_triples_df_pos.merge(test_collections.rename(columns={'doc_id':'pid'}))

train_triples_df_pos=train_triples_df_pos.merge(train_collections.rename(columns={'doc_id':'pid'}))
val_triples_df_pos=val_triples_df_pos.merge(val_collections.rename(columns={'doc_id':'pid'}))

In [22]:
val_triples_df_pos['set']='val'
train_triples_df_pos['set']='train'

test_triples_df_pos['set']='test'

In [23]:
train_triples_df_pos

,qid,pid,query,collection,set
0,526,25817,Revenue Model - Flash Sales Model,Here's the Twidlee company fact sheet based on...,train
1,55,34430,Consumer Segment - Advertisers,Here's the company fact sheet for Promise Medi...,train
2,836,28036,Industry - Social Media Tech,"Okay, here's the ZoomSphere company fact sheet...",train
3,806,28055,Consumer Segment - Growth Hackers,Here's the TryLeap AI company fact sheet based...,train
4,415,45380,Product/Service - Water Purification Tech,"Okay, here's the final fact sheet for Innocorp...",train
...,...,...,...,...,...
91375,738,31372,Revenue Model - Certification Exam Fees,Here's the Diversify Consult company fact shee...,train
91376,93,8401,Consumer Segment - Animal Enthusiasts,Here's the InvoCare fact sheet based on the in...,train
91377,740,45950,Customer Industry - Digital Payments industry,Here's the company fact sheet for Xpress Super...,train
91378,455,50287,Customer Industry - Ride Sharing industry,Here's the QUp World company fact sheet based ...,train
91379,694,8331,Consumer Segment - Photographers,"Here's the final Pond5 Company Fact Sheet, bas...",train

In [24]:
test_triples_df_pos

,qid,pid,query,collection,set
0,558,42707,Revenue Model - Merchant Discount Rate (MDR),Here's the company fact sheet for National Pay...,test
1,582,29836,Industry - Printing Industry,"Okay, here's the final company fact sheet for ...",test
2,306,8490,Revenue Model - Transaction Fees,"Okay, here's the final Keeros AB company fact ...",test
3,59,5162,Product/Service - Industrial Automation,Here's a company fact sheet for Inspire Automa...,test
4,878,29173,Industry - Gig Economy Platforms,Here's the GigSmart company fact sheet based o...,test
...,...,...,...,...,...
33107,181,25041,Consumer Segment - Energy Companies,Here's the Cranmore Partners fact sheet based ...,test
33108,522,47080,Revenue Model - Revenue from Hardware Sales,Here's the Snocom company fact sheet based on ...,test
33109,150,851,Customer Industry - Real Estate industry,Here's a company fact sheet for Rosano Capital...,test
33110,42,13823,Consumer Segment - Sales Professionals,"Here's the final Slater Consult fact sheet, ba...",test
33111,881,21784,Consumer Segment - Filmmakers,Here's the Lightworks Software Company Fact Sh...,test

In [25]:
val_triples_df_pos

,qid,pid,query,collection,set
0,141,19226,Consumer Segment - Artists,Here's the Jansen Art Center fact sheet based ...,val
1,12,13820,Revenue Model - E-commerce Direct Sales,"Okay, here's the final company fact sheet for ...",val
2,496,33288,Product/Service - Generative AI,Here's the Gizzmo.ai company fact sheet based ...,val
3,663,18751,Product/Service - DeFi Platforms,"Okay, here's the Finceptor company fact sheet ...",val
4,429,50548,Consumer Segment - Fitness Professionals,Here's the company fact sheet for Phoenix Capi...,val
...,...,...,...,...,...
16615,1056,15677,Industry - Music Tech,Here's the ADA Music company fact sheet based ...,val
16616,1056,32093,Industry - Music Tech,"Here's a company fact sheet for Session42, bas...",val
16617,1056,34906,Industry - Music Tech,"Okay, here's the final company fact sheet for ...",val
16618,1056,40568,Industry - Music Tech,"Okay, here's the company fact sheet for SSR Mu...",val
16619,1056,43524,Industry - Music Tech,Here's the company fact sheet for Bickerstaff ...,val

In [26]:
if not os.path.exists('../data/all_positives.tsv'):
    all_labelled_positives=all_labelled_pairs[all_labelled_pairs.label==1]
else:
    all_labelled_positives=pd.read_csv('../data/all_positives.tsv',sep='\t',header=None,index_col=None)

In [27]:
all_labelled_positives

,0,1,2,3,4
0,Artificial Intelligence,Industry,"Okay, here's the company fact sheet for Empowe...",1,Industry - Artificial Intelligence
1,Artificial Intelligence,Industry,Here's the KNS Technologies fact sheet based o...,1,Industry - Artificial Intelligence
2,Artificial Intelligence,Industry,"Okay, here's a company fact sheet for hi.guru ...",1,Industry - Artificial Intelligence
3,Artificial Intelligence,Industry,Here's a fact sheet for Lanchi Ventures based ...,1,Industry - Artificial Intelligence
4,Artificial Intelligence,Industry,"Here's the company fact sheet for nGrow.ai, ba...",1,Industry - Artificial Intelligence
...,...,...,...,...,...
825960,Interpretation Services,Product/Service,Here's the Currency Remit App fact sheet based...,1,Product/Service - Interpretation Services
825961,Interpretation Services,Product/Service,"Here's a company fact sheet for Kmong.com, bas...",1,Product/Service - Interpretation Services
825962,Interpretation Services,Product/Service,"Here's a company fact sheet for Shownotes.io, ...",1,Product/Service - Interpretation Services
825963,Interpretation Services,Product/Service,"Here's a company fact sheet for Voccent, based...",1,Product/Service - Interpretation Services
825964,Interpretation Services,Product/Service,Here's a company fact sheet for Foule Factory/...,1,Product/Service - Interpretation Services

In [28]:
all_labelled_positives.columns=['actual_query','aspect','collection','label','query']

In [29]:
all_labelled_positives

,actual_query,aspect,collection,label,query
0,Artificial Intelligence,Industry,"Okay, here's the company fact sheet for Empowe...",1,Industry - Artificial Intelligence
1,Artificial Intelligence,Industry,Here's the KNS Technologies fact sheet based o...,1,Industry - Artificial Intelligence
2,Artificial Intelligence,Industry,"Okay, here's a company fact sheet for hi.guru ...",1,Industry - Artificial Intelligence
3,Artificial Intelligence,Industry,Here's a fact sheet for Lanchi Ventures based ...,1,Industry - Artificial Intelligence
4,Artificial Intelligence,Industry,"Here's the company fact sheet for nGrow.ai, ba...",1,Industry - Artificial Intelligence
...,...,...,...,...,...
825960,Interpretation Services,Product/Service,Here's the Currency Remit App fact sheet based...,1,Product/Service - Interpretation Services
825961,Interpretation Services,Product/Service,"Here's a company fact sheet for Kmong.com, bas...",1,Product/Service - Interpretation Services
825962,Interpretation Services,Product/Service,"Here's a company fact sheet for Shownotes.io, ...",1,Product/Service - Interpretation Services
825963,Interpretation Services,Product/Service,"Here's a company fact sheet for Voccent, based...",1,Product/Service - Interpretation Services
825964,Interpretation Services,Product/Service,Here's a company fact sheet for Foule Factory/...,1,Product/Service - Interpretation Services

In [30]:
overall_set_positives=all_labelled_positives[['query','collection']].drop_duplicates()
overall_set_positives['set_z']='unsampled_positive'

In [31]:
overall_set_positives

,query,collection,set_z
0,Industry - Artificial Intelligence,"Okay, here's the company fact sheet for Empowe...",unsampled_positive
1,Industry - Artificial Intelligence,Here's the KNS Technologies fact sheet based o...,unsampled_positive
2,Industry - Artificial Intelligence,"Okay, here's a company fact sheet for hi.guru ...",unsampled_positive
3,Industry - Artificial Intelligence,Here's a fact sheet for Lanchi Ventures based ...,unsampled_positive
4,Industry - Artificial Intelligence,"Here's the company fact sheet for nGrow.ai, ba...",unsampled_positive
...,...,...,...
825960,Product/Service - Interpretation Services,Here's the Currency Remit App fact sheet based...,unsampled_positive
825961,Product/Service - Interpretation Services,"Here's a company fact sheet for Kmong.com, bas...",unsampled_positive
825962,Product/Service - Interpretation Services,"Here's a company fact sheet for Shownotes.io, ...",unsampled_positive
825963,Product/Service - Interpretation Services,"Here's a company fact sheet for Voccent, based...",unsampled_positive
825964,Product/Service - Interpretation Services,Here's a company fact sheet for Foule Factory/...,unsampled_positive

In [32]:
rankings

,qid,doc_id,rank,score,collection,query
0,0,5064,1,19.796875,"Okay, here's the final company fact sheet for ...",Industry - Artificial Intelligence
1,0,3686,2,19.781250,Here's the company fact sheet for Nothing Arti...,Industry - Artificial Intelligence
2,0,1757,3,19.468750,"Okay, here's the Relari.ai fact sheet based on...",Industry - Artificial Intelligence
3,0,3793,4,19.203125,Here's the EyeLevel.ai company fact sheet base...,Industry - Artificial Intelligence
4,0,1189,5,19.187500,Here's the company fact sheet for AI Innovatio...,Industry - Artificial Intelligence
...,...,...,...,...,...,...
1056995,1056,2202,996,13.398438,Here's the Cape Analytics company fact sheet b...,Product/Service - Interpretation Services
1056996,1056,1294,997,13.335938,Here's a company fact sheet for Veil.AI based ...,Product/Service - Interpretation Services
1056997,1056,11614,998,13.320312,"Okay, here's the final RiverZen Health company...",Product/Service - Interpretation Services
1056998,1056,30887,999,13.320312,Here's the Reward360 company fact sheet based ...,Product/Service - Interpretation Services
1056999,1056,2899,1000,13.312500,Here's the Lionize.ai company fact sheet based...,Product/Service - Interpretation Services

In [33]:
## doing in this order so that we can laterselect the set in this precedence
rankings_set_div=rankings.merge(train_triples_df_pos[['collection','query','set']],how='left',on=['collection','query'])
rankings_set_div=rankings_set_div.merge(test_triples_df_pos[['collection','query','set']],how='left',on=['collection','query'])
rankings_set_div=rankings_set_div.merge(val_triples_df_pos[['collection','query','set']],how='left',on=['collection','query'])

In [34]:
rankings_set_div=rankings_set_div.merge(overall_set_positives,on=['collection','query'],how='left')

In [35]:
# rankings_set_div.set_x.unique()
doc="""Okay, here\'s the company fact sheet for SoftBank Vision Fund based on our analysis of their website, visionfund.com:  **Company Fact Sheet: SoftBank Vision Fund**  **1. Products, Services, and Offerings:**  SoftBank Vision Fund doesn\'t offer products or services directly to consumers or businesses.  Its core offering is venture capital investment in AI-focused companies.  They invest across the entire AI technology stack, from hardware (like semiconductors) to software infrastructure and applications.  **2. Industry and Target Audience:** The industry is venture capital and private equity, specifically within the Artificial Intelligence (AI) technology sector.  Their target audience is companies developing AI technologies, particularly those with potential for significant growth and disruption within a "full-stack" AI ecosystem.  **3. Unique Selling Propositions (USPs) and Key Differentiators:**  The fund\'s key differentiator is its focus on investing across the entire AI technology stack, providing comprehensive support to companies at various stages of development.  Their significant financial resources and stated belief in the transformative power of AI also set them apart.  The scale of their investments is a major competitive advantage.  **4. Business Model:** Venture Capital/Private Equity.  The fund invests in promising AI companies and aims to generate returns through the growth and eventual sale or IPO of its portfolio companies.  **5. Technology Used (Optional):** The website doesn\'t specify the internal technologies used by SoftBank Vision Fund.  However, their investment focus clearly indicates expertise in evaluating and understanding AI technologies.  **6. Revenue Model (Optional):** The revenue model is based on capital appreciation of investments in portfolio companies.  Returns are generated through the eventual sale or IPO of these companies.  **7. Competitive Landscape (Optional):** The website doesn\'t directly address competitors.  However, it\'s inferred that SoftBank Vision Fund competes with other large venture capital firms and private equity funds that invest in the AI sector.  Further research would be needed to identify specific competitors.  **Business Model Classification:** Venture Capital/Private Equity (B2B)"""

In [36]:
rankings_set_div.loc[1056996].collection
rankings_set_div.loc[1056996]

qid                                                        1056
doc_id                                                     1294
rank                                                        997
score                                                 13.335938
collection    Here's a company fact sheet for Veil.AI based ...
query                 Product/Service - Interpretation Services
set_x                                                       NaN
set_y                                                       NaN
set                                                         NaN
set_z                                                       NaN
Name: 1056996, dtype: object

In [37]:
doc="""Okay, here's the final Rouvy company fact sheet based on our analysis of their website and some supplementary web searches.  Remember that some information, like their precise technology stack, wasn't explicitly stated and required some inference.  **Rouvy Company Fact Sheet**  **1. Company Overview:** Rouvy is a provider of realistic indoor cycling experiences through a subscription-based app.  They differentiate themselves by offering high-quality video footage of real-world cycling routes from around the globe.  **2. Products & Services:**  Rouvy offers a mobile and desktop application providing virtual cycling routes, structured training plans, and the ability to compete with other users.  The app integrates with various indoor cycling trainers.  **3. Industry & Target Audience:** Rouvy operates within the Fitness Technology and Virtual Reality Fitness industries. Their target audience is primarily cycling enthusiasts and fitness-conscious individuals seeking engaging indoor training options.  **4. Unique Selling Propositions (USPs):**  * **Realistic Routes:** High-quality video footage of actual cycling routes worldwide. * **Structured Workouts:** Training plans designed by professional cyclists. * **Competitive Features:** Ability to race and compete with other users. * **Cross-Platform Availability:** Accessible on various devices (PC, Mac, iOS, Android, Apple TV).  **5. Business Model:**  Direct-to-consumer (B2C) Software as a Service (SaaS).  **6. Revenue Model:** Subscription-based, offering monthly and yearly plans.  A free trial is available.  **7. Technology:** While the specific technology stack isn't publicly available, it likely includes video streaming technology, GPS data integration, and potentially some form of user performance tracking.  **8. Competitive Landscape:** Key competitors include Zwift, TrainerRoad, and Sufferfest.  **9. Financial Information:**  No financial information was readily available on the website.  Further research would be needed to obtain this data.   **Overall Assessment:** Rouvy presents a compelling value proposition within a growing market.  Their focus on realistic visuals and professional training programs differentiates them from competitors.  However, further investigation into their financial performance and market share is necessary for a complete investment assessment."""

In [38]:
overall_set_positives[overall_set_positives.collection==doc]

,query,collection,set_z
15393,Industry - Virtual Reality,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
17167,Industry - Software Development,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
42994,Industry - Direct-to-Consumer (DTC),"Okay, here's the final Rouvy company fact shee...",unsampled_positive
49364,Industry - Subscription Commerce,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
77331,Industry - Streaming Platforms,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
84011,Industry - Sports Tech,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
133646,Business Model - B2C,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
156255,Business Model - Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
191452,Business Model - Software-as-a-Service,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
239429,Business Model - Content Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
241021,Business Model - Membership Model,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
242697,Business Model - Niche Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
270038,Business Model - Self-Service,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
288697,Revenue Model - Monthly Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
297047,Revenue Model - Annual Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
365275,Revenue Model - Pay-per-User Model,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
366150,Revenue Model - User-Based Licensing,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
368624,Revenue Model - Platform Access Fees,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
375354,Revenue Model - Membership Fees,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
378819,Revenue Model - Media Streaming Subscriptions,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
388355,Revenue Model - Tiered Membership Fees,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
458029,Customer Industry - Sports & Fitness industry,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
653924,Consumer Segment - Sports Enthusiasts,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
654686,Consumer Segment - Athletes,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
664443,Consumer Segment - Subscription-based Consumers,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
720939,Product/Service - Streaming Media,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
789879,Technology - Computer Graphics,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
793858,Technology - UI/UX Design,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
796725,Technology - Simulation Software,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
813936,Consumer Segment - Hobbyists,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
814502,Consumer Segment - DIY Enthusiasts,"Okay, here's the final Rouvy company fact shee...",unsampled_positive

In [39]:
train_triples_df_pos.collection.loc[5777]

'Okay, here\'s the company fact sheet for SoftBank Vision Fund based on our analysis of their website, visionfund.com:  **Company Fact Sheet: SoftBank Vision Fund**  **1. Products, Services, and Offerings:**  SoftBank Vision Fund doesn\'t offer products or services directly to consumers or businesses.  Its core offering is venture capital investment in AI-focused companies.  They invest across the entire AI technology stack, from hardware (like semiconductors) to software infrastructure and applications.  **2. Industry and Target Audience:** The industry is venture capital and private equity, specifically within the Artificial Intelligence (AI) technology sector.  Their target audience is companies developing AI technologies, particularly those with potential for significant growth and disruption within a "full-stack" AI ecosystem.  **3. Unique Selling Propositions (USPs) and Key Differentiators:**  The fund\'s key differentiator is its focus on investing across the entire AI technology stack, providing comprehensive support to companies at various stages of development.  Their significant financial resources and stated belief in the transformative power of AI also set them apart.  The scale of their investments is a major competitive advantage.  **4. Business Model:** Venture Capital/Private Equity.  The fund invests in promising AI companies and aims to generate returns through the growth and eventual sale or IPO of its portfolio companies.  **5. Technology Used (Optional):** The website doesn\'t specify the internal technologies used by SoftBank Vision Fund.  However, their investment focus clearly indicates expertise in evaluating and understanding AI technologies.  **6. Revenue Model (Optional):** The revenue model is based on capital appreciation of investments in portfolio companies.  Returns are generated through the eventual sale or IPO of these companies.  **7. Competitive Landscape (Optional):** The website doesn\'t directly address competitors.  However, it\'s inferred that SoftBank Vision Fund competes with other large venture capital firms and private equity funds that invest in the AI sector.  Further research would be needed to identify specific competitors.  **Business Model Classification:** Venture Capital/Private Equity (B2B)'

In [40]:
train_triples_df_pos[train_triples_df_pos.collection==doc]

,qid,pid,query,collection,set
14861,1004,26469,Industry - Streaming Platforms,"Okay, here's the final Rouvy company fact shee...",train
23526,650,26469,Consumer Segment - DIY Enthusiasts,"Okay, here's the final Rouvy company fact shee...",train
65530,868,26469,Consumer Segment - Athletes,"Okay, here's the final Rouvy company fact shee...",train
78778,297,26469,Technology - UI/UX Design,"Okay, here's the final Rouvy company fact shee...",train

In [41]:
overall_set_positives[overall_set_positives.collection==doc]

,query,collection,set_z
15393,Industry - Virtual Reality,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
17167,Industry - Software Development,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
42994,Industry - Direct-to-Consumer (DTC),"Okay, here's the final Rouvy company fact shee...",unsampled_positive
49364,Industry - Subscription Commerce,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
77331,Industry - Streaming Platforms,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
84011,Industry - Sports Tech,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
133646,Business Model - B2C,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
156255,Business Model - Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
191452,Business Model - Software-as-a-Service,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
239429,Business Model - Content Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
241021,Business Model - Membership Model,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
242697,Business Model - Niche Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
270038,Business Model - Self-Service,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
288697,Revenue Model - Monthly Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
297047,Revenue Model - Annual Subscription,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
365275,Revenue Model - Pay-per-User Model,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
366150,Revenue Model - User-Based Licensing,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
368624,Revenue Model - Platform Access Fees,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
375354,Revenue Model - Membership Fees,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
378819,Revenue Model - Media Streaming Subscriptions,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
388355,Revenue Model - Tiered Membership Fees,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
458029,Customer Industry - Sports & Fitness industry,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
653924,Consumer Segment - Sports Enthusiasts,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
654686,Consumer Segment - Athletes,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
664443,Consumer Segment - Subscription-based Consumers,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
720939,Product/Service - Streaming Media,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
789879,Technology - Computer Graphics,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
793858,Technology - UI/UX Design,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
796725,Technology - Simulation Software,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
813936,Consumer Segment - Hobbyists,"Okay, here's the final Rouvy company fact shee...",unsampled_positive
814502,Consumer Segment - DIY Enthusiasts,"Okay, here's the final Rouvy company fact shee...",unsampled_positive

In [42]:
get_first_non_none = lambda str_list: next((s for s in str_list if not pd.isna(s)), None)

In [43]:

rankings_set_div['positive']=rankings_set_div.apply(lambda x:get_first_non_none(
    [x['set'], x['set_x'] , x['set_y'] , x['set_z'] ]),axis=1)

In [44]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive
0,0,5064,1,19.796875,"Okay, here's the final company fact sheet for ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive
1,0,3686,2,19.781250,Here's the company fact sheet for Nothing Arti...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive
2,0,1757,3,19.468750,"Okay, here's the Relari.ai fact sheet based on...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive
3,0,3793,4,19.203125,Here's the EyeLevel.ai company fact sheet base...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive
4,0,1189,5,19.187500,Here's the company fact sheet for AI Innovatio...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive
...,...,...,...,...,...,...,...,...,...,...,...
1056995,1056,2202,996,13.398438,Here's the Cape Analytics company fact sheet b...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056996,1056,1294,997,13.335938,Here's a company fact sheet for Veil.AI based ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056997,1056,11614,998,13.320312,"Okay, here's the final RiverZen Health company...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056998,1056,30887,999,13.320312,Here's the Reward360 company fact sheet based ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056999,1056,2899,1000,13.312500,Here's the Lionize.ai company fact sheet based...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None

In [45]:
cols=['query','collection','set']
actual_number_positives_per_query=pd.concat([train_triples_df_pos[cols],test_triples_df_pos[cols],val_triples_df_pos[cols],
                                             overall_set_positives.rename(columns={'set_z':'set'})[cols]])

In [46]:
actual_number_positives_per_query

,query,collection,set
0,Revenue Model - Flash Sales Model,Here's the Twidlee company fact sheet based on...,train
1,Consumer Segment - Advertisers,Here's the company fact sheet for Promise Medi...,train
2,Industry - Social Media Tech,"Okay, here's the ZoomSphere company fact sheet...",train
3,Consumer Segment - Growth Hackers,Here's the TryLeap AI company fact sheet based...,train
4,Product/Service - Water Purification Tech,"Okay, here's the final fact sheet for Innocorp...",train
...,...,...,...
825960,Product/Service - Interpretation Services,Here's the Currency Remit App fact sheet based...,unsampled_positive
825961,Product/Service - Interpretation Services,"Here's a company fact sheet for Kmong.com, bas...",unsampled_positive
825962,Product/Service - Interpretation Services,"Here's a company fact sheet for Shownotes.io, ...",unsampled_positive
825963,Product/Service - Interpretation Services,"Here's a company fact sheet for Voccent, based...",unsampled_positive
825964,Product/Service - Interpretation Services,Here's a company fact sheet for Foule Factory/...,unsampled_positive

In [47]:
actual_number_positives_per_query.drop_duplicates()

,query,collection,set
0,Revenue Model - Flash Sales Model,Here's the Twidlee company fact sheet based on...,train
1,Consumer Segment - Advertisers,Here's the company fact sheet for Promise Medi...,train
2,Industry - Social Media Tech,"Okay, here's the ZoomSphere company fact sheet...",train
3,Consumer Segment - Growth Hackers,Here's the TryLeap AI company fact sheet based...,train
4,Product/Service - Water Purification Tech,"Okay, here's the final fact sheet for Innocorp...",train
...,...,...,...
825960,Product/Service - Interpretation Services,Here's the Currency Remit App fact sheet based...,unsampled_positive
825961,Product/Service - Interpretation Services,"Here's a company fact sheet for Kmong.com, bas...",unsampled_positive
825962,Product/Service - Interpretation Services,"Here's a company fact sheet for Shownotes.io, ...",unsampled_positive
825963,Product/Service - Interpretation Services,"Here's a company fact sheet for Voccent, based...",unsampled_positive
825964,Product/Service - Interpretation Services,Here's a company fact sheet for Foule Factory/...,unsampled_positive

In [48]:
actual_number_positives_per_query['positives']=actual_number_positives_per_query.groupby(['set','query']).collection.transform('count')

In [49]:
actual_number_positives_per_query=actual_number_positives_per_query[['query','set','positives']].drop_duplicates()

In [50]:
actual_number_positives_per_query

,query,set,positives
0,Revenue Model - Flash Sales Model,train,14
1,Consumer Segment - Advertisers,train,100
2,Industry - Social Media Tech,train,100
3,Consumer Segment - Growth Hackers,train,49
4,Product/Service - Water Purification Tech,train,100
...,...,...,...
823491,Product/Service - Testing Services,unsampled_positive,982
824473,Product/Service - Certification Services,unsampled_positive,551
825024,Product/Service - Event Planning Services,unsampled_positive,497
825521,Product/Service - Translation Services,unsampled_positive,238
825759,Product/Service - Interpretation Services,unsampled_positive,206

In [51]:
actual_number_positives_per_query=actual_number_positives_per_query.rename(columns={'positives':'true_positives'})

In [52]:
actual_number_positives_per_query.loc[actual_number_positives_per_query['set']=='unsampled_positive','set']='total_with_unsampled'

In [53]:
rankings_set_div.loc[rankings_set_div['positive']=='unsampled_positive','positive']='total_with_unsampled'

In [54]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive
0,0,5064,1,19.796875,"Okay, here's the final company fact sheet for ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled
1,0,3686,2,19.781250,Here's the company fact sheet for Nothing Arti...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled
2,0,1757,3,19.468750,"Okay, here's the Relari.ai fact sheet based on...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled
3,0,3793,4,19.203125,Here's the EyeLevel.ai company fact sheet base...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled
4,0,1189,5,19.187500,Here's the company fact sheet for AI Innovatio...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled
...,...,...,...,...,...,...,...,...,...,...,...
1056995,1056,2202,996,13.398438,Here's the Cape Analytics company fact sheet b...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056996,1056,1294,997,13.335938,Here's a company fact sheet for Veil.AI based ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056997,1056,11614,998,13.320312,"Okay, here's the final RiverZen Health company...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056998,1056,30887,999,13.320312,Here's the Reward360 company fact sheet based ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None
1056999,1056,2899,1000,13.312500,Here's the Lionize.ai company fact sheet based...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None

In [55]:
actual_number_positives_per_query

,query,set,true_positives
0,Revenue Model - Flash Sales Model,train,14
1,Consumer Segment - Advertisers,train,100
2,Industry - Social Media Tech,train,100
3,Consumer Segment - Growth Hackers,train,49
4,Product/Service - Water Purification Tech,train,100
...,...,...,...
823491,Product/Service - Testing Services,total_with_unsampled,982
824473,Product/Service - Certification Services,total_with_unsampled,551
825024,Product/Service - Event Planning Services,total_with_unsampled,497
825521,Product/Service - Translation Services,total_with_unsampled,238
825759,Product/Service - Interpretation Services,total_with_unsampled,206

In [56]:
rankings_set_div=rankings_set_div.merge(actual_number_positives_per_query.rename(columns={'set':'positive'}),on=['query','positive'],how='left')

In [57]:
depths=[10,50,100,500]

In [58]:
positives_count={}
per_query_basis={}

for d in depths: 
    ### we need to calculate positives per query at a given depth : why? 
        ## 1. need to know if there is any pattern in low precision queries, 
        ## 2. precision can only be calculated Per query since each query has different number of positives 
    
    per_query_basis[d]=rankings_set_div.groupby('query').apply(lambda x:\
                                                               x[x['rank']<=d]['positive']\
                                                               .value_counts().to_dict()).rename('positives_distribution')\
                                                                .reset_index()
    positives_count[d]=rankings_set_div[rankings_set_div['rank']<=d].positive.value_counts().to_dict()

/tmp/ipykernel_8199/357064111.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  per_query_basis[d]=rankings_set_div.groupby('query').apply(lambda x:\
/tmp/ipykernel_8199/357064111.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  per_query_basis[d]=rankings_set_div.groupby('query').apply(lambda x:\
/tmp/ipykernel_8199/357064111.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  per_query_basis[d]=rankings_set_div.groupby('query').apply(lambda x:\
/tmp/ipykernel_8199/357064111.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  per_query_basis[d]=rankings_set_div.groupby('query').apply(lambda x:\

In [150]:
per_query_basis[100].sample(50)

,query,positives_distribution
1000,Technology - Distributed Ledger,"{'total_with_unsampled': 24, 'train': 11, 'tes..."
635,Industry - Vocational Training,"{'total_with_unsampled': 19, 'train': 7, 'test..."
480,Industry - AI in Agriculture,"{'train': 9, 'val': 2, 'total_with_unsampled':..."
495,Industry - Augmented Reality,"{'train': 24, 'total_with_unsampled': 15, 'val..."
1015,Technology - Infrastructure as Code,"{'train': 9, 'val': 2, 'test': 1}"
227,Consumer Segment - IT Professionals,"{'total_with_unsampled': 32, 'train': 5, 'val'..."
569,Industry - Longevity Science,"{'train': 13, 'val': 3, 'test': 3}"
420,Customer Industry - Mortgage Lenders,"{'total_with_unsampled': 6, 'train': 6, 'test'..."
488,Industry - Aeronautics,"{'total_with_unsampled': 13, 'train': 5, 'test..."
562,Industry - Internet of Things,"{'total_with_unsampled': 7, 'train': 4, 'test'..."
939,Revenue Model - Royalty Stacking,"{'train': 16, 'test': 2, 'val': 1}"
535,Industry - Employee Benefits Tech,"{'total_with_unsampled': 20, 'train': 9, 'test..."
448,Customer Industry - Restaurant Chains,"{'total_with_unsampled': 22, 'train': 3, 'test..."
417,Customer Industry - Mining industry,"{'total_with_unsampled': 24, 'train': 5, 'test..."
795,Product/Service - Smart Farming Equipment,"{'train': 27, 'test': 1, 'val': 1}"
765,Product/Service - Next-Gen Satellites,"{'train': 11, 'val': 1, 'test': 1}"
567,Industry - Live Shopping,{'train': 1}
1056,Technology - Zero-Knowledge Proofs,{}
953,Revenue Model - Tiered Membership Fees,"{'total_with_unsampled': 79, 'test': 2, 'val': 1}"
751,Product/Service - Legal Tech,"{'total_with_unsampled': 33, 'train': 17, 'tes..."
786,Product/Service - Remote Patient Monitoring,"{'train': 11, 'total_with_unsampled': 6, 'val'..."
38,Business Model - Crowdsource Innovation,"{'train': 4, 'val': 1}"
241,Consumer Segment - Loyalty Program Members,"{'total_with_unsampled': 46, 'train': 6, 'val'..."
415,Customer Industry - Microfinance industry,"{'train': 14, 'test': 2, 'val': 1}"
333,Customer Industry - Consumer Electronics industry,"{'total_with_unsampled': 26, 'train': 17, 'val..."
508,Industry - Clinical Trials,"{'total_with_unsampled': 18, 'train': 10, 'tes..."
719,Product/Service - Eco-Friendly Batteries,"{'train': 13, 'test': 2}"
941,Revenue Model - Seat-Based Pricing,"{'train': 3, 'total_with_unsampled': 1}"
367,Customer Industry - FinTech Startups,"{'total_with_unsampled': 45, 'train': 16, 'val..."
836,Revenue Model - Certification Exam Fees,"{'train': 19, 'val': 2, 'test': 1}"
450,Customer Industry - Retail industry,"{'total_with_unsampled': 86, 'test': 3, 'train..."
149,Business Model - Venture Studio,{'train': 7}
8,Business Model - Affiliate Commerce,"{'train': 2, 'total_with_unsampled': 1}"
907,Revenue Model - Outsourced Services,"{'total_with_unsampled': 70, 'train': 2, 'test..."
1025,Technology - NFTs,"{'train': 7, 'total_with_unsampled': 2}"
891,Revenue Model - Loyalty Program Revenue,"{'train': 9, 'test': 1}"
956,Revenue Model - Tokenomics Revenue,"{'train': 8, 'test': 1}"
588,Industry - Pharmaceuticals,"{'total_with_unsampled': 41, 'train': 4, 'val'..."
217,Consumer Segment - Growth Hackers,"{'train': 8, 'val': 2}"
26,Business Model - Circular Economy,"{'total_with_unsampled': 22, 'train': 11, 'tes..."
198,Consumer Segment - Energy Companies,"{'total_with_unsampled': 55, 'train': 4, 'test..."
695,Product/Service - Cloud DevOps,"{'total_with_unsampled': 65, 'train': 10, 'tes..."
50,Business Model - Donation-Based Crowdfunding,"{'total_with_unsampled': 37, 'train': 9, 'test..."
863,Revenue Model - Digital Wallet Fees,"{'train': 3, 'test': 1}"
878,Revenue Model - Grant Funding,"{'total_with_unsampled': 53, 'train': 8, 'test..."
112,Business Model - Pharmacy-as-a-Service,"{'train': 15, 'val': 2, 'test': 2}"
830,Revenue Model - Bandwidth Pricing,{'train': 7}
36,Business Model - Corporate Venture,{}
728,Product/Service - Financial Planning Software,"{'total_with_unsampled': 23, 'train': 4, 'val'..."
225,Consumer Segment - Hotel Managers,"{'total_with_unsampled': 43, 'train': 5, 'test..."

In [ ]:
rankings_set_div

In [129]:
train_triples_df_pos[train_triples_df_pos['query']=='Technology - Voice Assistants'].loc[73700].collection

"Okay, here's the Swoop company fact sheet based on our research.  Keep in mind that some information, particularly regarding revenue model, competitive landscape, and company size, requires further investigation beyond the publicly available information on their website.  **Swoop Company Fact Sheet**  **Company Name:** Swoop  **Products & Services:** Swoop Agents, Swoop Piper,  Direct-to-Consumer (DTC) marketing solutions, Healthcare Provider (HCP) marketing solutions, Television (TV) marketing solutions.  The platform integrates with MyHealthTeam, a large patient-centric social network.  **Industry:** Pharmaceutical and Life Sciences Marketing  **Target Audience:** Pharmaceutical and life sciences companies; patients, healthcare providers (HCPs), and caregivers.  **Unique Selling Propositions (USPs) & Key Differentiators:**  * AI-driven omnichannel marketing * Privacy-compliant (HIPAA-certified, NAI-compliant, compliant with Washington State's My Health My Data Act) * Platform-agnostic * High accuracy in connecting providers and patient populations * Coordinated messaging across channels * Converts fragmented data into actionable insights * Delivers superior audience quality and drives Rx lift   **Business Model:**  B2B SaaS (Inferred based on services offered to pharmaceutical and life sciences companies)  **Technology Used:** AI, data analytics, zero-knowledge methodology  **Revenue Model:**  Subscription-based SaaS (Inferred; requires further investigation for confirmation)  **Competitive Landscape:**  Requires further research.  The website does not explicitly list competitors.  **Company Size & Employee Count:**  Requires further research.  Information not available on the website.   **Overall Assessment:**  Swoop appears to be a promising B2B SaaS company operating in the rapidly growing market of AI-powered healthcare marketing.  Their focus on privacy and omnichannel integration is a significant strength. However, further due diligence is needed to validate the inferred revenue model, identify key competitors, and determine the company's size and financial performance.  This information will be crucial in assessing Swoop's overall investment potential."

In [127]:
train_triples_df_pos[train_triples_df_pos['query']=='Technology - Zero-Knowledge Proofs'].loc[65330].collection

"Here's the final Boxcryptor company fact sheet, incorporating information gathered from their website and simulated web searches:  **Boxcryptor GmbH Company Fact Sheet**  **Company Name:** Boxcryptor GmbH  **Website:** boxcryptor.com  **Industry:** Cybersecurity, Cloud Security, Data Encryption, SaaS  **Target Audience:** Individuals and businesses requiring secure cloud storage solutions compatible with services like Dropbox, Google Drive, and OneDrive.  **Products/Services:**  Zero-knowledge encryption service for cloud storage.  Enables users to encrypt files before uploading to various cloud providers. Offers tiered subscription plans with varying features and storage capacities.  **Unique Selling Propositions (USPs) & Key Differentiators:**  * **Zero-knowledge encryption:** Only the user possesses the decryption key, ensuring data privacy. * **Multi-cloud compatibility:** Seamless integration with popular cloud storage platforms. * **Ease of use:**  Intuitive interface for straightforward encryption and decryption. * **Strong encryption:** Employs AES-256 encryption (inferred from external research; not explicitly stated on the website).  **Business Model:** Software as a Service (SaaS)  **Revenue Model:** Subscription-based, with multiple pricing tiers offering different features and storage limits.  **Technology Used:** AES-256 encryption (inferred from external research), specific key derivation functions are not publicly disclosed.  **Competitive Landscape:** Key competitors include Tresorit, SpiderOak, and Sync.com (based on external research).  A comprehensive competitive analysis would require further investigation.  **Value Proposition:** Boxcryptor offers a user-friendly and secure solution for encrypting and protecting files stored in the cloud, ensuring user privacy and data security across multiple cloud platforms through robust AES-256 encryption and a zero-knowledge architecture."

In [125]:
train_triples_df_pos[train_triples_df_pos['query']=='Technology - Zero-Knowledge Proofs'].loc[47257].collection

"Here's a company fact sheet for Haun Ventures, based on the information gathered from their website and subsequent research:  **Company Fact Sheet: Haun Ventures**  **Company Name:** Haun Ventures  **Description:** Haun Ventures is a venture capital firm focused on investing in early-stage and growth-stage companies within the cryptocurrency and blockchain technology ecosystem.  They manage a $500 million early-stage fund and a $1 billion acceleration fund.  **Industry:** Venture Capital  **Investment Focus:**  Haun Ventures invests across various sectors within the crypto technology stack, including: on-chain gaming, privacy protocols, developer tools, creator tools, zero-knowledge technologies, decentralized finance (DeFi), NFTs, broader crypto projects, and blockchain infrastructure.  **Funding:** * Early-Stage Fund: $500 million * Acceleration Fund: $1 billion  **Target Companies:**  The firm invests in teams building across all layers of the crypto technology stack, at various stages of development.  Specific criteria regarding company size, stage, or other characteristics are not publicly available on their website.  **Products/Services:** Haun Ventures does not offer products or services directly; its core offering is investment capital for promising crypto-focused startups.  **Business Model:** Venture Capital  **Revenue Model:**  Management fees and carried interest (profit sharing) from successful investments.  **Technology Used:** While not explicitly stated, their investments heavily focus on companies utilizing various technologies within the crypto technology stack.  **Competitive Landscape:**  Detailed information on specific competitors and market share requires further research beyond the publicly available information on the Haun Ventures website.  However, it can be inferred that they compete with other venture capital firms investing in the cryptocurrency and blockchain space.   **Overall Value Proposition:** Haun Ventures provides significant capital and expertise to early-stage and growth-stage companies building the future of the internet within the cryptocurrency and blockchain ecosystem.  Their large fund sizes and focus on a rapidly evolving technology sector position them as a key player in this market."

In [124]:
train_triples_df_pos[train_triples_df_pos['query']=='Technology - Zero-Knowledge Proofs'].loc[46553].collection

"Here's the Ockam company fact sheet based on our analysis of their website, ockam.io:  **Ockam Company Fact Sheet**  **Company:** Ockam  **Website:** ockam.io  **Products/Services:** Ockam provides a secure communication layer for applications.  Their core offering includes secure channels and cryptographic protocols, enabling secure connections between applications regardless of location or network.  Specific products mentioned include Ockam Command and various programming libraries.  **Industry/Target Audience:** Ockam targets businesses involved in data integration, streaming data, and database protection. While specific industries aren't explicitly listed, their use cases suggest a focus on companies handling sensitive data across various sectors.  The business model appears to be primarily B2B.  **Unique Selling Propositions (USPs):**  * **Application-level security:** Ockam focuses on building trust and security directly into applications. * **Location-independent secure connections:**  Secure communication is enabled regardless of application location or network infrastructure. * **Developer-friendly approach:**  Ockam aims to simplify secure communication, allowing developers to build secure applications without requiring deep cryptography expertise.  **Business Model:**  The business model appears to be B2B SaaS, inferred from the tiered subscription pricing model observed on their website.  **Technology Used:**  While specific technologies aren't explicitly detailed, Ockam's platform relies heavily on cryptographic protocols and secure channels to achieve its secure communication capabilities.  **Revenue Model:** Subscription-based, with different tiers offering varying features and pricing.  **Competitive Landscape:**  No direct competitors are mentioned on the Ockam website.   This fact sheet provides a concise overview of Ockam based on publicly available information.  Further investigation, including analysis of financial statements (if available) and competitive analysis, would be beneficial for a more comprehensive understanding."

In [164]:
rankings_set_div[rankings_set_div['query']==query_]

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive,true_positives
5000,5,32251,1,16.781250,"Okay, here's the final KamerraCap company fact...",Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5001,5,4479,2,16.609375,"Okay, here's the LDV Capital fact sheet based ...",Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5002,5,640,3,16.546875,Here's the Equator VC fact sheet based on our ...,Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5003,5,22,4,16.500000,Here's the MangoCap company fact sheet based o...,Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5004,5,802,5,16.437500,Here's the Salesforce Ventures fact sheet base...,Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5995,5,26173,996,11.093750,Here's the G-Force Capital fact sheet based on...,Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5996,5,10556,997,11.062500,"Okay, here's the MITA Ventures fact sheet base...",Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5997,5,22627,998,11.007812,"Here's a company fact sheet for Appstean, base...",Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5998,5,19463,999,10.960938,"Okay, here's the final Investtech company fact...",Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN
5999,5,9038,1000,10.929688,"Okay, here's the final InvenCapital fact sheet...",Industry - Internet of Things,NaN,NaN,NaN,NaN,None,NaN

In [178]:
query_='Technology - Voice Assistants'

query_='Industry - Internet of Things'


query_="Industry - Longevity Science"

query_="Industry - Artificial Intelligence"

In [180]:
len(train_triples_df_pos[(train_triples_df_pos['query']==query_) & ((train_triples_df_pos['collection'].str.lower().str.contains('venture')) | (train_triples_df_pos['collection'].str.lower().str.contains('fund ')) )])

10

In [177]:
train_triples_df_pos[(train_triples_df_pos['query']==query_)]

,qid,pid,query,collection,set
1100,859,37700,Industry - Longevity Science,"Okay, here's the final company fact sheet for ...",train
2772,859,42995,Industry - Longevity Science,Here's the GERO.AI company fact sheet based on...,train
3692,859,46023,Industry - Longevity Science,"Here's a company fact sheet for AgelessRx, bas...",train
4712,859,14240,Industry - Longevity Science,Here's the company fact sheet for Health Wildc...,train
8844,859,34855,Industry - Longevity Science,"Okay, here's the final ATDC company fact sheet...",train
...,...,...,...,...,...
86163,859,18223,Industry - Longevity Science,"Okay, here's a company fact sheet for Loyal (l...",train
88816,859,2016,Industry - Longevity Science,"Okay, here's the final VelocityTX fact sheet b...",train
89753,859,950,Industry - Longevity Science,"Okay, here's the final Joyance Partners fact s...",train
89761,859,49879,Industry - Longevity Science,"Okay, here's the final fact sheet on Outset Ve...",train
89896,859,8690,Industry - Longevity Science,Here's a company fact sheet for Fleming Martin...,train

In [171]:
train_triples_df_pos[train_triples_df_pos['query']==query_].loc[17637].collection

'Here\'s the company fact sheet for Sonis Smart Security Ltd, based on the information gathered from noentrysystem.com:   **Company Fact Sheet: Sonis Smart Security Ltd**  **Company Name:** Sonis Smart Security Ltd  **Website:** noentrysystem.com  **Products, Services, and Offerings:**  The company\'s primary offering is the "NoEntry by Sonis" alarm system. This is a wireless, self-installable alarm system designed for homes, caravans, motorhomes, holiday homes, and lorries.  Key features include activation before entry, no need for additional sensors, pet-friendliness, and control via a smart app or key fob.  **Industry:** Home Security; Security Systems; IoT (Internet of Things)  **Target Audience:** Homeowners, renters, caravan/motorhome/campervan owners, holiday homeowners, and lorry owners.  **Unique Selling Propositions (USPs) and Key Differentiators:**  The NoEntry system differentiates itself through its wireless and sensorless design, ease of self-installation (under 5 minutes), lack of maintenance contracts, pet-friendliness, and its activation *before* entry.  This contrasts with traditional alarm systems that often require professional installation, ongoing maintenance, and may not be pet-friendly due to motion sensors.  **Business Model:** Direct-to-consumer (D2C)  **Revenue Model:** Direct sales  **Technology Used:** While not explicitly stated, the system likely utilizes wireless communication technology (e.g., Bluetooth, Wi-Fi, cellular) and a mobile application for remote control and monitoring.  **Competitive Landscape:**  The competitive landscape includes other home security systems, particularly those emphasizing wireless and DIY installation options.  Further research is needed to identify specific competitors.  **Pricing:** £295 (discounted price mentioned on the website)   This fact sheet provides a preliminary overview.  Further investigation, including competitive analysis and financial information, would be beneficial for a more comprehensive assessment.'

In [153]:
train_triples_df_pos[train_triples_df_pos['query']==query_].sample(50)

,qid,pid,query,collection,set
88984,939,31282,Industry - Internet of Things,Here's the Tech Vedika company fact sheet base...,train
66000,939,42586,Industry - Internet of Things,"Okay, here's the PentaForce company fact sheet...",train
37023,939,20942,Industry - Internet of Things,"Okay, here's the SmartLabs Inc. company fact s...",train
57580,939,30746,Industry - Internet of Things,Here's the AutoWiz company fact sheet based on...,train
81441,939,22126,Industry - Internet of Things,Here's the OrbitOnline company fact sheet base...,train
10714,939,45601,Industry - Internet of Things,"Okay, here's the company fact sheet for Data20...",train
61792,939,47518,Industry - Internet of Things,Here's a Netmore Group company fact sheet base...,train
26914,939,50394,Industry - Internet of Things,"Okay, here's the WithIntent company fact sheet...",train
17637,939,33287,Industry - Internet of Things,Here's the company fact sheet for Sonis Smart ...,train
86970,939,37281,Industry - Internet of Things,"Okay, here's the final company fact sheet for ...",train
24535,939,34013,Industry - Internet of Things,Here's a company fact sheet for Clear Blue Tec...,train
79381,939,37247,Industry - Internet of Things,"Here's a company fact sheet for Tego, based on...",train
65880,939,8711,Industry - Internet of Things,"Okay, here's the company fact sheet for SIARQ ...",train
14019,939,13385,Industry - Internet of Things,Here's the Madison Technologies company fact s...,train
60244,939,2186,Industry - Internet of Things,"Okay, here's the company fact sheet for Thinne...",train
71045,939,36595,Industry - Internet of Things,"Okay, here's the Rhea Fund fact sheet based on...",train
31395,939,23792,Industry - Internet of Things,"Okay, here's a company fact sheet for BleedIO ...",train
33231,939,49546,Industry - Internet of Things,"Okay, here's the final fact sheet for IQnext b...",train
39328,939,25093,Industry - Internet of Things,"Okay, here's the Energybox company fact sheet ...",train
23042,939,47988,Industry - Internet of Things,"Okay, here's the final Acellent Technologies f...",train
32420,939,26588,Industry - Internet of Things,"Okay, here's the company fact sheet for plat.o...",train
57899,939,29311,Industry - Internet of Things,"Here's a company fact sheet for Sweratel, base...",train
39400,939,36941,Industry - Internet of Things,Here's the WheelKeep company fact sheet based ...,train
18858,939,29595,Industry - Internet of Things,"Okay, here's the Vates company fact sheet base...",train
10370,939,51477,Industry - Internet of Things,"Okay, here's the Krucial company fact sheet ba...",train
58559,939,21839,Industry - Internet of Things,Here's the final Binoocle company fact sheet b...,train
74276,939,9716,Industry - Internet of Things,"Okay, here's the Toyota Ventures fact sheet ba...",train
10468,939,32600,Industry - Internet of Things,"Here's a company fact sheet for H2O Degree, ba...",train
24446,939,19681,Industry - Internet of Things,"Okay, here's the eAgile company fact sheet bas...",train
21462,939,13629,Industry - Internet of Things,"Okay, here's the DunavNET company fact sheet b...",train
1055,939,35103,Industry - Internet of Things,"Okay, here's the Hala Systems fact sheet based...",train
86588,939,42513,Industry - Internet of Things,Here's a company fact sheet for Hubble Network...,train
22009,939,48380,Industry - Internet of Things,"Here's the company fact sheet for WBPRO, based...",train
21850,939,16254,Industry - Internet of Things,Here's the company fact sheet for inUse (inuse...,train
21532,939,37168,Industry - Internet of Things,"Okay, here's the XY Sense company fact sheet b...",train
97,939,21363,Industry - Internet of Things,"Okay, here's the final company fact sheet for ...",train
14414,939,13123,Industry - Internet of Things,Here's the HUM Systems company fact sheet base...,train
18831,939,51044,Industry - Internet of Things,"Okay, here's the company fact sheet for CEN VC...",train
36350,939,45896,Industry - Internet of Things,Here's the Eseye company fact sheet based on o...,train
45479,939,12396,Industry - Internet of Things,"Okay, here's the Aware360 company fact sheet b...",train
75347,939,48283,Industry - Internet of Things,Here's the VOCSens company fact sheet based on...,train
61311,939,5597,Industry - Internet of Things,Here's the company fact sheet for Last Mile Se...,train
44085,939,48773,Industry - Internet of Things,Here's the PivotPoint Security company fact sh...,train
2822,939,335,Industry - Internet of Things,"Here's a company fact sheet for Xwork, based o...",train
47214,939,36868,Industry - Internet of Things,"Here's a company fact sheet for Trisense, base...",train
8034,939,10653,Industry - Internet of Things,"Okay, here's the Databaum company fact sheet b...",train
84250,939,37760,Industry - Internet of Things,"Okay, here's the Dventus company fact sheet ba...",train
8223,939,13687,Industry - Internet of Things,"Okay, here's the TempMate company fact sheet b...",train
4954,939,33467,Industry - Internet of Things,Here's the final Devicify.ca company fact shee...,train
68705,939,35647,Industry - Internet of Things,"Okay, here's the Innotek company fact sheet ba...",train

In [117]:
overall_set_positives[overall_set_positives['query']=='Technology - Zero-Knowledge Proofs']

,query,collection,set_z
766714,Technology - Zero-Knowledge Proofs,"Okay, here's the Internxt company fact sheet b...",unsampled_positive
766715,Technology - Zero-Knowledge Proofs,"Okay, here's the final Coven Labs fact sheet b...",unsampled_positive
766716,Technology - Zero-Knowledge Proofs,"Okay, here's the ByteHide company fact sheet b...",unsampled_positive
766717,Technology - Zero-Knowledge Proofs,"Okay, here's the Swoop company fact sheet base...",unsampled_positive
766718,Technology - Zero-Knowledge Proofs,"Okay, here's the final company fact sheet for ...",unsampled_positive
766719,Technology - Zero-Knowledge Proofs,Here's the Ockam company fact sheet based on o...,unsampled_positive
766720,Technology - Zero-Knowledge Proofs,"Okay, here's the final Cysic fact sheet based ...",unsampled_positive
766721,Technology - Zero-Knowledge Proofs,Here's the final Boxcryptor company fact sheet...,unsampled_positive
766722,Technology - Zero-Knowledge Proofs,Here's the Ixia Capital fact sheet based on ou...,unsampled_positive
766723,Technology - Zero-Knowledge Proofs,"Okay, here's the Ceras Ventures fact sheet bas...",unsampled_positive
766724,Technology - Zero-Knowledge Proofs,"Okay, here's the final Zcash company fact shee...",unsampled_positive
766725,Technology - Zero-Knowledge Proofs,Here's the final company fact sheet for zkRace...,unsampled_positive
766726,Technology - Zero-Knowledge Proofs,"Okay, here's the company fact sheet for Matter...",unsampled_positive
766727,Technology - Zero-Knowledge Proofs,Here's the final fact sheet for Primitive Vent...,unsampled_positive
766728,Technology - Zero-Knowledge Proofs,"Okay, here's the final company fact sheet for ...",unsampled_positive
766729,Technology - Zero-Knowledge Proofs,"Here's a company fact sheet for Haun Ventures,...",unsampled_positive

In [137]:
rankings_set_div[rankings_set_div['query']==query_].iloc[1].collection

'Here\'s a fact sheet for Wikus Ventures based on our analysis of their website and some supplementary research:  **Wikus Ventures Fact Sheet**  **Company Name:** Wikus Ventures  **Products/Services/Offerings:**  Investment in exceptional private companies, primarily through their Emerging Technologies Fund (ETF).  This fund focuses on Artificial Intelligence, Blockchain, Robotics, Nanotechnology, Internet of Things, and Genetics.  **Industry:** Venture Capital  **Target Audience:**  Startups in AI, Web3, Robotics, Nanotechnology, IoT, and Genetics seeking funding.  **Unique Selling Propositions (USPs) & Key Differentiators:**  * Focus on emerging technologies with a specific portfolio of high-growth sectors. * Operates as "silent (limited) partners," suggesting a hands-off, less intrusive investment approach. * Backed by a multimillion-dollar Limited Partner (LP) fund. * Composed of a close-knit team of experienced technology executives.  **Business Model:** Venture Capital (B2B)  **Technology Used:** Not specified on the website.  **Revenue Model:**  Likely carried interest and management fees (standard for venture capital firms).  This is not explicitly stated on the website.  **Competitive Landscape:**  Wikus Ventures competes with other venture capital firms investing in similar technologies.  Based on our research, potential competitors include:  * **Sequoia Capital:** Broad tech focus, including significant AI and Web3 investments. * **Andreessen Horowitz (a16z):**  Known for substantial investments in AI and cryptocurrency. * **Lightspeed Venture Partners:** Active in AI and fintech sectors. * **Accel:** Invests across various sectors, with a notable presence in AI. * **Insight Partners:** Focuses on enterprise software and technology, including some AI investments.   **Note:**  The competitive landscape analysis requires further research to fully assess the degree of overlap and direct competition between Wikus Ventures and these firms.  The information provided here is based on publicly available information and may not be exhaustive.'

In [97]:
positives_count

{10: {'total_with_unsampled': 2806, 'train': 1286, 'test': 252, 'val': 162},
 50: {'total_with_unsampled': 12304, 'train': 4989, 'test': 988, 'val': 665},
 100: {'total_with_unsampled': 22739,
  'train': 8551,
  'test': 1707,
  'val': 1173},
 500: {'total_with_unsampled': 89081,
  'train': 25653,
  'test': 5636,
  'val': 3775}}

In [99]:
rankings_set_div[rankings_set_div.qid==0]

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive,true_positives
0,0,3453,1,18.015625,"Okay, here's the company fact sheet for SoftBa...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
1,0,4479,2,17.828125,"Okay, here's the LDV Capital fact sheet based ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
2,0,3509,3,17.750000,Here's the company fact sheet for Basis Set Ve...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
3,0,3049,4,17.718750,Here's the FirstMark Capital fact sheet based ...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
4,0,3641,5,17.531250,"Okay, here's the Resonance Crowd company fact ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,5329,996,11.835938,Here's the UnBlinked company fact sheet based ...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
996,0,1170,997,11.828125,Here's the ILM Corporation fact sheet based on...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
997,0,4370,998,11.765625,"Here's the final fact sheet for Big4Data, base...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
998,0,4379,999,11.718750,Here's the Vocitec Company Fact Sheet based on...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
999,0,47629,1000,11.695312,Here's the Lohika company fact sheet based on ...,Industry - Artificial Intelligence,NaN,NaN,NaN,NaN,None,NaN

In [86]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive,true_positives
0,0,3453,1,18.015625,"Okay, here's the company fact sheet for SoftBa...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
1,0,4479,2,17.828125,"Okay, here's the LDV Capital fact sheet based ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
2,0,3509,3,17.750000,Here's the company fact sheet for Basis Set Ve...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
3,0,3049,4,17.718750,Here's the FirstMark Capital fact sheet based ...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
4,0,3641,5,17.531250,"Okay, here's the Resonance Crowd company fact ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1056995,1056,2206,996,11.453125,Here's the JusticeText company fact sheet base...,Product/Service - Interpretation Services,train,NaN,NaN,unsampled_positive,train,100.0
1056996,1056,11681,997,11.437500,"Okay, here's the final Rouvy company fact shee...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056997,1056,11478,998,11.421875,"Okay, here's the final company fact sheet for ...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056998,1056,14890,999,11.421875,Here's the ArtBinder company fact sheet based ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056999,1056,4603,1000,11.421875,"Okay, here's a company fact sheet for Spoken A...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN

In [87]:
rankings_set_div.groupby('query').apply(lambda x:x[x['rank']<=10]['positive'].value_counts().to_dict()).rename('positives_distribution').reset_index()

/tmp/ipykernel_45170/352534372.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  rankings_set_div.groupby('query').apply(lambda x:x[x['rank']<=10]['positive'].value_counts().to_dict()).rename('positives_distribution').reset_index()

,query,positives_distribution
0,Business Model - 3D Printing-as-a-Service,{'train': 2}
1,Business Model - AI Drug Discovery Model,{'train': 3}
2,Business Model - AI-as-a-Service,{'total_with_unsampled': 6}
3,Business Model - API-Based,"{'total_with_unsampled': 7, 'train': 1, 'val': 1}"
4,Business Model - Accelerator Model,"{'train': 4, 'test': 1}"
...,...,...
1052,Technology - Vector Search,{'train': 1}
1053,Technology - Voice Assistants,"{'train': 1, 'total_with_unsampled': 1}"
1054,Technology - Wireless Communication,{}
1055,Technology - Zero Trust Security,"{'train': 4, 'total_with_unsampled': 2}"
1056,Technology - Zero-Knowledge Proofs,{}

In [88]:
actual_number_positives_per_query

,query,set,true_positives
0,Revenue Model - Flash Sales Model,train,14
1,Consumer Segment - Advertisers,train,100
2,Industry - Social Media Tech,train,100
3,Consumer Segment - Growth Hackers,train,49
4,Product/Service - Water Purification Tech,train,100
...,...,...,...
823491,Product/Service - Testing Services,total_with_unsampled,982
824473,Product/Service - Certification Services,total_with_unsampled,551
825024,Product/Service - Event Planning Services,total_with_unsampled,497
825521,Product/Service - Translation Services,total_with_unsampled,238
825759,Product/Service - Interpretation Services,total_with_unsampled,206

In [89]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive,true_positives
0,0,3453,1,18.015625,"Okay, here's the company fact sheet for SoftBa...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
1,0,4479,2,17.828125,"Okay, here's the LDV Capital fact sheet based ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
2,0,3509,3,17.750000,Here's the company fact sheet for Basis Set Ve...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
3,0,3049,4,17.718750,Here's the FirstMark Capital fact sheet based ...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
4,0,3641,5,17.531250,"Okay, here's the Resonance Crowd company fact ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1056995,1056,2206,996,11.453125,Here's the JusticeText company fact sheet base...,Product/Service - Interpretation Services,train,NaN,NaN,unsampled_positive,train,100.0
1056996,1056,11681,997,11.437500,"Okay, here's the final Rouvy company fact shee...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056997,1056,11478,998,11.421875,"Okay, here's the final company fact sheet for ...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056998,1056,14890,999,11.421875,Here's the ArtBinder company fact sheet based ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056999,1056,4603,1000,11.421875,"Okay, here's a company fact sheet for Spoken A...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN

In [138]:
rankings_set_div[['query','true_positives']].dropna(subset=['true_positives'])\
.sort_values(['query','true_positives'],ascending=False).drop_duplicates(subset=['query'])\
.true_positives.apply(lambda x:min(10,x))

489500    10.0
466510    10.0
507000    10.0
482501    10.0
486000    10.0
          ...
108510    10.0
89500     10.0
122003    10.0
140500    10.0
123001    10.0
Name: true_positives, Length: 1053, dtype: float64

In [95]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive,true_positives
0,0,3453,1,18.015625,"Okay, here's the company fact sheet for SoftBa...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
1,0,4479,2,17.828125,"Okay, here's the LDV Capital fact sheet based ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
2,0,3509,3,17.750000,Here's the company fact sheet for Basis Set Ve...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
3,0,3049,4,17.718750,Here's the FirstMark Capital fact sheet based ...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
4,0,3641,5,17.531250,"Okay, here's the Resonance Crowd company fact ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,total_with_unsampled,5863.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1056995,1056,2206,996,11.453125,Here's the JusticeText company fact sheet base...,Product/Service - Interpretation Services,train,NaN,NaN,unsampled_positive,train,100.0
1056996,1056,11681,997,11.437500,"Okay, here's the final Rouvy company fact shee...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056997,1056,11478,998,11.421875,"Okay, here's the final company fact sheet for ...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056998,1056,14890,999,11.421875,Here's the ArtBinder company fact sheet based ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
1056999,1056,4603,1000,11.421875,"Okay, here's a company fact sheet for Spoken A...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN

In [61]:


rankings_set_div[(rankings_set_div['rank']<=100)].positive.value_counts().to_dict()

{'total_with_unsampled': 22817, 'train': 9398, 'test': 2063, 'val': 1405}

In [63]:

(122841+40839+7280+6990)/528500
(22817+9398+2063+1405)/rankings_set_div[['query','true_positives']].dropna(subset=['true_positives'])\
.sort_values(['query','true_positives'],ascending=False)\
.drop_duplicates(subset=['query']).true_positives.apply(lambda x:min(100,x)).sum()

# (3004+1718+311+256)/rankings_set_div[['query','true_positives']].dropna(subset=['true_positives']).sort_values(['query','true_positives'],ascending=False).drop_duplicates(subset=['query']).true_positives.apply(lambda x:min(10,x)).sum()

0.3915099515042461

In [142]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive,true_positives
0,0,3453,1,90.9375,"Okay, here's the company fact sheet for SoftBa...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive,5863.0
1,0,5339,2,90.0000,Here's the Redcliffe Capital fact sheet based ...,Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive,5863.0
2,0,3684,3,90.0000,"Okay, here's the final Intel Capital fact shee...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive,5863.0
3,0,1946,4,89.8125,"Here's the company fact sheet for Next Legacy,...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive,5863.0
4,0,1361,5,89.6250,"Okay, here's the final company fact sheet for ...",Industry - Artificial Intelligence,NaN,NaN,NaN,unsampled_positive,unsampled_positive,5863.0
...,...,...,...,...,...,...,...,...,...,...,...,...
528495,1056,1958,496,80.3125,"Okay, here's the BrightHire company fact sheet...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
528496,1056,2103,497,80.3125,"Okay, here's the Scribbl company fact sheet ba...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
528497,1056,5718,498,80.3125,"Okay, here's the final Shade.inc company fact ...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
528498,1056,8061,499,80.2500,Here's the NovoEd company fact sheet based on ...,Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN
528499,1056,619,500,80.2500,"Okay, here's the TeacherMatic company fact she...",Product/Service - Interpretation Services,NaN,NaN,NaN,NaN,None,NaN

In [137]:
rankings_set_div[['query','true_positives']].dropna(subset=['true_positives']).drop_duplicates()

                                            query  true_positives
0              Industry - Artificial Intelligence          5863.0
10             Industry - Artificial Intelligence            29.0
27             Industry - Artificial Intelligence            50.0
32             Industry - Artificial Intelligence           100.0
500                   Industry - Machine Learning          3933.0
...                                           ...             ...
527506     Product/Service - Translation Services           238.0
528001  Product/Service - Interpretation Services           100.0
528005  Product/Service - Interpretation Services            26.0
528014  Product/Service - Interpretation Services           206.0
528151  Product/Service - Interpretation Services            21.0

[3767 rows x 2 columns]

In [139]:
rankings_set_div[['query','true_positives']].dropna(subset=['true_positives']).sort_values(['query','true_positives'],ascending=False).drop_duplicates(subset=['query']).true_positives.apply(lambda x:min(10,x)).sum()

10409.0

In [136]:
len(rankings_set_div[rankings_set_div['rank']<=10])

10570

In [57]:
rankings_set_div.collection.iloc[0]

'Okay, here\'s the company fact sheet for SoftBank Vision Fund based on our analysis of their website, visionfund.com:  **Company Fact Sheet: SoftBank Vision Fund**  **1. Products, Services, and Offerings:**  SoftBank Vision Fund doesn\'t offer products or services directly to consumers or businesses.  Its core offering is venture capital investment in AI-focused companies.  They invest across the entire AI technology stack, from hardware (like semiconductors) to software infrastructure and applications.  **2. Industry and Target Audience:** The industry is venture capital and private equity, specifically within the Artificial Intelligence (AI) technology sector.  Their target audience is companies developing AI technologies, particularly those with potential for significant growth and disruption within a "full-stack" AI ecosystem.  **3. Unique Selling Propositions (USPs) and Key Differentiators:**  The fund\'s key differentiator is its focus on investing across the entire AI technology stack, providing comprehensive support to companies at various stages of development.  Their significant financial resources and stated belief in the transformative power of AI also set them apart.  The scale of their investments is a major competitive advantage.  **4. Business Model:** Venture Capital/Private Equity.  The fund invests in promising AI companies and aims to generate returns through the growth and eventual sale or IPO of its portfolio companies.  **5. Technology Used (Optional):** The website doesn\'t specify the internal technologies used by SoftBank Vision Fund.  However, their investment focus clearly indicates expertise in evaluating and understanding AI technologies.  **6. Revenue Model (Optional):** The revenue model is based on capital appreciation of investments in portfolio companies.  Returns are generated through the eventual sale or IPO of these companies.  **7. Competitive Landscape (Optional):** The website doesn\'t directly address competitors.  However, it\'s inferred that SoftBank Vision Fund competes with other large venture capital firms and private equity funds that invest in the AI sector.  Further research would be needed to identify specific competitors.  **Business Model Classification:** Venture Capital/Private Equity (B2B)'

In [58]:
rankings_set_div.collection.iloc[1]

"Here's the Redcliffe Capital fact sheet based on the information gathered from their website:  **Redcliffe Capital Fact Sheet**  **1. Company Overview:**  Redcliffe Capital is a venture capital and special situations investment firm with offices in London and Delhi.  They focus on investments leveraging the transformative power of Artificial Intelligence across various sectors.  **2. Products, Services, and Offerings:**  * Venture capital and early-stage investments. * Building ventures to capitalize on opportunities in transforming industries. * Structured finance. * Leveraged buyouts (LBOs) and leveraged buy-ins (LBIs). * Investment and advisory solutions.  **3. Industry and Target Audience:**  * **Industry:** Venture Capital, Private Equity, Investment Banking (specifically focused on AI-driven transformation across multiple sectors including Technology, Financial Services, FMCG, and Health). * **Target Audience:** Startups, SMEs, entrepreneurs, and investors interested in AI-driven businesses.  **4. Unique Selling Propositions (USPs) and Key Differentiators:**  * Focus on the transformative potential of Artificial Intelligence across diverse sectors. * Global reach with offices in London and Delhi. * Expertise in both venture capital and special situations investments, including structured finance and leveraged transactions. * Commitment to partnering with founders and providing strategic guidance beyond just capital.  **5. Business Model:**  Venture Capital firm utilizing a traditional model of management fees and carried interest from successful investments.  **6. Revenue Model:**  Management fees and carried interest from investments.  **7. Technology Used:**  Not explicitly detailed on the website.  However, given their focus on AI, it's likely they utilize technology for deal sourcing, due diligence, portfolio management, and other aspects of their investment process.  **8. Competitive Landscape:**  Not explicitly detailed on the website; this would require further research into other venture capital firms operating in similar sectors and geographies.   This fact sheet provides a summary of Redcliffe Capital based on publicly available information from their website.  Further research may be needed for a more comprehensive understanding of their competitive landscape, portfolio companies, and specific investment strategies."

In [258]:
rankings_set_div.dropna(subset=['positive']).sample(50)

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive
25689,51,26301,190,85.1250,"Okay, here's the GrubX company fact sheet base...",Industry - Point of Sale Systems,train,NaN,NaN,unsampled_positive,train
220652,441,25649,153,88.0625,"Okay, here's the company fact sheet for Life E...",Customer Industry - Biotechnology industry,train,NaN,NaN,unsampled_positive,train
462537,925,20534,38,82.0625,"Okay, here's the final MessageBus company fact...",Technology - Microservices,train,NaN,NaN,unsampled_positive,train
289108,578,24836,109,86.3125,Here's a company fact sheet for Mundo-Lab base...,Customer Industry - Philanthropic Foundations,NaN,test,val,unsampled_positive,val
397798,795,2327,299,83.1875,"Okay, here's the company fact sheet for Advanc...",Product/Service - AI-powered Trading,NaN,test,val,unsampled_positive,val
82187,164,33410,188,88.3750,Here's the company fact sheet for Optical Acad...,Business Model - Retail,NaN,NaN,NaN,unsampled_positive,unsampled_positive
161722,323,36087,223,83.0625,Here's a company fact sheet for Moguntia Food ...,Revenue Model - White Labeling,NaN,test,val,unsampled_positive,val
355042,710,2877,43,82.1250,"Okay, here's the VoxSmart company fact sheet b...",Consumer Segment - Compliance Officers,NaN,NaN,NaN,unsampled_positive,unsampled_positive
384365,768,11693,366,84.8125,"Here's the company fact sheet for TGS Tech, ba...",Product/Service - Cloud DevOps,train,NaN,NaN,unsampled_positive,train
506961,1013,3476,462,83.6250,"Okay, here's the EnlitenAI company fact sheet ...",Technology - Sensor Technology,NaN,NaN,NaN,unsampled_positive,unsampled_positive
316114,632,45117,115,83.1250,Here's the Blue Security company fact sheet ba...,Consumer Segment - Households,NaN,NaN,NaN,unsampled_positive,unsampled_positive
318897,637,8630,398,84.3125,"Okay, here's the final company fact sheet for ...",Consumer Segment - C-Suite,NaN,NaN,NaN,unsampled_positive,unsampled_positive
230960,461,44002,461,85.6875,"Here's a company fact sheet for FoodByUs, base...",Customer Industry - Hospitality industry,NaN,NaN,NaN,unsampled_positive,unsampled_positive
41727,83,35889,228,79.6875,"Okay, here's the final LetterOne company fact ...",Industry - Electric Utilities,NaN,NaN,NaN,unsampled_positive,unsampled_positive
521040,1042,18592,41,86.0000,Here's the ClassicDoge fact sheet based on our...,Consumer Segment - Collectors,train,NaN,NaN,unsampled_positive,train
126177,252,45166,178,84.1250,"Okay, here's the final Polyswarm company fact ...",Business Model - Crowdsource Innovation,train,NaN,NaN,unsampled_positive,train
477997,955,3995,498,85.0625,Here's a GrubMarket company fact sheet based o...,Technology - Retail Tech,NaN,test,NaN,unsampled_positive,test
340459,680,38940,460,86.6250,Here's the JustAskMe.com company fact sheet ba...,Consumer Segment - Graphic Designers,NaN,NaN,NaN,unsampled_positive,unsampled_positive
96404,192,12118,405,89.3125,Here's a company fact sheet for Parking Made E...,Business Model - Marketplace-as-a-Service,NaN,NaN,NaN,unsampled_positive,unsampled_positive
99233,198,29719,234,83.1875,Here's the FirstMate company fact sheet based ...,Business Model - Crypto-Native,train,NaN,NaN,unsampled_positive,train
37674,75,30010,175,82.4375,Here's the Sandwater company fact sheet based ...,Industry - Solar Energy,NaN,NaN,NaN,unsampled_positive,unsampled_positive
183018,366,22477,19,85.4375,Here's the final company fact sheet for Infini...,Revenue Model - Data Storage Fees,NaN,NaN,val,unsampled_positive,val
279185,558,18891,186,88.9375,"Okay, here's the Obermeyer fact sheet based on...",Customer Industry - Luxury Goods market,NaN,test,NaN,unsampled_positive,test
24255,48,41025,256,85.6250,"Okay, here's the RDEP company fact sheet based...",Industry - Retail Analytics,NaN,NaN,NaN,unsampled_positive,unsampled_positive
175208,350,32200,209,81.6250,Here's the Little Sun company fact sheet based...,Revenue Model - Channel Partnerships,NaN,NaN,NaN,unsampled_positive,unsampled_positive
317774,635,19241,275,82.0000,Here's the final company fact sheet for IT-Bra...,Consumer Segment - Young Professionals,train,NaN,NaN,unsampled_positive,train
235713,471,22607,214,87.6875,Here's the final company fact sheet for XC Ass...,Customer Industry - Medical Devices industry,NaN,NaN,NaN,unsampled_positive,unsampled_positive
32380,64,46813,381,84.9375,"Okay, here's the company fact sheet for Dots (...",Industry - Logistics Tech,train,NaN,NaN,unsampled_positive,train
56661,113,30150,162,85.3125,Here's the PLT4M company fact sheet based on o...,Industry - Interactive Content,NaN,NaN,NaN,unsampled_positive,unsampled_positive
285548,571,22730,49,85.1875,"Okay, here's a company fact sheet for GrowthFo...",Customer Industry - Nonprofit Organizations,NaN,NaN,NaN,unsampled_positive,unsampled_positive
487767,975,49447,268,84.8750,"Okay, here's the final company fact sheet for ...",Technology - Data Privacy,NaN,NaN,NaN,unsampled_positive,unsampled_positive
274211,548,47755,212,87.8750,"Okay, here's the SurveyLegend company fact she...",Customer Industry - HRTech industry,NaN,NaN,NaN,unsampled_positive,unsampled_positive
225985,451,37796,486,82.0625,"Okay, here's the Endurant Energy company fact ...",Customer Industry - Electric Utilities,NaN,test,NaN,unsampled_positive,test
75478,150,20457,479,84.3750,"Here's a company fact sheet for Zuvi, based on...",Business Model - B2C,NaN,NaN,NaN,unsampled_positive,unsampled_positive
279426,558,41340,427,88.0000,Here's the Nahaia Wellness company fact sheet ...,Customer Industry - Luxury Goods market,NaN,NaN,NaN,unsampled_positive,unsampled_positive
137807,275,48930,308,84.8125,Here's a company fact sheet for MyAccessHealth...,Business Model - Healthcare-as-a-Service,NaN,NaN,NaN,unsampled_positive,unsampled_positive
161322,322,35573,323,86.1875,"Okay, here's the company fact sheet for Peak P...",Revenue Model - Licensing Fees,NaN,NaN,NaN,unsampled_positive,unsampled_positive
121396,242,38414,397,88.5625,Here's the company fact sheet for Monument Sta...,Business Model - Talent-as-a-Service,NaN,NaN,NaN,unsampled_positive,unsampled_positive
408574,817,3057,75,86.3750,"Okay, here's the DigiStrive company fact sheet...",Product/Service - Cloud Security,NaN,NaN,NaN,unsampled_positive,unsampled_positive
267640,535,33742,141,84.5625,Here's the final Lattis.io company fact sheet ...,Customer Industry - Food Delivery Services,train,NaN,NaN,unsampled_positive,train
130390,260,43188,391,80.2500,"Okay, here's the Opolis company fact sheet bas...",Business Model - Community-Driven,NaN,NaN,NaN,unsampled_positive,unsampled_positive
124595,249,24443,96,81.0000,"Okay, here's the FunnelFox company fact sheet ...",Business Model - No-Code/Low-Code Platform,train,NaN,NaN,unsampled_positive,train
39792,79,47928,293,79.8125,Here's the Q ENERGY company fact sheet based o...,Industry - Hydrogen Economy,train,NaN,NaN,unsampled_positive,train
149578,299,10135,79,85.9375,"Here's a company fact sheet for Benefiti.rs, b...",Revenue Model - Tiered Pricing,NaN,NaN,NaN,unsampled_positive,unsampled_positive
525565,1051,26474,66,85.5625,Here's the Exciber Oy company fact sheet based...,Product/Service - Maintenance Services,NaN,NaN,NaN,unsampled_positive,unsampled_positive
26672,53,4581,173,89.0000,Here's the Gondola.ai company fact sheet based...,Industry - Personalization Tech,NaN,NaN,NaN,unsampled_positive,unsampled_positive
506116,1012,296,117,84.9375,"Okay, here's the AiNaDoctor company fact sheet...",Technology - Robotic Vision,NaN,NaN,NaN,unsampled_positive,unsampled_positive
64652,129,49880,153,81.3750,Here's the MyPlacers company fact sheet based ...,Industry - Gig Economy Platforms,NaN,NaN,NaN,unsampled_positive,unsampled_positive
335960,671,2266,461,84.8125,Here's the Wizzy.ai company fact sheet based o...,Consumer Segment - Marketplace Sellers,NaN,NaN,NaN,unsampled_positive,unsampled_positive
208699,417,2893,200,91.5625,Here's the Anttecipe company fact sheet based ...,Revenue Model - Fintech Loan Interest Revenue,NaN,NaN,NaN,unsampled_positive,unsampled_positive

In [261]:
rankings_set_div.loc[82187].collection

"Here's the company fact sheet for Optical Academy, based on the information gathered from their website:  **Company Name:** Optical Academy  **Products and Services:** Onsite mobile eye exams, eyewear sales (over 500 styles), contact lens sales (various brands including Acuvue, Air Optix, Biofinity, and Dailies), online consultations (via TeleEyes.com), online eyewear and contact lens shop, and franchise opportunities.  **Industry:** Healthcare (Optometry), Retail (Eyewear and Contact Lenses), Franchising  **Target Audience:** Schools, worksites, communities, homebound patients, educators, individuals, and potential franchisees.  **Unique Selling Propositions (USPs):**  Nation's leading onsite mobile eye care provider, mobile eye exam services at various locations, wide selection of eyewear (over 500 styles), online consultation and shopping, and franchise opportunities.  **Business Model:** Primarily B2C, with B2B elements (serving schools and worksites) and a franchising component.  **Technology Used:** TeleEyes.com (online consultation platform), an e-commerce platform for their online shop.  Specific details on the technology stack are not publicly available on the website.  **Revenue Model:** Product sales (eyewear, contact lenses), service fees (eye exams), and franchise fees.  **Competitive Landscape:**  Further research is needed to fully assess the competitive landscape.  The website does not explicitly name competitors.   This fact sheet provides a preliminary overview of Optical Academy.  A more comprehensive analysis would require further investigation, including competitive analysis and financial data (which is not available through the website alone)."

/home/ec2-user/SageMaker/ColBERT

In [144]:
!pwd

/home/ec2-user/SageMaker/ColBERT

In [145]:
!ls

all_reqs.txt			faiss
analyze_rankings.py		LICENSE
artifacts			LoTTE.md
baleen				MANIFEST.in
benchmark_triplet_generator.py	measure_triplet_generation.py
colbert				mutually_exclusive.py
ColBERT				README.md
colbert_evaluate.py		requirements.txt
colbert_indexer.py		search_inference.ipynb
colbert_searcher.py		server.py
conda_env_cpu.yml		setup.py
conda_env.yml			test_evaluator.py
config				test.ipynb
create_synthetic_dataset.py	tests
create_verifiable_dataset.py	tracking
data				train_colbert.py
docs				train_colbert_v0.py
evaluation.ipynb		training_requirements.txt
examples			training_workflow
experiments			utility

In [ ]:
### calling the evaluate script
from colbert_evaluate import evaluate
evaluate(model_checkpoint,checkpoint_path,experiment_name,root_dir,all_collections_path='../data/all_collection.tsv',
             data_path="./experiments/colbert_aspect_training/run_1741616267/data",
             all_queries_path="../data/all_queries.tsv",all_labelled_positives_path='../data/all_positives.tsv',
             attend_to_mask_tokens=True,top_k=2000,depths=[10,50,100,500,1000])

In [61]:
from colbert.modeling.checkpoint import Checkpoint
from colbert.infra import ColBERTConfig
from colbert.modeling.colbert import colbert_score

checkpoint = './experiments/colbert_aspect_training/none/run_1741616267/checkpoints/colbert-best'

config = ColBERTConfig(
                bsize=64,  # Small batch size for testing
                accumsteps=2,
                lr=5e-6,
                nway=2,  # Binary pairs for simplicity  
                query_maxlen=128,  
                doc_maxlen=512,   
                dim=128,
                similarity="cosine",
                use_ib_negatives=False,
                maxsteps=10000,  # Limit training steps
                warmup=250,
                val_check_interval=150,
                val_ema_alpha=0.95,
                attend_to_mask_tokens=True
            )

In [63]:

query=rankings.iloc[0]['query']
data=rankings.iloc[0:500]['collection'].to_list()

In [66]:



import torch
import numpy as np
ckpt = Checkpoint(checkpoint, colbert_config=config)

#> QueryTokenizer.tensorize(batch_text[0], batch_background[0], bsize) ==
#> Input: Industry - Artificial Intelligence, 		 True, 		 None
#> Output IDs: torch.Size([128]), tensor([ 101,    1, 3068, 1011, 7976, 4454,  102,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103], device='cuda:0')
#> Output Mask: torch.Size([128]), tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')

In [ ]:
del all_labelled_pairs

In [70]:



from tqdm import tqdm
query_groups=rankings.groupby('query')
groups_=[]
for query,group in tqdm(query_groups):
    
    data=group.collection.to_list()
    Q = ckpt.queryFromText([query])
    D = ckpt.docFromText(data, bsize=1024)[0]
    D_mask = torch.ones(D.shape[:2], dtype=torch.long)
    scores = colbert_score(Q, D, D_mask).flatten().cpu().numpy().tolist()
    ranking_colbert = np.argsort(scores)[::-1]
    group['true_scores']=scores
    group['true_rank']=ranking_colbert
    groups_.append(group)

/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  return torch.cuda.amp.autocast() if self.activated else NullContextManager()
/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:15: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.

In [71]:
rankings_new=pd.concat(groups_)

In [74]:
rankings_new.to_pickle('/home/ec2-user/SageMaker/ColBERT/experiments/run_1741616267_evaluation/colbert_searcher/2025-03/12/07.03.53/rankings_run_1741616267.colbert.best.all.nbits=2.attend_mask=True.true_ranking.pickle')

In [75]:
rankings_new

,qid,doc_id,rank,score,collection,query,true_scores,true_rank
123000,246,40675,1,89.5625,"Here's the company fact sheet for Levitate, ba...",Business Model - 3D Printing-as-a-Service,89.8125,0
123001,246,7727,2,89.0625,"Okay, here's the final MX3D company fact sheet...",Business Model - 3D Printing-as-a-Service,89.8125,1
123002,246,2482,3,89.0000,"Okay, here's the Factorem company fact sheet b...",Business Model - 3D Printing-as-a-Service,89.6250,2
123003,246,48082,4,88.9375,"Okay, here's the final company fact sheet for ...",Business Model - 3D Printing-as-a-Service,87.8750,4
123004,246,6974,5,88.6875,Here's the AnyShape company fact sheet based o...,Business Model - 3D Printing-as-a-Service,89.4375,15
...,...,...,...,...,...,...,...,...
489995,979,35911,496,74.7500,Here's a Corrata company fact sheet based on t...,Technology - Zero-Knowledge Proofs,74.1250,470
489996,979,3892,497,74.7500,"Here's a company fact sheet for Harness.io, ba...",Technology - Zero-Knowledge Proofs,74.1875,499
489997,979,7561,498,74.7500,"Okay, here's the final company fact sheet for ...",Technology - Zero-Knowledge Proofs,74.8750,356
489998,979,23,499,74.7500,Here's the WVV Capital fact sheet based on our...,Technology - Zero-Knowledge Proofs,73.8125,436
489999,979,17610,500,74.7500,"Okay, here's the CloudQA company fact sheet ba...",Technology - Zero-Knowledge Proofs,71.0000,233

In [67]:
ranking_colbert

array([  0,   2,   1,   3,   8,  10,   9,  24,  30,  13,   7,   6,  17,
        11,  27,  26,  14,  25,  18,  36,  33,  15,  28,  22,  38,  23,
        42,  37,  45,  16,   4,  29,  43,  35,  31,  12,  34,  21,  44,
        20,  52,  19,  60,  41,  48,  46,  40,  39,  61,  57,  32,  56,
        65,  78,  47,  54,  50,  55,  49,  53,  62,  79,  87,  76, 134,
        75, 117,  66,  70,  51,   5,  98,  80,  64,  68,  85,  91,  90,
       118,  99, 100,  71,  88, 101, 131, 136,  72, 102, 123,  84,  74,
        96, 132,  93,  59, 109, 125,  82,  58, 138, 108,  97, 147,  83,
       137, 122, 103,  73, 148, 194, 124, 133,  86, 128, 225,  77, 142,
       120, 193, 112, 104, 171, 111, 173, 106, 155, 287, 246, 200, 107,
       184, 143,  63, 203, 241, 278, 151, 201,  95, 154, 257, 177, 183,
        81, 165, 127, 126, 242, 231,  92, 211, 170, 208, 158, 264, 199,
        94, 258, 166, 376, 164, 141, 182, 196, 195, 202, 239, 175, 116,
       130,  69, 227, 114, 324, 157, 205, 135, 161, 245, 180, 433, 288,
       204, 294, 255, 235, 121, 223, 207, 260, 232, 179, 244, 139,  89,
       149, 226, 185, 277, 152, 222, 163, 272, 178, 129, 285, 315, 363,
       361, 145, 271, 198, 160, 335, 266, 286, 228, 206, 301, 110, 268,
       298, 217, 186, 303, 189, 176, 156, 372, 396, 146, 468, 295, 300,
       265, 270, 387, 291, 256, 336, 338, 233, 346, 250, 382, 220, 368,
       313, 401, 466, 168, 353, 327, 115, 359, 392, 349, 347, 341, 105,
       373, 197, 422, 370, 279, 252, 343, 293, 140, 314, 248, 230, 326,
       473, 426, 224, 340, 234, 445, 365, 299, 212, 407, 191, 477, 419,
       441, 330, 364, 280, 322, 267,  67, 356, 378, 261, 153, 375, 275,
       276, 362, 273, 283, 297, 354, 337, 174, 377, 436, 367, 421, 381,
       323, 429, 435, 369, 150, 243, 221, 328, 216, 312, 219, 302, 167,
       360, 453, 446, 431, 214, 269, 263, 284, 253, 169, 451, 215, 213,
       309, 181, 187, 479, 306, 339, 389, 459, 452, 449, 447, 437, 406,
       404, 400, 159, 393, 119, 274, 355, 334, 332, 329, 282, 254, 456,
       494, 491, 190, 471, 467, 229, 388, 358, 357, 458, 292, 430, 428,
       480, 484, 394, 397, 249, 144, 490, 487, 486, 209, 457, 444, 442,
       374, 391, 247, 251, 386, 344, 371, 385, 162, 390, 307, 418, 472,
       321, 499, 210, 481, 434, 415, 398, 316, 420, 350, 405, 425, 476,
       352, 192, 427, 281, 488, 319, 308, 333, 462, 318, 413, 432, 461,
       414, 310, 450, 238, 423, 464, 218, 454, 348, 482, 317, 498, 345,
       320, 489, 325, 410, 237, 412, 417, 469, 403, 416, 483, 497, 383,
       455, 485, 474, 475, 342, 331, 402, 424, 465, 172, 443, 495, 259,
       448, 438, 289, 470, 492, 463, 240, 296, 460, 304, 366, 384, 478,
       408, 409, 493, 380, 262, 311, 351, 236, 440, 305, 188, 399, 411,
       379, 113, 496, 290, 395, 439])

In [76]:
rankings_set_div_true=rankings_new.merge(train_triples_df_pos[['collection','query','set']],how='left',on=['collection','query'])
rankings_set_div_true=rankings_set_div_true.merge(test_triples_df_pos[['collection','query','set']],how='left',on=['collection','query'])
rankings_set_div_true=rankings_set_div_true.merge(val_triples_df_pos[['collection','query','set']],how='left',on=['collection','query'])
rankings_set_div_true=rankings_set_div_true.merge(overall_set_positives,on=['collection','query'],how='left')
rankings_set_div_true['positive']=rankings_set_div_true.apply(lambda x:get_first_non_none([x['set'], x['set_x'] , x['set_y'] , x['set_z'] ]),axis=1)

In [80]:
rankings_set_div_true[rankings_set_div_true['true_rank']<=100].positive.value_counts()

positive
unsampled_positive    29924
train                 14164
val                    2260
test                   2040
Name: count, dtype: int64

In [79]:
(3682+2319+360+283)/len(rankings_set_div_true[rankings_set_div_true['true_rank']<=10])

0.5714285714285714

In [81]:
(29924+14164+2260+2040)/len(rankings_set_div_true[rankings_set_div_true['true_rank']<=100])

0.4532536508144665

In [ ]:
(29924+14164+2260+2040)/len(rankings_set_div_true[rankings_set_div_true['true_rank']<=100])

In [242]:
# rankings_set_div

In [41]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive
0,0,39291,1,87.0625,"Okay, here's the company fact sheet for First ...",Customer Industry - Nutraceuticals industry,NaN,train,NaN,NaN,train
1,0,16989,2,86.0625,Here's the Native American Venture Fund (NAVF)...,Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
2,0,6460,3,85.8750,"Okay, here's the LESS+MORE company fact sheet ...",Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
3,0,51084,4,85.5000,"Here's a company fact sheet for Bend Health, b...",Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
4,0,10884,5,85.3750,"Here's a company fact sheet for Previnex, base...",Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
528495,1056,48002,496,78.9375,"Okay, here's the final company fact sheet for ...",Industry - Music Tech,NaN,NaN,NaN,NaN,None
528496,1056,812,497,78.9375,Here's the VdoCipher company fact sheet based ...,Industry - Music Tech,NaN,NaN,NaN,NaN,None
528497,1056,1347,498,78.8750,Here's the Aviron Pictures fact sheet based on...,Industry - Music Tech,NaN,NaN,NaN,NaN,None
528498,1056,23558,499,78.8750,Here's the company fact sheet for The Replay A...,Industry - Music Tech,NaN,NaN,NaN,NaN,None
528499,1056,50803,500,78.8750,Here's the final company fact sheet for MIS Ma...,Industry - Music Tech,NaN,NaN,NaN,NaN,None

In [192]:
positives=rankings_set_div.groupby('query').positive.value_counts().reset_index()
positives['pos_count']=positives.groupby('query')['count'].transform(sum)

/tmp/ipykernel_4067/2932103665.py:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  positives['pos_count']=positives.groupby('query')['count'].transform(sum)

In [193]:
positives

                                          query positive  count  pos_count
0     Business Model - 3D Printing-as-a-Service    train      8          9
1     Business Model - 3D Printing-as-a-Service     test      1          9
2      Business Model - AI Drug Discovery Model    train     50         59
3      Business Model - AI Drug Discovery Model     test      7         59
4      Business Model - AI Drug Discovery Model      val      2         59
...                                         ...      ...    ...        ...
2948           Technology - Zero Trust Security    train     27         35
2949           Technology - Zero Trust Security     test      6         35
2950           Technology - Zero Trust Security      val      2         35
2951         Technology - Zero-Knowledge Proofs    train      8         11
2952         Technology - Zero-Knowledge Proofs     test      3         11

[2953 rows x 4 columns]

In [172]:
test_triples_df_pos

,qid,pid,query,collection,set
0,582,29836,Industry - Printing Industry,"Okay, here's the final company fact sheet for ...",test
1,59,5162,Product/Service - Industrial Automation,Here's a company fact sheet for Inspire Automa...,test
2,878,29173,Industry - Gig Economy Platforms,Here's the GigSmart company fact sheet based o...,test
3,154,45909,Product/Service - Online Learning Platforms,Here's a fact sheet for Universidad Innovación...,test
4,717,28497,Business Model - Donation-Based Crowdfunding,"Okay, here's the company fact sheet for 9millo...",test
...,...,...,...,...,...
33107,429,45463,Consumer Segment - Fitness Professionals,Here's the company fact sheet for The Gene Box...,test
33108,804,21969,Industry - Alternative Proteins,Here's the GoLegendary company fact sheet base...,test
33109,828,22564,Business Model - Lease-to-Own,Here's the Avalon Transportation company fact ...,test
33110,1024,23792,Customer Industry - Home Automation industry,"Okay, here's a company fact sheet for BleedIO ...",test
33111,245,40636,Technology - Computer Vision,Here's the company fact sheet for The Data Sci...,test

In [175]:
test_triples_df_pos['pos_count']=test_triples_df_pos.groupby('query').pid.transform('count')

val_triples_df_pos['pos_count']=val_triples_df_pos.groupby('query').pid.transform('count')
train_triples_df_pos['pos_count']=train_triples_df_pos.groupby('query').pid.transform('count')

In [177]:
all_positives=pd.concat([train_triples_df_pos[['query','set','pos_count']],
                         val_triples_df_pos[['query','set','pos_count']],
                         test_triples_df_pos[['query','set','pos_count']]],ignore_index=True)

In [180]:
all_positives=all_positives.drop_duplicates()

In [182]:
all_positives=all_positives.sort_values(['query','set'])

In [187]:
9/14

0.6428571428571429

In [183]:
all_positives

                                            query    set  pos_count
116287  Business Model - 3D Printing-as-a-Service   test          3
11500   Business Model - 3D Printing-as-a-Service  train         11
118875   Business Model - AI Drug Discovery Model   test         11
104      Business Model - AI Drug Discovery Model  train         79
94178    Business Model - AI Drug Discovery Model    val         11
...                                           ...    ...        ...
115642           Technology - Zero Trust Security   test         26
737              Technology - Zero Trust Security  train        100
91809            Technology - Zero Trust Security    val         27
117805         Technology - Zero-Knowledge Proofs   test          3
20536          Technology - Zero-Knowledge Proofs  train         13

[3111 rows x 3 columns]

In [194]:
positives=positives.merge(all_positives.rename(columns={'pos_count':'all_pos_count','set':'positive'}),on=['positive','query'],how='left')

In [197]:
positives['recall_in_top_500']=positives['count']/positives.all_pos_count

In [199]:
positives.recall_in_top_500.mean()

0.30559478495232106

In [200]:
positives

,query,positive,count,pos_count,all_pos_count,recall_in_top_100,recall_in_top_500
0,Business Model - 3D Printing-as-a-Service,train,8,9,11,0.727273,0.727273
1,Business Model - 3D Printing-as-a-Service,test,1,9,3,0.333333,0.333333
2,Business Model - AI Drug Discovery Model,train,50,59,79,0.632911,0.632911
3,Business Model - AI Drug Discovery Model,test,7,59,11,0.636364,0.636364
4,Business Model - AI Drug Discovery Model,val,2,59,11,0.181818,0.181818
...,...,...,...,...,...,...,...
2948,Technology - Zero Trust Security,train,27,35,100,0.270000,0.270000
2949,Technology - Zero Trust Security,test,6,35,26,0.230769,0.230769
2950,Technology - Zero Trust Security,val,2,35,27,0.074074,0.074074
2951,Technology - Zero-Knowledge Proofs,train,8,11,13,0.615385,0.615385
2952,Technology - Zero-Knowledge Proofs,test,3,11,3,1.000000,1.000000

In [204]:
rankings_set_div

,qid,doc_id,rank,score,collection,query,set_x,set_y,set,set_z,positive
0,0,39291,1,87.0625,"Okay, here's the company fact sheet for First ...",Customer Industry - Nutraceuticals industry,NaN,train,NaN,NaN,train
1,0,16989,2,86.0625,Here's the Native American Venture Fund (NAVF)...,Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
2,0,6460,3,85.8750,"Okay, here's the LESS+MORE company fact sheet ...",Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
3,0,51084,4,85.5000,"Here's a company fact sheet for Bend Health, b...",Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
4,0,10884,5,85.3750,"Here's a company fact sheet for Previnex, base...",Customer Industry - Nutraceuticals industry,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
528495,1056,48002,496,78.9375,"Okay, here's the final company fact sheet for ...",Industry - Music Tech,NaN,NaN,NaN,NaN,None
528496,1056,812,497,78.9375,Here's the VdoCipher company fact sheet based ...,Industry - Music Tech,NaN,NaN,NaN,NaN,None
528497,1056,1347,498,78.8750,Here's the Aviron Pictures fact sheet based on...,Industry - Music Tech,NaN,NaN,NaN,NaN,None
528498,1056,23558,499,78.8750,Here's the company fact sheet for The Replay A...,Industry - Music Tech,NaN,NaN,NaN,NaN,None
528499,1056,50803,500,78.8750,Here's the final company fact sheet for MIS Ma...,Industry - Music Tech,NaN,NaN,NaN,NaN,None

In [101]:
rankings_set_div['set'].unique()

array([nan], dtype=object)

In [ ]:
Customer Industry - Nutraceuticals industry

In [203]:
rankings_set_div[rankings_set_div.qid==0].collection.iloc[:20].to_list()

["Okay, here's the company fact sheet for First Person™, based on our analysis of their website, getfirstperson.com:  **Company Fact Sheet: First Person™**  **1. Company Name:** First Person™  **2. Products and Services:** First Person™ sells natural brain supplements containing functional mushrooms and other bioactive compounds.  Their product line includes:  * Sunbeam (Motivation and focus) * Golden Hour (Connection and joy) * Moonlight (Deep, restorative sleep) * The Collection (Full throttle, all day) * Crystallized Lion's Mane (Energy and clarity)  They also offer bundles and subscription services with a 15% discount.  **3. Industry:** Dietary Supplements, Nutraceuticals  **4. Target Audience:**  While not explicitly stated, the website suggests their target audience is consumers interested in natural brain health supplements and cognitive enhancement.  More precise demographic information is unavailable on the website.  **5. Unique Selling Propositions (USPs) and Key Differentiators:**  * Science-backed formulations (Note:  The company clearly states that these claims have not been evaluated by the FDA and are not intended to diagnose, treat, cure, or prevent any disease). * Use of functional mushrooms and other bioactive compounds. * Focus on specific cognitive benefits (motivation, mood, sleep, etc.).  **6. Business Model:** Direct-to-consumer (D2C) e-commerce  **7. Technology Used:** The specific e-commerce platform and other technologies used are not disclosed on the website.  It's likely a common e-commerce platform such as Shopify.  **8. Revenue Model:** Direct sales of products through their website, supplemented by a subscription model offering discounts.  **9. Competitive Landscape:**  No specific competitors are mentioned on the website. Further market research is needed to fully assess the competitive landscape.   **Overall Assessment:** First Person™ operates in a growing market with a focus on natural and functional ingredients.  Their direct-to-consumer model allows for direct engagement with customers. However, a lack of detailed information regarding their technology stack, target audience specifics, and competitive analysis limits a more comprehensive evaluation at this time.  Further research is recommended to fully assess their market position and potential.",
 "Here's the Native American Venture Fund (NAVF) fact sheet based on the information gathered from navf.net:  **Native American Venture Fund (NAVF) Fact Sheet**  **Company Overview:** NAVF is a private equity and impact investment fund focused on Native American tribal enterprises.  Their mission is to generate high returns for investors while simultaneously fostering economic development within tribal communities by leveraging the unique economic and legal advantages afforded to tribes by the US government.  **Products, Services, and Offerings:** NAVF provides capital and expertise to federally and state-recognized Native American tribes for the development and operation of businesses.  Their investment focus includes several sectors: Pharmaceutical Production and Distribution, Specialty Finance, Renewable Energy, E-commerce Inversions, Online Gaming/Lottery/Fantasy, and Carbon Credit Projects.  They offer impact investment opportunities with a preferred return on invested capital and additional payouts after capital contributions are returned.  The target Internal Rate of Return (IRR) is 15%+32%.  **Industry and Target Audience:**  NAVF operates within the impact investing and private equity industries. Their target audience consists of two key groups:  Federally and state-recognized Native American Indian tribes seeking investment capital and investors seeking impact investment opportunities with a focus on socially responsible returns.  **Unique Selling Propositions (USPs) and Key Differentiators:** NAVF's key differentiator is its focus on leveraging the unique economic and legal advantages available to Native American tribes to generate superior returns for investors while simultaneously promoting tribal economic self-sufficiency.  The specific advantages are not detailed on the website.  The high target IRR (15%+32%) is also a significant differentiator.  **Business Model:** Private equity/impact investment fund.  B2B (business-to-business) model, investing in tribal enterprises.  **Technology Used:**  Not specified on the website.  **Revenue Model:** Management fees and a share of profits from investments in tribal enterprises.  **Competitive Landscape:** Information on the competitive landscape is not available on the website.   **Additional Notes:**  The website lacks detail on the fund's size, investment strategy beyond the listed sectors, management team, and track record.  Further research would be beneficial to gain a more comprehensive understanding of NAVF's operations and performance.",
 'Okay, here\'s the LESS+MORE company fact sheet based on our analysis of their website and the information we could gather.  Keep in mind that some information, like pricing and specific competitive details, wasn\'t publicly available on their site and would require further investigation.  **LESS+MORE Company Fact Sheet**  **1. Overview:**  LESS+MORE is a San Diego-based design and branding agency serving a diverse clientele.  Their tagline, "Creative That Works," emphasizes a results-oriented approach.  **2. Products, Services, and Offerings:**  LESS+MORE offers a range of design and branding services, inferred from their project portfolio:  * Branding Strategy * Logo Design * Brand Refreshing/Relaunching * Website Design (implied) * Marketing Materials (implied)  **3. Industry and Target Audience:**  LESS+MORE\'s client base spans various industries, including:  * Restaurants * Biotech * Cannabis * Technology (Software & Hardware) * Golf * Tourism  Their target audience appears to be businesses of all sizes seeking professional design and branding solutions.  **4. Unique Selling Propositions (USPs) and Key Differentiators:**  The website highlights a client-focused approach and a commitment to results.  However, specific, quantifiable USPs require further research.  **5. Business Model:**  B2B (Business-to-Business)  **6. Technology Used:**  Not specified on the website.  **7. Revenue Model:**  Likely project-based fees, but this needs confirmation.  **8. Competitive Landscape:**  Requires further research to identify key competitors in the San Diego design and branding agency market.  **9. Financial Information:**  Not available publicly.  **10. Team Size:**  Not disclosed on the website.  **11. Overall Assessment:**  LESS+MORE demonstrates a successful track record with a diverse client portfolio.  However, a more in-depth analysis, including financial data, competitor analysis, and a clearer understanding of their pricing and USPs, is needed for a complete assessment of investment potential.  Further due diligence is strongly recommended.',
 "Here's a company fact sheet for Bend Health, based on the information gathered from their website:  **Company Name:** Bend Health  **Website:** bendhealth.com  **Industry:** Telehealth, Mental Healthcare  **Target Audience:** Children, teens, and young adults.  Also, their website indicates they work with families.  **Products, Services, and Offerings:**  * Therapy and Psychiatry * Coaching * Acute Stabilization Program  **Unique Selling Propositions (USPs) and Key Differentiators:**  * Evidence-based approaches to treatment. * Positive outcomes supported by 8 peer-reviewed studies and partnerships. * Convenient access to care through telehealth. * Holds The Joint Commission’s Gold Seal of Approval®.  **Business Model:** B2C telehealth mental healthcare provider.  **Technology Used:**  Not specified on the website.  **Revenue Model:** Not specified on the website.  No pricing information was found regarding session fees, subscription models, or other revenue streams.  **Competitive Landscape:**  No specific competitors are mentioned on the website.   **Overall Assessment:** Bend Health appears to be a well-established telehealth provider focusing on a niche market (youth mental health).  Their emphasis on evidence-based practices and positive outcomes is a strong selling point. However, the lack of information regarding pricing and technology used on their website limits a full assessment. Further investigation, potentially including contacting the company directly, would be beneficial to gain a more complete understanding of their business model, revenue streams, and competitive positioning.",
 'Here\'s a company fact sheet for Previnex, based on information gathered from their website:  **Company Name:** Previnex  **Products/Services:** Previnex offers a range of dietary supplements categorized into Protein Powders, general Supplements, children\'s vitamins (Kids), and health Programs (a 21-Day Reset and a 7-Day Detox).  Specific products include Nourify® PLUS (vanilla and chocolate), Gut & Green Superfoods, Joint Health PLUS®, Muscle Health PLUS, a Multivitamin, a Probiotic, Optimal Health Pack, Omega Pure PLUS, Immune Health PLUS, and Super Vites® Multivitamin.  **Industry:** Dietary Supplements, Nutraceuticals  **Target Audience:**  While not explicitly stated, the website suggests a target audience encompassing both adults and children, given the product categories.  **Unique Selling Propositions (USPs):** Previnex highlights several key differentiators: clinically effective supplements, thoughtfully sourced ingredients, use of the highest quality and most bioavailable ingredients, adherence to stringent manufacturing processes comparable to pharmaceutical standards, a 100% money-back guarantee, and a "Get Health, Give Health®" initiative that donates children\'s vitamins with every purchase.  **Business Model:** Direct-to-consumer (D2C) e-commerce.  **Revenue Model:** Direct sales and a subscription model ("subscribe & save" option offering a 10% discount).  **Technology Used:**  Not specified on the website.  **Competitive Landscape:**  Information on the competitive landscape is not provided on the Previnex website.  Further research would be needed to assess this aspect.',
 "Here's a fact sheet for Saraf & Partners, based on information gathered from their website:  **Company Name:** Saraf & Partners  **Website:** sarafpartners.com  **Industry:** Legal Services  **Products/Services:** Saraf & Partners offers a wide range of legal services across numerous practice areas, including but not limited to: Anti-Trust & Competition, Banking & Finance, Capital Markets, Dispute Resolution (Litigation and Arbitration), Employment, Fintech & TMT, Gaming, General Corporate and Mergers & Acquisitions, Insolvency & Restructuring, Intellectual Property, Make in India, Pharmaceuticals & Life Sciences, Projects, Infrastructure & Energy, Private Equity & Venture Capital, Real Estate, Regulatory, Tax, and White-Collar Crime & Investigations.  **Target Audience:**  While not explicitly stated, their client list and practice areas suggest a focus on businesses, particularly large corporations and those involved in complex transactions.  **Unique Selling Propositions (USPs):**  The firm highlights its expertise across a broad spectrum of practice areas, its experience working with high-profile clients (including LIC Housing Finance Ltd, Adani Green Energy, Maruti Suzuki, Viatris Inc, Vedanta Group, and The Carlyle Group), and positive client testimonials emphasizing their expertise, responsiveness, and commercial awareness.  **Business Model:** Professional services firm providing legal advice and representation.  **Revenue Model:**  Likely based on billable hours and project fees.  **Technology Used:** Not specified on the website.  **Competitive Landscape:**  The website doesn't directly address competitors, but it's reasonable to assume that other large, full-service law firms with similar practice areas constitute their competitive landscape.",
 "Okay, here's the PaySpace company fact sheet based on our research.  Keep in mind that some information, particularly regarding specific technologies used and a detailed competitive landscape, was not readily available on their website or through readily accessible online searches.  Further investigation would be needed to complete those sections fully.  **PaySpace Company Fact Sheet**  * **Company Name:** PaySpace * **Products/Services:** High-risk merchant payment processing solutions, including credit card processing, fraud & chargeback prevention, company & account registration, various payment methods, payment orchestration, and white-label solutions. * **Industry:** Financial Technology (FinTech) * **Target Audience:** High-risk merchants in industries such as online gambling, crypto merchants, online dating, adult businesses, forex merchants, tech support, web hosting, travel booking, nutraceuticals, and SaaS. * **Unique Selling Propositions (USPs):** Focus on high-risk merchants, customized solutions, large acquiring network, PCI DSS compliance, multi-currency support, fraud & chargeback management. * **Business Model:** B2B SaaS * **Technology Used:**  Specific technologies are not publicly detailed.  The company mentions PCI DSS compliance, implying a secure payment processing infrastructure.  Further investigation is needed to determine the specific technology stack. * **Revenue Model:** Transaction fees (implied) * **Competitive Landscape:**  Several competitors exist in the high-risk payment processing market, including (but not limited to) iCheckout and Payline Data.  However, detailed information on the specific technologies used by PaySpace and its competitors requires further research.   This fact sheet provides a solid foundation for further due diligence.  I recommend additional research to fill in the gaps regarding technology and competitive analysis.  This could involve contacting PaySpace directly, analyzing competitor websites more deeply, and exploring industry reports on high-risk payment processing.",
 'Here\'s the Rubenstein Law Firm fact sheet based on our analysis of their website, rubensteinlaw.com:  **Rubenstein Law Firm Fact Sheet**  **Company:** Rubenstein Law  **Website:** rubensteinlaw.com  **Industry:** Personal Injury Law  **Target Audience:** Individuals who have suffered personal injuries.  **Products/Services:**  Legal representation specializing in personal injury cases, encompassing:  *   Motor vehicle accidents (cars, trucks, motorcycles, bicycles) *   Medical malpractice/negligence *   Premises liability *   Catastrophic injuries *   Defective products and pharmaceuticals (with specific examples cited, such as Philips CPAP and Zantac litigation) *   Toxic exposure (including cases related to Camp Lejeune and Roundup)  **Unique Selling Propositions (USPs):**  *   **Contingency Fee Model:** "No Fees Unless You Win!"  This significantly reduces client risk. *   **Proven Track Record:**  The website showcases substantial past settlements and verdicts (e.g., "$64 Million Verdict," "$20 Million Verdict," "$8.3 Million Settlement"), highlighting their success in securing significant compensation for clients. *   **24/7 Availability:**  Emphasizes accessibility and responsiveness to client needs. *   **Focus on High-Value Cases:**  Their case examples suggest a specialization in complex cases against large corporations and insurance companies.  **Business Model:** B2C (Business-to-Consumer)  **Revenue Model:** Contingency fees –  the firm only receives payment if they successfully obtain a settlement or verdict for their clients.  **Technology Used:**  Not explicitly detailed on the website.  **Competitive Landscape:**  Not directly addressed on the website; however, it can be inferred that the competitive landscape includes other personal injury law firms in their geographic area.  Further research would be needed to identify specific competitors.   This fact sheet provides a concise overview of Rubenstein Law based solely on publicly available information from their website.  A more comprehensive analysis would require additional research, including reviewing client testimonials (beyond those displayed on the site), examining their marketing materials, and researching their competitive landscape through external sources.',
 "Here's a company fact sheet for Gizmo Packaging Ltd. based on the information available on their website, gizmoclosures.com:  **Company Fact Sheet: Gizmo Packaging Ltd.**  **1. Company Overview:**  * **Name:** Gizmo Packaging Ltd. * **Website:** gizmoclosures.com * **Industry:** Packaging Technology (B2B)  **2. Products, Services, and Offerings:**  * **Gizmo Technology:** A patented closure and delivery system for liquid products.  This technology prevents ingredient degradation and separation, mixes ingredients upon opening, and potentially eliminates the need for chemical preservatives. It offers a visually appealing user experience.  Applications include beverages, nutraceuticals, hygiene products, pharmaceuticals, and chemicals.  **3. Target Audience:**  Manufacturers of beverages, nutraceuticals, cosmetics, and other products requiring innovative closures.  The business model is primarily B2B.  **4. Unique Selling Propositions (USPs) and Key Differentiators:**  * Unique closure and delivery system that mixes ingredients upon opening. * Reduces or eliminates the need for chemical preservatives. * Provides visual confirmation of product activation. * Customizable for various container materials (plastic, PET, glass, aluminum, etc.). * Wide-ranging patent portfolio.  **5. Business Model:**  Primarily B2B licensing of Gizmo Technology.  The possibility of direct sales of the Gizmo closure system also exists, though this is not explicitly stated on the website.  **6. Revenue Model:**  Licensing agreements (evidenced by Vessl Inc.'s global license acquisition).  Direct sales are a potential additional revenue stream.  **7. Technology Used:**  Gizmo Technology (detailed technical specifications are not available on the website).  **8. Competitive Landscape:**  Information on competitors is not provided on the website and requires further research.   **9. Additional Notes:**  The website lacks pricing information and detailed technical specifications for Gizmo Technology.  Further investigation is needed to fully assess the competitive landscape and the company's financial performance.  The current operational status of Gizmo Packaging Ltd. is also not explicitly stated.",

In [ ]:
ranking_doc_id_to_doc_mapping=

In [14]:
rankings['query'].iloc[0]

'Customer Industry - Nutraceuticals industry'

In [ ]:
all_

In [20]:
# rankings[rankings.qid==67]

In [114]:
### calculating precision

test_ranking=rankings.copy()

In [116]:
all_labelled_positives

,actual_query,aspect,collection,label,made_up_query
0,Artificial Intelligence,Industry,"Okay, here's the company fact sheet for Empowe...",1,Industry - Artificial Intelligence
1,Artificial Intelligence,Industry,Here's the KNS Technologies fact sheet based o...,1,Industry - Artificial Intelligence
2,Artificial Intelligence,Industry,"Okay, here's a company fact sheet for hi.guru ...",1,Industry - Artificial Intelligence
3,Artificial Intelligence,Industry,Here's a fact sheet for Lanchi Ventures based ...,1,Industry - Artificial Intelligence
4,Artificial Intelligence,Industry,"Here's the company fact sheet for nGrow.ai, ba...",1,Industry - Artificial Intelligence
...,...,...,...,...,...
54084477,Interpretation Services,Product/Service,Here's the Currency Remit App fact sheet based...,1,Product/Service - Interpretation Services
54084478,Interpretation Services,Product/Service,"Here's a company fact sheet for Kmong.com, bas...",1,Product/Service - Interpretation Services
54084479,Interpretation Services,Product/Service,"Here's a company fact sheet for Shownotes.io, ...",1,Product/Service - Interpretation Services
54084480,Interpretation Services,Product/Service,"Here's a company fact sheet for Voccent, based...",1,Product/Service - Interpretation Services
54084481,Interpretation Services,Product/Service,Here's a company fact sheet for Foule Factory/...,1,Product/Service - Interpretation Services

In [115]:
test_ranking.merge(all_labelled_positives[['made_up_query','collection','']])

,qid,doc_id,rank,score,collection,query
0,0,39291,1,87.0625,"Okay, here's the company fact sheet for First ...",Customer Industry - Nutraceuticals industry
1,0,16989,2,86.0625,Here's the Native American Venture Fund (NAVF)...,Customer Industry - Nutraceuticals industry
2,0,6460,3,85.8750,"Okay, here's the LESS+MORE company fact sheet ...",Customer Industry - Nutraceuticals industry
3,0,51084,4,85.5000,"Here's a company fact sheet for Bend Health, b...",Customer Industry - Nutraceuticals industry
4,0,10884,5,85.3750,"Here's a company fact sheet for Previnex, base...",Customer Industry - Nutraceuticals industry
...,...,...,...,...,...,...
528495,1056,48002,496,78.9375,"Okay, here's the final company fact sheet for ...",Industry - Music Tech
528496,1056,812,497,78.9375,Here's the VdoCipher company fact sheet based ...,Industry - Music Tech
528497,1056,1347,498,78.8750,Here's the Aviron Pictures fact sheet based on...,Industry - Music Tech
528498,1056,23558,499,78.8750,Here's the company fact sheet for The Replay A...,Industry - Music Tech
528499,1056,50803,500,78.8750,Here's the final company fact sheet for MIS Ma...,Industry - Music Tech

In [113]:
rankings[rankings['query']=='Customer Industry - Wholesale Trade industry'].iloc[:100]

,qid,doc_id,rank,score,collection,query
288000,576,35901,1,92.1250,"Here's a company fact sheet for SmartScout, ba...",Customer Industry - Wholesale Trade industry
288001,576,14211,2,92.1250,Here's the Stigo Bike company fact sheet based...,Customer Industry - Wholesale Trade industry
288002,576,46010,3,91.8750,Here's the company fact sheet for Mortgage One...,Customer Industry - Wholesale Trade industry
288003,576,50835,4,91.4375,Here's the Teleskope company fact sheet based ...,Customer Industry - Wholesale Trade industry
288004,576,47270,5,91.3750,"Okay, here's the final company fact sheet for ...",Customer Industry - Wholesale Trade industry
...,...,...,...,...,...,...
288495,576,41878,496,87.3125,Here's the Documentation Lab company fact shee...,Customer Industry - Wholesale Trade industry
288496,576,50828,497,87.3125,Here's the Cohen Taylor company fact sheet bas...,Customer Industry - Wholesale Trade industry
288497,576,1156,498,87.3125,"Okay, here's the Beistle company fact sheet ba...",Customer Industry - Wholesale Trade industry
288498,576,21868,499,87.3125,"Here's a company fact sheet for Sabrett, based...",Customer Industry - Wholesale Trade industry
288499,576,32721,500,87.3125,"Okay, here's the Lipari Foods company fact she...",Customer Industry - Wholesale Trade industry

In [43]:
all_labelled_positives.aspect.unique()

array(['Industry', 'Business Model', 'Revenue Model', 'Customer Industry',
       'Consumer Segment', 'Product/Service', 'Technology'], dtype=object)

In [44]:
### we are checking :
## 1. if the positives of queries are corect: 
## 2. if the positives in original labelld pairs are picked correctly n val and train and test sets : need to figure out if collection or query id is an issue anywhere
## 3.

,actual_query,aspect,collection,label,made_up_query
29348859,Nutraceuticals industry,Customer Industry,"Okay, here's the final MeCure Industries Plc f...",1,Customer Industry - Nutraceuticals industry
29348860,Nutraceuticals industry,Customer Industry,"Okay, here's the final company fact sheet for ...",1,Customer Industry - Nutraceuticals industry
29348861,Nutraceuticals industry,Customer Industry,"Okay, here's the Life Extension fact sheet bas...",1,Customer Industry - Nutraceuticals industry
29348862,Nutraceuticals industry,Customer Industry,Here's the LifeZen company fact sheet based on...,1,Customer Industry - Nutraceuticals industry
29348863,Nutraceuticals industry,Customer Industry,"Okay, here's the Tiger Fitness company fact sh...",1,Customer Industry - Nutraceuticals industry
...,...,...,...,...,...
29349065,Nutraceuticals industry,Customer Industry,"Okay, here's the company fact sheet for IDEM i...",1,Customer Industry - Nutraceuticals industry
29349066,Nutraceuticals industry,Customer Industry,Here's the final Nest Catalyst company fact sh...,1,Customer Industry - Nutraceuticals industry
29349067,Nutraceuticals industry,Customer Industry,"Okay, here's the company fact sheet for First ...",1,Customer Industry - Nutraceuticals industry
29349068,Nutraceuticals industry,Customer Industry,Here's the NutriBiotic company fact sheet base...,1,Customer Industry - Nutraceuticals industry
29349069,Nutraceuticals industry,Customer Industry,Here's a company fact sheet for DSM-Firmenich ...,1,Customer Industry - Nutraceuticals industry

In [67]:
all_labelled_positives['collection']=all_labelled_positives['collection'].apply(lambda x:x.replace("\t", " ").replace("\n", " "))

/tmp/ipykernel_3977/2050759878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_labelled_positives['collection']=all_labelled_positives['collection'].apply(lambda x:x.replace("\t", " ").replace("\n", " "))

In [136]:
query='Customer Industry - Healthcare Providers'

In [137]:
query_pos_dict={}

In [138]:
query_pos_dict[query]={'all':all_labelled_positives[all_labelled_positives.made_up_query==query].collection.to_list()}

In [139]:
query_pos_dict[query]['val']=val_triples_df_pos[val_triples_df_pos['query']==query].collection.to_list()

In [140]:
query_pos_dict[query]['train']=train_triples_df_pos[train_triples_df_pos['query']==query].collection.to_list()

In [141]:
query_pos_dict[query]['test']=test_triples_df_pos[test_triples_df_pos['query']==query].collection.to_list()

In [142]:
print(len(query_pos_dict[query]['train']),len(query_pos_dict[query]['val']))

100 27

In [143]:
print(len(set(query_pos_dict[query]['train'])-set(query_pos_dict[query]['all'])),len(set(query_pos_dict[query]['val'])-set(query_pos_dict[query]['all'])),
     len(set(query_pos_dict[query]['test'])-set(query_pos_dict[query]['all'])))
set(query_pos_dict[query]['val'])-set(query_pos_dict[query]['all'])
# set(query_pos_dict[query]['train'])-set(query_pos_dict[query]['all'])

0 3 0

{'Here\'s the Headshottr company fact sheet based on our analysis of their website and some supplementary online research:  **Headshottr Company Fact Sheet**  **Company Name:** Headshottr  **Products/Services:** AI-generated professional headshots.  The service offers various packages with differing numbers of generated images, outfit/pose options, and generation times.  **Industry:**  Photography, AI-powered image generation, SaaS (Software as a Service)  **Target Audience:** Professionals, job seekers, and individuals needing high-quality headshots for online profiles (LinkedIn, resumes, job applications, etc.).  The tiered pricing structure suggests targeting different career stages or seniority levels.  **Unique Selling Propositions (USPs) & Key Differentiators:**  * AI-generated headshots delivered in under an hour (for standard packages). * Multiple pricing tiers offering varying quantities of photos and customization options. *  Claims to use "real AI technology" without faceswapping. *  Headshots suitable for social media use. * 24/7 Support  **Business Model:** SaaS (Software as a Service)  **Revenue Model:** Tiered subscription model ("Entry Level," "Manager," "Executive") with varying pricing based on the number of photos, generation time, and customization options.  **Technology Used:**  The company mentions using "advanced AI technology" and "real AI technology," but specific details about the underlying technology stack are not publicly available.  **Competitive Landscape:**  Our initial research did not reveal clearly defined direct competitors with readily available information on their offerings, pricing, or market share.  Further investigation is needed to fully assess the competitive landscape.   This fact sheet provides a preliminary overview of Headshottr.  More in-depth market research and competitive analysis would be beneficial for a complete understanding of their position within the market.',
 "Okay, here's the OpsLab company fact sheet based on the information we could gather from their website and publicly available information.  Keep in mind that due to limited publicly available data, some sections require further investigation.  **OpsLab Company Fact Sheet**  **Company Name:** OpsLab  **Products/Services:** OpsLab provides asset management software designed to enhance operational readiness.  Their key features include automated long-range flight scheduling with disruption management, operational readiness level forecasting, mission-optimized route planning, and automated shift scheduling for ground crews, dispatchers, and other personnel.  They currently serve both the defense (U.S. Air Force and U.S. Navy) and commercial aviation sectors.  **Industry:** Software as a Service (SaaS), Aviation Software, Defense Technology, Asset Management Software  **Target Audience:** U.S. Air Force, U.S. Navy, Commercial Airlines  **Unique Selling Propositions (USPs):**  Automation of key operational processes, including flight scheduling, disruption handling, readiness forecasting, and route optimization, leading to improved operational readiness for defense clients and cost reduction for commercial airlines.  **Business Model:** B2B SaaS (Software as a Service)  **Technology Used:**  This information is not publicly available and requires further research.  **Revenue Model:**  A subscription-based SaaS model is inferred, but specific pricing details and subscription tiers are unavailable and require further investigation.  **Competitive Landscape:**  Information on key competitors and their offerings is not readily available and requires further research.   **Overall Assessment:** OpsLab appears to be a promising B2B SaaS company operating in a niche market with a potentially strong value proposition for both defense and commercial aviation clients.  However, further due diligence is crucial to assess their technology, market penetration, financial performance, and competitive positioning more thoroughly.  The lack of publicly available information on their technology stack, pricing, and competitive landscape highlights the need for more in-depth research before making any investment decisions.",
 "Okay, here's the final fact sheet for Gordon Commercial, based on our research.  Keep in mind that due to the limited information available publicly on their website and through online searches, this fact sheet contains significant gaps.  Further investigation, including direct contact with the company, is strongly recommended for a more complete understanding.   **Gordon Commercial Fact Sheet**  **Company Name:** Gordon Commercial  **Website:** gordoncommercial.com  **Industry:** Commercial Real Estate Brokerage  **Target Audience:** Businesses and individuals involved in commercial real estate transactions in the Bay Area, California. This includes property owners, developers, tenants, and investors.  **Products/Services:** Commercial real estate brokerage services encompassing sales and leasing of Office, Industrial, and Retail properties.  **Unique Selling Propositions (USPs) and Key Differentiators:**  Not identifiable from publicly available information.  The website lacks details on competitive advantages or unique selling points.  Further research is crucial.  **Business Model:** B2B (Business-to-Business)  **Revenue Model:** Commission-based (percentage of transaction value)  **Technology Used:**  Not specified on the website.  **Competitive Landscape:**  Highly competitive. The Bay Area commercial real estate market has numerous large and small brokerage firms.  Specific competitor analysis requires further research.  **Company Background:** Limited information is available online.  Further research is needed to understand the company's history, mission, and detailed background.  **Contact Information:**  lori@gordoncommercial.com, broker@gordoncommercial.com, kevin@gordoncommercial.com, jonathan@gordoncommercial.com, barbara@gordoncommercial.com, 510 898-0513  **Note:** This fact sheet is incomplete due to the limited information available publicly.  To gain a comprehensive understanding of Gordon Commercial, direct contact with the company is highly recommended.  We were unable to find any case studies, client testimonials, or news articles about the company online.  Their website is primarily focused on property listings and lacks detailed information about the company itself."}

In [145]:
all_labelled_positives

,actual_query,aspect,collection,label,made_up_query
0,Artificial Intelligence,Industry,"Okay, here's the company fact sheet for Empowe...",1,Industry - Artificial Intelligence
1,Artificial Intelligence,Industry,Here's the KNS Technologies fact sheet based o...,1,Industry - Artificial Intelligence
2,Artificial Intelligence,Industry,"Okay, here's a company fact sheet for hi.guru ...",1,Industry - Artificial Intelligence
3,Artificial Intelligence,Industry,Here's a fact sheet for Lanchi Ventures based ...,1,Industry - Artificial Intelligence
4,Artificial Intelligence,Industry,"Here's the company fact sheet for nGrow.ai, ba...",1,Industry - Artificial Intelligence
...,...,...,...,...,...
54084477,Interpretation Services,Product/Service,Here's the Currency Remit App fact sheet based...,1,Product/Service - Interpretation Services
54084478,Interpretation Services,Product/Service,"Here's a company fact sheet for Kmong.com, bas...",1,Product/Service - Interpretation Services
54084479,Interpretation Services,Product/Service,"Here's a company fact sheet for Shownotes.io, ...",1,Product/Service - Interpretation Services
54084480,Interpretation Services,Product/Service,"Here's a company fact sheet for Voccent, based...",1,Product/Service - Interpretation Services
54084481,Interpretation Services,Product/Service,Here's a company fact sheet for Foule Factory/...,1,Product/Service - Interpretation Services

In [165]:
## overall difference 

false_positives_in_val=all_labelled_positives[['made_up_query','collection','label']].rename(columns={'made_up_query':'query'}).merge(val_triples_df_pos,on=['query','collection'],how='right')
false_positives_in_train=all_labelled_positives[['made_up_query','collection','label']].rename(columns={'made_up_query':'query'}).merge(train_triples_df_pos,on=['query','collection'],how='right')
false_positives_in_test=all_labelled_positives[['made_up_query','collection','label']].rename(columns={'made_up_query':'query'}).merge(test_triples_df_pos,on=['query','collection'],how='right')

In [166]:
false_positives_in_val=false_positives_in_val[false_positives_in_val['label'].isna()]
false_positives_in_train=false_positives_in_train[false_positives_in_train['label'].isna()]
false_positives_in_test=false_positives_in_test[false_positives_in_test['label'].isna()]

In [152]:
val_triples_df_pos

,qid,pid,query,collection,set
0,141,19226,Consumer Segment - Artists,Here's the Jansen Art Center fact sheet based ...,val
1,12,13820,Revenue Model - E-commerce Direct Sales,"Okay, here's the final company fact sheet for ...",val
2,496,33288,Product/Service - Generative AI,Here's the Gizzmo.ai company fact sheet based ...,val
3,663,18751,Product/Service - DeFi Platforms,"Okay, here's the Finceptor company fact sheet ...",val
4,429,50548,Consumer Segment - Fitness Professionals,Here's the company fact sheet for Phoenix Capi...,val
...,...,...,...,...,...
22537,1056,14392,Industry - Music Tech,"Okay, here's the final ElasticStage company fa...",val
22538,1056,15831,Industry - Music Tech,Here's the Play Virtuoso company fact sheet ba...,val
22539,1056,16843,Industry - Music Tech,"Okay, here's the Uberchord company fact sheet ...",val
22540,1056,30013,Industry - Music Tech,Here's the Salt Lick Incubator fact sheet base...,val
22541,1056,34298,Industry - Music Tech,Here's a UseMogul company fact sheet based on ...,val

In [111]:
all_labelled_positives[all_labelled_positives.collection.str.contains(' Area42')]

,actual_query,aspect,collection,label,made_up_query
820317,Digital Health,Industry,"Okay, here's the final Area42 fact sheet based...",1,Industry - Digital Health
1076384,Healthcare IT,Industry,"Okay, here's the final Area42 fact sheet based...",1,Industry - Healthcare IT
7653472,B2B,Business Model,"Okay, here's the final Area42 fact sheet based...",1,Business Model - B2B
8970376,Professional Services,Business Model,"Okay, here's the final Area42 fact sheet based...",1,Business Model - Professional Services
9019180,Consulting,Business Model,"Okay, here's the final Area42 fact sheet based...",1,Business Model - Consulting
17521658,Consulting Services,Revenue Model,"Okay, here's the final Area42 fact sheet based...",1,Revenue Model - Consulting Services
17570175,Custom Development,Revenue Model,"Okay, here's the final Area42 fact sheet based...",1,Revenue Model - Custom Development
17722741,Implementation Fees,Revenue Model,"Okay, here's the final Area42 fact sheet based...",1,Revenue Model - Implementation Fees
23511112,Government Agencies,Customer Industry,"Okay, here's the final Area42 fact sheet based...",1,Customer Industry - Government Agencies
23564316,Healthcare Providers,Customer Industry,"Okay, here's the final Area42 fact sheet based...",1,Customer Industry - Healthcare Providers
24381343,Public Sector,Customer Industry,"Okay, here's the final Area42 fact sheet based...",1,Customer Industry - Public Sector
31196366,Enterprises,Consumer Segment,"Okay, here's the final Area42 fact sheet based...",1,Consumer Segment - Enterprises
31247155,Corporations,Consumer Segment,"Okay, here's the final Area42 fact sheet based...",1,Consumer Segment - Corporations
33549615,Hospitals,Consumer Segment,"Okay, here's the final Area42 fact sheet based...",1,Consumer Segment - Hospitals
33600719,Clinics,Consumer Segment,"Okay, here's the final Area42 fact sheet based...",1,Consumer Segment - Clinics
35752775,Nonprofits,Consumer Segment,"Okay, here's the final Area42 fact sheet based...",1,Consumer Segment - Nonprofits
35803728,Charities,Consumer Segment,"Okay, here's the final Area42 fact sheet based...",1,Consumer Segment - Charities
36007361,Public Sector Workers,Consumer Segment,"Okay, here's the final Area42 fact sheet based...",1,Consumer Segment - Public Sector Workers
53470873,Government Contractors,Customer Industry,"Okay, here's the final Area42 fact sheet based...",1,Customer Industry - Government Contractors

In [ ]:
'Win Semiconductor Corporation'

In [66]:
query_pos_dict[query]['all']

["Okay, here's the final MeCure Industries Plc fact sheet based on our research.  Keep in mind that some information, specifically pricing models and a detailed competitive landscape, remains unavailable due to limitations in publicly accessible data.  Further investigation using the strategies outlined above (industry reports, competitor website analysis, news articles, etc.) would be necessary to complete the picture.\n\n\n**MeCure Industries Plc Fact Sheet**\n\n**Company:** MeCure Industries Plc\n\n**Website:** mecure.com\n\n**Industry:** Pharmaceutical Manufacturing (Generics and Specialty Pharmaceuticals, Nutraceuticals)\n\n**Target Audience:** Pharmacists, healthcare providers, consumers in Nigeria\n\n**Products/Services:** OTC Medicines, Branded Generics (tablets, capsules, liquids), Dietary Supplements, Track & Trace Solution (smartphone-based authentication program)\n\n**Unique Selling Propositions (USPs) and Key Differentiators:**\n\n* Track & Trace solution combating counterfeit drugs.\n* Focus on affordable generic drugs and innovative specialty pharmaceuticals, increasing access to high-quality healthcare across Nigeria.\n* Commitment to quality control and patient safety (ISO 9001:2015 accredited).\n* Experienced management team with extensive pharmaceutical industry knowledge.\n* Recent listing on the NGX, increasing visibility and access to capital.\n* Pharmacist Loyalty Program (details unavailable).\n\n**Business Model:** B2B (to pharmacies and distributors) and B2C (direct to consumers)\n\n**Revenue Model:**  Likely a mix of wholesale and retail sales of pharmaceutical products.  Specific pricing details (e.g., per-unit pricing, tiered pricing, volume discounts) are unavailable.\n\n**Technology Used:** Track & Trace technology (in collaboration with ACG Inspection), state-of-the-art manufacturing methods and technology for dietary supplements. Further details on other technologies are not explicitly stated.\n\n**Competitive Landscape:**  Not explicitly detailed on the website or readily available through online searches.  Further research is needed to identify and analyze key competitors in the Nigerian pharmaceutical market.\n\n\nThis fact sheet provides a solid foundation, but additional research is strongly recommended to fill in the gaps regarding pricing and competitive analysis.",
 "Okay, here's the final company fact sheet for PlusCBD Oil based on our analysis of their website, pluscbdoil.com:\n\n\n**Company Fact Sheet: PlusCBD Oil**\n\n**1. Company:** PlusCBD Oil (pluscbdoil.com)\n\n**2. Industry:**  Cannabidiol (CBD) Oil and Wellness Products; Direct-to-Consumer (DTC) E-commerce\n\n**3. Products & Services:** PlusCBD Oil offers a range of CBD products designed for sleep, pain relief, and stress reduction.  These include:\n\n* CBD Oils\n* Softgels (various mg strengths and counts)\n* Gummies (including sleep-focused formulations)\n* Topicals (balms, roll-ons, creams)\n* Sprays\n\n**4. Target Audience:** Health-conscious consumers seeking natural wellness solutions, specifically those interested in CBD products for sleep, pain management, and stress relief.\n\n**5. Unique Selling Propositions (USPs) & Key Differentiators:**\n\n* **Emphasis on Quality and Transparency:**  The website prominently features Certificates of Analysis (COAs), highlighting their commitment to product quality and testing.\n* **Loyalty Program:** The PlusPOINTS loyalty program incentivizes repeat purchases.\n* **Wholesale Program:**  Indicates a potential B2B element, although details are limited on the website.\n\n**6. Business Model:** Primarily Direct-to-Consumer (DTC) e-commerce, with potential for a secondary B2B (wholesale) component.\n\n**7. Revenue Model:** Direct sales of products through their website.\n\n**8. Technology Used:**  Not explicitly detailed on the website.\n\n**9. Competitive Landscape:**  The website doesn't directly name competitors. However, PlusCBD Oil operates in a highly competitive market with numerous other brands offering similar CBD products.  Competitive analysis would require further research beyond the website.\n\n\n**Overall Assessment:** PlusCBD Oil appears to be a well-established player in the DTC CBD market, focusing on product quality and customer loyalty.  Further investigation into their financials, marketing strategies, and competitive positioning would be necessary for a complete venture capital assessment.",
 "Okay, here's the Life Extension fact sheet based on our analysis of their website:\n\n**Life Extension Fact Sheet**\n\n**Company:** Life Extension\n\n**Industry:** Direct-to-Consumer (D2C) e-commerce, Dietary Supplements, Health and Wellness\n\n**Target Audience:** Health-conscious adults (primarily over 40) interested in longevity, preventative health, and nutritional supplementation.  They are likely to be relatively affluent and actively seeking ways to improve their health and well-being.\n\n**Products/Services:** A broad range of dietary supplements categorized by health concern (e.g., heart health, brain health, immune support, etc.).  These include vitamins, minerals, and specialized formulas.  They also offer educational resources and information related to healthy aging and various health topics.\n\n**Unique Selling Propositions (USPs):**\n\n* **High-quality supplements:**  Emphasis on sourcing and manufacturing processes.\n* **Scientific backing:**  Marketing materials highlight research and scientific studies supporting their products.\n* **Wide product range:**  Caters to a variety of health concerns and individual needs.\n* **Educational resources:**  Provides valuable information to empower consumers to make informed decisions.\n* **Focus on longevity:**  Clearly positions itself as a brand dedicated to extending healthy lifespan.\n\n**Business Model:** Direct-to-consumer (D2C) e-commerce.  Products are sold directly to consumers through their website.\n\n**Revenue Model:** Direct sales of products through their website.  Pricing varies depending on the product and quantity purchased.\n\n**Technology Used:**  Not explicitly detailed on the website.  However, given the scale of their operation and online presence, we can infer the use of e-commerce platforms, CRM systems, and potentially data analytics tools for marketing and customer management.\n\n**Competitive Landscape:**  This requires further research beyond the scope of the website analysis.  However, Life Extension operates in a highly competitive market with numerous other supplement brands and health and wellness companies.\n\n\nThis fact sheet provides a solid overview of Life Extension.  Further investigation into their financials, marketing strategies, and competitive landscape would provide a more complete picture for investment consideration.",
 "Here's the LifeZen company fact sheet based on the information gathered from their website:\n\n**Company Name:** LifeZen\n\n**Website:** lifezen.in\n\n**Industry:** Health and Wellness, Dietary Supplements; Direct-to-Consumer (D2C) e-commerce\n\n**Products/Services:** LifeZen offers a range of dietary supplements focusing on immunity, bladder health, kidney detox, and hair and skin health.  Specific products include IMMUWIN (immunity booster), PROSTOWIN (bladder relief), STONEX (kidney detox), ASHWAMED Ashwagandha (immunity booster), and several TUSKCA effervescent tablets with various formulations (Vitamin C + Zinc, Biotin + Selenium + Zinc, Glutathione).\n\n**Target Audience:** Individuals seeking natural health supplements and immunity boosters.\n\n**Unique Selling Propositions (USPs) & Key Differentiators:**  The company emphasizes the use of natural ingredients.  While specific USPs aren't explicitly stated, the focus on natural formulations and targeting specific health concerns could be considered differentiators in a competitive market.  Further market research would be needed to confirm this.\n\n**Business Model:** Direct-to-consumer (D2C) e-commerce.\n\n**Revenue Model:** Direct sales of products through their online store.\n\n**Technology Used:**  The website doesn't specify the technology used for its e-commerce platform or backend systems.\n\n**Competitive Landscape:**  This requires further research beyond the website to identify direct competitors in the Indian dietary supplement market.\n\n\n**Overall Assessment:** LifeZen operates a straightforward D2C e-commerce business selling natural health supplements.  Their success will depend on factors such as brand building, effective marketing, and competitive pricing within a crowded market.  Further investigation into their marketing strategy, customer acquisition costs, and the competitive landscape is recommended.",
 'Okay, here\'s the Tiger Fitness company fact sheet based on our analysis of their website and some preliminary competitive research.  Keep in mind that a more thorough competitive analysis would require further investigation.\n\n**Tiger Fitness Company Fact Sheet**\n\n**Company Name:** Tiger Fitness\n**Website:** tigerfitness.com\n**Industry:** Health and Fitness, Supplements Retail, E-commerce\n**Products & Services:** Supplements (amino acids, creatine, protein powders, etc.), vitamins and minerals, sports nutrition products, apparel and clothing, books and accessories, supplement stacks, free and paid workout plans, articles on health and fitness, recipes, fitness tools and calculators, loyalty rewards program.\n\n**Target Audience:** Individuals interested in fitness, health, and sports nutrition; likely includes athletes and fitness enthusiasts.\n\n**Unique Selling Propositions (USPs):** Wide variety of supplements and fitness resources; loyalty rewards program; free workout plans; product categorization by type and brand; top 10 best-selling product lists.\n\n**Business Model:** Direct-to-consumer (D2C) e-commerce\n\n**Revenue Model:** Primarily product sales; potentially affiliate marketing through their "Join Our Team" program (further investigation needed to confirm).\n\n**Technology Used:** Shopify\n\n**Competitive Landscape:**  The competitive landscape requires further research. Initial web searches indicate numerous competitors in the online supplement and fitness retail space, many offering similar product categories and marketing strategies.  A deeper dive is needed to identify direct competitors and assess their market positioning relative to Tiger Fitness.  We have not yet identified specific competitors and their market positioning in detail.\n\n\nThis fact sheet provides a solid foundation for further due diligence.  The next steps should include a more in-depth competitive analysis, a review of customer reviews and ratings, and an assessment of Tiger Fitness\'s marketing and sales strategies.',
 'Okay, here\'s the Puori company fact sheet based on our analysis of their website:\n\n**Puori Company Fact Sheet**\n\n**Company Name:** Puori\n\n**Products and Services:** Puori offers a range of high-quality dietary supplements, including fish oil capsules (O3), magnesium complex (M3), vitamin D (D3), a combination sachet containing O3, M3, and D3 (P3), a multivitamin and mineral supplement (V), whey protein (PW1), and a whey and collagen blend (CP2).  Detailed product specifications, including pricing (both one-time purchase and subscription options), are available on individual product pages on their website.\n\n**Industry:** Dietary Supplements, Health and Wellness\n\n**Target Audience:** Health-conscious consumers seeking high-quality, transparent supplements.  This is inferred from their marketing materials emphasizing purity and third-party testing.\n\n**Unique Selling Propositions (USPs) and Key Differentiators:**\n\n* **"Pure Origin, Potency and Peace of Mind"**:  This is their core brand message.\n* **Third-party testing by The Clean Label Project:**  Testing is conducted against over 200 contaminants, with results publicly available online.\n* **Transparency:**  Detailed testing results are shared to build consumer trust.\n* **Subscription Service with Discount:** A 15% discount is offered for monthly subscriptions.\n\n**Business Model:** Direct-to-consumer (D2C) –  selling directly to consumers through their website.\n\n**Technology Used:**  Not specified on the website.\n\n**Revenue Model:**  Subscription and one-time purchases.\n\n**Competitive Landscape:**  The website does not explicitly list competitors. Further market research would be needed to fully assess the competitive landscape.\n\n\nThis fact sheet provides a comprehensive overview of Puori based on publicly available information from their website.  Further investigation, including competitor analysis and financial data, would be beneficial for a more complete due diligence process.',
 "Here's a company fact sheet for SmartFlow Industrial, based on information gathered from their website:\n\n**Company Name:** SmartFlow Industrial\n\n**Products & Services:** SmartFlow Industrial designs and manufactures innovative open channel filtration and separation systems and consumable filter modules.  Their product lines include the PuroSep® systems (Lynx, Pegasus, Phoenix, Infinity, Gemini) and ConSep® modules (1000, 3000, 7000, 11000).  They offer custom system design based on application-specific testing.\n\n**Industry & Target Audience:**  SmartFlow Industrial operates in a B2B model, serving a diverse range of industries including nutraceuticals, chemicals, food and beverage processing, water treatment, renewable fuels, wastewater processing, FOG removal, process recovery, and biopharmaceuticals.\n\n**Unique Selling Propositions (USPs):**  SmartFlow's key differentiators include advanced technology solutions for solids separation,  the ability to replace centrifugation steps at a lower capital cost, ease of solving solids separation problems, cost-effective retrofits for existing plants, reduced evaporator energy needs, custom membrane pore sizes for precise protein retention, and the production of protein-free products to simplify downstream processes.\n\n**Business Model:**  B2B direct sales of complete filtration systems and consumable filter modules.\n\n**Revenue Model:**  A dual revenue stream is likely, combining upfront sales of complete systems with recurring revenue generated from the sale of replacement filter modules.\n\n**Technology Used:**  Specific technologies are not detailed on the website.\n\n**Competitive Landscape:**  Information on competitors is not provided on the website.\n\n**Overall Market Position (Estimate):** Based on the breadth of industries served and the focus on advanced technology, SmartFlow Industrial appears to be a niche player within the broader solids separation market, potentially targeting higher-value applications requiring specialized solutions.\n\n**Financial Health (Estimate):**  Without access to financial statements, a definitive assessment is impossible. However, the company's focus on custom solutions and recurring revenue from consumables suggests a potential for strong profitability if market demand and sales execution are successful.  Further due diligence would be required to assess their financial health accurately.",
 "Okay, here's the Mikart company fact sheet based on our analysis of their website, mikart.com.  Keep in mind that due to the limited information publicly available on the site, some sections are less detailed than we'd ideally like.  Further research, potentially including contacting Mikart directly, would be beneficial for a more complete picture.\n\n**Mikart Company Fact Sheet**\n\n**Company:** Mikart\n\n**Website:** mikart.com\n\n**Industry:** Contract Development and Manufacturing Organization (CDMO) for Pharmaceutical and Nutraceutical Industries\n\n**Target Audience:** Pharmaceutical and nutraceutical companies requiring CDMO services, with a focus on those needing geriatric, pediatric, and controlled substance formulations.\n\n**Products, Services, and Offerings:**  Contract development and manufacturing services encompassing:\n\n* Oral solid dose manufacturing\n* Liquid and suspension manufacturing\n* Packaging services\n* Formulation development\n* Process development\n* Analytical testing\n\n**Unique Selling Propositions (USPs) and Key Differentiators:** Mikart emphasizes high-quality products and services, strong client partnerships, and expertise in specialized formulations (geriatric, pediatric, and controlled substances). However, concrete differentiators beyond these general claims are not clearly defined on their website.\n\n**Business Model:** B2B CDMO (Contract Development and Manufacturing Organization)\n\n**Technology Used:**  Not specified on the website.  Further investigation is needed.\n\n**Revenue Model:**  Likely fee-for-service, project-based pricing.  Specific pricing details are unavailable on the website.\n\n**Competitive Landscape:**  Not detailed on the website.  Further market research is required.\n\n**Value Proposition:** Mikart positions itself as a high-quality CDMO providing comprehensive development and manufacturing services to pharmaceutical and nutraceutical companies, particularly those requiring specialized formulations.  Their focus is on strong client relationships.\n\n\n**Overall Assessment:** Mikart presents itself as a competent CDMO, but the website lacks crucial details regarding their technology, pricing, competitive advantages, and specific revenue model.  More in-depth research is strongly recommended before making any investment decisions.",
 "Okay, here's the final BeeBird company fact sheet based on our analysis.  Keep in mind that because we couldn't directly access and fully translate the website, some information remains incomplete and relies on inferences from the limited English content and common e-commerce practices.  Further investigation would be needed for a complete picture.\n\n\n**BeeBird Company Fact Sheet**\n\n**Company Name:** BeeBird\n\n**Website:** beebird.io\n\n**Industry:** Health and Wellness (specifically, supplements and related products derived from bee products)\n\n**Target Audience:** Primarily Turkish-speaking consumers interested in natural health and wellness solutions.  Further market research is needed to define the target audience more precisely (age, income, etc.).\n\n**Products/Services:**  BeeBird appears to sell a range of health and wellness products, likely including supplements such as propolis extract, bee pollen capsules, and royal jelly.  The exact product line requires further investigation of the product pages.\n\n**Unique Selling Propositions (USPs) and Key Differentiators:**  Currently unknown.  Further analysis of the website's marketing materials and competitive landscape is needed to identify BeeBird's unique selling points.  Potential USPs could include the use of natural ingredients, high-quality sourcing, or specific health benefits associated with their products.\n\n**Business Model:** Direct-to-consumer (DTC) e-commerce.\n\n**Revenue Model:** Direct sales of products through their website.  They accept Turkish Lira (TRY), US Dollars (USD), and Euros (EUR).\n\n**Technology Used:**  Likely utilizes a standard e-commerce platform (Shopify, WooCommerce, etc.) for their online store.  Specific technology details are unknown.\n\n**Competitive Landscape:**  Requires further external research to identify direct and indirect competitors within the Turkish health and wellness supplement market.\n\n**Overall Assessment:** BeeBird is a DTC e-commerce business operating primarily within the Turkish market.  Their focus on bee-derived health and wellness products presents a niche opportunity.  However, their reliance on a primarily Turkish-language website may limit their potential for international expansion.  Further due diligence, including a thorough website analysis and competitive landscape assessment, is strongly recommended before making any investment decisions.",

In [120]:
len(set(train_triples_df_pos.collection.to_list())-set(val_triples_df_pos.collection.to_list()))

22702

In [121]:
len(set(val_triples_df_pos.collection.to_list())-set(train_triples_df_pos.collection.to_list()))

3295

In [122]:
len(set(test_triples_df_pos.collection.to_list())-set(train_triples_df_pos.collection.to_list()))

4376

In [123]:
len(set(train_triples_df_pos.collection.to_list())-set(test_triples_df_pos.collection.to_list()))

18460

In [124]:
len(set(val_triples_df_pos.collection.to_list())-set(test_triples_df_pos.collection.to_list()))

4396

In [125]:
len(set(test_triples_df_pos.collection.to_list())-set(val_triples_df_pos.collection.to_list()))

9719

In [117]:
val_triples_df_pos

,qid,pid,query,collection,set
0,141,19226,Consumer Segment - Artists,Here's the Jansen Art Center fact sheet based ...,val
1,12,13820,Revenue Model - E-commerce Direct Sales,"Okay, here's the final company fact sheet for ...",val
2,496,33288,Product/Service - Generative AI,Here's the Gizzmo.ai company fact sheet based ...,val
3,663,18751,Product/Service - DeFi Platforms,"Okay, here's the Finceptor company fact sheet ...",val
4,429,50548,Consumer Segment - Fitness Professionals,Here's the company fact sheet for Phoenix Capi...,val
...,...,...,...,...,...
22537,1056,14392,Industry - Music Tech,"Okay, here's the final ElasticStage company fa...",val
22538,1056,15831,Industry - Music Tech,Here's the Play Virtuoso company fact sheet ba...,val
22539,1056,16843,Industry - Music Tech,"Okay, here's the Uberchord company fact sheet ...",val
22540,1056,30013,Industry - Music Tech,Here's the Salt Lick Incubator fact sheet base...,val
22541,1056,34298,Industry - Music Tech,Here's a UseMogul company fact sheet based on ...,val

In [27]:
val_triples_df_pos[val_triples_df_pos['query']=='Customer Industry - Nutraceuticals industry']

,qid,pid,query,collection,set
111,0,12296,Customer Industry - Nutraceuticals industry,"Okay, here's the company fact sheet for PSC Bi...",val
693,0,2861,Customer Industry - Nutraceuticals industry,Here's a company fact sheet for Arjuna Natural...,val
2396,0,13935,Customer Industry - Nutraceuticals industry,Here's the final Circulegg fact sheet based on...,val
2888,0,3098,Customer Industry - Nutraceuticals industry,"Okay, here's the company fact sheet for IDEM i...",val
3345,0,51292,Customer Industry - Nutraceuticals industry,Here's a company fact sheet for The Vitamin Sh...,val
3945,0,36737,Customer Industry - Nutraceuticals industry,Here's the Vital Solutions fact sheet based on...,val
5322,0,43187,Customer Industry - Nutraceuticals industry,"Here's a company fact sheet for Myovaterra, ba...",val
5582,0,15354,Customer Industry - Nutraceuticals industry,"Okay, here's the final company fact sheet for ...",val
5609,0,32291,Customer Industry - Nutraceuticals industry,Here's the company fact sheet for Internationa...,val
6193,0,33445,Customer Industry - Nutraceuticals industry,Here's the Free Soul company fact sheet based ...,val
8207,0,13023,Customer Industry - Nutraceuticals industry,Here's a company fact sheet for DSM-Firmenich ...,val
8208,0,13963,Customer Industry - Nutraceuticals industry,"Okay, here's the final Be Levels company fact ...",val
8209,0,17435,Customer Industry - Nutraceuticals industry,"Okay, here's the final Claridream company fact...",val
8210,0,18459,Customer Industry - Nutraceuticals industry,Here's the Looni company fact sheet based on o...,val
8211,0,22197,Customer Industry - Nutraceuticals industry,"Okay, here's the AlgiSys BioSciences, Inc. fac...",val
8212,0,23808,Customer Industry - Nutraceuticals industry,Here's a company fact sheet for Focus Suppleme...,val
8213,0,28885,Customer Industry - Nutraceuticals industry,Here's the Crosstree Capital fact sheet based ...,val
8214,0,33251,Customer Industry - Nutraceuticals industry,"Okay, here's the AdvitamIP company fact sheet ...",val
8215,0,37960,Customer Industry - Nutraceuticals industry,"Okay, here's the final Swisse Company Fact She...",val
8216,0,50262,Customer Industry - Nutraceuticals industry,"Okay, here's the final Curlew Capital fact she...",val

In [6]:
# import pandas as pd

pd.read_csv('./experiments/colbert_aspect_training/run_1741616267/data/train/corpus.train.colbert.tsv',sep='\t')

,0,"Okay, here's the final company fact sheet for Sorgenia, based on our analysis of their website, sorgenia.it. Keep in mind that this is based on publicly available information and further investigation might be needed for a truly comprehensive understanding. **Sorgenia Company Fact Sheet** **Company Name:** Sorgenia **Website:** sorgenia.it **Industry:** Energy (Electricity & Gas), Telecommunications (Fiber Internet), Renewable Energy (Photovoltaic Systems) **Target Audience:** Residential and business customers in Italy **Products/Services:** Electricity, natural gas, fiber optic internet, photovoltaic system installation and maintenance, participation in energy communities, electric vehicle charging app (MyNextMove). **Business Model:** Primarily B2C and B2B, offering a suite of energy and telecommunications services. **Revenue Model:** Direct sales of energy and telecommunication services. Revenue likely also generated through the installation and maintenance of photovoltaic systems. **Unique Selling Propositions (USPs) and Key Differentiators:** While not explicitly stated, the website strongly emphasizes competitive pricing and a commitment to green energy solutions (photovoltaic systems and energy communities). Further research is needed to identify other potential differentiators. **Technology Used:** The specific technology stack is not publicly disclosed. However, their offerings imply expertise in renewable energy technologies, mobile app development (MyNextMove), and potentially smart grid technologies. **Competitive Landscape:** Requires further market research to identify and analyze key competitors in the Italian energy and telecommunications markets. **Sustainability Initiatives:** Sorgenia actively promotes its involvement in renewable energy through photovoltaic systems and energy communities. However, the extent and specifics of their sustainability initiatives require further investigation. **Overall Assessment:** Sorgenia appears to be a significant player in the Italian energy and telecommunications market, focusing on providing competitive services while emphasizing sustainability. However, a deeper dive into their financial performance, market share, and competitive strategies is necessary for a complete investment assessment. Further investigation into their technology infrastructure, customer acquisition costs, and long-term growth strategy would also be beneficial."
0,1,Here's the company fact sheet for Borderless C...
1,2,"Okay, here's the True Linkswear company fact s..."
2,3,"Okay, here's the final company fact sheet for ..."
3,4,"Okay, here's the final fact sheet for Mount Ca..."
4,5,"Okay, here's the final company fact sheet for ..."
...,...,...
51533,51534,Here's a company fact sheet for Like Air Snack...
51534,51535,"Okay, here's the final company fact sheet for ..."
51535,51536,"Okay, here's the Dovetail fact sheet based on ..."
51536,51537,"Okay, here's the final fact sheet for Unutilit..."
51537,51538,Here's the Pinnacle Experiential Marketing com...

In [7]:
51537

51537

In [ ]:
from colbert.data import Queries
from colbert.infra import Run, RunConfig, ColBERTConfig
from colbert import Searcher

if __name__=='__main__':
    with Run().context(RunConfig(nranks=1, experiment="msmarco")):

        config = ColBERTConfig(
            root="/path/to/experiments",
        )
        searcher = Searcher(index="msmarco.nbits=2", config=config)
        queries = Queries("/path/to/MSMARCO/queries.dev.small.tsv")
        ranking = searcher.search_all(queries, k=100)
        ranking.save("msmarco.nbits=2.ranking.tsv")

## validating if the model has learned to differentiate between aspects

In [29]:
from colbert.modeling.checkpoint import Checkpoint
from colbert.infra import ColBERTConfig
from colbert.modeling.colbert import colbert_score

checkpoint = './experiments/colbert_aspect_training/none/run_1741616267/checkpoints/colbert-best'
checkpoint = "./experiments/colbert_aspect_training/none/run_1741795018/checkpoints/colbert-7000"

config = ColBERTConfig(
                bsize=64,  # Small batch size for testing
                accumsteps=2,
                lr=5e-6,
                nway=2,  # Binary pairs for simplicity  
                query_maxlen=32,  
                doc_maxlen=512,   
                dim=128,
                similarity="cosine",
                use_ib_negatives=False,
                maxsteps=10000,  # Limit training steps
                warmup=250,
                val_check_interval=150,
                val_ema_alpha=0.95,
                attend_to_mask_tokens=True
            )




import torch
import numpy as np
ckpt = Checkpoint(checkpoint, colbert_config=config)

/home/ec2-user/SageMaker/ColBERT/colbert/utils/amp.py:12: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler()

In [31]:
test_df=rankings.copy()

In [33]:
test_df['aspect']= test_df['query'].apply(lambda x:x.split(' - ')[0])
test_df['og_query']= test_df['query'].apply(lambda x:x.split(' - ')[1])

In [36]:
test_df.aspect.unique()

array(['Industry', 'Business Model', 'Revenue Model', 'Customer Industry',
       'Consumer Segment', 'Product/Service', 'Technology'], dtype=object)

In [38]:
consumer_df=test_df[test_df.aspect.isin(['Customer Industry','Consumer Segment'])]
industry_df=test_df[test_df.aspect.isin(['Industry'])]

array(['Aerospace & Defense industry', 'Agriculture industry',
       'Automotive industry', 'Banking industry',
       'Biotechnology industry', 'Chemical Manufacturing industry',
       'Cloud Computing Providers', 'Construction industry',
       'Consumer Electronics industry', 'Consumer Goods industry'],
      dtype=object)

In [39]:
common_queries=set(industry_df.og_query).intersection(consumer_df.og_query)

In [40]:
common_queries

{'Electric Utilities', 'Online Marketplaces'}

In [43]:
consumer_test_subset_df=consumer_df[consumer_df['og_query'].isin(common_queries)]
industry_test_subset_df=industry_df[industry_df['og_query'].isin(common_queries)]

In [54]:
industry_test_subset_df.iloc[0].collection

'Here\'s a company fact sheet for directly.me, based on our analysis of their website and some competitive research:  **Company Name:** directly.me  **Products/Services:**  A digital marketplace enabling the buying and selling of digital goods. This includes content (articles, ebooks), images, videos, how-to guides, services, and other digital products.  The platform also facilitates the monetization of knowledge and audience through direct connections.  A unique feature is the ability to offer "bounties" (further details on this feature would require additional research).  **Industry:** Digital marketplace, creator economy, online education/courses.  **Target Audience:**  Digital creators (e.g., writers, educators, artists, software developers), individuals seeking to monetize their expertise or existing audience, and consumers seeking digital products and services.  **Unique Selling Propositions (USPs) & Key Differentiators:**  Ease of use for selling digital goods; a large existing network of over 3,602,600 direct connections; and the unique offering of bounties (the exact mechanics of which require further investigation).  This differentiates it from competitors by emphasizing direct creator-consumer relationships and potentially offering incentives for both buyers and sellers.  **Business Model:** Multi-sided platform (MSP) connecting buyers and sellers of digital goods.  **Revenue Model:** Transaction-based fees (a percentage of each sale).  **Technology Used:** Not specified on the website; further research is needed.  **Competitive Landscape:**  Key competitors include Gumroad, Etsy, Udemy, Skillshare, and other digital marketplaces and online learning platforms. directly.me distinguishes itself through its focus on direct connections, ease of use for sellers, and the bounty system.   This fact sheet provides a preliminary overview.  A more in-depth analysis, including a deeper dive into their technology, bounty system, financial performance, and a more comprehensive competitive analysis, would be beneficial for a complete investment assessment.'

In [51]:
consumer_test_subset_df

,qid,doc_id,rank,score,collection,query,aspect,og_query
451000,451,15290,1,16.765625,Here's the company fact sheet for Webster Elec...,Customer Industry - Electric Utilities,Customer Industry,Electric Utilities
451001,451,33867,2,16.718750,Here's a company fact sheet for Cowell Electri...,Customer Industry - Electric Utilities,Customer Industry,Electric Utilities
451002,451,45912,3,16.531250,"Here's the company fact sheet for Bulbs.com, b...",Customer Industry - Electric Utilities,Customer Industry,Electric Utilities
451003,451,46135,4,16.515625,"Here's the company fact sheet for S&S Power, b...",Customer Industry - Electric Utilities,Customer Industry,Electric Utilities
451004,451,17655,5,16.500000,Here's the final company fact sheet for Broadw...,Customer Industry - Electric Utilities,Customer Industry,Electric Utilities
...,...,...,...,...,...,...,...,...
575995,575,1119,996,13.890625,Here's the AlignedBiz company fact sheet based...,Customer Industry - Online Marketplaces,Customer Industry,Online Marketplaces
575996,575,30368,997,13.890625,Here's the Carmichael Lynch company fact sheet...,Customer Industry - Online Marketplaces,Customer Industry,Online Marketplaces
575997,575,9936,998,13.875000,"Okay, here's a company fact sheet for SmartPla...",Customer Industry - Online Marketplaces,Customer Industry,Online Marketplaces
575998,575,50994,999,13.867188,Here's the Skipta company fact sheet based on ...,Customer Industry - Online Marketplaces,Customer Industry,Online Marketplaces
575999,575,309,1000,13.859375,Here's the Gladiator Law Marketing company fac...,Customer Industry - Online Marketplaces,Customer Industry,Online Marketplaces

In [53]:
consumer_test_subset_df.iloc[-2].collection

"Here's the Skipta company fact sheet based on our research:  **Company:** Skipta  **Founded:** 2009  **Founder:** Dr. Theodore Search, Pharm.D.  **Industry:** Healthcare Marketing, B2B SaaS  **Target Audience:** Pharmaceutical and healthcare marketers  **Products/Services:** Skipta offers a suite of marketing solutions targeting healthcare professionals (HCPs) through its network of online medical communities.  These solutions are categorized into: Awareness, Brand Content, Condition Community, Peer-to-Peer – Editorial Content, and Market Access. Each category contains multiple sub-categories, but specifics are not detailed on the website.  **Business Model:** B2B SaaS. Skipta provides a platform and associated services to pharmaceutical and healthcare companies for marketing to HCPs.  **Revenue Model:**  Likely subscription-based or project-based fees.  Further investigation is needed to determine the exact pricing structure and subscription tiers.  **Technology Used:**  The specific technology stack used by Skipta is not publicly disclosed on their website.  **Unique Selling Propositions (USPs):** Skipta's key differentiators include its network of verified healthcare professional communities and its targeted marketing solutions designed to reach specific HCP audiences.  **Competitive Landscape:**  Further research is required to fully analyze Skipta's competitive landscape.  However, it's likely they compete with other healthcare marketing companies offering digital solutions and HCP engagement platforms.   **Overall Assessment:** Skipta operates in a growing market with a potentially strong value proposition.  However, further due diligence is needed to fully assess their financial performance, competitive positioning, and the specifics of their technology and revenue model."

In [80]:
test_query='Online Marketplaces'
test_query='Electric Utilities'
query2=f'Customer Industry - {test_query}'
query1=f'Industry - {test_query}'

In [81]:
pos_for_1=industry_test_subset_df[industry_test_subset_df['query']==query1].collection.sample(2).to_list()
pos_for_2=consumer_test_subset_df[consumer_test_subset_df['query']==query2].collection.sample(2).to_list()

In [82]:
pos_for_1

["Here's the company fact sheet for Enduro-Tech Energy Services (eesokc.com), based on the information available on their website:  **Enduro-Tech Energy Services Fact Sheet**  **Company Name:** Enduro-Tech Energy Services  **Website:** eesokc.com  **Products & Services:**  Enduro-Tech Energy Services offers a range of specialty products across multiple industries.  These include:  * **Oilfield Specialty Chemicals:**  Products for fracturing, simulation, completion, and production in the oil and gas industry. * **Enduro-Bond® Anti-Corrosive Coatings:** Coatings designed to prevent corrosion. * **Enzyme Products:** Enzymes for applications in animal nutrition, soil conditioning, and H2S and odor removal.  Specific product names mentioned include Wonderscent and ECOZYME.   **Industry:** The company operates in several industries: oilfield services, anti-corrosive coatings, and enzyme production.  **Target Audience:**  The primary target audience appears to be B2B, encompassing oil and gas companies, agricultural businesses, and potentially other sectors depending on the specific applications of their enzyme products.  The website does not explicitly list all target audiences.  **Unique Selling Propositions (USPs):**  * Personalized specialty products tailored to customer needs. * Excellent service and customer support. * Longer-lasting solutions compared to competitors. * All products are manufactured in the U.S.A.  **Business Model:** B2B direct sales.  **Technology Used:**  The website does not detail the specific technologies used in their product manufacturing or service delivery.  **Revenue Model:**  The revenue model is inferred to be direct sales.  Specific pricing structures, volume discounts, or other sales models are not publicly available on the website.  **Competitive Landscape:**  Information on the competitive landscape is not provided on the website.  **Value Proposition:** To provide customers with a competitive advantage through the delivery of personalized specialty products, excellent service, and longer-lasting solutions that add value to their operations.   **Notes:**  Several aspects of the business, including specific technologies, detailed revenue model, and competitive landscape, require further investigation beyond the information available on the company website.",
 "Okay, here's the final Energyminer GmbH fact sheet based on our analysis of their website and additional web searches.  Keep in mind that some information remains unclear due to the limited publicly available data.  **Energyminer GmbH Fact Sheet**  **1. Company:** Energyminer GmbH  **2. Website:** energyminer.eu  **3. Products, Services, and Offerings:** The primary offering is the Energyfish, a modular hydropower technology designed to generate clean energy from river currents.  **4. Industry:** Renewable Energy, specifically Hydropower.  **5. Target Audience:**  The target audience is likely B2B, encompassing energy companies, utilities, and potentially government agencies seeking sustainable energy solutions.  **6. Unique Selling Propositions (USPs) and Key Differentiators:** The Energyfish is marketed as a sustainable, efficient, and environmentally friendly hydropower solution with minimal impact on river ecosystems.  Its modular design allows for scalability to suit various river sizes and energy needs.  **7. Business Model:**  The business model is unclear based on publicly available information.  It is *likely* a B2B model, involving the direct sale of Energyfish units to energy companies or utilities.  However, alternative models such as licensing agreements or revenue sharing based on energy generated cannot be ruled out without further information.  **8. Technology Used:** The website highlights the innovative design of the Energyfish, but specific technological details are not publicly disclosed.  **9. Revenue Model:**  Unclear.  Potential models include direct sales of Energyfish units, licensing agreements, or revenue sharing based on energy generated.  Further investigation is needed to determine the precise revenue model.  **10. Competitive Landscape:**  Not explicitly addressed on the website or in publicly available information.  **11. Value Proposition:** Sustainable and efficient clean energy generation from river currents with minimal environmental impact.   **12.  Overall Assessment:** Energyminer GmbH presents a promising technology with a strong focus on sustainability. However, a lack of transparency regarding their business model and financial details limits a comprehensive assessment.  Further due diligence, potentially involving direct contact with the company, is recommended before making any investment decisions."]

In [83]:
pos_for_2

['The website smithpinktrucks.com is actually for Smith Plumbing, Heating, Cooling & Electrical, a company based in Colorado Springs.  Therefore, it\'s not a trucking company as the domain name might initially suggest.  Here\'s the company fact sheet based on the information gathered from their website:  **Company Name:** Smith Plumbing, Heating, Cooling & Electrical  **Industry:**  Home Services (Plumbing, HVAC, Electrical)  **Target Audience:** Residential and commercial customers in Colorado Springs and surrounding areas.  **Products and Services:**  Plumbing repairs and installations; drain cleaning and sewer line repairs; HVAC repairs, replacements, and installations; electrical repairs and installations; commercial plumbing; air conditioning installation, maintenance, and repair; heating repair, maintenance, and installation; indoor air quality services (duct cleaning, air filtration); water heater services; 24/7 emergency service.  **Unique Selling Propositions (USPs) and Key Differentiators:**  "Integrity First Pricing," 24/7 availability with a four-hour guarantee or free service call, USA Club Membership with benefits (no overtime charges and 15% discounts), satisfaction guarantee.  The company also highlights its long history (since 1974) and recognition on the Inc. 5000 list (2020, 2021, 2022).  **Business Model:** B2C and B2B service business.  **Revenue Model:** Service fees based on the type and complexity of the work performed. Additional revenue streams may exist through the USA Club Membership.  **Technology Used:** Not specified on the website.  **Competitive Landscape:**  Not available from the website.   This fact sheet provides a summary of Smith Plumbing, Heating, Cooling & Electrical based solely on information available on their website.  Further research would be needed to fully assess their competitive landscape and other aspects of their business.',
 'Here\'s the Paragon Air Heater company fact sheet based on the information gathered from their website:  **Company Fact Sheet: Paragon Air Heater**  **1. Company Overview:**  Paragon Air Heater, established in 1967, is a provider of rotary and tubular air heaters and related services to industrial clients.  Their website emphasizes a commitment to superior customer service and product solutions.  **2. Products, Services, and Offerings:**  * **Products:** Rotary and tubular air heaters, replacement parts (including high-performance radial seals and basketed elements), DuraTEC coating. * **Services:** Inspections, turnkey services.  **3. Industry and Target Audience:**  * **Industry:** Industrial heating equipment manufacturing and maintenance. * **Target Audience:** Businesses and industrial facilities requiring rotary and tubular air heaters, likely in manufacturing, processing, or other industrial settings.  The B2B nature is strongly suggested by the website\'s focus on services and lack of direct-to-consumer sales.  **4. Unique Selling Propositions (USPs) and Key Differentiators:**  The website highlights "the air heater industry’s best customer service and product solutions" as a key differentiator.  Specific technological advantages or unique features beyond this claim are not explicitly detailed on the website.  **5. Business Model:**  Primarily B2B (Business-to-Business), offering products and services directly to industrial clients.  **6. Revenue Model:**  Direct sales of air heaters and replacement parts, plus service revenue from inspections and turnkey projects.  Specific pricing details are not publicly available on the website.  **7. Technology Used:**  The website does not explicitly detail the specific technologies used in their manufacturing processes or product design.  Further investigation would be needed to ascertain this information.  **8. Competitive Landscape:**  The competitive landscape is not discussed on the Paragon Air Heater website.  Further market research would be required to identify and analyze key competitors.']

In [84]:
queries=[query1,query2]
data=pos_for_1+pos_for_2
query_score_dict={}
for query in queries:
    Q = ckpt.queryFromText([query])
    D = ckpt.docFromText(data, bsize=1024)[0]
    D_mask = torch.ones(D.shape[:2], dtype=torch.long)
    scores = colbert_score(Q, D, D_mask).flatten().cpu().numpy().tolist()
    query_score_dict[query]=scores
    # ranking_colbert = np.argsort(scores)[::-1]

In [85]:
query_score_dict

{'Industry - Electric Utilities': [6.9609375, 9.984375, 6.07421875, 7.6328125],
 'Customer Industry - Electric Utilities': [12.3828125,
  11.734375,
  8.609375,
  11.25]}

In [87]:
consumer_df.og_query.unique()[:10]

array(['Aerospace & Defense industry', 'Agriculture industry',
       'Automotive industry', 'Banking industry',
       'Biotechnology industry', 'Chemical Manufacturing industry',
       'Cloud Computing Providers', 'Construction industry',
       'Consumer Electronics industry', 'Consumer Goods industry'],
      dtype=object)

In [92]:
consumer_df[consumer_df.og_query.isin(['Banking industry'])].collection.iloc[2]

"Okay, here's the final Arch Finance fact sheet based on our analysis of their website and the limitations of our ability to conduct external web searches:  **Arch Finance Fact Sheet**  **Company:** Arch Finance  **Website:** archfinance.com.au  **Industry:** Commercial Real Estate Finance Brokerage  **Target Audience:** Australian businesses involved in commercial property, including property owners, developers, and tenants.  They also appear to work with commercial property brokers.  **Products/Services:** Commercial real estate financing solutions.  While specific loan types aren't explicitly listed, case studies reveal they handle loans for acquisitions, debt refinancing, and business relocation.  Their services are presented as tailored to individual client needs.  **Unique Selling Propositions (USPs):**  Personalized service, a deep understanding of the Australian commercial property market, and a demonstrated track record of successful loan placements (as shown in case studies).  They emphasize a close working relationship with clients to create bespoke finance solutions.  **Business Model:** B2B (Business-to-Business) brokerage. Arch Finance acts as an intermediary between commercial property clients and lenders.  **Revenue Model:**  Commission-based.  This is inferred from their business model as a brokerage; they likely earn fees from lenders for successful loan placements.  This is not explicitly stated on the website.  **Technology Used:**  Not specified on the website.  **Competitive Landscape:**  Unable to determine from website or simulated web searches.  Further research is needed to identify their key competitors within the Australian commercial real estate finance brokerage market.  **Loan Types:**  The website doesn't provide a comprehensive list.  However, case studies indicate they facilitate financing for acquisitions, debt refinancing, and business relocations.  The exact range of loan products offered remains unclear and requires further investigation.   **Important Note:**  This fact sheet is based solely on information publicly available on the Arch Finance website.  A more complete picture, including a detailed competitive analysis and a precise list of loan products, would require additional research beyond the scope of this analysis."

In [93]:
consumer_df[consumer_df.og_query.isin(['Automotive industry'])].collection.iloc[0]

"Here's the final DealerSocket company fact sheet, based on our research:  **DealerSocket Company Fact Sheet**  **Company:** DealerSocket  **Website:** dealersocket.com  **Industry:** Automotive Software (B2B SaaS)  **Target Audience:** Automotive dealerships, particularly independent dealerships.  **Products & Services:**  Integrated platform including:  * **Digital Retailing:** PrecisePrice (transparent pricing), DealerFire (website & digital marketing) * **Inventory Management:** Inventory+ * **Dealer Management System (DMS):** Auto/Mate (for independent dealers) * **Customer Relationship Management (CRM):** RevenueRadar (integrated data mining & digital retailing tools) * **Equity Mining:** Tools to maximize used car inventory value   **Unique Selling Propositions (USPs):**  * Integrated platform streamlining dealership operations. * Focus on independent dealerships. * Emphasis on increasing profitability and efficiency.   **Business Model:** B2B SaaS (Software as a Service) – subscription-based access to software and services.  **Revenue Model:** Subscription fees based on features and number of users/dealerships.  (Precise details not publicly available.)  **Competitive Landscape:** Key competitors include CDK Global, Cox Automotive, and Reynolds and Reynolds, among others. (Further, more in-depth research is needed for a complete competitive analysis.)  **Technology Used:** Not publicly disclosed; likely cloud-based technologies given the SaaS model. (Further research is needed to determine the specific technology stack.)   This fact sheet provides a solid overview of DealerSocket.  However, keep in mind that some information, such as precise revenue figures and the detailed technology stack, requires further investigation beyond publicly available resources."

In [94]:
consumer_df[consumer_df.og_query.isin(['Automotive industry'])].collection.iloc[1]

"Here's the AutoAnything company fact sheet based on our analysis of their website:  **Company Name:** AutoAnything  **Website:** autoanything.com  **Industry:**  B2C E-commerce, Automotive Parts and Accessories Retail  **Target Audience:** Individual car and truck owners, potentially some smaller repair shops.  **Products, Services, and Offerings:**  A wide selection of automotive parts and accessories, categorized by vehicle make and model (Ford, Chevy, Ram/Dodge, GMC, etc.), and further sub-categorized into numerous areas such as brakes, bumpers, engine parts, exhaust systems, interior accessories, lift kits, lighting, suspension components, wheels and tires, and bed covers.  They also offer deals and promotions.  Customer service is provided via phone, chat, and email.  **Unique Selling Propositions (USPs) and Key Differentiators:** While not explicitly stated as unique selling points on the homepage,  AutoAnything's extensive catalog,  vehicle-specific product filtering, and free shipping on orders over $119 suggest a focus on convenience and selection.  The partnership with AmericanTrucks.com for truck parts strengthens their offerings in that segment.  **Business Model:** B2C (Business-to-Consumer) e-commerce.  **Revenue Model:** Direct sales of automotive parts and accessories through their online platform.  **Technology Used:**  The specific technology stack is not publicly disclosed on the website. However, it's implied to include an e-commerce platform capable of handling product catalogs, order processing, payment processing, and customer relationship management (CRM) functions.  **Competitive Landscape:**  (Information not gathered from the website; requires further external research.)  Likely competitors include other online retailers of automotive parts and accessories, as well as brick-and-mortar auto parts stores.   **Additional Notes:** The website features a strong emphasis on customer service, including FAQs, contact information, and a community support section.  Promotional activities such as sweepstakes are also used to engage customers."

In [ ]:
query=rankings.iloc[0]['query']
data=rankings.iloc[0:500]['collection'].to_list()

In [ ]:
from tqdm import tqdm
query_groups=rankings.groupby('query')
groups_=[]
for query,group in tqdm(query_groups):
    
    data=group.collection.to_list()
    Q = ckpt.queryFromText([query])
    D = ckpt.docFromText(data, bsize=1024)[0]
    D_mask = torch.ones(D.shape[:2], dtype=torch.long)
    scores = colbert_score(Q, D, D_mask).flatten().cpu().numpy().tolist()
    ranking_colbert = np.argsort(scores)[::-1]
    group['true_scores']=scores
    group['true_rank']=ranking_colbert
    groups_.append(group)

## counting tokesn

In [ ]:
from transformers import BertTokenizer

# Load pre-trained BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Input sentence
sentence = "Encode this sentence using BERT tokenizer."

# Encode the sentence
encoded = tokenizer(sentence, 
                    padding='max_length',   # Pad to the maximum length
                    truncation=True,        # Truncate if too long
                    max_length=128,         # Set the max length
                    return_tensors='pt')    # Return as PyTorch tensors

# Encoded output
input_ids = encoded['input_ids']
attention_mask = encoded['attention_mask']

print("Input IDs:", input_ids)
print("Attention Mask:", attention_mask)

In [ ]:
!ls /home/ec2-user/SageMaker/ColBERT/experiments/colbert_aspect_training/run_1741558706/data/test/