In [1]:
import pandas as pd

In [2]:
from colbert.evaluation.evaluator import ColBERTEvaluator

In [3]:
from colbert.infra import ColBERTConfig

In [4]:
config = ColBERTConfig(bsize=32, lr=1e-05, warmup=20_000, doc_maxlen=512, dim=128, attend_to_mask_tokens=False, nway=64, accumsteps=1, similarity='cosine', use_ib_negatives=True)

In [5]:
evaluator=ColBERTEvaluator(config=config,checkpoint_path='bert-base-uncased')

Some weights of HF_ColBERT were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['linear.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[Mar 06, 06:54:40] Loading segmented_maxsim_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...

In [6]:
import os
eval_out_path='/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/eval_out'
os.makedirs(eval_out_path,exist_ok=True)

In [7]:
from pathlib import Path
p=Path('baleen')

In [8]:
from colbert.evaluation.triplet_loader import convert_triplets_to_qrels

In [9]:
queries_path='/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/queries.train.colbert.tsv'
triplets_path='/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/triples.train.colbert.jsonl'
qrels_path = convert_triplets_to_qrels(triplets_path,output_path=os.path.join(Path(queries_path).parent,'qrels.train.colbert.tsv')) if triplets_path else None

#> Loading triplets from /Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/triples.train.colbert.jsonl
#> Loaded 9 queries with positives
#> Average positives per query: 1.56
#> Average negatives per query: 1.33
#> Converted triplets to qrels format: /Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/qrels.train.colbert.tsv

In [10]:
p.root

''

In [11]:
eval_res=evaluator.evaluate(
        queries_path='/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/queries.train.colbert.tsv',
        collection_path='/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/corpus.train.colbert.tsv',
        triplets_path='/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/triples.train.colbert.jsonl',
        output_path=os.path.join(eval_out_path,'output.train.colbert.tsv'),
        batch_size=128,
        depth=1000,
        step=None
    )

[Mar 06, 06:54:40] #> Loading the queries from /Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/queries.train.colbert.tsv ...
[Mar 06, 06:54:40] #> Got 20 queries. All QIDs are unique.

[Mar 06, 06:54:40] #> Loading collection...
0M
#> Loading triplets from /Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/triples.train.colbert.jsonl
#> Loaded 9 queries with positives
#> Average positives per query: 1.56
#> Average negatives per query: 1.33
#> Converted triplets to qrels format: /Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/qrels.train.colbert.tsv
[Mar 06, 06:54:40] #> Loading qrels from /Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_verification/test/qrels.train.colbert.tsv ...
[Mar 06, 06:54:40] #> Loaded qrels for 9 unique queries with 1.56 positives per query on average.

[Mar 06, 06:54:49] #> Processing query 1 / 20

#> QueryTokenizer.tensorize(batch_text[0], batch_background[0], bsize) ==
#> Input: price||information on it, 		 True, 		 None
#> Output IDs: torch.Size([32]), tensor([ 101,    1, 3976, 1064, 1064, 2592, 2006, 2009,  102,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
         103,  103,  103,  103,  103,  103,  103,  103])
#> Output Mask: torch.Size([32]), tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])

[Mar 06, 06:54:51] #> Processing query 2 / 20
[Mar 06, 06:54:53] #> Processing query 3 / 20
[Mar 06, 06:54:55] #> Processing query 4 / 20
[Mar 06, 06:54:57] #> Processing query 5 / 20
[Mar 06, 06:54:59] #> Processing query 6 / 20
[Mar 06, 06:55:01] #> Processing query 7 / 20
[Mar 06, 06:55:03] #> Processing query 8 / 20
[Mar 06, 06:57:06] #> Processing query 9 / 20
[Mar 06, 06:57:30] #> Processing query 10 / 20
[Mar 06, 06:57:52] #> Processing query 11 / 20
[Mar 06, 06:58:07] #> Processing query 12 / 20
[Mar 06, 06:58:21] #> Processing query 13 / 20
[Mar 06, 06:58:33] #> Processing query 14 / 20
[Mar 06, 06:58:35] #> Processing query 15 / 20
[Mar 06, 06:58:37] #> Processing query 16 / 20
[Mar 06, 06:58:39] #> Processing query 17 / 20
[Mar 06, 06:58:41] #> Processing query 18 / 20
[Mar 06, 06:58:43] #> Processing query 19 / 20
[Mar 06, 06:58:45] #> Processing query 20 / 20
[Mar 06, 06:58:47] [0] 		 Metric ranking/max_query_idx = 19 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/num_queries_added = 20 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/MRR.10 = 0.03958333333333333 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/MRR.100 = 0.05317927170868347 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/MRR.1000 = 0.05317927170868347 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/Success.10 = 0.2 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/Success.100 = 0.45 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/Success.1000 = 0.45 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/Recall.10 = 0.18333333333333332 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/Recall.100 = 0.45 (step 19)
[Mar 06, 06:58:47] [0] 		 Metric ranking/Recall.1000 = 0.45 (step 19)
Precision@30 = 0.021666666666666667
Precision@50 = 0.018421052631578942
Precision@100 = 0.018421052631578942
Precision@200 = 0.018421052631578942
Precision@500 = 0.018421052631578942
NDCG@10 = 0.07304411052376385
NDCG@100 = 0.14218625876618843

In [12]:
eval_res

defaultdict(dict,
            {'mrr': {10: 0.03958333333333333,
              100: 0.05317927170868347,
              1000: 0.05317927170868347},
             'success': {10: 0.2, 100: 0.45, 1000: 0.45},
             'recall': {10: 0.18333333333333332, 100: 0.45, 1000: 0.45},
             'precision': {30: 0.021666666666666667,
              50: 0.018421052631578942,
              100: 0.018421052631578942,
              200: 0.018421052631578942,
              500: 0.018421052631578942},
             'ndcg': {10: np.float64(0.07304411052376385),
              100: np.float64(0.14218625876618843)}})

In [23]:
queries=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_curated/test/queries.train.colbert.tsv',sep='\t',header=None)
docs=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_curated/test/corpus.train.colbert.tsv',sep='\t',header=None)
queries.columns=['qid','query']
docs.columns=['pid','doc']
import json

with open('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/data/human_curated/test/triples.train.colbert.jsonl') as f:
    triples = [json.loads(line) for line in f]

pd.DataFrame(triples,columns=['qid','pid','nid'])

    qid  pid  nid
0     2   37   24
1    12   28   19
2    13   22    8
3    13   20   17
4     4   23   27
5     0   11   23
6    15   37    1
7     8   31   36
8    13    3   12
9     8    2   36
10   16   29   16
11   12   18   19
12   18   14   11
13    2   13   10

In [7]:
### calculating all posiives and negatives per query

(1/19+1/23 +1/7 +1/19 +1/13+1/3 +1/16 +1/3+1/5)/9

0.14418758946790983

In [8]:
(1/19 + 1/23 + 1/7 + 1/19 + 1/13 + 1/3 + 1/16 + 1/3 + 1/5) / 9

0.14418758946790983

In [24]:
docs['phrase_present']=docs['doc'].apply(lambda x: [phrase for phrase in all_phrases if phrase in x])

    pid                                                doc
0     0  Document 180: The service is poor. The quality...
1     1               Document 208: The price is average.
2     2                Document 184: The quality is poor.
3     3  Document 461: The service is average. The qual...
4     4                   Document 71: The price is good.
5     5  Document 95: The quality is excellent. The ser...
6     6              Document 40: The price is excellent.
7     7                    Document 4: The price is poor.
8     8  Document 85: The quality is poor. The price is...
9     9                Document 356: The quality is good.
10   10  Document 447: The price is terrible. The servi...
11   11  Document 378: The price is good. The quality i...
12   12  Document 23: The price is terrible. The qualit...
13   13  Document 396: The price is excellent. The serv...
14   14  Document 365: The price is good. The service i...
15   15               Document 430: The price is average.
16   16  Document 352: The service is excellent. The qu...
17   17                Document 250: The quality is poor.
18   18  Document 383: The service is average. The pric...
19   19  Document 307: The quality is excellent. The pr...
20   20  Document 306: The service is excellent. The qu...
21   21            Document 215: The service is terrible.
22   22  Document 247: The service is poor. The quality...
23   23  Document 328: The quality is poor. The service...
24   24             Document 434: The price is excellent.
25   25  Document 393: The service is poor. The quality...
26   26                  Document 205: The price is good.
27   27                  Document 300: The price is poor.
28   28  Document 321: The quality is terrible. The ser...
29   29  Document 218: The service is poor. The quality...
30   30            Document 374: The quality is terrible.
31   31  Document 392: The quality is excellent. The se...
32   32  Document 274: The service is average. The qual...
33   33  Document 331: The service is poor. The price i...
34   34                Document 148: The quality is poor.
35   35  Document 362: The service is average. The pric...
36   36              Document 14: The price is excellent.
37   37  Document 412: The quality is good. The price i...

In [35]:
queries['aspect']=queries['query'].apply(lambda x: x.split('||')[0])
queries['phrase']=queries['query'].apply(lambda x: x.split('||')[1].split(' ')[0])
all_aspects=queries['aspect'].unique()
all_phrases=queries['phrase'].unique()

In [36]:
all_phrases

array(['information', 'rating', 'review', 'how', 'tell', "what's",
       'describe', 'details'], dtype=object)

In [3]:
4/9

0.4444444444444444

In [5]:
(1/30+2/30+1/30+2/30+2/30+3/30+1/30+1/30+1/30)/9

0.05185185185185185

4/9

In [39]:
docs['phrase_present']=docs['doc'].apply(lambda x: [phrase for phrase in all_phrases if phrase.lower() in x.lower()])

In [41]:
docs.doc.iloc[0]

'Document 180: The service is poor. The quality is poor. '