In [1]:
import pandas as pd

In [74]:
industries=pd.read_csv('/Users/pragalbh.devsingh/Downloads/sqllab_untitled_query_1_20250508T103526.csv')
industries=industries[['company_id','Company Name','industry']].rename(columns={'Company Name':'company_name','industry':'industry_chain_hierarchy'})

In [75]:
industries.columns

Index(['company_id', 'company_name', 'industry_chain_hierarchy'], dtype='object')

In [76]:
industries.industry_chain_hierarchy.iloc[0]

'Media & Entertainment > Video > Television > Streaming Platform'

In [77]:
industries[industries.industry_chain_hierarchy.str.contains('specific')].head().iloc[0].industry_chain_hierarchy

'Enterprise > IT Software > Business Application > Advertising > Ad Buying & Selling Platform > Ad Exchange > Programmatic Platform > Kids-specific'

In [78]:
industries.to_csv('data/industries.csv',index=False)

In [45]:
import pandas as pd
factsheets=pd.read_parquet('/Users/pragalbh.devsingh/Downloads/all_factsheets_cleaned (1).parquet')

In [46]:
factsheets.factsheet=factsheets.factsheet.str.replace(',',';')

In [47]:
factsheets.factsheet.iloc[0]

"the company company fact sheet **\n\n **company name :**gogo \n\n **website :**the company \n\n **products & services :**the company provides inflight internet connectivity and entertainment solutions for both commercial and business aviation .    their offerings include a range of connectivity solutions for various aircraft types and sizes ; utilizing a combination of satellite and air - to - ground ( atg ) technologies .    a key product is the the company avance system ; a factory - installed option available from major business aviation oems ; supported by a large mro network .    they emphasize a global network and redundancy for reliable connectivity .    the avance system uniquely offers dual network capabilities ( leo satellite and atg ) ; enabling bandwidth prioritization and service redundancy .   unlimited atg data plans include the company galileo data at no additional cost . \n\n **industry :**in - flight connectivity and entertainment \n\n **target audience :**airlines ; business aviation operators ; and passengers . \n\n **unique selling propositions ( usps ) & key differentiators :**\n\n * wide range of connectivity solutions for diverse aircraft types . \n * strong partnerships with major business aviation oems and a large mro network ; including factory installation options . \n * dual network capabilities ( satellite and atg ) providing redundancy and enhanced reliability . \n\n **business model :**hybrid b2b ( selling to airlines and business aviation operators ) and b2c ( selling directly to passengers ) . \n\n **technology used :**  the company utilizes a global network of satellites ( specifically mentioning leo satellites ) and terrestrial towers ( atg ) .    precise details on satellite constellations and terrestrial network infrastructure require further research . \n\n **revenue model :**  a combination of subscription fees from airlines and per - use fees from passengers .    specific pricing details remain unavailable due to limitations in publicly accessible information . \n\n **competitive landscape :**key competitors identified through web searches include viasat ; panasonic avionics ; and intelsat .    market share data and detailed competitive analysis require further research using specialized financial databases . \n\n **financial data :**  detailed financial reports ; investor presentations ; and sec filings were not readily downloadable from publicly available sources .    we attempted to obtain this information through gogo 's investor relations contact form ; but received no response .    the sec 's edgar database ( link provided in previous responses ) contains their filings ; but detailed analysis requires manual review of the documents . \n\n **recent partnerships :**information on recent partnerships requires further research . \n\n **summary :**the company is a well - established player in the inflight connectivity market ; offering a diverse range of solutions and leveraging strong industry partnerships .    their dual - network approach provides a key competitive advantage .   however ; obtaining detailed financial and competitive information requires access to proprietary databases or direct communication with the company . \n\n\n this fact sheet provides a solid foundation ; but further research using specialized financial databases is strongly recommended to complete the analysis and fill in the missing quantitative data . \n "

In [48]:
factsheets.to_csv('data/all_factsheets_cleaned.csv',index=False)

In [49]:
industries.sample(5000).industry_chain_hierarchy.nunique()

3215

In [ ]:
overlapping_industries=industries.merge(industries,on='company_id',how='inner')
overlapping_industries=overlapping_industries[overlapping_industries.industry_chain_hierarchy_x!=overlapping_industries.industry_chain_hierarchy_y]
overlapping_industries.to_csv('data/overlapping_industries.csv',index=False)
overlapping_industries.sample(1000).to_csv('data/overlapping_industries_sample.csv',index=False)
overlapping_industries.sample(100).to_csv('data/overlapping_industries_quickie.csv',index=False)
overlapping_industries.sample(10).to_csv('data/overlapping_industries_tiny.csv',index=False)

In [79]:
pd.concat([pd.read_csv('data/overlapping_industries_sample.csv'),industries[industries.industry_chain_hierarchy.isin(industries.industry_chain_hierarchy.drop_duplicates().sample(500))].sample(5000)]).to_csv('data/industries_sample.csv',index=False)

In [94]:
industries[industries.industry_chain_hierarchy.isin(industries.industry_chain_hierarchy.drop_duplicates().sample(10))].sample(100).to_csv('data/industries_quickey.csv',index=False)

In [3]:
sample_industries=pd.read_csv('data/industries_sample.csv')
quick_industries=pd.read_csv('data/industries_quickie.csv')

In [6]:
sample_industries

,company_id,company_name,industry_chain_hierarchy
0,1104171,Artsploitation Films,Media & Entertainment > Video > Movie > Distri...
1,395052,From Babies with Love,"Non-Profit, Non-Operational & Junk > Non-Profi..."
2,295667,Procurement Foundry,"Non-Profit, Non-Operational & Junk > Non-Profi..."
3,294041,We Make History,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4,533083,Pacific Maritime Association,"Non-Profit, Non-Operational & Junk > Non-Profi..."
...,...,...,...
4995,366340,NRV,Financial Industry > Financial Institution > A...
4996,219830,eCompanies,Financial Industry > Financial Institution > A...
4997,423404,La Fresque du Climat,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4998,615690,Special Olympics Washington,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4999,367063,Laticnios Porto Alegre,"Agriculture, Food & Beverage > Food & Beverage..."

In [7]:
sample_industries.merge(sample_industries,on='company_id',how='inner')

,company_id,company_name_x,industry_chain_hierarchy_x,company_name_y,industry_chain_hierarchy_y
0,1104171,Artsploitation Films,Media & Entertainment > Video > Movie > Distri...,Artsploitation Films,Media & Entertainment > Video > Movie > Distri...
1,395052,From Babies with Love,"Non-Profit, Non-Operational & Junk > Non-Profi...",From Babies with Love,"Non-Profit, Non-Operational & Junk > Non-Profi..."
2,295667,Procurement Foundry,"Non-Profit, Non-Operational & Junk > Non-Profi...",Procurement Foundry,"Non-Profit, Non-Operational & Junk > Non-Profi..."
3,294041,We Make History,"Non-Profit, Non-Operational & Junk > Non-Profi...",We Make History,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4,533083,Pacific Maritime Association,"Non-Profit, Non-Operational & Junk > Non-Profi...",Pacific Maritime Association,"Non-Profit, Non-Operational & Junk > Non-Profi..."
...,...,...,...,...,...
4995,366340,NRV,Financial Industry > Financial Institution > A...,NRV,Financial Industry > Financial Institution > A...
4996,219830,eCompanies,Financial Industry > Financial Institution > A...,eCompanies,Financial Industry > Financial Institution > A...
4997,423404,La Fresque du Climat,"Non-Profit, Non-Operational & Junk > Non-Profi...",La Fresque du Climat,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4998,615690,Special Olympics Washington,"Non-Profit, Non-Operational & Junk > Non-Profi...",Special Olympics Washington,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4999,367063,Laticnios Porto Alegre,"Agriculture, Food & Beverage > Food & Beverage...",Laticnios Porto Alegre,"Agriculture, Food & Beverage > Food & Beverage..."

In [9]:
industries=pd.read_csv('data/industries.csv')

In [10]:
industries

,company_id,company_name,industry_chain_hierarchy
0,1,Apple,Media & Entertainment > Video > Television > S...
1,1,Apple,Consumer Product > Consumer Brand > Electronic...
2,1,Apple,Consumer Product > Consumer Brand > Electronic...
3,1,Apple,Consumer Product > Consumer Brand > Electronic...
4,2,Ubisoft,Media & Entertainment > Video Gaming > Gaming ...
...,...,...,...
671936,1602549,Hairbook,Consumer Internet & Service > Platform > Beaut...
671937,1602549,Hairbook,Consumer Internet & Service > Business Solutio...
671938,1602553,Gaishishukatsu.com,Enterprise > IT Software > Business Applicatio...
671939,1602555,Roglio,Enterprise > Service > Outsourcing > Business ...
671940,1602556,Mirroh.ai,Technology > Internet of Things > Application ...

In [13]:
# 1079527/671941

In [15]:
overlapping_industries

,company_id,company_name_x,industry_chain_hierarchy_x,company_name_y,industry_chain_hierarchy_y
1,1,Apple,Media & Entertainment > Video > Television > S...,Apple,Consumer Product > Consumer Brand > Electronic...
2,1,Apple,Media & Entertainment > Video > Television > S...,Apple,Consumer Product > Consumer Brand > Electronic...
3,1,Apple,Media & Entertainment > Video > Television > S...,Apple,Consumer Product > Consumer Brand > Electronic...
4,1,Apple,Consumer Product > Consumer Brand > Electronic...,Apple,Media & Entertainment > Video > Television > S...
6,1,Apple,Consumer Product > Consumer Brand > Electronic...,Apple,Consumer Product > Consumer Brand > Electronic...
...,...,...,...,...,...
1079505,1602528,Zieg & Liphardt,Real Estate & Construction > Construction > Se...,Zieg & Liphardt,Real Estate & Construction > Construction > Se...
1079512,1602535,Bad & Heizung,Real Estate & Construction > Construction > Se...,Bad & Heizung,Real Estate & Construction > Construction > Se...
1079513,1602535,Bad & Heizung,Real Estate & Construction > Construction > Se...,Bad & Heizung,Real Estate & Construction > Construction > Se...
1079521,1602549,Hairbook,Consumer Internet & Service > Platform > Beaut...,Hairbook,Consumer Internet & Service > Business Solutio...
1079522,1602549,Hairbook,Consumer Internet & Service > Business Solutio...,Hairbook,Consumer Internet & Service > Platform > Beaut...

In [81]:
sample_industries

,company_id,company_name,industry_chain_hierarchy
0,1104171,Artsploitation Films,Media & Entertainment > Video > Movie > Distri...
1,395052,From Babies with Love,"Non-Profit, Non-Operational & Junk > Non-Profi..."
2,295667,Procurement Foundry,"Non-Profit, Non-Operational & Junk > Non-Profi..."
3,294041,We Make History,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4,533083,Pacific Maritime Association,"Non-Profit, Non-Operational & Junk > Non-Profi..."
...,...,...,...
4995,366340,NRV,Financial Industry > Financial Institution > A...
4996,219830,eCompanies,Financial Industry > Financial Institution > A...
4997,423404,La Fresque du Climat,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4998,615690,Special Olympics Washington,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4999,367063,Laticnios Porto Alegre,"Agriculture, Food & Beverage > Food & Beverage..."

In [97]:
factsheets[factsheets.company_id.isin(sample_industries.company_id)].to_csv('data/all_factsheets_cleaned_sample.csv',index=False)
factsheets[factsheets.company_id.isin(quick_industries.company_id)].to_csv('data/all_factsheets_cleaned_quickey.csv',index=False)

In [ ]:
quick_industries

In [59]:
dataset=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/colbert_training/colbert_training_data.csv')

In [62]:
dataset

,query,factsheet,score,is_positive
0,Biotechnology > Biomedicine Research > Molecul...,the company company fact sheet **\n\n **1 . ...,1.0,True
1,Biotechnology > Biomedicine Research > Molecul...,the company fact sheet **\n\n **company name :...,1.0,True
2,Biotechnology > Biomedicine Research > Molecul...,redwood biosciences company fact sheet ( final...,1.0,True
3,Biotechnology > Biomedicine Research > Molecul...,the company fact sheet **\n\n **1 . company ...,1.0,True
4,Biotechnology > Biomedicine Research > Molecul...,company fact sheet : rls therapeutics **\n\n *...,1.0,True
...,...,...,...,...
43297,Service > IT Implementation & Integration > Ou...,visionqms company fact sheet **\n\n **company ...,0.0,False
43298,Service > IT Implementation & Integration > Ou...,company fact sheet : the company ( the company...,0.0,False
43299,Service > IT Implementation & Integration > Ou...,company fact sheet : getexclusively **\n\n **c...,0.0,False
43300,Service > IT Implementation & Integration > Ou...,nordic legal fact sheet **\n\n **company name ...,0.0,False
43301,Service > IT Implementation & Integration > Ou...,the company company fact sheet **\n\n **1 . ...,0.0,False

In [64]:
import json
cleaned_chain_dict=json.loads(open('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/cleaned_chains/cleaned_chains.json').read())

In [67]:
list(cleaned_chain_dict.keys())

['Enterprise > Add-on > Enterprise Software > HR Tech > Payroll Management Solution',
 'Lifestyle > Application > Consumer Internet & Service > Product Discovery, Comparison & Recommendation > Chat-based > Product Discovery > Multiline',
 'Technology > Detection & Ranging > RFID & NFC Reader > Semiconductor > System-on-a-Chip > Fabless',
 'Technology > Smart Lock > Physical Access Control > Internet of Things > Commercial IoT > IoT Application > Connected Building > Safety & Security',
 'Technology > AI Application > Chemical Industry > Business Function-Specific > Artificial Intelligence > R&D Management Solution',
 'Technology > Manufacturer > 3D Printing > Printer > Stereolithography Printers',
 'Healthcare & Life Sciences > Intensive Care Unit > Digital Health > Health Care IT > Hospital Management & Information System > EHR Platform & Practice Management',
 'Technology > Legal Tech > Knowledge Management > AI Application > Business Function-Specific > Artificial Intelligence > Generative AI-Based',
 'Financial Industry > Backend Solution > InsureTech > Product Pricing Solution > Insurer Solution > FinTech',
 'Public Safety & Governance > Industrials > Political Campaign Management > Software > Recruitment Platform > Political Party Operations',
 'Consumer Product > Multiline > Computers, Mobiles & Accessories > Personal Appliance > Electronic Product > E-Commerce > Marketplace > Retailer',
 'Technology > Virtual Reality > Rehabilitation Equipment > Application > Healthcare & Life Sciences > Medical Device',
 'Media & Entertainment > Service > Video > Pre-Production Service',
 'FinTech > Financial Industry > Portfolio Risk Analytics > Backend Solution > Portfolio Management Solution > Trading and Investment',
 'Multiline > Service > Technology > Electronics Ecosystem',
 'Consumer Product > Home Furnishing > Home Decor > Retailer > Party Supplies',
 'Consumer Product > Coffee Machine > Electronic Product > Kitchen > Consumer Brand > Home Appliance > Coffee Pod Maker > Beverage',
 'Enterprise > Business Function-Specific > Enterprise Software > Location > Data Analytics > Customer Intelligence > Marketing and Advertising > Business Analytics',
 'Data Analytics > Customer Success and Service > Business Function-Specific > Business Analytics > Service Intelligence > Enterprise Software > Enterprise',
 'Industrials > Software > Mining > Ore Analysis',
 'Food & Beverage > Agriculture, Food & Beverage > B2B > FoodTech > Hardware Solution > Automatic Juice Machine > Beverage Dispenser',
 'Technology > Internet of Things > IoT Application > Connected Home > Monitoring & Analytics > Leakage Monitoring > Consumer IoT',
 'Consumer Product > E-Commerce > Software > Cross-Border E-Commerce Solution > Business Solution > Storefront',
 'Agriculture > Animal Husbandry > Cow Milk > Poultry & Dairy Farming > Agriculture, Food & Beverage > Agricultural Producer',
 'Media & Entertainment > Enterprise > Content Lifecycle > Content Engagement',
 'Robotics > Industrials > Cleaning Robot > Manufacturer > Technology > Commercial Robotics > Floor Cleaning Robot',
 'Real Estate & Construction > Sale, Leasing & Management > Printing > Service > Brokerage-Focused',
 'Enterprise > Cloud Infrastructure > Serverless Computing > Enterprise Infrastructure',
 'Enterprise > Enterprise Service > IT Implementation and Integration > Application Software > Information Technology > ERP > Consulting',
 'Healthcare & Life Sciences > HRMS > Digital Health > Health Care IT > HR Solution > Hospital Management & Information System',
 'Supply Chain & Logistics > Logistics > Temperature Tracker > Hardware > Freight',
 'Healthcare & Life Sciences > B2B Service > Insurance Provider > Healthcare Service > Advisory & Consulting Service',
 'Artificial Intelligence > Security & Surveillance > AI Application > Physical Security > Technology > Industry-Specific > Safety & Risk Analytics > Industrials',
 'Media & Entertainment > Print Media > News > College News > Print & Digital Media',
 'Technology > Application > Digital Characters > Consumer > Chatbots',
 'Media & Entertainment > Gaming > eSports > Aim Trainer > Coaching & Training',
 'Technology > E-Commerce > Marketplace > 3D Printing > 3D Product',
 'Energy & Utilities > Engineering Service > State of Health > Test & Measurement > Service > Energy Storage',
 'Agriculture, Food & Beverage > Agrochemical > Soil Amendment > Agriculture > Multiline > Farm Input',
 'Enterprise > Organizational Structure & Design > Enterprise Software > Employee Information Management > HR Tech',
 'Retailer > Consumer Product > Clothing, Accessories & Footwear > Swimwear > Clothing > E-Commerce > Activewear & Outdoor Wear > Water Sports',
 'Agriculture, Food & Beverage > Agriculture > Service > Controlled Environment Agriculture',
 'IoT Application > Technology > Commercial IoT > Tracking & Monitoring > Industrial IoT > Internet of Things > Inventory Tracking',
 'Financial Industry > Asset Manager > Securities > Financial Institution > Catalysts',
 'Media & Entertainment > Stealth Mode',
 'Financial Industry > Banking > FinTech > Financial Service > Cryptocurrency > Treasury Management',
 'Utilities > Water Utilities > Membrane-based > Manufacturer > Energy & Utilities > Desalination',
 'Consumer Internet & Service > Platform > Home Service > Laundry',
 'Industrials > Rigid Packaging > Packaging > Application-Based > Compostable Packaging > Manufacturer > Multiline',
 'Consumer Internet & Service > Devotional Apps > Lifestyle > Application',
 'Travel & Hospitality > Booking Platform > Accommodation > Vacation Rental > Hospitality Tech',
 'Media & Entertainment > Live Event > Movie Theatres > Offline Entertainment',
 'GRC > Data Deletion Request Management > Data Privacy > IT Compliance > Personal Information Management System > Enterprise > Compliance Management > Enterprise Software',
 "Consumer Product > Clothing, Accessories & Footwear > Multiline > Clothing > Women's Product > Retailer",
 "Personal Care > Beauty & Personal Care > Men's Product > E-Commerce > Consumer Product > Consumer Brand > Hygiene Product > Intimate Care",
 'Restaurant, Cafe & Bar > Maintenance Solution > Restaurant > Operation Management > Travel & Hospitality > Enterprise Software > Hospitality Tech',
 'Healthcare Service > Psychological Assessments > Behavioral, Speech & Physical Therapy > Pediatric Care Center > Healthcare Provider > Healthcare & Life Sciences > Healthcare Center',
 'Healthcare & Life Sciences > Non Invasive Imaging Device > X-Ray Device > Diagnostic & Monitoring Device > Hospital Equipment & Supplies > Medical Device > Imaging & Radiology Equipment > Portable Device',
 'Agriculture, Food & Beverage > Novel Food > B2C > Alternative Dairy Product > Food & Beverage > E-Commerce > Cultured Dairy Product > FoodTech',
 'Food & Beverage > Nut > Packaged Food > B2C > Snack > E-Commerce > Agriculture, Food & Beverage > FoodTech',
 'Power Production > Geothermal Energy > Tools & Equipment > Drilling > Energy & Utilities > Manufacturer',
 'Enterprise > Lead Management > LinkedIn Automation > Sales Tech > Enterprise Software > Social Media Lead Generation > Lead Generation Tools',
 'Education > EdTech > Digital Learning > Communication Skill > Corporate Training > Personal Development > Game-Based Learning',
 'Media & Entertainment > Video > Lighting > Film Lighting > Hardware',
 'Technology > Thermal Image Sensor > Application-Based > Electronic Component > Sensor > Electronics Ecosystem > Manufacturer > Imaging',
 'Financial Industry > Consulting > Auditing Solution > Financial Service > Service for Businesses',
 'Enterprise > Operating Systems > Server Operating System > Enterprise Infrastructure',
 'Financial Industry > FinTech > Credit Rating Provider > Consumer Finance > Credit Report Management',
 'Consumer Product > Beauty & Personal Care > E-Commerce > Personal Care > Distributor & Wholesaler > Adult Product > Hygiene Product',
 'Industrials > Space Vehicle Launch Service Providers > Terrestrial-based Launch Platform > Service > Space',
 'Automotive > Transportation > Mobility > Transport Tech > B2B > Rental Management',
 'Technology > Opto-Electronic Devices > Multiline > Passive Optical Component > Manufacturer > Electronics Ecosystem',
 'Technology > Business Idea Generation > AI Application > Business Function-Specific > Artificial Intelligence > Enterprise Productivity > Niche Productivity Solution',
 'Financial Industry > FinTech > Decentralized ID > Cryptocurrency > NFT Platform',
 'Healthcare & Life Sciences > Pharmaceuticals > Radiation Therapy > Oncology > Acute Radiation Syndrome',
 'Industrials > Physical Security > CCTV Cameras > Manufacturer',
 'Print & Digital Media > News > Digital Media > Europe-Focused > Local News > Media & Entertainment',
 'Financial Industry > Consumer Finance > Marketplace > Multiline > Insurance > FinTech',
 'Media & Entertainment > Gaming > Social Platform > Highlight Sharing > Content Creation',
 'Energy & Utilities > Wind Energy > Consulting & Advisory > Power Production > Service',
 'FoodTech > Agriculture, Food & Beverage > B2C > Packaged Food > Meat Product > Food & Beverage > Chicken > E-Commerce',
 'Agriculture, Food & Beverage > Soup & Canned Food > E-Commerce > B2C > Convenience Food > FoodTech > Food & Beverage > Fish & Sea-Food Based',
 'Media & Entertainment > Distribution > Television > Video',
 'Enterprise Service > Business Intelligence & Analytics > Outsourcing > Industrial > Enterprise > Knowledge Process Outsourcing > Industry-Specific',
 'Food & Beverage > Packaged Food > FoodTech > Agriculture, Food & Beverage > B2C > Ingredient > E-Commerce > Condiments, Flavors & Sauce',
 'Financial Industry > Consumer Loan > Balance Sheet Lender > Lending Platform > FinTech > Medical Financing > Fertility-Focused',
 'Healthcare & Life Sciences > Neurodivergence Care > Healthcare Provider > Healthcare Service > Home Care',
 'Consumer Internet & Service > Multiline > Application > Product Recommendation > Product Discovery, Comparison & Recommendation > Apparel, Accessories and Footwear > Lifestyle',
 'Biotechnology > Biotherapeutic > Healthcare & Life Sciences > Biomedicine Research > Genetic Engineering > Genomic Medicine > Gene Therapy',
 "Offline Entertainment > Media & Entertainment > Women's Hockey > Hockey > Sports > Organizer",
 'Consumer Brand > Air Purifier & Quality Monitor > Home Appliance > E-Commerce > Consumer Product > Electronic Product > HVAC',
 'Inland & Maritime > Mobility > Enterprise Software > Inspection, Maintenance & Repair > Vessel & Fleet Management > Operation & Maintenance',
 'Consumer Product > Houseware & Home Supplies > Self-Defense Product > Firearm > Consumer Brand > Firearms, Ammunition & Accessories',
 'Media & Entertainment > Audio > Streaming > Aggregator > Music',
 'Technology > Voice Modulation > Industry-Specific > Audio Processing > Media & Entertainment > Artificial Intelligence > AI Application',
 'Media & Entertainment > Movies > On-Demand Streaming > World Equality-Focused > Video',
 'Enterprise > Collaboration Platform > Audio Creation & Processing > Media & Entertainment > Audio > Production',
 'Building Solution > Utility Solution > Real Estate & Construction > HVAC > Manufacturer > Refrigeration Solution > Construction',
 'Energy & Utilities > Oil & Gas > Offshore Support Vessel > Fuel Production > Upstream Operations > Offshore Production > Manufacturer > Vessel',
 'Healthcare & Life Sciences > Infectious Disease > Fungal Disease > Pharmaceuticals',
 'Supply Chain & Logistics > Service > Courier > Logistics',
 'Telecom > Wireline Operators > Telecom Operator > Business Communication Solution',
 'Mobility > Financial Solution > Inland & Maritime > Enterprise Software > Business Support Solution > Expense Management',
 'Enterprise > Press Distribution > Media Outreach Management > Enterprise Software > Public Relations Tech',
 'Enterprise > GRC > IT Vendor Risk Management > IT Risk > Enterprise Software > Risk Management',
 'Enterprise > White Label Solution > Affiliate Marketing > Affiliate Network > Marketing Tech > Enterprise Software',
 'Enterprise > Routers > Enterprise Infrastructure > IT Networking',
 'Healthcare & Life Sciences > Urology > Therapeutic Device > Medical Device > Urinary Catheter',
 'Enterprise > Exhibition Equipment Supplier > Experiential Marketing > Enterprise Service > Outsourcing > Business Process Outsourcing > Marketing & Advertising > Marketing Agency',
 'Healthcare & Life Sciences > Surgical Sponge > Medical Device > Surgical Equipment > Hospital Equipment & Supplies',
 'Industrials > Defense > Service > Software Design & Development > Defense Contracting',
 'Media & Entertainment > Kart Racing > Sports > Recreational Sports > Offline Entertainment',
 'Consumer Product > Equipment > Recreational & Leisure > Skiing > Consumer Brand > E-Commerce > Sports, Fitness & Outdoor Products > Winter Sports',
 'Technology > Test, Measurement & Instrumentation > Imaging System > Manufacturer > Multiline',
 'Healthcare & Life Sciences > Foot Ulcer > Health Care IT > Digital Health > Patient Data > Clinical Operation > Clinical Data Management',
 'Education > EdTech > Digital Learning > Corporate Training > Game-Based Learning > Language Learning',
 'Service > Material Handling Equipment > Manufacturing > Industrial Production > Stacking System > Customized Equipment > Industrials',
 'Artificial Intelligence > Industry-Specific > Technology > Store Automation Solution > AI Application > Retail',
 'Enterprise > Engagement & Collaboration > Chatbot > Event Management > Enterprise Software',
 "K-12 > Classroom Management Tool > Software Solution > Teacher's Solution > School Solution > Education > Performance Evaluation Tool > EdTech",
 'Financial Industry > Bank > Financial Institution > Investment Bank > Small Businesses',
 'Industrial Production > Heat Exchanger > Industrials > Heating & Cooling Equipment > Machinery & Equipment > Heating Equipment',
 'Technology > Application > Enterprise > Blockchain > Distributed Computing',
 'Enterprise > Enterprise Software > Candidate Sourcing > HR Tech > Job Board > MBA Jobs',
 'Technology > Home Automation > Consumer IoT > IoT Application > Internet of Things > Connected Home',
 'Technology > Wearables > Workplace Safety > Wearable Band > Commercial',
 'Education > Student Solution > EdTech > Digital Learning > Practice Platform > K-12',
 'Consumer Product > Home Appliance > E-Commerce > Multiline > Retailer > Electronic Product',
 'Enterprise > HR Tech > Enterprise Software > Employee Engagement Solution > Team Building Activities Management',
 'Construction > Multiline > Subcontracting > Service > Real Estate & Construction > Environmental & Safety Service',
 'Print & Digital Media > Sports > Media & Entertainment > Digital Media > Baseball > Blog',
 'Enterprise > Enterprise Software > White-Label Platform > HR Tech > Recruitment Process Management',
 'Media & Entertainment > Ad Tech > Enterprise > Advertising Solution > Gaming',
 'Industrial Production > Machinery & Equipment > Manufacturing Equipment > Waterjet Machine > Cutting Equipment > Industrials',
 'Consumer Internet & Service > Petition Platforms > Lifestyle > Social Support > Application',
 'Industrials > Machinery & Equipment > Forklift > Material Handling Equipment > Industrial Production > Material Transportation Vehicle',
 'Distributor > Convenience Food > Agriculture, Food & Beverage > Food & Beverage > Cookie Dough > Ready-to-eat > Snack > Service',
 'IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security > Technology',
 'Media & Entertainment > Marketplace > Audio Processing > Audio > Hardware',
 'FinTech > Analytics Platforms > Health Insurance > Financial Industry > Backend Solution > InsureTech',
 'Technology > Outsourcing > Custom AI Development > Security & Surveillance > AI Service > Artificial Intelligence > Industrials > Industry-Specific',
 'Inland & Maritime > Transportation > Rental Platform > Boat & Yacht > Transport Tech > Mobility',
 'Real Estate & Construction > Construction > Service > Subcontracting > Ceiling Installation > Interior Construction & Finishing',
 'Supply Chain & Logistics > Warehouse Automation & Robotics > Picking System > Hardware > Warehousing & Inventory Management',
 'Technology > Industry-Specific > Internet of Things > Artificial Intelligence > Multiline > Connected Cities > AI Application',
 'Food & Beverage > Tracking & Monitoring > Agriculture, Food & Beverage > B2B > FoodTech > Hardware Solution > Food Monitoring',
 'Travel Tech > Water-Based > Travel & Hospitality > Cruise > Booking Platform > Transport',
 'Industrial Production > Machinery & Equipment > Electrical & Electronic Equipment > Industrials > Device > Drive > AC Drive',
 'Agriculture, Food & Beverage > B2B > Food & Beverage > FoodTech > Data Analytics > Image Recognition > Software Solution',
 'Enterprise > Employee Helpdesk & Self-Service > Enterprise Software > Employee Relocation > HR Tech',
 'Healthcare & Life Sciences > Health Care IT > Solution for Life Sciences Industry > CRM > Marketing Solution > Digital Health',
 'Healthcare & Life Sciences > Disease-Focused Device > Dermatology > Therapeutic Device > Skin Condition Treatment > Disposable Device > Medical Device',
 'Financial Industry > Shipping Projects > FinTech > Trading and Investment > Alternative Investments Platform',
 'Consumer Brand > Candle > Home Fragrance > Consumer Product > E-Commerce > Home Furnishing > Home Decor',
 'Agriculture > Aquaculture Farming > Agricultural Producer > Controlled Environment Farming > Fish Farm > Caviar > Agriculture, Food & Beverage',
 'Technology > Blockchain > Enterprise > Customer Success > Application > Loyalty Management Platform',
 'Test, Measurement & Instrumentation > Technology > Resistivity & Induced Polarization Meter > Manufacturer > Polarization Meter > Measurement & Calibration',
 'Financial Industry > FinTech > Lending Platform > Multiline > Commercial Loan > Listing Platform',
 'Enterprise > Ad Ops > Media Buying Platform > Enterprise Software > Ad Tech',
 'Consumer Product > Clothing, Accessories & Footwear > Consumer Brand > Activewear & Outdoor Wear > Clothing > Winter Wear',
 'Consumer Internet & Service > Online Rewards > Application > Deals and Rewards > Lifestyle',
 'Enterprise > Data Analytics > Predictive Analytics > Enterprise Software > Business Analytics > Multiline',
 'Enterprise Software > Content Personalization > Enterprise > Customer Engagement > Email Enhancement > Customer Success',
 'Enterprise > Measurement & Analytics > Enterprise Software > Customer Service & Support > Call Tracking & Analytics',
 'Healthcare & Life Sciences > Medical Device > Hospital Equipment & Supplies',
 'Enterprise > Candidate Sourcing > Pre-Screened Candidates > HR Tech > Enterprise Software',
 'AI Infrastructure > Predictive Analytics > Artificial Intelligence > Software Stack > Middleware & Framework > Machine Learning > ML Toolkits & Libraries > Technology',
 'Industrials > Packaging > Material-Based > Glass > Manufacturer > Bottle & Can',
 'Enterprise > Enterprise Service > Media & Entertainment > Industry Specific > Legal Service > Law Firms',
 'Media & Entertainment > Multiline > Publisher > Books > Digital Media > Print & Digital Media',
 'Healthcare & Life Sciences > Physical Therapy > Clinical Operation > Health Care IT > Real-Time Monitoring & Tracking > Digital Health > Digital Therapeutic Solution',
 'Enterprise > HR Tech > Human Capital Allocation Optimization > Internal Mobility > Enterprise Software',
 'Technology > Electronics Ecosystem > Multiline > Retailing > Service',
 'Recreational & Leisure > Equipment > Gym > Sports, Fitness & Outdoor Products > Consumer Brand > Consumer Product > At-Home Fitness',

In [73]:
cleaned_chain_dict['Financial Industry > Backend Solution > InsureTech > Product Pricing Solution > Insurer Solution > FinTech']


cleaned_chain_dict['Consumer Product > Clothing, Accessories & Footwear > Fabric > Nylon & Polyester > B2B Manufacturer > Component']

'Consumer Product > Clothing, Accessories & Footwear > Fabric > Nylon & Polyester > Component'

In [88]:
negative_chains=json.loads(open('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/negative_chains/negative_chains.json').read())

In [90]:
import random
random.sample(list(negative_chains.keys()),10)

['FinTech > Financial Industry > Security Solution > Merchant Payment Solution > Security & Compliance Solution > Payment Recall > Payments',
 'Test, Measurement & Instrumentation > Resistivity & Induced Polarization Meter > Polarization Meter > Measurement & Calibration',
 'IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security',
 'Enterprise > Enterprise Software > Product Analytics > Design Analytics > Product Management',
 'Agriculture > Agriculture, Food & Beverage > Food Safety & Quality > Testing Platform > Agri Tech > Produce Inspection',
 'Automotive > Transport Tech > Mobility > Parking Payment > Payment Solution > B2C',
 'Educational Institution > Basketball > Sports & Fitness > Skill Development',
 'Financial Industry > Consulting > Auditing Solution > Financial Service > Service for Businesses',
 'Retailer > Consumer Product > Clothing, Accessories & Footwear > Swimwear > Activewear & Outdoor Wear > Water Sports',
 'Agriculture, Food & Beverage > Ingredient > Food Product > Quinoa > Grain']

In [93]:
negative_chains['IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security']

{'hard_negatives': ['Technology > Outsourcing > Custom AI Development > Security & Surveillance > AI Service > Artificial Intelligence > Industrials > Industry-Specific',
  'Service > Technology > Electronics Ecosystem',
  'Technology > Thermal Image Sensor > Electronic Component > Sensor > Electronics Ecosystem > Manufacturer > Imaging',
  'Industrials > Engineering, Research & Development > Software > Data Provider > Safety Data > Material & Chemical',
  'Inland & Maritime > Mobility > Enterprise Software > Inspection, Maintenance & Repair > Vessel & Fleet Management > Operation & Maintenance',
  'Technology > Wearable Camera > Commercial',
  'Healthcare & Life Sciences > Health Care IT > Financial Management Solution > Digital Health > Hospital Management & Information System'],
 'soft_negatives': ['Energy & Utilities > Utilities > Gas Utilities > Infrastructure > Distribution > Service',
  'Consumer Brand > Candle > Home Fragrance > Home Furnishing > Home Decor',
  'Healthcare & Life Sciences > Hospital Equipment & Supplies > Adhesive Bandage > Wound Care',
  'Agriculture, Food & Beverage > Agriculture > Agri Tech > Analytics & Intelligence > Aquaculture Analysis > Software Solution',
  'Financial Industry > Managing General Agents > Commercial Insurance > Specialty Insurance > InsureTech > FinTech']}

In [84]:
# industries[industries.industry_chain_hierarchy.str.contains('Financial Industry > Backend Solution')]

In [85]:
# dataset.factsheet.iloc[345]

In [86]:
# sample=pd.read_csv('data/all_factsheets_cleaned_sample.csv')

In [87]:
# sample.factsheet.iloc[0]

In [1]:
import sys
sys.path.append('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/')
from knowledge_data_curation.src.data_processors.negative_generator import NegativeSampleGenerator

In [2]:
from knowledge_data_curation.src.pipelines.main_pipeline import ColBERTTrainingPipeline

In [3]:
data_curator=ColBERTTrainingPipeline(config_path='config/default.yaml')

2025-05-08 19:11:23,556 - knowledge_data_curation.src.utils.token_counter - INFO - Initialized token counter
2025-05-08 19:11:23,556 - knowledge_data_curation.src.models.llm_client - INFO - Initialized OpenAI client with model=gpt-4.1-mini, max_threads=2
2025-05-08 19:11:23,557 - knowledge_data_curation.src.models.llm_client - INFO - Initialized OpenAI client with model=gpt-4.1-mini, max_threads=2

In [4]:
# negative_chains['IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security']

In [5]:
chain='IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security'
negative_chains = data_curator.negative_generator.generate_negatives_for_chain(chain)

2025-05-08 19:11:25,578 - knowledge_data_curation.src.models.llm_client - INFO - Using response format: <class 'knowledge_data_curation.src.models.pydantic.NegativeSamplingResponse'>
2025-05-08 19:11:29,681 - knowledge_data_curation.src.utils.token_counter - INFO - Token usage - Total: 1,013 (Prompt: 839, Completion: 174)

In [6]:
negative_chains.hard_negatives

['Technology > Internet of Things > Infrastructure > Connectivity > Networking > IoT Gateway > Industry-Specific > Industrial IoT',
 'Technology > Internet of Things > Infrastructure > Tracking & Navigation',
 'Industrials > Public Safety & Governance > Software > Communication > Open Data Platform',
 'Enterprise > IT Infrastructure > Cybersecurity > Identity & Access Management > Identity Management > Decentralized Identity Management']

In [7]:
negative_chains

NegativeSamplingResponse(hard_negatives=['Enterprise > IT Software > Business Application > Productivity & Collaboration > Business Contact Management > Digital Business Card', 'Industrials > Business Product & Service > Manufacturer > Furnishing > Space-Based > Residential', 'Enterprise > IT Software > Business Application > Human Resources > Candidate Sourcing > Freelancer > Private Security Professionals'], soft_negatives=['Financial Industry > FinTech > Trading & Investment > Trading Platform > Public Market > Exchange-Traded Fund', 'Media & Entertainment > Software > Production > Feedback Management', 'Industrials > Industrial Production > Machinery & Equipment > Fluid Transfer Equipment > Pump & Compressor', 'Technology > Artificial Intelligence > Business Function-Specific > Customer Service & Support > Feedback Tool', 'Financial Industry > FinTech > Finance & Accounting > Taxation Software > Transfer Pricing'])