In [1]:
import pandas as pd

In [74]:
industries=pd.read_csv('/Users/pragalbh.devsingh/Downloads/sqllab_untitled_query_1_20250508T103526.csv')
industries=industries[['company_id','Company Name','industry']].rename(columns={'Company Name':'company_name','industry':'industry_chain_hierarchy'})

In [1]:
industries.columns

NameError: name 'industries' is not defined

In [76]:
industries.industry_chain_hierarchy.iloc[0]

'Media & Entertainment > Video > Television > Streaming Platform'

In [77]:
industries[industries.industry_chain_hierarchy.str.contains('specific')].head().iloc[0].industry_chain_hierarchy

'Enterprise > IT Software > Business Application > Advertising > Ad Buying & Selling Platform > Ad Exchange > Programmatic Platform > Kids-specific'

In [78]:
industries.to_csv('data/industries.csv',index=False)

In [1]:
import pandas as pd
factsheets=pd.read_parquet('/Users/pragalbh.devsingh/Downloads/all_factsheets_cleaned (1).parquet')

In [3]:
print(factsheets.sample(2).factsheet.to_list()[0])
print(factsheets.sample(2).factsheet.to_list()[1])

mifinda company fact sheet **

 **1 .   company overview :**

 mifinda provides a platform for managing and optimizing the entire lifecycle of digital assets , focusing on streamlining workflows and improving collaboration for creative teams .    their target market appears to be large enterprises and organizations with significant digital asset management needs .

 **2 .   products , services , and offerings :**

 mifinda offers a cloud - based digital asset management ( dam ) solution .    while specific features are n't exhaustively listed , the website emphasizes features designed to improve organization , collaboration , and workflow efficiency around digital assets .    this includes features for asset storage , organization , version control , and likely workflow automation tools .

 **3 .   industry and target audience :**

 mifinda operates in the digital asset management ( dam ) software industry .   their target audience is primarily large enterprises and organizations with complex needs for managing large volumes of digital assets .    this could include marketing teams , creative agencies , and other businesses with substantial digital content .

 **4 .   unique selling propositions ( usps ) and key differentiators :**

 the website highlights mifinda 's focus on simplifying complex workflows and improving collaboration .    specific differentiators are n't explicitly stated , but the implication is that their platform offers a more intuitive and user - friendly experience compared to competitors , leading to increased efficiency and reduced operational costs .    further investigation would be needed to confirm these claims .

 **5 .   business model :**

 mifinda operates on a b2b saas ( software as a service ) model .    this is inferred from the nature of their product ( a cloud - based platform ) and their target audience ( large organizations ) .

 **6 .   technology used ( optional ): **

 the specific technologies used by mifinda are not detailed on their website .    however , given their saas model , it 's likely they utilize cloud infrastructure ( e . g . , aws , azure , google cloud ) , databases , and various software development technologies for their platform .

 **7 .   revenue model ( optional ): **

 mifinda 's revenue model is likely a subscription - based saas model , charging clients recurring fees based on usage or features .    pricing details are not publicly available on their website .

 **8 .   competitive landscape ( optional ): **

 based on mifinda 's offerings , their main competitors likely include other enterprise - level dam solutions .    a more thorough competitive analysis would require further research to identify specific competitors and their market share .


 **in summary :**mifinda is a promising player in the growing dam market , targeting large enterprises with a cloud - based solution focused on workflow optimization and collaboration .    further due diligence , including a deeper competitive analysis and financial review , would be necessary to fully assess their investment potential .

rareté studios company fact sheet **

 **1 .   products , services , and offerings :**  high - end luxury jewelry , primarily rings and bracelets .    the website does not detail specific materials or manufacturing processes .

 **2 .   industry and target audience :**luxury goods / jewelry industry .   the target audience is affluent consumers seeking high - quality , handcrafted jewelry .

 **3 .   unique selling propositions ( usps ) and key differentiators :**the website emphasizes luxury and craftsmanship .    however , specific usps differentiating rareté studios from competitors are not explicitly stated and require further research .    potential usps , based on the website 's presentation , could include unique designs , ethically sourced materials ( if applicable ) , or a focus on personalized customer service .

 **4 .   business model :**direct - to - consumer ( d2c ) e - commerce .

 **5 .   technology used :**shopify e - commerce platform .

 **6 .   revenue model :**direct sales of jewelry through their online store .    pricing is not publicly listed on the website , but based on industry standards , it 's likely they utilize value - based or prestige pricing strategies .

 **7 .   competitive landscape :**  key competitors in the luxury jewelry market include established brands such as tiffany & co . , cartier , van cleef & arpels , bulgari , and chopard .   these brands compete on brand reputation , design , material quality , craftsmanship , and pricing .   rareté studios will need to differentiate itself through a strong brand identity , unique designs , and potentially a focus on specific niche markets or exceptional customer service .


 **recommendations for further due diligence :**

 *** detailed competitive analysis :**conduct a thorough competitive analysis to identify rareté studios ' precise positioning within the market and pinpoint its key differentiators .
 *** sourcing and manufacturing :**investigate their sourcing and manufacturing processes to assess the quality and sustainability of their materials and production methods .
 *** pricing strategy :**determine their exact pricing strategy and analyze its effectiveness in relation to their target market and competitive landscape .
 *** marketing and sales :**evaluate their marketing and sales strategies to understand their customer acquisition costs and overall market penetration .
 *** financial performance :**obtain financial statements to assess their revenue , profitability , and growth trajectory .


 this fact sheet provides a solid foundation for further due diligence .    the additional research suggested above will provide a more comprehensive understanding of rareté studios ' potential and viability as an investment opportunity .

In [46]:
factsheets.factsheet=factsheets.factsheet.str.replace(',',';')

In [47]:
factsheets.factsheet.iloc[0]

"the company company fact sheet **\n\n **company name :**gogo \n\n **website :**the company \n\n **products & services :**the company provides inflight internet connectivity and entertainment solutions for both commercial and business aviation .    their offerings include a range of connectivity solutions for various aircraft types and sizes ; utilizing a combination of satellite and air - to - ground ( atg ) technologies .    a key product is the the company avance system ; a factory - installed option available from major business aviation oems ; supported by a large mro network .    they emphasize a global network and redundancy for reliable connectivity .    the avance system uniquely offers dual network capabilities ( leo satellite and atg ) ; enabling bandwidth prioritization and service redundancy .   unlimited atg data plans include the company galileo data at no additional cost . \n\n **industry :**in - flight connectivity and entertainment \n\n **target audience :**airlines ; business aviation operators ; and passengers . \n\n **unique selling propositions ( usps ) & key differentiators :**\n\n * wide range of connectivity solutions for diverse aircraft types . \n * strong partnerships with major business aviation oems and a large mro network ; including factory installation options . \n * dual network capabilities ( satellite and atg ) providing redundancy and enhanced reliability . \n\n **business model :**hybrid b2b ( selling to airlines and business aviation operators ) and b2c ( selling directly to passengers ) . \n\n **technology used :**  the company utilizes a global network of satellites ( specifically mentioning leo satellites ) and terrestrial towers ( atg ) .    precise details on satellite constellations and terrestrial network infrastructure require further research . \n\n **revenue model :**  a combination of subscription fees from airlines and per - use fees from passengers .    specific pricing details remain unavailable due to limitations in publicly accessible information . \n\n **competitive landscape :**key competitors identified through web searches include viasat ; panasonic avionics ; and intelsat .    market share data and detailed competitive analysis require further research using specialized financial databases . \n\n **financial data :**  detailed financial reports ; investor presentations ; and sec filings were not readily downloadable from publicly available sources .    we attempted to obtain this information through gogo 's investor relations contact form ; but received no response .    the sec 's edgar database ( link provided in previous responses ) contains their filings ; but detailed analysis requires manual review of the documents . \n\n **recent partnerships :**information on recent partnerships requires further research . \n\n **summary :**the company is a well - established player in the inflight connectivity market ; offering a diverse range of solutions and leveraging strong industry partnerships .    their dual - network approach provides a key competitive advantage .   however ; obtaining detailed financial and competitive information requires access to proprietary databases or direct communication with the company . \n\n\n this fact sheet provides a solid foundation ; but further research using specialized financial databases is strongly recommended to complete the analysis and fill in the missing quantitative data . \n "

In [48]:
factsheets.to_csv('data/all_factsheets_cleaned.csv',index=False)

In [1]:
import pandas as pd
industries =pd.read_csv('data/industries.csv')
factsheets =pd.read_csv('data/all_factsheets_cleaned.csv')

In [2]:
# industries.sample(5000).industry_chain_hierarchy.nunique()

In [3]:
overlapping_industries=industries.merge(industries,on='company_id',how='inner')
overlapping_industries=overlapping_industries[overlapping_industries.industry_chain_hierarchy_x!=overlapping_industries.industry_chain_hierarchy_y]
overlapping_industries=pd.concat([overlapping_industries[['company_id','industry_chain_hierarchy_x']].rename(columns={'industry_chain_hierarchy_x':'industry_chain_hierarchy'}),overlapping_industries[['company_id','industry_chain_hierarchy_y']].rename(columns={'industry_chain_hierarchy_y':'industry_chain_hierarchy'})])
overlapping_industries.to_csv('data/overlapping_industries.csv',index=False)
overlapping_industries.sort_values('company_id').iloc[:1000].to_csv('data/overlapping_industries_sample.csv',index=False)
overlapping_industries.sort_values('company_id').iloc[:100].to_csv('data/overlapping_industries_quickie.csv',index=False)
overlapping_industries.sample(10).to_csv('data/overlapping_industries_tiny.csv',index=False)

In [4]:
pd.concat([pd.read_csv('data/overlapping_industries_sample.csv'),industries[industries.industry_chain_hierarchy.isin(industries.industry_chain_hierarchy.drop_duplicates().sample(500))].sample(5000)]).to_csv('data/industries_sample.csv',index=False)

In [5]:

pd.concat([pd.read_csv('data/overlapping_industries_quickie.csv'),industries[industries.industry_chain_hierarchy.isin(industries.industry_chain_hierarchy.drop_duplicates().sample(100))].sample(100)]).drop_duplicates(subset=['company_id','industry_chain_hierarchy']).to_csv('data/industries_quickie.csv',index=False)
# industries[industries.industry_chain_hierarchy.isin(industries.industry_chain_hierarchy.drop_duplicates().sample(10))].sample(100).to_csv('data/industries_quickey.csv',index=False)

In [6]:
# pd.read_csv('data/overlapping_industries_quickie.csv')

In [7]:
sample_industries=pd.read_csv('data/industries_sample.csv')
quick_industries=pd.read_csv('data/industries_quickie.csv')

In [10]:
sample_industries.industry_chain_hierarchy.nunique()

534

In [8]:
quick_industries

,company_id,industry_chain_hierarchy,company_name
0,1,Media & Entertainment > Video > Television > S...,NaN
1,1,Consumer Product > Consumer Brand > Electronic...,NaN
2,1,Consumer Product > Consumer Brand > Electronic...,NaN
3,1,Consumer Product > Consumer Brand > Electronic...,NaN
4,2,Media & Entertainment > Video Gaming > Gaming ...,NaN
...,...,...,...
109,523708,Travel & Hospitality > Digital Solution > Soft...,Lunchbox
110,433515,Industrials > Public Safety & Governance > Gov...,Govos
111,485860,Consumer Product > Consumer Brand > Electronic...,FireAngel Safety Technology
112,1429181,Travel & Hospitality > Digital Solution > Soft...,Albion Hotel Albury
113,239861,Consumer Internet & Service > Service Provider...,True Rest

In [9]:
sample_industries

,company_id,industry_chain_hierarchy,company_name
0,1,Media & Entertainment > Video > Television > S...,NaN
1,1,Consumer Product > Consumer Brand > Electronic...,NaN
2,1,Media & Entertainment > Video > Television > S...,NaN
3,1,Consumer Product > Consumer Brand > Electronic...,NaN
4,1,Consumer Product > Consumer Brand > Electronic...,NaN
...,...,...,...
5995,214137,"Consumer Product > Consumer Brand > Clothing, ...",Blundstone
5996,57924,"Consumer Product > Consumer Brand > Clothing, ...",Jako Enterprises
5997,67691,Energy & Utilities > Power Production > Solar ...,Solar Roadways
5998,10870,Travel & Hospitality > Digital Solution > Plat...,Campr
5999,125571,"Consumer Product > Rental Platform > Clothing,...",ShopStyle

In [7]:
sample_industries.merge(sample_industries,on='company_id',how='inner')

,company_id,company_name_x,industry_chain_hierarchy_x,company_name_y,industry_chain_hierarchy_y
0,1104171,Artsploitation Films,Media & Entertainment > Video > Movie > Distri...,Artsploitation Films,Media & Entertainment > Video > Movie > Distri...
1,395052,From Babies with Love,"Non-Profit, Non-Operational & Junk > Non-Profi...",From Babies with Love,"Non-Profit, Non-Operational & Junk > Non-Profi..."
2,295667,Procurement Foundry,"Non-Profit, Non-Operational & Junk > Non-Profi...",Procurement Foundry,"Non-Profit, Non-Operational & Junk > Non-Profi..."
3,294041,We Make History,"Non-Profit, Non-Operational & Junk > Non-Profi...",We Make History,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4,533083,Pacific Maritime Association,"Non-Profit, Non-Operational & Junk > Non-Profi...",Pacific Maritime Association,"Non-Profit, Non-Operational & Junk > Non-Profi..."
...,...,...,...,...,...
4995,366340,NRV,Financial Industry > Financial Institution > A...,NRV,Financial Industry > Financial Institution > A...
4996,219830,eCompanies,Financial Industry > Financial Institution > A...,eCompanies,Financial Industry > Financial Institution > A...
4997,423404,La Fresque du Climat,"Non-Profit, Non-Operational & Junk > Non-Profi...",La Fresque du Climat,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4998,615690,Special Olympics Washington,"Non-Profit, Non-Operational & Junk > Non-Profi...",Special Olympics Washington,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4999,367063,Laticnios Porto Alegre,"Agriculture, Food & Beverage > Food & Beverage...",Laticnios Porto Alegre,"Agriculture, Food & Beverage > Food & Beverage..."

In [9]:
industries=pd.read_csv('data/industries.csv')

In [10]:
industries

,company_id,company_name,industry_chain_hierarchy
0,1,Apple,Media & Entertainment > Video > Television > S...
1,1,Apple,Consumer Product > Consumer Brand > Electronic...
2,1,Apple,Consumer Product > Consumer Brand > Electronic...
3,1,Apple,Consumer Product > Consumer Brand > Electronic...
4,2,Ubisoft,Media & Entertainment > Video Gaming > Gaming ...
...,...,...,...
671936,1602549,Hairbook,Consumer Internet & Service > Platform > Beaut...
671937,1602549,Hairbook,Consumer Internet & Service > Business Solutio...
671938,1602553,Gaishishukatsu.com,Enterprise > IT Software > Business Applicatio...
671939,1602555,Roglio,Enterprise > Service > Outsourcing > Business ...
671940,1602556,Mirroh.ai,Technology > Internet of Things > Application ...

In [13]:
# 1079527/671941

In [15]:
overlapping_industries

,company_id,company_name_x,industry_chain_hierarchy_x,company_name_y,industry_chain_hierarchy_y
1,1,Apple,Media & Entertainment > Video > Television > S...,Apple,Consumer Product > Consumer Brand > Electronic...
2,1,Apple,Media & Entertainment > Video > Television > S...,Apple,Consumer Product > Consumer Brand > Electronic...
3,1,Apple,Media & Entertainment > Video > Television > S...,Apple,Consumer Product > Consumer Brand > Electronic...
4,1,Apple,Consumer Product > Consumer Brand > Electronic...,Apple,Media & Entertainment > Video > Television > S...
6,1,Apple,Consumer Product > Consumer Brand > Electronic...,Apple,Consumer Product > Consumer Brand > Electronic...
...,...,...,...,...,...
1079505,1602528,Zieg & Liphardt,Real Estate & Construction > Construction > Se...,Zieg & Liphardt,Real Estate & Construction > Construction > Se...
1079512,1602535,Bad & Heizung,Real Estate & Construction > Construction > Se...,Bad & Heizung,Real Estate & Construction > Construction > Se...
1079513,1602535,Bad & Heizung,Real Estate & Construction > Construction > Se...,Bad & Heizung,Real Estate & Construction > Construction > Se...
1079521,1602549,Hairbook,Consumer Internet & Service > Platform > Beaut...,Hairbook,Consumer Internet & Service > Business Solutio...
1079522,1602549,Hairbook,Consumer Internet & Service > Business Solutio...,Hairbook,Consumer Internet & Service > Platform > Beaut...

In [81]:
sample_industries

,company_id,company_name,industry_chain_hierarchy
0,1104171,Artsploitation Films,Media & Entertainment > Video > Movie > Distri...
1,395052,From Babies with Love,"Non-Profit, Non-Operational & Junk > Non-Profi..."
2,295667,Procurement Foundry,"Non-Profit, Non-Operational & Junk > Non-Profi..."
3,294041,We Make History,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4,533083,Pacific Maritime Association,"Non-Profit, Non-Operational & Junk > Non-Profi..."
...,...,...,...
4995,366340,NRV,Financial Industry > Financial Institution > A...
4996,219830,eCompanies,Financial Industry > Financial Institution > A...
4997,423404,La Fresque du Climat,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4998,615690,Special Olympics Washington,"Non-Profit, Non-Operational & Junk > Non-Profi..."
4999,367063,Laticnios Porto Alegre,"Agriculture, Food & Beverage > Food & Beverage..."

In [97]:
factsheets[factsheets.company_id.isin(sample_industries.company_id)].to_csv('data/all_factsheets_cleaned_sample.csv',index=False)
factsheets[factsheets.company_id.isin(quick_industries.company_id)].to_csv('data/all_factsheets_cleaned_quickey.csv',index=False)

In [ ]:
quick_industries

In [59]:
dataset=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/colbert_training/colbert_training_data.csv')

In [62]:
dataset

,query,factsheet,score,is_positive
0,Biotechnology > Biomedicine Research > Molecul...,the company company fact sheet **\n\n **1 . ...,1.0,True
1,Biotechnology > Biomedicine Research > Molecul...,the company fact sheet **\n\n **company name :...,1.0,True
2,Biotechnology > Biomedicine Research > Molecul...,redwood biosciences company fact sheet ( final...,1.0,True
3,Biotechnology > Biomedicine Research > Molecul...,the company fact sheet **\n\n **1 . company ...,1.0,True
4,Biotechnology > Biomedicine Research > Molecul...,company fact sheet : rls therapeutics **\n\n *...,1.0,True
...,...,...,...,...
43297,Service > IT Implementation & Integration > Ou...,visionqms company fact sheet **\n\n **company ...,0.0,False
43298,Service > IT Implementation & Integration > Ou...,company fact sheet : the company ( the company...,0.0,False
43299,Service > IT Implementation & Integration > Ou...,company fact sheet : getexclusively **\n\n **c...,0.0,False
43300,Service > IT Implementation & Integration > Ou...,nordic legal fact sheet **\n\n **company name ...,0.0,False
43301,Service > IT Implementation & Integration > Ou...,the company company fact sheet **\n\n **1 . ...,0.0,False

In [64]:
import json
cleaned_chain_dict=json.loads(open('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/cleaned_chains/cleaned_chains.json').read())

In [67]:
list(cleaned_chain_dict.keys())

['Enterprise > Add-on > Enterprise Software > HR Tech > Payroll Management Solution',
 'Lifestyle > Application > Consumer Internet & Service > Product Discovery, Comparison & Recommendation > Chat-based > Product Discovery > Multiline',
 'Technology > Detection & Ranging > RFID & NFC Reader > Semiconductor > System-on-a-Chip > Fabless',
 'Technology > Smart Lock > Physical Access Control > Internet of Things > Commercial IoT > IoT Application > Connected Building > Safety & Security',
 'Technology > AI Application > Chemical Industry > Business Function-Specific > Artificial Intelligence > R&D Management Solution',
 'Technology > Manufacturer > 3D Printing > Printer > Stereolithography Printers',
 'Healthcare & Life Sciences > Intensive Care Unit > Digital Health > Health Care IT > Hospital Management & Information System > EHR Platform & Practice Management',
 'Technology > Legal Tech > Knowledge Management > AI Application > Business Function-Specific > Artificial Intelligence > Generative AI-Based',
 'Financial Industry > Backend Solution > InsureTech > Product Pricing Solution > Insurer Solution > FinTech',
 'Public Safety & Governance > Industrials > Political Campaign Management > Software > Recruitment Platform > Political Party Operations',
 'Consumer Product > Multiline > Computers, Mobiles & Accessories > Personal Appliance > Electronic Product > E-Commerce > Marketplace > Retailer',
 'Technology > Virtual Reality > Rehabilitation Equipment > Application > Healthcare & Life Sciences > Medical Device',
 'Media & Entertainment > Service > Video > Pre-Production Service',
 'FinTech > Financial Industry > Portfolio Risk Analytics > Backend Solution > Portfolio Management Solution > Trading and Investment',
 'Multiline > Service > Technology > Electronics Ecosystem',
 'Consumer Product > Home Furnishing > Home Decor > Retailer > Party Supplies',
 'Consumer Product > Coffee Machine > Electronic Product > Kitchen > Consumer Brand > Home Appliance > Coffee Pod Maker > Beverage',
 'Enterprise > Business Function-Specific > Enterprise Software > Location > Data Analytics > Customer Intelligence > Marketing and Advertising > Business Analytics',
 'Data Analytics > Customer Success and Service > Business Function-Specific > Business Analytics > Service Intelligence > Enterprise Software > Enterprise',
 'Industrials > Software > Mining > Ore Analysis',
 'Food & Beverage > Agriculture, Food & Beverage > B2B > FoodTech > Hardware Solution > Automatic Juice Machine > Beverage Dispenser',
 'Technology > Internet of Things > IoT Application > Connected Home > Monitoring & Analytics > Leakage Monitoring > Consumer IoT',
 'Consumer Product > E-Commerce > Software > Cross-Border E-Commerce Solution > Business Solution > Storefront',
 'Agriculture > Animal Husbandry > Cow Milk > Poultry & Dairy Farming > Agriculture, Food & Beverage > Agricultural Producer',
 'Media & Entertainment > Enterprise > Content Lifecycle > Content Engagement',
 'Robotics > Industrials > Cleaning Robot > Manufacturer > Technology > Commercial Robotics > Floor Cleaning Robot',
 'Real Estate & Construction > Sale, Leasing & Management > Printing > Service > Brokerage-Focused',
 'Enterprise > Cloud Infrastructure > Serverless Computing > Enterprise Infrastructure',
 'Enterprise > Enterprise Service > IT Implementation and Integration > Application Software > Information Technology > ERP > Consulting',
 'Healthcare & Life Sciences > HRMS > Digital Health > Health Care IT > HR Solution > Hospital Management & Information System',
 'Supply Chain & Logistics > Logistics > Temperature Tracker > Hardware > Freight',
 'Healthcare & Life Sciences > B2B Service > Insurance Provider > Healthcare Service > Advisory & Consulting Service',
 'Artificial Intelligence > Security & Surveillance > AI Application > Physical Security > Technology > Industry-Specific > Safety & Risk Analytics > Industrials',
 'Media & Entertainment > Print Media > News > College News > Print & Digital Media',
 'Technology > Application > Digital Characters > Consumer > Chatbots',
 'Media & Entertainment > Gaming > eSports > Aim Trainer > Coaching & Training',
 'Technology > E-Commerce > Marketplace > 3D Printing > 3D Product',
 'Energy & Utilities > Engineering Service > State of Health > Test & Measurement > Service > Energy Storage',
 'Agriculture, Food & Beverage > Agrochemical > Soil Amendment > Agriculture > Multiline > Farm Input',
 'Enterprise > Organizational Structure & Design > Enterprise Software > Employee Information Management > HR Tech',
 'Retailer > Consumer Product > Clothing, Accessories & Footwear > Swimwear > Clothing > E-Commerce > Activewear & Outdoor Wear > Water Sports',
 'Agriculture, Food & Beverage > Agriculture > Service > Controlled Environment Agriculture',
 'IoT Application > Technology > Commercial IoT > Tracking & Monitoring > Industrial IoT > Internet of Things > Inventory Tracking',
 'Financial Industry > Asset Manager > Securities > Financial Institution > Catalysts',
 'Media & Entertainment > Stealth Mode',
 'Financial Industry > Banking > FinTech > Financial Service > Cryptocurrency > Treasury Management',
 'Utilities > Water Utilities > Membrane-based > Manufacturer > Energy & Utilities > Desalination',
 'Consumer Internet & Service > Platform > Home Service > Laundry',
 'Industrials > Rigid Packaging > Packaging > Application-Based > Compostable Packaging > Manufacturer > Multiline',
 'Consumer Internet & Service > Devotional Apps > Lifestyle > Application',
 'Travel & Hospitality > Booking Platform > Accommodation > Vacation Rental > Hospitality Tech',
 'Media & Entertainment > Live Event > Movie Theatres > Offline Entertainment',
 'GRC > Data Deletion Request Management > Data Privacy > IT Compliance > Personal Information Management System > Enterprise > Compliance Management > Enterprise Software',
 "Consumer Product > Clothing, Accessories & Footwear > Multiline > Clothing > Women's Product > Retailer",
 "Personal Care > Beauty & Personal Care > Men's Product > E-Commerce > Consumer Product > Consumer Brand > Hygiene Product > Intimate Care",
 'Restaurant, Cafe & Bar > Maintenance Solution > Restaurant > Operation Management > Travel & Hospitality > Enterprise Software > Hospitality Tech',
 'Healthcare Service > Psychological Assessments > Behavioral, Speech & Physical Therapy > Pediatric Care Center > Healthcare Provider > Healthcare & Life Sciences > Healthcare Center',
 'Healthcare & Life Sciences > Non Invasive Imaging Device > X-Ray Device > Diagnostic & Monitoring Device > Hospital Equipment & Supplies > Medical Device > Imaging & Radiology Equipment > Portable Device',
 'Agriculture, Food & Beverage > Novel Food > B2C > Alternative Dairy Product > Food & Beverage > E-Commerce > Cultured Dairy Product > FoodTech',
 'Food & Beverage > Nut > Packaged Food > B2C > Snack > E-Commerce > Agriculture, Food & Beverage > FoodTech',
 'Power Production > Geothermal Energy > Tools & Equipment > Drilling > Energy & Utilities > Manufacturer',
 'Enterprise > Lead Management > LinkedIn Automation > Sales Tech > Enterprise Software > Social Media Lead Generation > Lead Generation Tools',
 'Education > EdTech > Digital Learning > Communication Skill > Corporate Training > Personal Development > Game-Based Learning',
 'Media & Entertainment > Video > Lighting > Film Lighting > Hardware',
 'Technology > Thermal Image Sensor > Application-Based > Electronic Component > Sensor > Electronics Ecosystem > Manufacturer > Imaging',
 'Financial Industry > Consulting > Auditing Solution > Financial Service > Service for Businesses',
 'Enterprise > Operating Systems > Server Operating System > Enterprise Infrastructure',
 'Financial Industry > FinTech > Credit Rating Provider > Consumer Finance > Credit Report Management',
 'Consumer Product > Beauty & Personal Care > E-Commerce > Personal Care > Distributor & Wholesaler > Adult Product > Hygiene Product',
 'Industrials > Space Vehicle Launch Service Providers > Terrestrial-based Launch Platform > Service > Space',
 'Automotive > Transportation > Mobility > Transport Tech > B2B > Rental Management',
 'Technology > Opto-Electronic Devices > Multiline > Passive Optical Component > Manufacturer > Electronics Ecosystem',
 'Technology > Business Idea Generation > AI Application > Business Function-Specific > Artificial Intelligence > Enterprise Productivity > Niche Productivity Solution',
 'Financial Industry > FinTech > Decentralized ID > Cryptocurrency > NFT Platform',
 'Healthcare & Life Sciences > Pharmaceuticals > Radiation Therapy > Oncology > Acute Radiation Syndrome',
 'Industrials > Physical Security > CCTV Cameras > Manufacturer',
 'Print & Digital Media > News > Digital Media > Europe-Focused > Local News > Media & Entertainment',
 'Financial Industry > Consumer Finance > Marketplace > Multiline > Insurance > FinTech',
 'Media & Entertainment > Gaming > Social Platform > Highlight Sharing > Content Creation',
 'Energy & Utilities > Wind Energy > Consulting & Advisory > Power Production > Service',
 'FoodTech > Agriculture, Food & Beverage > B2C > Packaged Food > Meat Product > Food & Beverage > Chicken > E-Commerce',
 'Agriculture, Food & Beverage > Soup & Canned Food > E-Commerce > B2C > Convenience Food > FoodTech > Food & Beverage > Fish & Sea-Food Based',
 'Media & Entertainment > Distribution > Television > Video',
 'Enterprise Service > Business Intelligence & Analytics > Outsourcing > Industrial > Enterprise > Knowledge Process Outsourcing > Industry-Specific',
 'Food & Beverage > Packaged Food > FoodTech > Agriculture, Food & Beverage > B2C > Ingredient > E-Commerce > Condiments, Flavors & Sauce',
 'Financial Industry > Consumer Loan > Balance Sheet Lender > Lending Platform > FinTech > Medical Financing > Fertility-Focused',
 'Healthcare & Life Sciences > Neurodivergence Care > Healthcare Provider > Healthcare Service > Home Care',
 'Consumer Internet & Service > Multiline > Application > Product Recommendation > Product Discovery, Comparison & Recommendation > Apparel, Accessories and Footwear > Lifestyle',
 'Biotechnology > Biotherapeutic > Healthcare & Life Sciences > Biomedicine Research > Genetic Engineering > Genomic Medicine > Gene Therapy',
 "Offline Entertainment > Media & Entertainment > Women's Hockey > Hockey > Sports > Organizer",
 'Consumer Brand > Air Purifier & Quality Monitor > Home Appliance > E-Commerce > Consumer Product > Electronic Product > HVAC',
 'Inland & Maritime > Mobility > Enterprise Software > Inspection, Maintenance & Repair > Vessel & Fleet Management > Operation & Maintenance',
 'Consumer Product > Houseware & Home Supplies > Self-Defense Product > Firearm > Consumer Brand > Firearms, Ammunition & Accessories',
 'Media & Entertainment > Audio > Streaming > Aggregator > Music',
 'Technology > Voice Modulation > Industry-Specific > Audio Processing > Media & Entertainment > Artificial Intelligence > AI Application',
 'Media & Entertainment > Movies > On-Demand Streaming > World Equality-Focused > Video',
 'Enterprise > Collaboration Platform > Audio Creation & Processing > Media & Entertainment > Audio > Production',
 'Building Solution > Utility Solution > Real Estate & Construction > HVAC > Manufacturer > Refrigeration Solution > Construction',
 'Energy & Utilities > Oil & Gas > Offshore Support Vessel > Fuel Production > Upstream Operations > Offshore Production > Manufacturer > Vessel',
 'Healthcare & Life Sciences > Infectious Disease > Fungal Disease > Pharmaceuticals',
 'Supply Chain & Logistics > Service > Courier > Logistics',
 'Telecom > Wireline Operators > Telecom Operator > Business Communication Solution',
 'Mobility > Financial Solution > Inland & Maritime > Enterprise Software > Business Support Solution > Expense Management',
 'Enterprise > Press Distribution > Media Outreach Management > Enterprise Software > Public Relations Tech',
 'Enterprise > GRC > IT Vendor Risk Management > IT Risk > Enterprise Software > Risk Management',
 'Enterprise > White Label Solution > Affiliate Marketing > Affiliate Network > Marketing Tech > Enterprise Software',
 'Enterprise > Routers > Enterprise Infrastructure > IT Networking',
 'Healthcare & Life Sciences > Urology > Therapeutic Device > Medical Device > Urinary Catheter',
 'Enterprise > Exhibition Equipment Supplier > Experiential Marketing > Enterprise Service > Outsourcing > Business Process Outsourcing > Marketing & Advertising > Marketing Agency',
 'Healthcare & Life Sciences > Surgical Sponge > Medical Device > Surgical Equipment > Hospital Equipment & Supplies',
 'Industrials > Defense > Service > Software Design & Development > Defense Contracting',
 'Media & Entertainment > Kart Racing > Sports > Recreational Sports > Offline Entertainment',
 'Consumer Product > Equipment > Recreational & Leisure > Skiing > Consumer Brand > E-Commerce > Sports, Fitness & Outdoor Products > Winter Sports',
 'Technology > Test, Measurement & Instrumentation > Imaging System > Manufacturer > Multiline',
 'Healthcare & Life Sciences > Foot Ulcer > Health Care IT > Digital Health > Patient Data > Clinical Operation > Clinical Data Management',
 'Education > EdTech > Digital Learning > Corporate Training > Game-Based Learning > Language Learning',
 'Service > Material Handling Equipment > Manufacturing > Industrial Production > Stacking System > Customized Equipment > Industrials',
 'Artificial Intelligence > Industry-Specific > Technology > Store Automation Solution > AI Application > Retail',
 'Enterprise > Engagement & Collaboration > Chatbot > Event Management > Enterprise Software',
 "K-12 > Classroom Management Tool > Software Solution > Teacher's Solution > School Solution > Education > Performance Evaluation Tool > EdTech",
 'Financial Industry > Bank > Financial Institution > Investment Bank > Small Businesses',
 'Industrial Production > Heat Exchanger > Industrials > Heating & Cooling Equipment > Machinery & Equipment > Heating Equipment',
 'Technology > Application > Enterprise > Blockchain > Distributed Computing',
 'Enterprise > Enterprise Software > Candidate Sourcing > HR Tech > Job Board > MBA Jobs',
 'Technology > Home Automation > Consumer IoT > IoT Application > Internet of Things > Connected Home',
 'Technology > Wearables > Workplace Safety > Wearable Band > Commercial',
 'Education > Student Solution > EdTech > Digital Learning > Practice Platform > K-12',
 'Consumer Product > Home Appliance > E-Commerce > Multiline > Retailer > Electronic Product',
 'Enterprise > HR Tech > Enterprise Software > Employee Engagement Solution > Team Building Activities Management',
 'Construction > Multiline > Subcontracting > Service > Real Estate & Construction > Environmental & Safety Service',
 'Print & Digital Media > Sports > Media & Entertainment > Digital Media > Baseball > Blog',
 'Enterprise > Enterprise Software > White-Label Platform > HR Tech > Recruitment Process Management',
 'Media & Entertainment > Ad Tech > Enterprise > Advertising Solution > Gaming',
 'Industrial Production > Machinery & Equipment > Manufacturing Equipment > Waterjet Machine > Cutting Equipment > Industrials',
 'Consumer Internet & Service > Petition Platforms > Lifestyle > Social Support > Application',
 'Industrials > Machinery & Equipment > Forklift > Material Handling Equipment > Industrial Production > Material Transportation Vehicle',
 'Distributor > Convenience Food > Agriculture, Food & Beverage > Food & Beverage > Cookie Dough > Ready-to-eat > Snack > Service',
 'IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security > Technology',
 'Media & Entertainment > Marketplace > Audio Processing > Audio > Hardware',
 'FinTech > Analytics Platforms > Health Insurance > Financial Industry > Backend Solution > InsureTech',
 'Technology > Outsourcing > Custom AI Development > Security & Surveillance > AI Service > Artificial Intelligence > Industrials > Industry-Specific',
 'Inland & Maritime > Transportation > Rental Platform > Boat & Yacht > Transport Tech > Mobility',
 'Real Estate & Construction > Construction > Service > Subcontracting > Ceiling Installation > Interior Construction & Finishing',
 'Supply Chain & Logistics > Warehouse Automation & Robotics > Picking System > Hardware > Warehousing & Inventory Management',
 'Technology > Industry-Specific > Internet of Things > Artificial Intelligence > Multiline > Connected Cities > AI Application',
 'Food & Beverage > Tracking & Monitoring > Agriculture, Food & Beverage > B2B > FoodTech > Hardware Solution > Food Monitoring',
 'Travel Tech > Water-Based > Travel & Hospitality > Cruise > Booking Platform > Transport',
 'Industrial Production > Machinery & Equipment > Electrical & Electronic Equipment > Industrials > Device > Drive > AC Drive',
 'Agriculture, Food & Beverage > B2B > Food & Beverage > FoodTech > Data Analytics > Image Recognition > Software Solution',
 'Enterprise > Employee Helpdesk & Self-Service > Enterprise Software > Employee Relocation > HR Tech',
 'Healthcare & Life Sciences > Health Care IT > Solution for Life Sciences Industry > CRM > Marketing Solution > Digital Health',
 'Healthcare & Life Sciences > Disease-Focused Device > Dermatology > Therapeutic Device > Skin Condition Treatment > Disposable Device > Medical Device',
 'Financial Industry > Shipping Projects > FinTech > Trading and Investment > Alternative Investments Platform',
 'Consumer Brand > Candle > Home Fragrance > Consumer Product > E-Commerce > Home Furnishing > Home Decor',
 'Agriculture > Aquaculture Farming > Agricultural Producer > Controlled Environment Farming > Fish Farm > Caviar > Agriculture, Food & Beverage',
 'Technology > Blockchain > Enterprise > Customer Success > Application > Loyalty Management Platform',
 'Test, Measurement & Instrumentation > Technology > Resistivity & Induced Polarization Meter > Manufacturer > Polarization Meter > Measurement & Calibration',
 'Financial Industry > FinTech > Lending Platform > Multiline > Commercial Loan > Listing Platform',
 'Enterprise > Ad Ops > Media Buying Platform > Enterprise Software > Ad Tech',
 'Consumer Product > Clothing, Accessories & Footwear > Consumer Brand > Activewear & Outdoor Wear > Clothing > Winter Wear',
 'Consumer Internet & Service > Online Rewards > Application > Deals and Rewards > Lifestyle',
 'Enterprise > Data Analytics > Predictive Analytics > Enterprise Software > Business Analytics > Multiline',
 'Enterprise Software > Content Personalization > Enterprise > Customer Engagement > Email Enhancement > Customer Success',
 'Enterprise > Measurement & Analytics > Enterprise Software > Customer Service & Support > Call Tracking & Analytics',
 'Healthcare & Life Sciences > Medical Device > Hospital Equipment & Supplies',
 'Enterprise > Candidate Sourcing > Pre-Screened Candidates > HR Tech > Enterprise Software',
 'AI Infrastructure > Predictive Analytics > Artificial Intelligence > Software Stack > Middleware & Framework > Machine Learning > ML Toolkits & Libraries > Technology',
 'Industrials > Packaging > Material-Based > Glass > Manufacturer > Bottle & Can',
 'Enterprise > Enterprise Service > Media & Entertainment > Industry Specific > Legal Service > Law Firms',
 'Media & Entertainment > Multiline > Publisher > Books > Digital Media > Print & Digital Media',
 'Healthcare & Life Sciences > Physical Therapy > Clinical Operation > Health Care IT > Real-Time Monitoring & Tracking > Digital Health > Digital Therapeutic Solution',
 'Enterprise > HR Tech > Human Capital Allocation Optimization > Internal Mobility > Enterprise Software',
 'Technology > Electronics Ecosystem > Multiline > Retailing > Service',
 'Recreational & Leisure > Equipment > Gym > Sports, Fitness & Outdoor Products > Consumer Brand > Consumer Product > At-Home Fitness',

In [73]:
cleaned_chain_dict['Financial Industry > Backend Solution > InsureTech > Product Pricing Solution > Insurer Solution > FinTech']


cleaned_chain_dict['Consumer Product > Clothing, Accessories & Footwear > Fabric > Nylon & Polyester > B2B Manufacturer > Component']

'Consumer Product > Clothing, Accessories & Footwear > Fabric > Nylon & Polyester > Component'

In [88]:
negative_chains=json.loads(open('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/negative_chains/negative_chains.json').read())

In [90]:
import random
random.sample(list(negative_chains.keys()),10)

['FinTech > Financial Industry > Security Solution > Merchant Payment Solution > Security & Compliance Solution > Payment Recall > Payments',
 'Test, Measurement & Instrumentation > Resistivity & Induced Polarization Meter > Polarization Meter > Measurement & Calibration',
 'IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security',
 'Enterprise > Enterprise Software > Product Analytics > Design Analytics > Product Management',
 'Agriculture > Agriculture, Food & Beverage > Food Safety & Quality > Testing Platform > Agri Tech > Produce Inspection',
 'Automotive > Transport Tech > Mobility > Parking Payment > Payment Solution > B2C',
 'Educational Institution > Basketball > Sports & Fitness > Skill Development',
 'Financial Industry > Consulting > Auditing Solution > Financial Service > Service for Businesses',
 'Retailer > Consumer Product > Clothing, Accessories & Footwear > Swimwear > Activewear & Outdoor Wear > Water Sports',
 'Agriculture, Food & Beverage > Ingredient > Food Product > Quinoa > Grain']

In [93]:
negative_chains['IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security']

{'hard_negatives': ['Technology > Outsourcing > Custom AI Development > Security & Surveillance > AI Service > Artificial Intelligence > Industrials > Industry-Specific',
  'Service > Technology > Electronics Ecosystem',
  'Technology > Thermal Image Sensor > Electronic Component > Sensor > Electronics Ecosystem > Manufacturer > Imaging',
  'Industrials > Engineering, Research & Development > Software > Data Provider > Safety Data > Material & Chemical',
  'Inland & Maritime > Mobility > Enterprise Software > Inspection, Maintenance & Repair > Vessel & Fleet Management > Operation & Maintenance',
  'Technology > Wearable Camera > Commercial',
  'Healthcare & Life Sciences > Health Care IT > Financial Management Solution > Digital Health > Hospital Management & Information System'],
 'soft_negatives': ['Energy & Utilities > Utilities > Gas Utilities > Infrastructure > Distribution > Service',
  'Consumer Brand > Candle > Home Fragrance > Home Furnishing > Home Decor',
  'Healthcare & Life Sciences > Hospital Equipment & Supplies > Adhesive Bandage > Wound Care',
  'Agriculture, Food & Beverage > Agriculture > Agri Tech > Analytics & Intelligence > Aquaculture Analysis > Software Solution',
  'Financial Industry > Managing General Agents > Commercial Insurance > Specialty Insurance > InsureTech > FinTech']}

In [84]:
# industries[industries.industry_chain_hierarchy.str.contains('Financial Industry > Backend Solution')]

In [85]:
# dataset.factsheet.iloc[345]

In [86]:
# sample=pd.read_csv('data/all_factsheets_cleaned_sample.csv')

In [87]:
# sample.factsheet.iloc[0]

In [1]:
import sys
sys.path.append('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/')
from knowledge_data_curation.src.data_processors.negative_generator import NegativeSampleGenerator

In [2]:
from knowledge_data_curation.src.pipelines.main_pipeline import ColBERTTrainingPipeline

In [3]:
data_curator=ColBERTTrainingPipeline(config_path='config/default.yaml')

2025-05-08 19:11:23,556 - knowledge_data_curation.src.utils.token_counter - INFO - Initialized token counter
2025-05-08 19:11:23,556 - knowledge_data_curation.src.models.llm_client - INFO - Initialized OpenAI client with model=gpt-4.1-mini, max_threads=2
2025-05-08 19:11:23,557 - knowledge_data_curation.src.models.llm_client - INFO - Initialized OpenAI client with model=gpt-4.1-mini, max_threads=2

In [4]:
# negative_chains['IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security']

In [5]:
chain='IoT Application > Connected Building > Commercial IoT > Internet of Things > Physical Access Control > Safety & Security'
negative_chains = data_curator.negative_generator.generate_negatives_for_chain(chain)

2025-05-08 19:11:25,578 - knowledge_data_curation.src.models.llm_client - INFO - Using response format: <class 'knowledge_data_curation.src.models.pydantic.NegativeSamplingResponse'>
2025-05-08 19:11:29,681 - knowledge_data_curation.src.utils.token_counter - INFO - Token usage - Total: 1,013 (Prompt: 839, Completion: 174)

In [6]:
negative_chains.hard_negatives

['Technology > Internet of Things > Infrastructure > Connectivity > Networking > IoT Gateway > Industry-Specific > Industrial IoT',
 'Technology > Internet of Things > Infrastructure > Tracking & Navigation',
 'Industrials > Public Safety & Governance > Software > Communication > Open Data Platform',
 'Enterprise > IT Infrastructure > Cybersecurity > Identity & Access Management > Identity Management > Decentralized Identity Management']

In [7]:
negative_chains

NegativeSamplingResponse(hard_negatives=['Enterprise > IT Software > Business Application > Productivity & Collaboration > Business Contact Management > Digital Business Card', 'Industrials > Business Product & Service > Manufacturer > Furnishing > Space-Based > Residential', 'Enterprise > IT Software > Business Application > Human Resources > Candidate Sourcing > Freelancer > Private Security Professionals'], soft_negatives=['Financial Industry > FinTech > Trading & Investment > Trading Platform > Public Market > Exchange-Traded Fund', 'Media & Entertainment > Software > Production > Feedback Management', 'Industrials > Industrial Production > Machinery & Equipment > Fluid Transfer Equipment > Pump & Compressor', 'Technology > Artificial Intelligence > Business Function-Specific > Customer Service & Support > Feedback Tool', 'Financial Industry > FinTech > Finance & Accounting > Taxation Software > Transfer Pricing'])

In [5]:
import pandas as pd
industries=pd.read_csv('data/industries_quickie.csv')
company_factsheets=pd.read_csv('data/all_factsheets_cleaned.csv')

In [6]:
company_factsheets_quickie=company_factsheets[company_factsheets.company_id.isin(industries.company_id)]
company_factsheets_quickie.to_csv('data/all_factsheets_cleaned_quickie.csv',index=False)

In [7]:
# industries[industries.company_id.isin(company_factsheets.company_id)]

In [12]:
# industries['industry_chain_hierarchy'].value_counts()

In [26]:
import pandas as pd

augmented_ind_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/synthetic_data_cache/integrated_augmented_industry_data.csv')

augmented_factsheet_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/output/synthetic_data_cache/integrated_augmented_factsheet_data.csv')

In [27]:
import pandas as pd

ind_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/data/industries_quickie.csv')
factsheet_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/data/all_factsheets_cleaned_quickie.csv')

In [28]:
augmented_factsheet_df

                 company_id                                          factsheet
0                         1  company fact sheet : the company inc . **\n\n ...
1                     17087  company fact sheet : the company **\n\n **1 . ...
2                     41735  numat fact sheet **\n\n **company name :**numa...
3                     55111  inipower company fact sheet **\n\n **1 .   com...
4                    115596  vectra global fact sheet **\n\n **company name...
..                      ...                                                ...
151  synthetic_3b7dde81c886  Products / Services / Offerings: Vertex Interi...
152  synthetic_13e430bcb589  Products / Services / Offerings: CVStreamX pro...
153  synthetic_d56bfd775d0e  Products / Services / Offerings: StreamSight I...
154  synthetic_e3d0e837bea4  Products / Services / Offerings: ADNexis provi...
155  synthetic_278782bd7a1c  Products / Services / Offerings: SearchAdLink7...

[156 rows x 2 columns]

In [29]:
augmented_ind_df

,company_id,industry_chain_hierarchy,company_name
0,1,Media & Entertainment > Video > Television > S...,NaN
1,1,Consumer Product > Consumer Brand > Electronic...,NaN
2,1,Consumer Product > Consumer Brand > Electronic...,NaN
3,1,Consumer Product > Consumer Brand > Electronic...,NaN
4,2,Media & Entertainment > Video Gaming > Gaming ...,NaN
...,...,...,...
179,synthetic_3b7dde81c886,Real Estate & Construction > Construction > Ma...,NaN
180,synthetic_13e430bcb589,Technology > Artificial Intelligence > Infrast...,NaN
181,synthetic_d56bfd775d0e,Technology > Artificial Intelligence > Infrast...,NaN
182,synthetic_e3d0e837bea4,Enterprise > IT Software > Business Applicatio...,NaN
183,synthetic_278782bd7a1c,Enterprise > IT Software > Business Applicatio...,NaN

In [30]:
import pandas as pd

aug_data=pd.merge(augmented_ind_df,augmented_factsheet_df,on='company_id',how='left')

In [31]:
aug_data[aug_data.company_id.str.contains('synthetic_')].head(10)

,company_id,industry_chain_hierarchy,company_name,factsheet
114,synthetic_b84b84819f8c,Enterprise > IT Infrastructure > IT Operations...,NaN,Products / Services / Offerings: AMS-001 provi...
115,synthetic_925df415d31e,Enterprise > IT Infrastructure > IT Operations...,NaN,Products / Services / Offerings: ECO-TechAsset...
116,synthetic_6dea8a87131b,Enterprise > IT Software > Business Applicatio...,NaN,Products / Services / Offerings: PsychoInsight...
117,synthetic_92b62ff5885d,Enterprise > IT Software > Business Applicatio...,NaN,Products / Services / Offerings: NeuroTrack So...
118,synthetic_69802f24302e,Consumer Product > Consumer Brand > Electronic...,NaN,Products / Services / Offerings: The company m...
119,synthetic_b49797e660a7,Consumer Product > Consumer Brand > Electronic...,NaN,Products / Services / Offerings: The enterpris...
120,synthetic_f3cc8264ffc8,Technology > Artificial Intelligence > Applica...,NaN,Products / Services / Offerings: Summalyze pro...
121,synthetic_6802f5738100,Technology > Artificial Intelligence > Applica...,NaN,Products / Services / Offerings: DocuBrief off...
122,synthetic_df97d796be2d,"Media & Entertainment > Books, News & Magazine...",NaN,Products / Services / Offerings: The company d...
123,synthetic_d6b5edaaadf5,"Media & Entertainment > Books, News & Magazine...",NaN,Products / Services / Offerings: This firm pro...

In [32]:
syn_comp_id='synthetic_f3cc8264ffc8'
print(aug_data[aug_data.company_id==syn_comp_id].industry_chain_hierarchy.iloc[0])
print(aug_data[aug_data.company_id==syn_comp_id].factsheet.iloc[0])

Technology > Artificial Intelligence > Application > Industry-Specific > Consumer > Utility & Productivity > Content Summary Generator
Products / Services / Offerings: Summalyze provides an AI-driven content summarization platform that generates concise, context-aware summaries from lengthy documents and multimedia content.
Industry & Target Audience: Operating within the AI software application sector, Summalyze targets enterprises and content creators requiring efficient content digestion tools.
Business Model: The company operates a SaaS model delivering subscription-based access to its summarization APIs and user interface.
Revenue Model: Revenue is generated through tiered subscriptions and API usage fees with additional premium customization services.
Technology Used: Summalyze leverages advanced transformer-based deep learning models and natural language understanding techniques for accurate content summarization.

In [33]:
aug_data[~(aug_data.company_id=='synthetic_15af2f610aa3') & (aug_data.industry_chain_hierarchy=='Media & Entertainment > Video > Television > Streaming Platform')]

,company_id,industry_chain_hierarchy,company_name,factsheet
0,1,Media & Entertainment > Video > Television > S...,NaN,company fact sheet : the company inc . **\n\n ...
123,synthetic_11a444dda42b,Media & Entertainment > Video > Television > S...,NaN,company fact sheet : FlickStream Inc. **\n\n**...

In [36]:
ind_df.groupby('industry_chain_hierarchy').transform(len)

     company_id  company_name
0             1             1
1             1             1
2             1             1
3             1             1
4             1             1
..          ...           ...
109          12            12
110           3             3
111           1             1
112          12            12
113           4             4

[114 rows x 2 columns]

In [38]:
len(ind_df[ind_df.groupby('industry_chain_hierarchy').company_id.transform(len)<2])

36

In [43]:
ind_df[(~ind_df.industry_chain_hierarchy.isin(aug_data[aug_data.company_id.str.contains('syn')].industry_chain_hierarchy)) & (ind_df.groupby('industry_chain_hierarchy').company_id.transform(len)<2) ]

,company_id,industry_chain_hierarchy,company_name
103,153799,Education > EdTech > Higher Education > Studen...,Pairprep

In [ ]:
aug_data[(aug_data.company_id.str.contains('syn')) & (aug_data.industry_chain_hierarchy.isin())]

In [40]:
aug_data[aug_data.company_id.str.contains('syn')]

,company_id,industry_chain_hierarchy,company_name,factsheet
114,synthetic_47278bdfb8c8,Consumer Product > Consumer Brand > Electronic...,NaN,smokealert solutions ltd. company factsheet\n\...
115,synthetic_0844d5e15e0b,Consumer Product > Consumer Brand > Electronic...,NaN,guardian alarms inc. company factsheet\n\n**1....
116,synthetic_4e31084ebd71,Consumer Internet & Service > Application > Ut...,NaN,skyfox search inc. company factsheet **\n\n**1...
117,synthetic_6f9daa276e1a,Consumer Internet & Service > Application > Ut...,NaN,searchloop technologies ltd. company factsheet...
118,synthetic_471076485e70,Enterprise > IT Software > Business Applicatio...,NaN,"MailBridge Technologies, Inc. Factsheet **\n\n..."
...,...,...,...,...
179,synthetic_78cd1b2cf117,Technology > Semiconductor > Integrated Device...,NaN,company fact sheet: Onyx Signal Solutions\n\n*...
180,synthetic_229fca2b2081,Consumer Product > B2B Manufacturer > Clothing...,NaN,**BlueThread Textiles Ltd. Company Fact Sheet*...
181,synthetic_990c982cc669,Consumer Product > B2B Manufacturer > Clothing...,NaN,**IndiCycle Denim Innovations Fact Sheet**\n\n...
182,synthetic_9127c795f22b,Media & Entertainment > Video Gaming > Gaming ...,NaN,the company company fact sheet **\n\n**company...
183,synthetic_2dbbfdb33d73,Media & Entertainment > Video Gaming > Gaming ...,NaN,the company company fact sheet **\n\n**company...

In [32]:
print(aug_data[~(aug_data.company_id=='synthetic_15af2f610aa3') & (aug_data.industry_chain_hierarchy=='Media & Entertainment > Video > Television > Streaming Platform')].factsheet.iloc[0])

company fact sheet : the company inc . **

 **1 .   company overview :**

 the company inc .   is a multinational technology company headquartered in cupertino ; california .    it designs ; develops ; and sells consumer electronics ; computer software ; and online services .

 **2 .   products ; services ; and offerings :**

 *** hardware :**  iphones ; ipads ; macs ( desktops and laptops ) ; the company watch ; airpods ; the company tv ; the company vision pro ; and various accessories .
 *** software :**macos ; ios ; ipados ; watchos ; tvos ; and various productivity and creativity applications .
 *** services :**  app store ; the company music ; the company tv+ ; icloud ; the company arcade ; the company fitness+ ; the company pay ; the company news+ ; and other subscription services .

 **3 .   industry and target audience :**

 *** industry :**consumer electronics ; computer software ; online services .    the company also has a significant presence in the b2b market ; particularly with its mac and ipad offerings for businesses and educational institutions .
 *** target audience :**  broad consumer base across various demographics ; with a focus on premium - priced products and services .    specific marketing efforts target businesses ; education ; and government sectors .

 **4 .   unique selling propositions ( usps ) and key differentiators :**

 *** ecosystem integration :**seamless integration across its hardware and software products .
 *** premium branding and design :**  focus on high - quality design and user experience .
 *** strong brand loyalty :**  cultivated a highly loyal customer base .
 *** proprietary technology :**  development of its own processors ( e . g . ; the company silicon ) and operating systems .
 *** app store ecosystem :**  a thriving app ecosystem with a large selection of applications .

 **5 .   business model :**

 primarily a direct - to - consumer ( d2c ) model ; with some reliance on authorized retailers .    the company also utilizes a freemium model for some services ( e . g . ; icloud storage ) .

 **6 .   revenue model :**

 *** hardware sales :**direct sales of its consumer electronics devices .
 *** software sales :**sales of applications through the app store and mac app store .
 *** services revenue :**subscription revenue from services like the company music ; the company tv+ ; icloud ; and others .
 *** licensing and other revenue streams :**  revenue from licensing its technology and other sources .

 **7 .   technology used :**

 the company designs its own processors ( the company silicon ) ; operating systems ( ios ; ipados ; macos ; watchos ; tvos ) ; and a significant portion of its hardware and software components .    the company utilizes advanced technologies in areas such as mobile computing ; artificial intelligence ; and augmented reality .

 **8 .   competitive landscape :**

 the company faces competition from various companies ; including samsung ( in smartphones and tablets ) ; google ( in mobile operating systems and services ) ; microsoft ( in personal computing and cloud services ) ; and amazon ( in digital content and services ) .    the competitive landscape is highly dynamic and varies across different product categories .


 **9 .   summary :**

 apple 's success is built on a foundation of premium products ; a tightly integrated ecosystem ; and a strong brand .    its diversified revenue streams ; encompassing hardware ; software ; and services ; provide resilience and growth opportunities .    the company 's continued innovation and focus on user experience are key to its ongoing competitive advantage .

In [26]:
import pandas as pd

ind_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/data/industries_quickie.csv')
factsheet_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/data/all_factsheets_cleaned_quickie.csv')

print(ind_df[ind_df.industry_chain_hierarchy=='Technology > Semiconductor > Integrated Device Manufacturer > Analog & Mixed Signal > Multiline'].company_id.to_list(),ind_df[ind_df.industry_chain_hierarchy=='Technology > Semiconductor > Integrated Device Manufacturer > Analog & Mixed Signal > Multiline'].company_id.nunique())

[1328511] 1

In [11]:
print(factsheet_df.factsheet.iloc[0])

company fact sheet : the company inc . **

 **1 .   company overview :**

 the company inc .   is a multinational technology company headquartered in cupertino ; california .    it designs ; develops ; and sells consumer electronics ; computer software ; and online services .

 **2 .   products ; services ; and offerings :**

 *** hardware :**  iphones ; ipads ; macs ( desktops and laptops ) ; the company watch ; airpods ; the company tv ; the company vision pro ; and various accessories .
 *** software :**macos ; ios ; ipados ; watchos ; tvos ; and various productivity and creativity applications .
 *** services :**  app store ; the company music ; the company tv+ ; icloud ; the company arcade ; the company fitness+ ; the company pay ; the company news+ ; and other subscription services .

 **3 .   industry and target audience :**

 *** industry :**consumer electronics ; computer software ; online services .    the company also has a significant presence in the b2b market ; particularly with its mac and ipad offerings for businesses and educational institutions .
 *** target audience :**  broad consumer base across various demographics ; with a focus on premium - priced products and services .    specific marketing efforts target businesses ; education ; and government sectors .

 **4 .   unique selling propositions ( usps ) and key differentiators :**

 *** ecosystem integration :**seamless integration across its hardware and software products .
 *** premium branding and design :**  focus on high - quality design and user experience .
 *** strong brand loyalty :**  cultivated a highly loyal customer base .
 *** proprietary technology :**  development of its own processors ( e . g . ; the company silicon ) and operating systems .
 *** app store ecosystem :**  a thriving app ecosystem with a large selection of applications .

 **5 .   business model :**

 primarily a direct - to - consumer ( d2c ) model ; with some reliance on authorized retailers .    the company also utilizes a freemium model for some services ( e . g . ; icloud storage ) .

 **6 .   revenue model :**

 *** hardware sales :**direct sales of its consumer electronics devices .
 *** software sales :**sales of applications through the app store and mac app store .
 *** services revenue :**subscription revenue from services like the company music ; the company tv+ ; icloud ; and others .
 *** licensing and other revenue streams :**  revenue from licensing its technology and other sources .

 **7 .   technology used :**

 the company designs its own processors ( the company silicon ) ; operating systems ( ios ; ipados ; macos ; watchos ; tvos ) ; and a significant portion of its hardware and software components .    the company utilizes advanced technologies in areas such as mobile computing ; artificial intelligence ; and augmented reality .

 **8 .   competitive landscape :**

 the company faces competition from various companies ; including samsung ( in smartphones and tablets ) ; google ( in mobile operating systems and services ) ; microsoft ( in personal computing and cloud services ) ; and amazon ( in digital content and services ) .    the competitive landscape is highly dynamic and varies across different product categories .


 **9 .   summary :**

 apple 's success is built on a foundation of premium products ; a tightly integrated ecosystem ; and a strong brand .    its diversified revenue streams ; encompassing hardware ; software ; and services ; provide resilience and growth opportunities .    the company 's continued innovation and focus on user experience are key to its ongoing competitive advantage .

In [33]:
## issues identified:

ind_df

,company_id,industry_chain_hierarchy,company_name
0,1,Media & Entertainment > Video > Television > S...,NaN
1,1,Consumer Product > Consumer Brand > Electronic...,NaN
2,1,Consumer Product > Consumer Brand > Electronic...,NaN
3,1,Consumer Product > Consumer Brand > Electronic...,NaN
4,2,Media & Entertainment > Video Gaming > Gaming ...,NaN
...,...,...,...
109,523708,Travel & Hospitality > Digital Solution > Soft...,Lunchbox
110,433515,Industrials > Public Safety & Governance > Gov...,Govos
111,485860,Consumer Product > Consumer Brand > Electronic...,FireAngel Safety Technology
112,1429181,Travel & Hospitality > Digital Solution > Soft...,Albion Hotel Albury
113,239861,Consumer Internet & Service > Service Provider...,True Rest

In [34]:
import pandas as pd

all_ind_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/data/industries.csv')
all_factsheet_df=pd.read_csv('/Users/pragalbh.devsingh/Documents/work/models/ColBERT/knowledge_data_curation/data/all_factsheets_cleaned.csv')

In [35]:
df=all_ind_df.merge(all_factsheet_df)

In [36]:
import pandas as pd


count_df=df.groupby('industry_chain_hierarchy').company_id.nunique().reset_index().sort_values(by='company_id', ascending=False)

In [37]:
count_df

                                industry_chain_hierarchy  company_id
26643  Non-Profit, Non-Operational & Junk > Non-Profi...        9844
26642  Non-Profit, Non-Operational & Junk > Non-Opera...        5492
14640  Financial Industry > Financial Institution > A...        5171
12920  Enterprise > Service > Outsourcing > Informati...        3950
14719  Financial Industry > Financial Institution > B...        2370
...                                                  ...         ...
2129   Agriculture, Food & Beverage > Food & Beverage...           1
2128   Agriculture, Food & Beverage > Food & Beverage...           1
13450  Financial Industry > FinTech > Finance & Accou...           1
21009  Industrials > Environment > Conservation & Pre...           1
12393  Enterprise > Service > Outsourcing > Business ...           1

[32878 rows x 2 columns]

In [38]:
to_create_fatchseet=count_df[count_df.company_id<5]

In [39]:
to_create_fatchseet

                                industry_chain_hierarchy  company_id
28944  Technology > Artificial Intelligence > Applica...           4
26116  Mobility > Aviation > Manufacturer > Aircraft ...           4
5703   Consumer Product > Retailer > Houseware & Home...           4
25905  Mobility > Automotive > Software > Business Ma...           4
32342  Travel & Hospitality > Digital Solution > Plat...           4
...                                                  ...         ...
2129   Agriculture, Food & Beverage > Food & Beverage...           1
2128   Agriculture, Food & Beverage > Food & Beverage...           1
13450  Financial Industry > FinTech > Finance & Accou...           1
21009  Industrials > Environment > Conservation & Pre...           1
12393  Enterprise > Service > Outsourcing > Business ...           1

[18191 rows x 2 columns]

In [54]:
to_create_fatchseet['n']=5-to_create_fatchseet.company_id

/var/folders/bk/nd8kztbd1yjd9yhl3cdt76kc0000gs/T/ipykernel_1794/3511335916.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_create_fatchseet['n']=5-to_create_fatchseet.company_id

In [40]:

factsheets_required_to_be_created=57480
chains_to_create_factsheets_for=18191

out_toks=factsheets_required_to_be_created*500/1000000
out_cost=out_toks*1.60

in_toks=chains_to_create_factsheets_for*2000/1000000
in_cost=in_toks*0.40

In [55]:
to_create_fatchseet.n.sum()

np.int64(57480)

In [58]:
out_toks=57480*500/1000000
out_cost=out_toks*1.60

In [59]:
in_toks=57480*1000/1000000
in_cost=in_toks*0.40

In [41]:
in_cost+out_cost

60.5368

In [45]:
32000*0.3/50

192.0

In [15]:
## cost for industry negative sampling
avg_token_per_chain=30

In [1]:
input_chains_per_negative_sampling=32

In [ ]:
1,2,3,4,5,6,7

In [2]:
len([
  "Enterprise>Service>Outsourcing",
  "Power Production",
  "Education>EdTech>Higher Education",
  "Interior Solution",
  "Canada-Focused",
  "Public Safety & Governance",
  "Higher Education",
  "Media & Entertainment>Video Gaming>Game Publisher",
  "Modeling & Simulation",
  "Visual Analysis",
  "Employee Benefits Solution",
  "Consumer Product",
  "Application",
  "Building Solution",
  "Advertising",
  "Consumer Product>Consumer Brand>Electronic Product",
  "IT Service Management",
  "Content & Experience Marketing",
  "Video Gaming",
  "Business & Finance",
  "Gastroenterology",
  "Retail",
  "Occupational Health Management",
  "Digital>News>Medical",
  "Ad Buying & Selling Platform>Ad Network>Search Advertising Network",
  "Manufacturer",
  "Streaming Analytics",
  "Compliance Solution",
  "IT Software",
  "Sport, Fitness & Outdoor Product>Equipment>Gym",
  "Utility",
  "Technology>Semiconductor>Integrated Device Manufacturer",
  "Online",
  "Travel & Hospitality",
  "Sale, Leasing & Management>Agency & Brokerage>Software",
  "Thermal Energy",
  "Industrials>Industrial Production>Software",
  "Internet of Things",
  "Agency & Brokerage",
  "Financial Management",
  "Material & Chemical",
  "Personal Appliance",
  "Computer Vision>Visual Analysis>Streaming Analytics",
  "Television",
  "Industry-Specific>Consumer>Utility & Productivity",
  "Ad Network",
  "Store Automation Solution",
  "Outsourcing",
  "Application>Industry-Specific>Retail",
  "Asset Management & Disposition",
  "Solar Product",
  "Consumer Internet & Service>Application>Lifestyle",
  "Service",
  "Speaker & Sound Bar",
  "Lifestyle",
  "Consumer Brand",
  "Task Management",
  "Gym",
  "Restaurant, Cafe & Bar",
  "Sales",
  "Sale, Leasing & Management",
  "Outsourcing>Information Technology>Software Testing",
  "Commercial IoT",
  "Computer, Mobile & Accessories",
  "Asset Tracking",
  "Connected Logistics",
  "Integrated Device Manufacturer",
  "Streaming Platform",
  "Consumer Product>Recreational & Leisure>Sport, Fitness & Outdoor Product",
  "Real Estate & Construction>Construction>Building Solution",
  "Digital Learning>Entrance Exam>Q&A Platform",
  "Distributor",
  "Email Solution",
  "Social Media",
  "Marketing",
  "Online Forum",
  "Language Learning",
  "Detector",
  "Building Solution>Interior Solution>Floor",
  "Lifestyle>Product Discovery, Comparison & Recommendation>Apparel, Accessories & Footwear",
  "Industry-Specific",
  "Utility>Internet Browser>Search Engine",
  "Computer & Console Gaming",
  "Consumer Internet & Service>Application>Utility",
  "Ad Buying & Selling Platform",
  "Utility & Productivity",
  "Technology",
  "Education>EdTech>Skill Development",
  "Security & Safety",
  "Student Solution",
  "Communication Platform",
  "Clothing, Accessories & Footwear",
  "Search Engine",
  "Human Resources",
  "Governance>Software>Administration & Management Platform",
  "Consumer Product>Electronic Product>Home Appliance",
  "Consumer Product>Electronic Product>Personal Appliance",
  "Home Care Product",
  "Ad Exchange",
  "Devotional Product",
  "Power Generation Unit",
  "Houseware & Home Supplies",
  "Media & Entertainment>Video Gaming>Gaming Studio",
  "Web & Mobile Gaming",
  "Software Solution>Hospitality>Restaurant, Cafe & Bar",
  "Sport, Fitness & Outdoor Product",
  "Agriculture, Food & Beverage>Food & Beverage>Distributor",
  "Enterprise>IT Infrastructure>IT Operations",
  "Ad Buying & Selling Platform>Ad Exchange>Online",
  "Higher Education>Student Solution>Digital Learning",
  "Email",
  "Power System",
  "Data Security",
  "Wellness Service",
  "Education",
  "Technology>Artificial Intelligence>Computer Vision",
  "Specialty Medical Device>Gastroenterology>Therapeutic Device",
  "Personal Development",
  "Digital Rights Management",
  "Administration & Management Platform",
  "Healthcare & Life Sciences",
  "Fixtures, Fittings & Finishes",
  "Smart Watch",
  "Skill Development",
  "Task Tracking",
  "Energy & Utilities>Power Production>Thermal Energy",
  "Computer Vision",
  "Internet Browser",
  "Digital>News>Business & Finance",
  "Business Application>Productivity & Collaboration>Project Management",
  "Digital Solution",
  "Thermal Energy>Power System>Power Generation Unit",
  "Consumer Product>Consumer Brand>Houseware & Home Supplies",
  "Medical",
  "Technology>Artificial Intelligence>Application",
  "Learning Material",
  "Employee Benefits Solution>Healthcare>Occupational Health Management",
  "Wearable",
  "Personal Appliance>Wearable>Smart Watch",
  "Recreational & Leisure",
  "Media & Entertainment>Video>Television",
  "Audience Data",
  "Enterprise>IT Infrastructure>Cybersecurity",
  "Digital",
  "Project Management",
  "Home Appliance>Entertainment>Home Audio",
  "Enterprise>IT Software>Marketing",
  "Content Summary Generator",
  "IT Asset Management",
  "Business Application>Marketing>Marketing Management",
  "Industrials>Public Safety & Governance>Governance",
  "Business & Finance>Startup & Entrepreneurship>Newsletters",
  "Food & Beverage",
  "Business Application>Sales>Sales Intelligence Platform",
  "Home Audio>Speaker & Sound Bar>Smart Speaker",
  "Industrials",
  "Game Publisher",
  "Enterprise>IT Software>Business Application",
  "Cybersecurity",
  "Software",
  "Consumer Internet & Service",
  "Houseware & Home Supplies>Home Care Product>Devotional Product",
  "Technology>Artificial Intelligence>Machine Learning",
  "Apparel, Accessories & Footwear",
  "Component",
  "Energy & Utilities>Power Production>Solar Energy",
  "EdTech",
  "Electronic Product>Personal Appliance>Computer, Mobile & Accessories",
  "Entertainment",
  "Skill Development>Personal Development>Language Learning",
  "Business Application",
  "Real Estate & Construction",
  "Energy & Utilities",
  "IT Operations>IT Service Management>IT Asset Management",
  "Home Appliance",
  "Specialty Medical Device",
  "Consumer Internet & Service>Social Media>Online Forum",
  "Smoke Detector",
  "Marketing Management",
  "Cybersecurity>Data Security>Digital Rights Management",
  "Digital Learning",
  "IT Operations",
  "Artificial Intelligence",
  "IT Infrastructure",
  "Media & Entertainment",
  "Model Hosting",
  "Marketing Management>Content & Experience Marketing>Content Marketing",
  "Software Testing",
  "Beauty & Wellness",
  "Startup & Entrepreneurship",
  "Sales Intelligence Platform",
  "Business Application>Advertising>Ad Buying & Selling Platform",
  "Productivity & Collaboration",
  "Entrance Exam",
  "Tracking & Monitoring",
  "Software>Financial Management>Compliance Solution",
  "News",
  "Denim",
  "Component>Fabric>Denim",
  "Enterprise",
  "Newsletters",
  "Research & Development",
  "Software>Product Management>Modeling & Simulation",
  "Semiconductor",
  "Consumer Product>Clothing, Accessories & Footwear>Component",
  "Product Management",
  "Media & Entertainment>Books, News & Magazine>Digital",
  "Therapeutic Device",
  "Technology>Artificial Intelligence>Industry-Specific",
  "Dry Ice",
  "Home Audio",
  "Apheresis Therapy Device",
  "Gaming Studio",
  "Product Discovery",
  "Equipment",
  "Search Advertising Network",
  "Healthcare & Life Sciences>Device & Equipment>Laboratory & Research Equipment",
  "Consumer Internet & Service>Beauty & Wellness>Wellness Service",
  "Device & Equipment",
  "Project Documentation",
  "Q&A Platform",
  "Healthcare",
  "Business Application>Human Resources>Employee Benefits Solution",
  "Healthcare & Life Sciences>Device & Equipment>Specialty Medical Device",
  "Floor",
  "Video",
  "Industrial Production",
  "Solar Energy>Manufacturer>Solar Product",
  "Construction",
  "Business Application>Productivity & Collaboration>Communication Platform",
  "Content Marketing",
  "Machine Learning",
  "Governance",
  "Electronic Product",
  "Information Technology",
  "Books, News & Magazine",
  "Product Discovery, Comparison & Recommendation",
  "Real Estate & Construction>Digital Solution>Sale, Leasing & Management",
  "Fabric",
  "Smart Speaker",
  "Technology>Internet of Things>Commercial IoT",
  "Consumer",
  "Home Appliance>Security & Safety>Detector",
  "Software Solution",
  "Industrials>Material & Chemical>Research & Development",
  "Agriculture, Food & Beverage",
  "Solar Energy",
  "Commercial IoT>Connected Logistics>Tracking & Monitoring",
  "Analog & Mixed Signal",
  "Project Management>Task Management>Task Tracking",
  "Hospitality",
  "Laboratory & Research Equipment",
  "Psychographic Intelligence",
  "Travel & Hospitality>Digital Solution>Software Solution"
])

254

In [9]:
tokens_in_sample_subchains=1944
avg_tokens_per_subchain=tokens_in_sample_subchains/254

In [10]:
avg_tokens_per_subchain

7.653543307086614

In [12]:
# total1,944

In [3]:
number_of_chains=50
number_of_subchains=254
avg_subchain_per_chain=number_of_subchains/number_of_chains

In [4]:
avg_subchain_per_chain

5.08

In [28]:
total_chains=32000

total_in_toks=input_chains_per_negative_sampling*(total_chains*avg_token_per_chain + total_chains*avg_subchain_per_chain*avg_tokens_per_subchain)

In [29]:
max_negatives_per_chain=8
total_out_toks=total_chains*max_negatives_per_chain*avg_token_per_chain + total_chains*avg_subchain_per_chain*max_negatives_per_chain*avg_tokens_per_subchain

In [30]:
total_cost=total_in_toks/1000000*0.4 + total_out_toks/1000000*1.6

In [31]:
total_cost

56.426496

In [ ]:
input_toks=total_chains*avg_token_per_chain +

In [57]:
28.74 * 1.60

45.984

In [49]:
count_df

                                industry_chain_hierarchy  company_id
26643  Non-Profit, Non-Operational & Junk > Non-Profi...        9844
26642  Non-Profit, Non-Operational & Junk > Non-Opera...        5492
14640  Financial Industry > Financial Institution > A...        5171
12920  Enterprise > Service > Outsourcing > Informati...        3950
14719  Financial Industry > Financial Institution > B...        2370
...                                                  ...         ...
2129   Agriculture, Food & Beverage > Food & Beverage...           1
2128   Agriculture, Food & Beverage > Food & Beverage...           1
13450  Financial Industry > FinTech > Finance & Accou...           1
21009  Industrials > Environment > Conservation & Pre...           1
12393  Enterprise > Service > Outsourcing > Business ...           1

[32878 rows x 2 columns]